### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by chromer030** [msasanmh/SecureDNSClient#10]
Hi, Thanks for this great tool, any plan to provide a release for Linux ?

(Like [xdm](https://github.com/subhra74/xdm) which is also in C#)

**Comment by msasanmh** [comment]
Writing cross-platform application is something different, all methods and algorithms must support both platforms. Since I'm using many methods which are only available to Windows, it makes the project impossible to compile for Linux.

**Comment by chromer030** [comment]
So, Thanks for answer. ❤️
I appreciate you efforts for tools and lists.
