### ISSUE TITLE
باگ برنامه

### ISSUE THREAD

**Issue by NIOOFARI** [msasanmh/SecureDNSClient#100]
درودv2.7.5  برای من رو ویندوز 10  کار نمیکنه قسمت SET DNS اجرا نمیشه( نمیزنه UNSET DNS) صدای دی ان اس انلاین را اجرا  میکنه ولی در همین حالت  می ماند بقیه را هم اجرا می کنم ولی عمل نمیکنه  اخرین اپدیت ویندوز  10  را دارم  برگشتم به ورژن 2.7.0 اون کار میکنه ولی این جدیده  قسمت دوم را اجرا نمیکنه    ورژن های قبلی همه برا من جواب میدادن این  جواب نمیده 
نکته  دوم  برای راه اندازی  برنامه کاش فقط یک دکمه بود کلیک میکردیم وصل میشد الان  قطع و وصل شدنش  کمی تلاش  و  ست کردن میخاد 
نکته سوم من نمیدونم ایا میشه تلگرام را باهاش ست کرد  یه پراکسی  چیزی بده که   تلگرام را هم وصل کنیم؟ الان ما برا تلگرام  که  هات اسپات شیلد  استفاده می کنیم با این برنامه ناسازگاره اون که ران بشه اینو  آفلاین  میکنه 
با سپاس

**Comment by msasanmh** [comment]
> درودv2.7.5  برای من رو ویندوز 10  کار نمیکنه قسمت SET DNS اجرا نمیشه( نمیزنه UNSET DNS) صدای دی ان اس انلاین را اجرا  میکنه ولی در همین حالت  می ماند بقیه را هم اجرا می کنم ولی عمل نمیکنه  اخرین اپدیت ویندوز  10  را دارم  برگشتم به ورژن 2.7.0 اون کار میکنه ولی این جدیده  قسمت دوم را اجرا نمیکنه    ورژن های قبلی همه برا من جواب میدادن این  جواب نمیده 

ممنون، برطرف می‌کنم.

> نکته  دوم  برای راه اندازی  برنامه کاش فقط یک دکمه بود کلیک میکردیم وصل میشد الان  قطع و وصل شدنش  کمی تلاش  و  ست کردن میخاد 

از اونجایی که برنامه راه‌های زیادی برای کانکت شدن داره دکمه quick connect رو ایجاد کردم، هر جوری که دوست دارید تنظیمش کنید و بعد با یک کلیک وصل میشه، برای قطع کردن هم رو آیکن برنامه کلیک کن و گزینه disconnect all رو بزن تا همه چیز خاموش بشه.

> نکته سوم من نمیدونم ایا میشه تلگرام را باهاش ست کرد  یه پراکسی  چیزی بده که   تلگرام را هم وصل کنیم؟ الان ما برا تلگرام  که  هات اسپات شیلد  استفاده می کنیم با این برنامه ناسازگاره اون که ران بشه اینو  آفلاین  میکنه 

تلگرام براساس IP فیلتر شده و این برنامه متاسفانه نمیتونه بازش کنه.
ناسازگاریش رو باید سر فرصت بررسی کنم

> با سپاس

**Comment by NIOOFARI** [comment]
تشکر   از   جوابگویی سریع و موثرتون   سلامت و موفق باشید
