### ISSUE TITLE
Problems .

### ISSUE THREAD

**Issue by DogancanYr** [msasanmh/SecureDNSClient#101]
1)Goodbyedpi is not connected.
When I select the goodbyedpi option from quickconnect in the settings, it does not work. (It was working in the previous version)

2)The application can be stopped completely from the start menu icon.
When I wanted to uninstall the application, it did not allow me to delete windiwert64.sys. After a long effort, I managed to stop it from the icon in the start menu.

3)Complicated to use 
To run Goodbyedpi, you need to turn on the Share+bypass dpi setting.
(Open automatically)

**Comment by msasanmh** [comment]
> 1)Goodbyedpi is not connected.
> When I select the goodbyedpi option from quickconnect in the settings, it does not work. (It was working in the previous version)
> 

I didn't face this issue, although I'm gonna check it again. 

> 2)The application can be stopped completely from the start menu icon.
> When I wanted to uninstall the application, it did not allow me to delete windiwert64.sys. After a long effort, I managed to stop it from the icon in the start menu.
> 

It's WinDivert's known issue which is used by GoodbyeDPI, it's a separate application and there's nothing I can do about it.
To delete WinDivert file, rename it, restart Windows and then delete.

> 3)Complicated to use 

I'm sure you previously said it's easy to use Lol

> To run Goodbyedpi, you need to turn on the Share+bypass dpi setting.

GoodbyeDPI can run independently, Proxy (share + dpi bypass) has nothing to do with that.

> (Open automatically)
> 
> 

How to use:
You can separate application to two parts.

1. Connect to a secure dns and set it to windows.

2. Now if you want to bypass DPI, you have two options: 

A) activate GoodbyeDPI
B) or activate Proxy with built-in DPI bypass support. Which the success rate is more than GoodbyeDPI. 

Note: you don't need to activate both GoodbyeDPI and Proxy. It's totally unnecessary.

**Comment by DogancanYr** [comment]
2) I was able to delete it by right-clicking on the icon in the start menu and selecting cut all connections. Can you move it to the application?

3)It's easy for me, but it won't be easy for everyone.Could you please edit the software a bit?
(Like showing what they are used for when hovering over them .Frankly, I don't know how some of them work or how to make them work)

3.2)Automatically start share+dpi bypass when goodbyedpi is started.
Because I didn't know I had to start it and it took me a long time or it was written somewhere, I didn't see it :b

Thank you for everything .❤️

**Comment by msasanmh** [comment]
> 2)İ was able to delete it by right-clicking on the icon in the start menu and selecting cut all connections. Can you move it to the application?
> 

Well, you shouldn't try to delete an application while it's running.

> 3)It's easy for me, but it won't be easy for everyone.Could you please edit the software a bit?
> (Like showing what they are used for when hovering over them .Frankly, I don't know how some of them work or how to make them work)

I know, there is a lack of documentation, I need to do something about it.

> 
> 3.2)Automatically start share+dpi bypass when goodbyedpi is started.

That's why I created quick connect. I'm gonna enhance it in next version. 

> Because I didn't know I had to start it and it took me a long time or it was written somewhere, I didn't see it :b

It will get better in time.

> 
> Thank you for everything .❤️

Thank you too.

**Comment by DogancanYr** [comment]
I pressed stop quickconnect.Does it stop the application?

**Comment by msasanmh** [comment]
> I pressed stop quickconnect.
> 

Stop quick connect will cancel whatever it was going to do.

To stop everything: 
Click "disconnect all" from menu
