### ISSUE TITLE
not working Proxy Failed to start

### ISSUE THREAD

**Issue by MehdiiPanahi** [msasanmh/SecureDNSClient#102]
Starting Proxy Server...
Upstream proxy cannot open www.youtube.com.
سلام مهندس
 اقا پروکسی اینجا استارت نمیشه انلاین هم میشه ولی جایی باز نمیشه 
certificate
 رو هم از دوباره گذاشتم نصب  کنه بازم آپ استریم پروکسی رو نمیشه استارت زد انتیویروس اوست غیر فعاله از ادمین اجراش کردم برنامه تو و هیچ کاری انجام نمیده. کار اصلی که باید بکنه رو انجامش نمیده

Hello, engineer, the proxy cannot be started here, it can be online, but it won't open anywhere, I put the certificate to install it again, and the upstream proxy can't be started. The antivirus is inactive. I ran it from the admin, and your program does nothing.

**Comment by msasanmh** [comment]
در این نسخه پراکسی نیازی به certificate نداره و برای باز کردن یوتیوب هم نیازی به تنظیم upstream ندارید.
درنتیجه چه certificate ی رو به چه منظوری دارید نصب می‌کنید؟ لطفا مراحل کاری که انجام دادید رو توضیح بدید
مطمئنم همه مراحل رو اشتباه رفتید.
