### ISSUE TITLE
 Github please remove this repository someone can't even use a simple app

### ISSUE THREAD

**Issue by MehdiiPanahi** [msasanmh/SecureDNSClient#103]

**Comment by msasanmh** [comment]
![Screenshot_20231121_165647_Gmail.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/be246ca3-48ad-4b75-aeea-7e565d400ab2)

و تویی که حتی کار کردن با یه نرم‌افزار ساده رو هم بلد نیستی.
و تویی که حتی سواد خوندن هم نداری به منی که وقتی به دنیا نیومده بودی برنامه‌نویس بودم میگی آبروی سی شارپ رو نبرم؟
مگه داخل change log اینو ننوشتم:
Can't you even read?
System Startup Implemented.
To Activate: Settings --> Quick Connect --> Apply to Startup
To Deactivate: Settings --> Quick Connect --> Remove from Startup
If you change the application path, you need to fix Startup:
To Fix Startup: Settings --> Quick Connect --> Fix Startup

**Comment by msasanmh** [comment]
System Startup Implemented.
To Activate: Settings --> Quick Connect --> Apply to Startup
To Deactivate: Settings --> Quick Connect --> Remove from Startup
If you change the application path, you need to fix Startup:
To Fix Startup: Settings --> Quick Connect --> Fix Startup

**Comment by msasanmh** [comment]
اون جای مخفی اسمش tray icons هستش، همون کنار ساعت.
That "secret place" is called Tray Icons, you can find it beside the windows clock.

**Comment by nonbarbari** [comment]
من بعید میدونم 14 سالش تموم شده باشه 


همین که مثلا خواسته به گیت هاب ریپورت کنه به جاش اومده ایشیو باز کرده گویای همه چیز هست 😁
