### ISSUE TITLE
Saving problem.

### ISSUE THREAD

**Issue by DogancanYr** [msasanmh/SecureDNSClient#104]
Site section to be checked from the settings check section does not save.

At the same time, the quick connect part does not save.

**Comment by msasanmh** [comment]
> Site section to be checked from the settings check section does not save.
> 
> At the same time, the quick connect part does not save.

App will save settings:
Every 2 minutes. 
On exiting application. 
On exporting user data.

Did you just force stop the app or restarted Windows without closing application?

**Comment by DogancanYr** [comment]
Quick connect part works.

When I enter the site address in the Check section and then enter other settings or move the application, it is reset.

❤️☺️❤️

**Comment by msasanmh** [comment]
> Quick connect part works.
> 
> When I enter the site address in the Check section and then enter other settings or move the application, it is reset.
> 
> ❤️☺️❤️

Because your address is wrong. 
Do not use http:// or https://
Write a domain like this:
Let's just say you want to change it to Google. Write it like this:
www.google.com

**Comment by DogancanYr** [comment]
Yes, I wrote that.

**Comment by msasanmh** [comment]
> Yes, I wrote that.

You mean with http: ?
Does your issue solved now?

**Comment by DogancanYr** [comment]
No, I tried again now.Still same .

**Comment by msasanmh** [comment]
> No, I tried again now.Still same .

Damn. You're right. I'm so sorry, I forgot something. 
I'm gonna fix it soon. 🙏

**Comment by msasanmh** [comment]
> No, I tried again now.Still same .

Please Update:
https://github.com/msasanmh/SecureDNSClient/releases/tag/v2.8.1
