### ISSUE TITLE
Issue v2.8.0

### ISSUE THREAD

**Issue by Noktomezo** [msasanmh/SecureDNSClient#106]
Can't change the domain for checking. There is no such problem in version 2.7. Domain version with www doesn't help either
![SecureDNSClient_ZcHhKovkBq](https://github.com/msasanmh/SecureDNSClient/assets/73643707/63038be3-2c17-41eb-a030-3048c5c6ee61)

**Comment by msasanmh** [comment]
> Can't change the domain for checking. There is no such problem in version 2.7. Domain version with www doesn't help either
> ![SecureDNSClient_ZcHhKovkBq](https://github.com/msasanmh/SecureDNSClient/assets/73643707/63038be3-2c17-41eb-a030-3048c5c6ee61)
> 

Already fixed:
https://github.com/msasanmh/SecureDNSClient/releases/tag/v2.8.1
