### ISSUE TITLE
مشکل مصرف  بالا cpu

### ISSUE THREAD

**Issue by wolfkingal2000** [msasanmh/SecureDNSClient#108]
سلام از نسخه جدید 2.8.0 به بعدا مشکل cpu داره قبلا اینطوری نبود خیلی مصرفش بالا رفته میشه یه نگاه بندازی ؟

![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/a7c36224-88cb-4c47-91b9-14665750086c)

این هم تنظیمات cpu  هست 
![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/49b79c90-6a37-4743-a5d4-27338b2af93c)
و بعدا یه مدت  همش این رو طوری میشه لوگش 
![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/e55ab851-4d34-48b7-9f91-0f08dfb40986)

**Comment by msasanmh** [comment]
همیشه اینطور میشه یا گاهی اوقات؟ 
و اینکه از قسمت status یه اسکرین بده بدونم چه چیزایی روشنه.

**Comment by wolfkingal2000** [comment]
> همیشه اینطور میشه یا گاهی اوقات؟ و اینکه از قسمت status و تنظیمات quick connect یه اسکرین بده بدونم چه چیزایی روشنه. @wolfkingal2000

![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/5c588ead-1907-4e26-94c0-31c18cafb2d0)
بیا من چک کردم توی status کم نشون میده ولی توی تکست منیجر بالا نشون میده  فکر کنم این وسط یه cpu لیکی چیزی میشه 

![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/6dafe430-d146-4855-82a6-8f1236c7470d)
این هم تنظیمات quick connect

**Comment by msasanmh** [comment]
چرا همه گزینه‌ها روی هم افتاده، مگه روی فایل اجرایی برنامه کلیک راست کردی و تنظیمات Change High DPI Settings رو تغییر دادی؟
@wolfkingal2000

**Comment by msasanmh** [comment]
الان عین تنظیماتت رو اجرا کردم. برای من همچین مشکلی ایجاد نشد

![SDC_CPU_Usage](https://github.com/msasanmh/SecureDNSClient/assets/1586825/02a04d87-414b-4251-b3ac-905bea8a2440)

من تا نتونم مشکلت رو روی کامپیوتر خودم شبیه سازی کنم نمیتونم برطرفش کنم.
و من همه فیچرهایی که کاربرها درخواست داده بودن رو روی برنامه پیاده کردم و طبیعیه که هرچقدر امکانات برنامه بالاتر بره مصرف CPU هم بیشتر میشه.
حالا سعی میکنم ورژن بعد یه آپشنی مخصوص کامپیوترهای ضعیف بذارم تا میزان CPU بیاد پایین اما باید بدونید که هوشیاری برنامه هم پایین میاد.
لطفا به دو تا سوالی که بالا پرسیدم پاسخ بده. مهمه.
و این issue رو هم فعلا نبند شاید بقیه تونستن کمک یا همفکری کنن.
@wolfkingal2000

**Comment by wolfkingal2000** [comment]
> چرا همه گزینه‌ها روی هم افتاده، مگه روی فایل اجرایی برنامه کلیک راست کردی و تنظیمات Change High DPI Settings رو تغییر دادی؟
> @wolfkingal2000 

نه  تغییر ندادم وای دیدم اینطوری یه بار تغییر داد ولی مشکل حل نشد دوباره برگردونم خوب کار میشه با هاش کرد زیاد مشکلی برام ایجاد نکرد

**Comment by wolfkingal2000** [comment]
> الان این 20 درصد که نشون میده، مدام روی همین 20 درصد میمونه یا اینکه بین 5 تا 20 درصد متغیره؟
> و CPU ت چند هسته‌ایه؟ مشخصاتش چیه؟
> @wolfkingal2000 

ماین ۱۵ تا ۳۰ متغیر  بعضی وقت ها پایین میاد بعدا دوباره بالا میره  cpu هم ۴ هسته ای

**Comment by msasanmh** [comment]
> > چرا همه گزینه‌ها روی هم افتاده، مگه روی فایل اجرایی برنامه کلیک راست کردی و تنظیمات Change High DPI Settings رو تغییر دادی؟
> > @wolfkingal2000 
> 
> نه  تغییر ندادم وای دیدم اینطوری یه بار تغییر داد ولی مشکل حل نشد دوباره برگردونم خوب کار میشه با هاش کرد زیاد مشکلی برام ایجاد نکرد 

الان برنامه خودش همه چیز رو تنظیم میکنه، اگه فعالش داری حتما غیرفعال کن تا همه چیز تمیز نشون داده شه.

**Comment by msasanmh** [comment]
> > الان این 20 درصد که نشون میده، مدام روی همین 20 درصد میمونه یا اینکه بین 5 تا 20 درصد متغیره؟
> > و CPU ت چند هسته‌ایه؟ مشخصاتش چیه؟
> > @wolfkingal2000 
> 
> ماین ۱۵ تا ۳۰ متغیر  بعضی وقت ها پایین میاد بعدا دوباره بالا میره  cpu هم ۴ هسته ای شاید مشکل ار استارت آپ باشه اون خواستی چک کن قبل ۲.۸.۰ این مشکل نبود

اگه از استارت‌آپ باشه فقط موقع استارت‌آپ باید این مشکل پیش بیاد.
بخاطر سرعت آپدیت متغیر هاست. که تاخیر بروی ۲۰ میلی ثانیه قرار داره و مصرف cpu من بین ۱ تا ۸ متغیره، الان تاخیر رو بروی ۲ ثانیه گذاشتم مصرف cpu اومد بین ۱ و ۲ درصد. 
این آپشن رو توی ورژن بعد قسمت تنظیمات cpu اضافه میکنم، اونوقت هرچقدر اون تاخیر رو بالاتر ببری مصرف cpu پایین‌تر میاد

**Comment by wolfkingal2000** [comment]
> > > چرا همه گزینه‌ها روی هم افتاده، مگه روی فایل اجرایی برنامه کلیک راست کردی و تنظیمات Change High DPI Settings رو تغییر دادی؟
> > > @wolfkingal2000 
> > 
> > نه  تغییر ندادم وای دیدم اینطوری یه بار تغییر داد ولی مشکل حل نشد دوباره برگردونم خوب کار میشه با هاش کرد زیاد مشکلی برام ایجاد نکرد 
> 
> الان برنامه خودش همه چیز رو تنظیم میکنه، اگه فعالش داری حتما غیرفعال کن تا همه چیز تمیز نشون داده شه.

این گفتار اول اینطوری  بود تغیی ر هم دادم بد تر شد پس برش گردونم  دیفالت

**Comment by msasanmh** [comment]
> > > > چرا همه گزینه‌ها روی هم افتاده، مگه روی فایل اجرایی برنامه کلیک راست کردی و تنظیمات Change High DPI Settings رو تغییر دادی؟
> > > > @wolfkingal2000 
> > > 
> > > نه  تغییر ندادم وای دیدم اینطوری یه بار تغییر داد ولی مشکل حل نشد دوباره برگردونم خوب کار میشه با هاش کرد زیاد مشکلی برام ایجاد نکرد 
> > 
> > الان برنامه خودش همه چیز رو تنظیم میکنه، اگه فعالش داری حتما غیرفعال کن تا همه چیز تمیز نشون داده شه.
> 
> این گفتار اول اینطوری  بود تغیی ر هم دادم بد تر شد پس برش گردونم  دیفالت

بسیارخب، پس باید این قسمت رو هم مقداری optimize کنم.
برای cpu هم یه کاریش میکنم.
ممنون بابت گزارش.
