### ISSUE TITLE
ver 2.8.1 عدم  امکان  کانکت شدن 

### ISSUE THREAD

**Issue by NIOOFARI** [msasanmh/SecureDNSClient#109]
درود   قبلا هم باگ در  2.7.5  را گزارش کردم   که  نتونستم بهش وصل بشم اما   این ورژن  2.8.1   از ابتدا   گزینه  کانتکش  غیر فعال میشه و  از  ورژن قبلی 2.7.5 هم باز بدتره و هر چه  صبر می کنم  هیچ اتفاقی نمیفته    ویندوز  10 LTSC استفاده می کنم  به  2.7.0   وصل میشم و کار میکنه ولی ورژن های جدید را نمیتونه وصل بشه  تصاویر  را   اپلود کردم کلا از  2.7.0   به بعد دیگه  کار نکرد( هم نسخه  64 و هم 32  برنامه را  تست کردم وصل  نشد) در کل  این مشکل  از اپدیت  نسخه  2.7.5 شروع شده متشکر  موفق باشید

![Capture555](https://github.com/msasanmh/SecureDNSClient/assets/149754932/554869c9-8567-4b39-932a-800b6473ae65)

**Comment by msasanmh** [comment]
این ورژن متاسفانه یه باگ داره که نمیتونه سرورهای ذخیره شده رو به طور اتوماتیک لود کنه.
اما چیزی نیست که مانع استفاده شما بشه.
کافیه اول مقداری سرور اسکن کنی.
در تب Check بروی Scan کلیک کن تا چک سرورها شروع بشه، بعد پیدا کردن چندتا سرور میتونی کنسلش کنی.
اونوقت وقتی به تب Connect بری میبینی که گزینه فعاله.
این مشکل در ورژن بعد برطرف میشه.

**Comment by NIOOFARI** [comment]
با تشکر  بله این کار را هم کردم   سرور  پیدا کرد و پیام انلاین شدن هم داد ولی بقیه مراحلش مثل  ورژن  2.7.0  جلو   نرفت و نتونستم  وصل بشم  مشکل  دیگه ای که داره خیلی پیچیدگی زیادی داره و برای کاربر  عادی   مشکله  کاربر  حرفه ای   شاید   بتونه  وصل بشه. حوصله میخاد  یو آی پیچیده ای داره  فعلا از 2.7.0  استفاده میکنم  ببینیم  بعدا چه میشه این   شلوغی  زیاد برا  کاربر  سخته  واقعا. ساده سازی و اتصال و قطع راحت الان  نیاز  من هست  این برنامه با همه خوبی هایی که داره  مثل  ماشینی است که تمام  موتورش  بیرونه یا انسانی است که پوست نداره همه دل و روده اش بیرونه   تنظیماتش  خیلی خیلی زیاده  یک دکمه  وصل  یک دکمه قطع  برا کاربر عادی کافیه  تشکر از زحمات شما

**Comment by msasanmh** [comment]
>  با تشکر  بله این کار را هم کردم   سرور  پیدا کرد و پیام انلاین شدن هم داد ولی بقیه مراحلش مثل  ورژن  2.7.0  جلو   نرفت و نتونستم  وصل بشم  مشکل  دیگه ای که داره خیلی پیچیدگی زیادی داره و برای کاربر  عادی   مشکله  کاربر  حرفه ای   شاید   بتونه  وصل بشه. حوصله میخاد  یو آی پیچیده ای داره  فعلا از 2.7.0  استفاده میکنم  ببینیم  بعدا چه میشه این   شلوغی  زیاد برا  کاربر  سخته  واقعا. ساده سازی و اتصال و قطع راحت الان  نیاز  من هست  این برنامه با همه خوبی هایی که داره  مثل  ماشینی است که تمام  موتورش  بیرونه یا انسانی است که پوست نداره همه دل و روده اش بیرونه   تنظیماتش  خیلی خیلی زیاده  یک دکمه  وصل  یک دکمه قطع  برا کاربر عادی کافیه  تشکر از زحمات شما 

بزودی ویدئوهایی آموزشی از قسمت‌های مختلف برنامه درست می‌کنم و همینطور وصل شدن و قطع شدن با یک دکمه. هر وقت ویدئو آماده شد برای شما در همین صفحه گیتهاب پیام می‌ذارم 🙏

**Comment by NIOOFARI** [comment]
بهترین  راه حل همین ساخت ویدئوی آموزشیه 
مرسی

**Comment by msasanmh** [comment]
چون مشکل لود سرورها برطرف شد این issue رو میبندم اما هر زمان که ویدئوها آماده شدن به شما اطلاع میدم.

**Comment by msasanmh** [comment]
> بهترین  راه حل همین ساخت ویدئوی آموزشیه 
> مرسی

فکر میکنم این آموزش به کار شما میاد:
[Here](https://yasserdivar.ir/secure-dns-client/)
