### ISSUE TITLE
how add custom dns servers and set DoH in windows?

### ISSUE THREAD

**Issue by saeex71** [msasanmh/SecureDNSClient#11]
سلام چجوری میشه dns دیگه به لیست اضافه کرد؟ ایا باید بصورت خاص وارد بشه؟
,و اگر امکان داره برای تنظیم DoH در ویندوز یک راهنما بزارید ( با برنامه yoga dns میشه؟)
و اینکه مشکل فونت در ورژن جدید حل شده تشکر

**Comment by msasanmh** [comment]
برنامه برای استفاده از سرورها، دو حالت داره، یا از سرورهای داخلی خودش استفاده میکنه یا از سرورهای کاربر.
اگه میخوای از سرورهای خودت استفاده کنی، در صفحه Check دکمه 
Edit custom servers 
رو بزن و در هر خط یک سرور وارد کن و فایل رو سئو کن و ببند.
بعد در همین قسمت گزینه 
Use custom servers 
رو انتخاب کن. و وقتی بروی اسکن کردن کلیک کنی، برنامه سرورهای خودت رو اسکن می‌کنه و اگه سرورها سالم باشن ازشون استفاده میکنه.
در مورد ست کردن DoH بطور مستقیم روی ویندوز:
این کار فقط در ویندوز ۱۱ امکانپذیره و همینطور میتونی به طور مستقیم سرور DoH رو به مرورگرها بدی، مثل فایرفاکس یا کروم. که در تنظیمات شون هست.
اگه میخوای برنامه در حالت DoH کار کنه و بهت سرور لوکال DoH بده:
قبل از کانکت کردن برنامه، به این قسمت برو:
Settings --> Working mode
و گزینه پایین رو انتخاب کن:
Legacy DNS + DNS-Over-HTTPS Server
و وقتی برنامه رو کانکت کنی، برنامه آدرس سرور لوکال DoH رو توی قسمت لاگ می‌نویسه.

**Comment by saeex71** [comment]
ممنون بابت راهنمایی
1.در نسخه قبلی وقتی دکمه connect all/disccnnect all میزدم کل مراحل 1 تا 4 خودش انجام میداد ولی در نسخه جدید بعد از اسکن کردن dns ها و کانکت شدن متوقف میشه مرحله 3 و 4 انجام نمیده و پیغام connect first دو بار نشون میده
2. احتیاجی هست در قسمت core dns برنامه v2rayn چیزی وارد کنیم ؟ مثلا ادرس local dns ؟  و اینکه توی همین قسمت میشه ادرس لوکال DoH وارد کرد؟

**Comment by msasanmh** [comment]
۱. فعلا از connect all استفاده نکنید تا بررسی کنم.
۲. میتونید سرور لوکال DoH رو روی v2rayn بذارید اما اگه Set DNS رو زدید نیازی به انجام این کار نیست.
