### ISSUE TITLE
ریکانکت شدن مکرر برنامه ها در ورژن 2.8.1

### ISSUE THREAD

**Issue by mztd006** [msasanmh/SecureDNSClient#110]
با سلام و خسته نباشید بابت این زحمتی که کشیدی برای تکمیل برنامه.
نکته اول اینکه در نسخه  2.8.1 ، پلتفرم معاملاتی که ازش استفاده میکنم مدام reconnect میشه برای همین از  نسخه 2.7.5 استفاده میکنم و این مشکل پیش نمیاد.
نکته دوم اینکه من از ورژن 2.0.6  از برنامه استفاده میکنم و چون از اول ذره ذره اضافه شدن امکاناتش رو دیدم همه چی برام واضحه اما دیروز که روی سیستم یه دوستی نصبش کرده بودم و میخواستم توضیح بدم چطور استفاده کنه و هر کدوم از این آپشن ها برای چه کاری هست متوجه شدم که  چقدر طرف گیج شده و به نظرم جای یه منوی help توی رابط کاربری خالی هست.

**Comment by wolfkingal2000** [comment]
سلام اره برا منم این میشه وقتی می خام دانلود سنگین انجام بدم یا idm چیزی دانلود بکنم برای دانلود د ن س ست رو وردارم درست میشه بقیه نه  اینطوری میشه یا وقتی گذاشتم روب اسلیپ یا هایبر نت هم اینطوری میشه

**Comment by msasanmh** [comment]
> با سلام و خسته نباشید بابت این زحمتی که کشیدی برای تکمیل برنامه.

🙏

> نکته اول اینکه در نسخه  2.8.1 ، پلتفرم معاملاتی که ازش استفاده میکنم مدام reconnect میشه برای همین از  نسخه 2.7.5 استفاده میکنم و این مشکل پیش نمیاد.

در نسخه 2.7.5 تشخیص وجود اینترنت از طریق خوندن send و receive آداپتر شبکه بوده که در استارت‌آپ مشکل ایجاد می‌کرد چون زمانیکه سیستم بالا میاد آداپتر send و receive به خودش میگیره و برنامه فکر می‌کرد که اینترنت وجود داره درحالیکه تا چند ثانیه اینترنت وجود نداره و برنامه نمی‌تونست در استارت‌آپ کانکت بشه.
الان تشخیص وجود اینترنت از طریق پینگ گرفتن ip Bootstrap هستش که در تنظیمات وجود داره.
اگه برای شما قطع و وصل میشه باید Bootstrap رو به ip که با نتورک شما سازگاره انتخاب کنی.
حالا من امشب یه ورژن جدیدتر دارم میدم لطفا ازش استفاده کن و اگه باز این مشکل وجود داشت اونوقت یه فکری به حالش می‌کنم. 

> نکته دوم اینکه من از ورژن 2.0.6  از برنامه استفاده میکنم و چون از اول ذره ذره اضافه شدن امکاناتش رو دیدم همه چی برام واضحه اما دیروز که روی سیستم یه دوستی نصبش کرده بودم و میخواستم توضیح بدم چطور استفاده کنه و هر کدوم از این آپشن ها برای چه کاری هست متوجه شدم که  چقدر طرف گیج شده و به نظرم جای یه منوی help توی رابط کاربری خالی هست.

آره، به شدت دنبال تهیه آموزش‌های متنی و ویدئویی هستم و بزودی قرار می‌گیره.

**Comment by msasanmh** [comment]
دیگه دارم همین الان درستش میکنم و تا امشب آپلود میکنم.
میذارم تا یک دقیقه اول برنامه و یا زمانیکه quick connect داره کانکت میشه از پینگ Bootstrap استفاده کنه و در بقیه موارد از send و receive آداپتر برای تشخیص اینترنت استفاده کنه.
اینجوری هم در استارت‌آپ مشکل پیش نمیاد و هم این مشکل شما.
@mztd006 
@wolfkingal2000

**Comment by msasanmh** [comment]
دیگه مشکل باید برطرف شده باشه.
https://github.com/msasanmh/SecureDNSClient/releases/tag/v2.8.2

اگه باز مشکلی پیدا کردید در هر زمینه لطفا گزارش بدید. بدون گزارش شما مشکلات حل نمیشه و برنامه پیشرفت نمیکنه 🙏

@mztd006 
@wolfkingal2000

**Comment by msasanmh** [comment]
> سلام
> با عرض معذرت از تاخیر در اعلام نتیجه، بله مشکل کامل حل شده. از این نرم افزار روی 4 تا PC و Laptop با OS های مختلف و سخت افزار های مختلف استفاده می کنیم و نسخه ی 2.8.2  بهترین نسخه تا بحال بوده

ممنون بابت اطلاع، بهترین خبر امروزم بود 🙏
