### ISSUE TITLE
dpi  هنوز یکم کار داره

### ISSUE THREAD

**Issue by wolfkingal2000** [msasanmh/SecureDNSClient#111]
سلام ممنون  برای cpu خیلی خوب شده 
 فقط این قسمت  optimize همه جا  خوب ولی  هنوز یکم dpi
![SecureDNSClient_6E7ryQOJhl](https://github.com/msasanmh/SecureDNSClient/assets/131250049/27b344fc-fdd3-4258-8de7-a2d1717e2404)

**Comment by msasanmh** [comment]
در هر صفحه‌ای که دیدی گزینه‌ای روی یکی دیگه افتاده از همون صفحه اسکرین شات بده.
بهمراه مشخصات مانیتورت و تنظیمات رزولوشن و dpi سیستمت. 
اونوقت میتونم در ورژن بعد برطرف شون کنم.
@wolfkingal2000

**Comment by wolfkingal2000** [comment]
> در هر صفحه‌ای که دیدی گزینه‌ای روی یکی دیگه افتاده از همون صفحه اسکرین شات بده. بهمراه مشخصات مانیتورت و تنظیمات رزولوشن و dpi سیستمت. اونوقت میتونم در ورژن بعد برطرف شون کنم. @wolfkingal2000
![SecureDNSClient_7SJjtaTQc9](https://github.com/msasanmh/SecureDNSClient/assets/131250049/5b6c229a-60de-4fc3-ab14-3b5c04dc7a8c)
![SecureDNSClient_aCLKMZAZir](https://github.com/msasanmh/SecureDNSClient/assets/131250049/33ff0244-0bf2-4cf9-bc0b-3c4e35b9b05e)
![SecureDNSClient_HCM2pnd2VI](https://github.com/msasanmh/SecureDNSClient/assets/131250049/e82ed78c-2535-4977-a668-e214ed5d7426)
![SecureDNSClient_TpgZ5BFhJb](https://github.com/msasanmh/SecureDNSClient/assets/131250049/be6af883-4a25-45b8-bc8e-a35c82a94a08)
![SecureDNSClient_HVSSWSJqCt](https://github.com/msasanmh/SecureDNSClient/assets/131250049/9d68ae55-05b1-4937-aa88-b9e7492ca929)
![SecureDNSClient_nGh48az6rh](https://github.com/msasanmh/SecureDNSClient/assets/131250049/af0c50f8-51de-4061-91cf-746b50045e8a)
![SecureDNSClient_JJjBJYDNsf](https://github.com/msasanmh/SecureDNSClient/assets/131250049/7481272d-c23a-4c6a-8c56-c7eae4a34230)
![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/ea653267-c5cd-4a17-9a97-9bead48a2fd6)
  dpi هم نیمدونم از کجا باید دید
  و مال من  لپ تاپه مشخساتش هم همینه lcd  هم  هست

**Comment by msasanmh** [comment]
عالیه، ممنون بابت تصاویر.
میتونی برای dpi روی آیکن ویندوز روی تسکبار راست کلیک کن و بعد به این مسیر برو:
Settings -> System -> Display
و گزینه Scale رو برام بفرست. مرسی

**Comment by wolfkingal2000** [comment]
> عالیه، ممنون بابت تصاویر. میتونی برای dpi روی آیکن ویندوز روی تسکبار راست کلیک کن و بعد به این مسیر برو: Settings -> System -> Display و گزینه Scale رو برام بفرست. مرسی.
> 
> و راستی در بقیه جاها که اسکرین شات ندادی یعنی مشکلی نبود؟ @wolfkingal2000

![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/276c358c-0af5-4585-ba1f-ab1bb3a52442)
اره فقط یکم متن شون بزرگ که مشکلی نداره بنظرم

**Comment by msasanmh** [comment]
> > عالیه، ممنون بابت تصاویر. میتونی برای dpi روی آیکن ویندوز روی تسکبار راست کلیک کن و بعد به این مسیر برو: Settings -> System -> Display و گزینه Scale رو برام بفرست. مرسی.
> > 
> > و راستی در بقیه جاها که اسکرین شات ندادی یعنی مشکلی نبود؟ @wolfkingal2000
> 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/276c358c-0af5-4585-ba1f-ab1bb3a52442)
> اره فقط یکم متن شون بزرگ که مشکلی نداره بنظرم 
> 

یه پیشنهاد دارم. اینطوری من هرچقدر سعی کنم درست کنم dpi رو، فقط میتونم توی ذهنم تصور کنم که درست شده یا نه. چون روی مانیتور من همه چی درسته.
حالا پیشنهاد اینه، من روی dpi کار میکنم و قبل از اینکه نسخه جدید ریلز بدم اول برای تو برنامه رو ارسال میکنم و اگه باز جایی دیدی مشکل داشت برام اسکرین بفرستی و این کار رو تکرار کنیم تا زمانیکه که مشکلی باقی نمونه، اونوقت اسمت یا اسم گیتهابت رو در قسمت About special thanks اضافه می‌کنم.
نظرت چیه؟

**Comment by wolfkingal2000** [comment]
> > > عالیه، ممنون بابت تصاویر. میتونی برای dpi روی آیکن ویندوز روی تسکبار راست کلیک کن و بعد به این مسیر برو: Settings -> System -> Display و گزینه Scale رو برام بفرست. مرسی.
> > > 
> > > و راستی در بقیه جاها که اسکرین شات ندادی یعنی مشکلی نبود؟ @wolfkingal2000
> > 
> > ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/276c358c-0af5-4585-ba1f-ab1bb3a52442)
> > اره فقط یکم متن شون بزرگ که مشکلی نداره بنظرم 
> > 
> 
> یه پیشنهاد دارم. اینطوری من هرچقدر سعی کنم درست کنم dpi رو، فقط میتونم توی ذهنم تصور کنم که درست شده یا نه. چون روی مانیتور من همه چی درسته.
> حالا پیشنهاد اینه، من روی dpi کار میکنم و قبل از اینکه نسخه جدید ریلز بدم اول برای تو برنامه رو ارسال میکنم و اگه باز جایی دیدی مشکل داشت برام اسکرین بفرستی و این کار رو تکرار کنیم تا زمانیکه که مشکلی باقی نمونه، اونوقت اسمت یا اسم گیتهابت رو در قسمت About special thanks اضافه می‌کنم.
> نظرت چیه؟

باشه مشکی حتما

**Comment by msasanmh** [comment]
عالیه، پس این issue باز بمونه تا همینجا در ارتباط باشیم

**Comment by msasanmh** [comment]
خب، از اونجاییکه حدس میزدم ویندوز نمیتونه عرض کنترل ها رو خودش به درستی تشخیص بده یه متد نوشتم برای تعیین عرض.
هر کنترلی که تحت تاثیر متد قرار بگیره رنگ پسزمینه اش نارنجی میشه برای تشخیص بهتر.
به اون رنگ توجه نکن، فقط هرجا چیزی روی چیز دیگه ای بود اسکرین بده.
نمیخوام از کار و زندگیت بزنی، هر زمان وقت کردی تست کن:
https://drive.google.com/file/d/1KkpqSd23qdQDjfe3B7UtixTx06g83Slc/view?usp=sharing
@wolfkingal2000

**Comment by wolfkingal2000** [comment]
> خب، از اونجاییکه حدس میزدم ویندوز نمیتونه عرض کنترل ها رو خودش به درستی تشخیص بده یه متد نوشتم برای تعیین عرض. هر کنترلی که تحت تاثیر متد قرار بگیره رنگ پسزمینه اش نارنجی میشه برای تشخیص بهتر. به اون رنگ توجه نکن، فقط هرجا چیزی روی چیز دیگه ای بود اسکرین بده. نمیخوام از کار و زندگیت بزنی، هر زمان وقت کردی تست کن: https://drive.google.com/file/d/1KkpqSd23qdQDjfe3B7UtixTx06g83Slc/view?usp=sharing @wolfkingal2000

خب چکش کردم خیلی خوب شده دیگه روی هم نیفاد کلا فقط این انگار یکمش از سمت راست معلوم نیست  اون توضیح های  پالیک کی و هش رو میگم ولی کلا مشکلی نداره خیلی خوب شده و ممنون و خسته نباشی 
![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/adb2daef-cad9-41b9-8053-b8c199a3a04d)

**Comment by msasanmh** [comment]
تست دوم:
https://drive.google.com/file/d/1ufhr_vRPZEj-FOWNK32Bb0kxxpbZPxfx/view?usp=drivesdk

یادت باشه این پنجره رو هم چک کنی:
Tools  -> DNS Scanner -> Export
قبلش برنامه باید کانکت باشه، یه سرور هم اسکن کن تا دکمه export فعال بشه.
همینطور پنجره کاستوم سرور.

اگه جایی مشکل وجود داشت فقط از همون اسکرین شات بده، اگه مشکلی نبود بی‌زحمت از همه پنجره‌ها اسکرین بگیر که نحوه قرار گیری کنترل‌ها رو ببینم. این باعث میشه در آینده بدونم دارم چی کار میکنم.
میتونی همه رو داخل فایل زیپ بذاری. هر جور راحتی.
@wolfkingal2000

**Comment by msasanmh** [comment]
> > تست سوم: https://drive.google.com/file/d/1rVMvXRDlwzadQYKG_CLgBcxE7DDUa6Vs/view?usp=drivesdk
> > 
> > فقط یه اسکرین از تب Check کافیه 🙏 @wolfkingal2000
> 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/8e2b77cf-6bf3-4100-84ca-23d7b2b7eb3e)
>  بیا این شد

عالی شد. توی قسمت about برنامه  وقتی لینک به گیتهابت میدم دوست داری اسمش رو چی بنویسم؟

**Comment by wolfkingal2000** [comment]
> > > تست سوم: https://drive.google.com/file/d/1rVMvXRDlwzadQYKG_CLgBcxE7DDUa6Vs/view?usp=drivesdk
> > > 
> > > فقط یه اسکرین از تب Check کافیه 🙏 @wolfkingal2000
> > 
> > ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/8e2b77cf-6bf3-4100-84ca-23d7b2b7eb3e)
> >  بیا این شد
> 
> عالی شد. توی قسمت about برنامه  وقتی لینک به گیتهابت میدم دوست داری اسمش رو چی بنویسم؟

همین آیدی github  رو بنویسی کافی ممنون
