### ISSUE TITLE
Couldn't retrieve information

### ISSUE THREAD

**Issue by Milad-Parsa** [msasanmh/SecureDNSClient#112]
سلام
وقتی در حالت Custom Servers اسکن رو می‌زنم این ارور رو می‌ده:
[Failed] [-1] [Host: https://ha.example.com/dns-query] [Protocol: DNS-Over-HTTPS] [Couldn't retrieve information.]

**Comment by msasanmh** [comment]
> سلام
> وقتی در حالت Custom Servers اسکن رو می‌زنم این ارور رو می‌ده:
> [Failed] [-1] [Host: https://ha.example.com/dns-query] [Protocol: DNS-Over-HTTPS] [Couldn't retrieve information.]
> 

سلام، این ارور نیست، فقط آدرس dns شما در دیتابیس آفلاین برنامه وجود نداره.
و Failed زدنش نشونه فیلتر بودن یا در دسترس نبودن سرور  dns هستش. البته اگه سرور dns شما ip یوتیوب رو بسته باشه باز هم برنامه Failed میزنه. چون از Blocked Address ی که در قسمت تنظیمات وجود داره query گرفته میشه.
درنتیجه اگه دارید dns یا doh های ایرانی رو اسکن میکنید باید آدرس یوتیوب رو از تنظیمات مثلا به گوگل تغییر بدید.

**Comment by Milad-Parsa** [comment]
- سرور در دسترس هست. چون مستقیم توی مرورگر می‌زنم کار می‌کنه.
- یوتیوب رو هم تغییر دادم هم گوگل زدم هم انویدیا ولی کار نکرد

**Comment by msasanmh** [comment]
> - سرور در دسترس هست. چون مستقیم توی مرورگر می‌زنم کار می‌کنه.
> - یوتیوب رو هم تغییر دادم هم گوگل زدم هم انویدیا ولی کار نکرد
> 

در تنظیمات 
Settings -> Check -> Check timeout 
رو بروی 10 بذار و دوباره تست کن.

**Comment by Milad-Parsa** [comment]
> > * سرور در دسترس هست. چون مستقیم توی مرورگر می‌زنم کار می‌کنه.
> > * یوتیوب رو هم تغییر دادم هم گوگل زدم هم انویدیا ولی کار نکرد
> 
> در تنظیمات Settings -> Check -> Check timeout رو بروی 10 بذار و دوباره تست کن.

باز نشد

**Comment by msasanmh** [comment]
> > > * سرور در دسترس هست. چون مستقیم توی مرورگر می‌زنم کار می‌کنه.
> > > * یوتیوب رو هم تغییر دادم هم گوگل زدم هم انویدیا ولی کار نکرد
> > 
> > در تنظیمات Settings -> Check -> Check timeout رو بروی 10 بذار و دوباره تست کن.
> 
> باز هم نشد

پس سرور صددرصد فیلتره و اگه فکر می‌کنید در مرورگر کار میکنه بخاطر اینه که مرورگر اگه آدرس در دسترس نباشه fallback میزنه و از سیستم استفاده میکنه.

**Comment by Milad-Parsa** [comment]
پینگ دارم. فیلتر نیست. مرورگر هم داره ازش استفاده می‌کنه. دی‌ان‌اس سیستم نیست.

**Comment by msasanmh** [comment]
> پینگ دارم. فیلتر نیست. مرورگر هم داره ازش استفاده می‌کنه. دی‌ان‌اس سیستم نیست.

پینگ برای سرور dns مهم نیست، سرور باید جواب query رو بده و dns message بفرسته.
میتونی به این روش هم امتحان کنی:
از قسمت Tools ابزار DNS Lookup رو اجرا کن.
کاستوم رو انتخاب کن و آدرس dns خودت رو مقابلش وارد کن.
قسمت Domain هم google.com بنویس.
بروی Lookup کلیک کن ببین سرور جواب میده یا نه.

اگه کلا به برنامه اعتماد نداری میتونی مستقیم از کاماند لاین dnslookup استفاده کنی:
dnslookup.exe google.com https://YourDnsAddress.com/dns-query 

میتونی این آدرس رو هم که بیشتر جاها فیلتر نیست رو تست کنی:
https://max.rethinkdns.com/dns-query

**Comment by Milad-Parsa** [comment]
درست می‌گی مشکل از سمت سروره. باید چک کنم.
با همین لوکاپ چک کردم جواب نداد.
