### ISSUE TITLE
problem  with set  dns 

### ISSUE THREAD

**Issue by NIOOFARI** [msasanmh/SecureDNSClient#113]
درود
ست دی ان اس set dns را  ورژن جدید  بازم مثل   قبلی ها اجرا نمیکنه  مشکل حل نشده  و مثل ورژن های  بعد 2.7.0  هست   ورژن  2.7.0   برای من  هنوز وصل  میشه ولی   2.8.2   هم   مثل  چند ورژن قبل کار نکرد  پیام صوتی وصل  شدم را اجرا  میکنه   ولی  در عمل  فعال نیست  و نمیشه   باهاش  یوتوب را باز کرد  تصاویر  وضعیت  ضمیمه  شد

 اموزشی که داده بودید هم   اثری نداشت مشکل  از جای دیگری است که بعد  اپدیت   2.7.0  ایجاد شده

ضمنا  سرورها را بعد اینکه برنامه بسته شد در خودش ذخیره نمیکنه و   بعد  بستن دوباره  صفر میشه باید از  ابتدا شروع کرد که کلی وقت  میگیره  
متشکرم

![Capture1](https://github.com/msasanmh/SecureDNSClient/assets/149754932/2793d168-144c-41c2-a4ad-e28f54aeccc2)
![Capture2](https://github.com/msasanmh/SecureDNSClient/assets/149754932/b9190550-acd7-43d1-a8a3-d6b31073be44)
![Capture3](https://github.com/msasanmh/SecureDNSClient/assets/149754932/b9d63004-7e94-48ff-a61e-99a351cec1ef)
![Capture4](https://github.com/msasanmh/SecureDNSClient/assets/149754932/a7bb0a87-fe45-4dcc-bf2a-4e336a6d0f25)

**Comment by msasanmh** [comment]
باز نمیکنه بخاطر اینه که dns ست نشده.
حالا چرا ست نشده؟
به اون خطای قرمز رنگ دقت کن، نوشته Media disconnected این یعنی شما اصلا آنلاین نیستی یا داری dns رو بروی آداپتر دیگه‌ای به اشتباه ست میکنی.
بهت اطمینان میدم مشکل از برنامه نیست.
اول با آداپترت به اینترنت وصل باش و بعد همون آداپتر رو از داخل لیست انتخاب کن و dns رو روش ست کن

**Comment by msasanmh** [comment]
> باز نمیکنه بخاطر اینه که dns ست نشده.
> حالا چرا ست نشده؟
> به اون خطای قرمز رنگ دقت کن، نوشته Media disconnected این یعنی شما داری dns رو بروی آداپتر دیگه‌ای به اشتباه ست میکنی.
> بهت اطمینان میدم مشکل از برنامه نیست.
> اول با آداپترت به اینترنت وصل باش و بعد همون آداپتر رو از داخل لیست انتخاب کن و dns رو روش ست کن

**Comment by msasanmh** [comment]
آقا، از لیست آداپترها اون آداپتری رو انتخاب کن که باهاش به اینترنت وصل هستی.
شما یکی دیگه رو انتخاب کردی.

**Comment by msasanmh** [comment]
> بله   متوجه  شدم  وای فای باید میزدم    ورژن 2.7.0  این  تنظیمات را  نداره  و خودش بای دیفالت رو وای فای هست   اینو متوجه  نبودم چون در اموزش اولیه  گفته  نشده بود و لازم هم نبود تنظیم بشه   دیفالتش رفته بود رو  اترنت در نهایت  وصل  شدم  تنها مشکلی که داره   سرورهای قبلی   را  با  چند دقیقه تاخیر پیدا میکنه  ولی  2.7.0  سریع   می  اورد ولی در کل  مشکلم  حل  شد    متشکرم 

خوشحالم که مشکلت حل شد. 
اون تاخیر بخاطر کنترل مصرف CPU هستش.

**Comment by NIOOFARI** [comment]
خیلی  ممنونم ازت  رو حساب اینکه خودش  مثل   قبل  ست  میشه  بی دقتی و بی توجهی   کرده بودم  مرسی

**Comment by msasanmh** [comment]
> خیلی  ممنونم ازت  رو حساب اینکه خودش  مثل   قبل  ست  میشه  بی دقتی و بی توجهی   کرده بودم  مرسی 

فدات عزیز ❤️
