### ISSUE TITLE
How to combine SDC with VPN?

### ISSUE THREAD

**Issue by aolko** [msasanmh/SecureDNSClient#116]
How do i run both SDC connection and VPN connection? VPN complains about having "no network" or proxy when SDC is on.

**Comment by msasanmh** [comment]
A VPN connection will Override everything. Dns, proxy, etc.
If you want to use both _a DNS Client_ plus _a VPN_, the VPN software must support split tunneling and dns settings, like NordVPN.
If your VPN software doesn't support above requirements then you can't use SecureDNSClient or any other DNS client with it.
