### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by BarsamJahanvash** [msasanmh/SecureDNSClient#118]
درود بر شما
امیدوارم حالتون خوب باشد.
اول تشکر میکنم از برنامه خوبتون و یک خسته نباشید جانانه خدمت شما
مشکلی که برای من به وجود اومده این هست که خیلی وقته دیگه برنامه برای من کار نمیکنه و نمیتونم باهاش یوتوب و... رو باز کنم
اگر میشه در قالب متن یک دور دیگر کار هایی که برای استفاده از اپلیکیشن باید انجام داد و یوتوب رو باز کرد رو برام مینویسید؟

**Comment by msasanmh** [comment]
سلام، ممنون.
اگه جز اون افرادی هستید که از ISP مخابرات یا شاتل استفاده میکنید و پیام inner exception می‌گرفتید، شما باید از روش زیر استفاده کنید:
در فایل ویدئویی همه چیز مشخصه و بزودی به کمک یکی از دوستان راهنمای کامل استفاده قرار میگیره

https://github.com/msasanmh/SecureDNSClient/blob/main/Help/How%20to%20use%20SSL%20Decryption_Farsi.mp4

**Comment by BarsamJahanvash** [comment]
نه از همراه اول یا ایرانسل استفاده میکنم

**Comment by msasanmh** [comment]
> نه از همراه اول یا ایرانسل استفاده میکنم
> 

وقتی بروی Check DPI Bypass کلیک میکنید چه خطایی دریافت میکنی؟

**Comment by msasanmh** [comment]
از این راهنما هم میتونید استفاده کنید: 
[Click Here](https://yasserdivar.ir/secure-dns-client/)

**Comment by BarsamJahanvash** [comment]
> > نه از همراه اول یا ایرانسل استفاده میکنم
> 
> وقتی بروی Check DPI Bypass کلیک میکنید چه خطایی دریافت میکنی؟

Check DPI Bypass:The request was aborted.
Check DPI Bypass: RanToCompletion

**Comment by msasanmh** [comment]
> > > نه از همراه اول یا ایرانسل استفاده میکنم
> > 
> > وقتی بروی Check DPI Bypass کلیک میکنید چه خطایی دریافت میکنی؟
> 
> Check DPI Bypass:The request was aborted.
> Check DPI Bypass: RanToCompletion
> 
> 

این پیام میگه خودت زدی کنسلش کردی، یه جا رو داری اشتباه انجام میدی.
برات دو تا آموزش گذاشتم، طبق اونا عمل کردی؟
اگه عین همون‌ها رو انجام دادی و موفق نشدی، متن‌های داخل log رو کپی کن و اینجا پیست کن تا بخونم شون. 
از قسمت status هم یه اسکرین‌شات بگیر تا بتونم کمکت کنم.
