### ISSUE TITLE
Error: Couldn't start DNSProxy! 

### ISSUE THREAD

**Issue by sonixto** [msasanmh/SecureDNSClient#119]
سلام من مودم موبینت دارم و دیروز sdc ارور Error: Couldn't start DNSProxy! داد.
من 2 ماه هست از این برنامه کار میکنم و بهترین برنامه هست ولی دیروز اون ارور را به من داد.من اینترنت های دیگه را تست کرد ولی کارنکرد من این برنامه را روی یک لپ تاپ دیگر ریختم و راحت کارکرد.من از شما کمک میخواستم

**Comment by msasanmh** [comment]
این پیام یعنی برنامه dnsproxy کرش شده، بعضی از دلایل:

۱. اگه DoH روشن باشه و پورت اشغال باشه اما برنامه نتونه پورت رو اشغال تشخیص بده این مشکل پیش میاد و باید پورت DoH رو تغییر بدید.

۲. ممکنه آنتی‌ویروس جلوی فعالیت dnsproxy رو گرفته باشه که باید در وایت لیست آنتی‌ویروس واردش کنید.

۳. ممکنه یه برنامه مشابه دیگه‌ای نصب داشته باشی که باعث ایجاد تداخل شده.

دلیل دیگه‌ای نداره، اگه تنظیماتی رو تغییر دادی به حالت اول برگردون، اگه حل نشد اول یه بکاپ از تنظیمات بگیر و بعد تنظیمات رو دیفالت کن ببین مشکل حل میشه یا نه.

**Comment by sonixto** [comment]
ببخشید میشه بگویید که 
1چطور برنامه را در وایت لیست انتی ویروس وارد کنم
2چطور بکاپ از تنظیمات بگیرم و بعد دیفالت کنم

**Comment by sonixto** [comment]
من از انتی ویروس روی خود ویندوز استفاده میکنم

**Comment by sonixto** [comment]
برنامه هم دیفالت کردم برنامه جدیدی هم در لپ تاپم نریختم و از doh استفاده نمیکنم

**Comment by sonixto** [comment]
هنوز هم درست نشده

**Comment by sonixto** [comment]
![Screenshot 2023-12-20 165217](https://github.com/msasanmh/SecureDNSClient/assets/154427403/55907c08-9cff-402b-908d-7a8eab15269a)
![Screenshot 2023-12-20 165232](https://github.com/msasanmh/SecureDNSClient/assets/154427403/67388bbf-1ff7-4b05-af4b-0e6f99e69f61)

**Comment by sonixto** [comment]
قبلا هم بعضی وقت ها ارور را میداد ولی دیسکانکت ری کانکت در برنامه میکردم درست می شد

**Comment by sonixto** [comment]
بعضی وقت ها هم برنامه را می خواستم باز کنم می گفت همچین برنامه یا فایلی وجود نداره پس من دوباره از برنامه شورت کات میگرفتم و دوبارخ کارمی کرد.
مطمءن نیستم ولی فکر کنم تازگی از انتی ویروسم در مورد فایل این برنامه امد ولی من ندیدم از چه برنامه ای خست و بلاک را زدم ولی الان میرم تو هیستوری ریپورت ها انجا ننوشته که همچین ریپورتی امده من هم هیستوری کیلیر نکردم
 ببخشید و از زحمت شما تشکر میکنم

**Comment by msasanmh** [comment]
> قبلا هم بعضی وقت ها ارور را میداد ولی دیسکانکت ری کانکت در برنامه میکردم درست می شد
> 

خیلی عجیبه نباید این مشکل پیش بیاد.
مطمئن شو همه ران‌تایم‌های c++ رو نصب داشته باشی.

از تب Connect گزینه دوم رو انتخاب کن ببین وصل میشه یا نه.

**Comment by msasanmh** [comment]
> بعضی وقت ها هم برنامه را می خواستم باز کنم می گفت همچین برنامه یا فایلی وجود نداره پس من دوباره از برنامه شورت کات میگرفتم و دوبارخ کارمی کرد.
> مطمءن نیستم ولی فکر کنم تازگی از انتی ویروسم در مورد فایل این برنامه امد ولی من ندیدم از چه برنامه ای خست و بلاک را زدم ولی الان میرم تو هیستوری ریپورت ها انجا ننوشته که همچین ریپورتی امده من هم هیستوری کیلیر نکردم
>  ببخشید و از زحمت شما تشکر میکنم
> 

وقتی میگه فایلی وجود نداره یعنی حتما آنتی‌ویروس یکی از فایل‌های برنامه رو پاک کرده.
از بابت آنتی‌ویروس مطمئن باش که برنامه گیر نده.

نسخه 32 بیت رو هم تست کن

**Comment by sonixto** [comment]
درست شد نسخه *86 رو امتحان کردم خیلی ممنونم
