### ISSUE TITLE
سؤال

### ISSUE THREAD

**Issue by shabda7** [msasanmh/SecureDNSClient#12]
سلام. می‌شه لطفا یه راهنمایی درباره‌ی تفاوت مودهای مختلف DPI بکنید؟ چه گودبای چه اولی که لایت تا اکستریم داره.
ممنون برای وقتی که می‌گذارید

**Comment by msasanmh** [comment]
گزینه‌هایی که در تب basic هست درواقع حالت‌های مختلفی از تب Advanced هستن که به صورت پیش‌فرض انتخاب شده.
مثلا گزینه light فقط SNI رو فرگمنت میکنه و در جهت مستقیم ارسال میکنه و همینطور که از light به extreme میریم گزینه‌های بیشتری از تب Advanced انتخاب میشه، مثل برعکس فرستادن فرگمنت‌ها یا جایگزین کردن SNI با یه SNI جعلی.
باعث میشه روی ISP های مختلف یکی شون جواب بده.
اینکه هر گزینه دقیقا چه کاری انجام میده رو میتونم فردا برات ارسال کنم اگه بخوای.
چون امشب به PC دسترسی ندارم.

**Comment by shabda7** [comment]
> گزینه‌هایی که در تب basic هست درواقع حالت‌های مختلفی از تب Advanced هستن که به صورت پیش‌فرض انتخاب شده. مثلا گزینه light فقط SNI رو فرگمنت میکنه و در جهت مستقیم ارسال میکنه و همینطور که از light به extreme میریم گزینه‌های بیشتری از تب Advanced انتخاب میشه، مثل برعکس فرستادن فرگمنت‌ها یا جایگزین کردن SNI با یه SNI جعلی. باعث میشه روی ISP های مختلف یکی شون جواب بده. اینکه هر گزینه دقیقا چه کاری انجام میده رو میتونم فردا برات ارسال کنم اگه بخوای. چون امشب به PC دسترسی ندارم.

ممنون می‌شم اگر وقت کنی بفرستی و اگر کلن تو readme بذاری که دیگه خیلی خوب می‌شه و اون مودهای گودبای رو هم بگو لطفا.

**Comment by shabda7** [comment]
> گزینه‌هایی که در تب basic هست درواقع حالت‌های مختلفی از تب Advanced هستن که به صورت پیش‌فرض انتخاب شده. مثلا گزینه light فقط SNI رو فرگمنت میکنه و در جهت مستقیم ارسال میکنه و همینطور که از light به extreme میریم گزینه‌های بیشتری از تب Advanced انتخاب میشه، مثل برعکس فرستادن فرگمنت‌ها یا جایگزین کردن SNI با یه SNI جعلی. باعث میشه روی ISP های مختلف یکی شون جواب بده. اینکه هر گزینه دقیقا چه کاری انجام میده رو میتونم فردا برات ارسال کنم اگه بخوای. چون امشب به PC دسترسی ندارم.

ممنون می‌شم اگر وقت کنی بفرستی و اگر کلن تو readme بذاری که دیگه خیلی خوب می‌شه. اون مودهای گودبای هم بگو لطفا.

**Comment by shabda7** [comment]
> گزینه‌هایی که در تب basic هست درواقع حالت‌های مختلفی از تب Advanced هستن که به صورت پیش‌فرض انتخاب شده. مثلا گزینه light فقط SNI رو فرگمنت میکنه و در جهت مستقیم ارسال میکنه و همینطور که از light به extreme میریم گزینه‌های بیشتری از تب Advanced انتخاب میشه، مثل برعکس فرستادن فرگمنت‌ها یا جایگزین کردن SNI با یه SNI جعلی. باعث میشه روی ISP های مختلف یکی شون جواب بده. اینکه هر گزینه دقیقا چه کاری انجام میده رو میتونم فردا برات ارسال کنم اگه بخوای. چون امشب به PC دسترسی ندارم.

ممنون می‌شم اگر وقت کنی و یه توضیح کلی بدی. جزئیات فنی‌ش خیلی لازم نمی‌شه واقعا و اگر کلن تو readme بذاری که دیگه خیلی خوب می‌شه و اون مودهای گودبای رو هم بگو لطفا.

**Comment by msasanmh** [comment]
> > گزینه‌هایی که در تب basic هست درواقع حالت‌های مختلفی از تب Advanced هستن که به صورت پیش‌فرض انتخاب شده. مثلا گزینه light فقط SNI رو فرگمنت میکنه و در جهت مستقیم ارسال میکنه و همینطور که از light به extreme میریم گزینه‌های بیشتری از تب Advanced انتخاب میشه، مثل برعکس فرستادن فرگمنت‌ها یا جایگزین کردن SNI با یه SNI جعلی. باعث میشه روی ISP های مختلف یکی شون جواب بده. اینکه هر گزینه دقیقا چه کاری انجام میده رو میتونم فردا برات ارسال کنم اگه بخوای. چون امشب به PC دسترسی ندارم.
> 
> ممنون می‌شم اگر وقت کنی و یه توضیح کلی بدی. جزئیات فنی‌ش خیلی لازم نمی‌شه واقعا و اگر کلن تو readme بذاری که دیگه خیلی خوب می‌شه و اون مودهای گودبای رو هم بگو لطفا.

داخل این صفحه گذاشتم:
https://github.com/msasanmh/SecureDNSClient/blob/main/How%20to%20use%20(Farsi)/README.md

**Comment by msasanmh** [comment]
> توی DOH برای اضافه کردن دامین به ورکر، cname رو به هر آدرسی می‌شه زد؟ و گزینه‌ی پروکسی خاموش باشه یا روشن؟

این توضیحش طولانیه، از این ویدیو وحید فرید استفاده کن. کامل توضیح داده:
https://www.youtube.com/watch?v=Hdom5IZIzJQ
و پروکسی رو بعد اینکه برای دامین سرتیفیکیت گرفتی روشن کن.

**Comment by shabda7** [comment]
> > توی DOH برای اضافه کردن دامین به ورکر، cname رو به هر آدرسی می‌شه زد؟ و گزینه‌ی پروکسی خاموش باشه یا روشن؟
> 
> این توضیحش طولانیه، از این ویدیو وحید فرید استفاده کن. کامل توضیح داده: https://www.youtube.com/watch?v=Hdom5IZIzJQ و پروکسی رو بعد اینکه برای دامین سرتیفیکیت گرفتی روشن کن.

ممنون. این رو قبلن انجام دادم. منظورم این رپو بود
https://github.com/msasanmh/cf-workers-dns-over-https
برای اینم همون جوری پیش می‌ره؟

**Comment by msasanmh** [comment]
> > > توی DOH برای اضافه کردن دامین به ورکر، cname رو به هر آدرسی می‌شه زد؟ و گزینه‌ی پروکسی خاموش باشه یا روشن؟
> > 
> > این توضیحش طولانیه، از این ویدیو وحید فرید استفاده کن. کامل توضیح داده: https://www.youtube.com/watch?v=Hdom5IZIzJQ و پروکسی رو بعد اینکه برای دامین سرتیفیکیت گرفتی روشن کن.
> 
> ممنون. این رو قبلن انجام دادم. منظورم این رپو بود
> https://github.com/msasanmh/cf-workers-dns-over-https
> برای اینم همون جوری پیش می‌ره؟

آره اینم همونطوره، از وسط ویدئو به بعد توضیح میده چطور به ورکر وصلش کنی.
