### ISSUE TITLE
نحوه اجرا بدون دسترسی ادمین

### ISSUE THREAD

**Issue by BugHunter021** [msasanmh/SecureDNSClient#120]
**سلام ممنون از برنامه بسیار عالیت** 

یه درخواستی دارم ازت و اونم اینه که چجوری میتونم **بدون دسترسی ادمین** اجراش کنم؟
توی شبکه مون یوزرها دسترسی محدودی دارن.مثلا برای پورت باز کردن مشکل نداریم و میتونیم پروکسی ران کنیم اما تغییر DNS و تغییر تنظیمات کارت شبکه خیر.
روی سیستم با دسترسی ادمین تست کردم روی SecureDNSClient تنها با اسکن مرحله اول و کانکت مرحله دوم و استارت پروکسی و ست کردن پورت روی مرورگر همه چی خوب کار میکنه و نیاز به مرحله سوم که ست کردن DNS هستش ندارم همچنین مرحله آخر که GoodbyeDPI هستش.

سوالم اینه که آیا با همین تنظیمات اندک میتونم بدون دسترسی ادمین ازش استفاده کنم ؟
دوم اینکه اگه با یوزر با دسترسی پایین میشه ران کرد چطوری باید بخش های اضافه که دسترسی ادمین میخاد رو حذف کنم که در ابتدای اجرا ازم دسترسی ادمین نخواد؟

میخواستم روی سورس کدش خودم کار کنم و یه **فورک جدید برای اجرا با یوزر محدود شده** بسازم اما اولش گفتم با شما درمیون بزارم که نظرتون چیه؟
راه سریع تری سراغ دارید ؟
لطفا راهنماییم کنید.متشکرم

**Comment by msasanmh** [comment]
اینکه گفتید تست کردید و بدون ست dns کار کرد، قطعا موقت یا بخاطر اختلال اینترنت بوده که باعث شده ip درست برگشت داده بشه.
پراکسی بدون داشتن ip واقعی نمی‌تونه کاری انجام بده.
اگه دسترسی ادمین نباشه حدود ۹۰ درصد کارایی برنامه ازبین میره.

اما شما گفتی یه فورک بگیری و دسترسی ادمین رو برداری، باید بدونی دیگه اسکن کردن dns ها و حتی کانکت شدن بی‌فایده است چون dns نمیتونه ست بشه.
اما پراکسی میتونه بصورت مستقیم dns ساپورت کنه بدون اینکه dns بروی سیستم ست بشه.

برای این کار، یعنی بدون دسترسی ادمین فقط این یک روش ممکنه:
از تنظیمات پراکسی گزینه fake dns باید فعال بشه.
حالت dpi bypass پراکسی باید بروی فرگمنت قرار داده بشه نه بروی ssl decryption و بعد کافیه پراکسی اجرا بشه و در مرورگر ست بشه.

این کار بالا در بکگراند به این شکل اجرا میشه:
دو تا پراکسی اجرا میشن.
پراکسی اول وظیفه دور زدن doh کلودفلر رو داره.
پراکسی دوم از پراکسی اول استفاده میکنه تا ip های اصلی رو بدست بیاره.

پس تنها راه اینه که فورک شخصی خودتون رو بسازید و فقط از پراکسی استفاده کنید.
