### ISSUE TITLE
Changing the following addresses from official to unofficial

### ISSUE THREAD

**Issue by Noob2Pr0** [msasanmh/SecureDNSClient#122]
سلام دوست من
متاسفانه ادرس های زیر در بعضی از انتی ویروس ها از نظیر بیت دفندر مورد بلاک شدن قرار می گیرن
https://nsc.torgues.net/
https://dns.nguyendn.com/
https://cloud.tezoi.com/
https://dns.silentlybren.com/
https://dns.cretu.xyz/
https://www.dnsadguard.co.uk/
https://yovbak.com/
که جدا از آزاردهنده بودن ناتیفیکیشن این ادرس ها به علت های فیشینگ و صفحات الوده، قطعا مشکلات امنیتی به دنبال خواهد داشت
طبیعتاً ساده ترین کار استثنا دونستن این ادرس ها در پیکربندی انتی ویروس هستش
اما ترجیح میدم به دلیل رفع مشکلات امنیتی و افزایش بهبود عملکرد ابزار فوق العاده شما
این ادرس ها رو اعلام تا فقط با جا به جایی این ادرس ها از بخش رسمی به بخش غیر رسمی مسئولیت استفاده از ادرس های فوق به عهده کاربر باشد.

EN:
Hello my friend
Unfortunately, the following addresses are blocked in some antiviruses, such as Bitdefender,
https://nsc.torgues.net/
https://dns.nguyendn.com/
https://cloud.tezoi.com/
https://dns.silentlybren.com/
https://dns.cretu.xyz/
https://www.dnsadguard.co.uk/
https://yovbak.com/
which apart from the annoying notification of these addresses due to phishing and infected pages, will definitely cause security problems.
absolutely, the easiest thing to do is to exception these addresses in the antivirus configuration
But I prefer it because of the security issues and increased performance improvement of your wonderful tool
Announce these addresses so that only by moving these addresses from the official part to the unofficial part, the user is responsible for using the above addresses.

**Comment by nonbarbari** [comment]
سلام راست میگه میتونی لیست DNS داخلی ها رو داخل این وب سایت [https://www.virustotal.com/gui/home/url](url) چک کنی و اون مشکوک ها رو حذف کنی که وسط اسکن انتی ویروساشون گیر نده بهشون

**Comment by msasanmh** [comment]
اگه یه کم زودتر می‌گفتید توی ورژن 2.8.5 اعمال می‌کردم. دیگه متاسفانه باید بمونه برای ورژن بعدتر.
و ممنون بابت اطلاع. 
@Noob2Pr0

**Comment by Noob2Pr0** [comment]
فدا سرت، مهم اینه که راحتی و امنیت کلاینت برقرار بشه
ممنون بابت پشتیبانی و پاسخگویی ♥
