### ISSUE TITLE
Microsoft.NETcore.App error 

### ISSUE THREAD

**Issue by mztd006** [msasanmh/SecureDNSClient#123]
با سلام
بعد از اجرای نسخه2.8.5 portable/installer  این ارور رو نمایش میده بعد از نصب run time هم باز همچنان همین پنجره نشان داده میشه
![Screenshot 2024-01-04 072029](https://github.com/msasanmh/SecureDNSClient/assets/131897783/335a1090-39c7-4c79-a73a-8bc98e120f57)

**Comment by msasanmh** [comment]
برای شما نیاز به آپدیت داره، این نسخه رو نصب کن:
[.Net Destop 6.0.25 x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.25-windows-x64-installer)

**Comment by mostafa9112** [comment]
برای منم همین ارور رو میده که نسخه 6.0.27 که آخرین هست نصب کردم اما همچان ارور رو داره

**Comment by msasanmh** [comment]
> برای منم همین ارور رو میده که نسخه 6.0.27 که آخرین هست نصب کردم اما همچان ارور رو داره

ببینید صفحه دانلود رانتایم [اینجاست](https://dotnet.microsoft.com/en-us/download/dotnet/6.0).

شما دو تا انتخاب داری، یا SDK رو نصب میکنی یا 
.NET Destop Runtime + ASP .NET Core

پس اگه ASP .NET Core رو نصب ندارید نصب کنید.
من باید پیش‌نیاز برنامه رو آپدیت کنم تا شما این شکلی با مشکل روبرو نشید.
