### ISSUE TITLE
It does not start automatically at startup.

### ISSUE THREAD

**Issue by DogancanYr** [msasanmh/SecureDNSClient#124]
The application opens but does not make quick connect.

**Comment by msasanmh** [comment]
Did you check the "Execute quick connect on startup" option?
Because I just turned on my pc and sdc started to connect on startup.

**Comment by DogancanYr** [comment]
Yes. **By the way, I am using the installer option.

**Comment by msasanmh** [comment]
I just applied the installer version on startup  and restarted pc, it worked as expected. 

This is the installer version: 
![20240105_191721.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/5ab3d8cd-f02e-453d-aeda-5c0635bbc590)

Can you see **"Network Detected"** in your log?

**Comment by DogancanYr** [comment]
Yes.

Initializing...
Waiting for Network...
Network Detected (Up Time: 3 Seconds, 484 Milliseconds)

Also, it opens itself as a window. (It does not start minimized.)

**Comment by msasanmh** [comment]
> Also, it opens itself as a window. (It does not start minimized.)

Oh, so that's why the app thinks you started it manually not from startup.
Please remove from startup and apply it to startup up again. 
And let me know if problem solved.

**Comment by msasanmh** [comment]
You can only set one version to startup, installer or portable. 

So you mean problem is fixed?

**Comment by DogancanYr** [comment]
I deleted the installer one and installed the no installer one, it didn't work in both. It works in the previous version .

**Comment by msasanmh** [comment]
You mean it opens itself as a window? And not minimized?

**Comment by DogancanYr** [comment]
In version 2.8.5, it does not start automatically and starts in window mode.
It works in version 2.8.2.

**Comment by msasanmh** [comment]
> In version 2.8.5, it does not start automatically and starts in window mode.
> It works in version 2.8.2.

Let me ask others to test.
I can't replicate your issue, it works normally on my pc.

**Comment by DogancanYr** [comment]
> > In version 2.8.5, it does not start automatically and starts in window mode.
> > It works in version 2.8.2.
> 
> Let me ask others to test. I can't replicate your issue, it works normally on my pc.

Does it work on virtual machine ?

**Comment by msasanmh** [comment]
> > > In version 2.8.5, it does not start automatically and starts in window mode.
> > > It works in version 2.8.2.
> > 
> > Let me ask others to test. I can't replicate your issue, it works normally on my pc.
> 
> Does it work on virtual machine ?
> 

I never tested in on virtual machines, but I guess not all part of application would be compatible. 

Do you have this issue on virtual machine?

**Comment by DogancanYr** [comment]
> > > > In version 2.8.5, it does not start automatically and starts in window mode.
> > > > It works in version 2.8.2.
> > > 
> > > 
> > > Let me ask others to test. I can't replicate your issue, it works normally on my pc.
> > 
> > 
> > Does it work on virtual machine ?
> 
> I never tested in on virtual machines, but I guess not all part of application would be compatible.
> 
> Do you have this issue on virtual machine?

When I tried it on the virtual machine, the application ran automatically, but although it did not bypass the sites and did not give a connection error. I guess the virtual machine uses special dll to get the internet from the hardware.

**Comment by DogancanYr** [comment]
I completely uninstalled it with BCuninstaller and made sure it wasn't there anymore, but I wonder where I'm wrong?

**Comment by DogancanYr** [comment]
I use it as in the guide.
It starts in the virtual machine but not on my own computer.

**Comment by msasanmh** [comment]
> I use it as in the guide. It starts in the virtual machine but not on my own computer.

Open Task Scheduler. The action and command line should b like this:
![sssssssss](https://github.com/msasanmh/SecureDNSClient/assets/1586825/730afa4f-10ff-43a5-b450-b50f94d45d15)

**Comment by DogancanYr** [comment]
İn this wise and when I right click on it and click run, it still doesn't work.

**Comment by msasanmh** [comment]
> İn this wise and when I right click on it and click run, it still doesn't work.
> 

That Run button does not intend to run the application. 

Just check the command line arguments, they must be like the picture I attached. 

Also you can test the app with arguments: 

SecureDNSClient.exe -IsPortable=True -IsStartup=True

The above command must run the app as portable and minimized, and if you have the "Execute quick connect on startup" checked, it must connect automatically.

**Comment by DogancanYr** [comment]
I made some attempts and it still didn't change. Never mind, maybe it will be fixed in the next update.

**Comment by msasanmh** [comment]
How can it be fixed in next update if i don't change anything.
your problem is that the app doesn't start minimize.
please take a screenshot and show me this part:
![Screenshot 2024-01-05 221925](https://github.com/msasanmh/SecureDNSClient/assets/1586825/d3eb633f-5fdd-4c91-9611-4c13789931d6)

**Comment by DogancanYr** [comment]
![image](https://github.com/msasanmh/SecureDNSClient/assets/90002969/8efef2a9-8085-46e0-a4d4-4113f4b7c886)
The problem is not general, it is specific to me, maybe it will be fixed magically. Because it works in other versions.

**Comment by msasanmh** [comment]
OK, I was just trying to find what cause this issue.
Please let me know whenever you found the cause.

Anyway I uploaded a video of my startup:
https://drive.google.com/file/d/18nwP9oCS4k6_ZJFp1HxdTEbf4F-Rg-mu/view?usp=drivesdk

**Comment by msasanmh** [comment]
> My Windows user name is the same. I just changed the system language Turkish to English.

Thank you for letting me know. I'm gonna work on it.
