### ISSUE TITLE
DPI Glitch: Game Keeps Returning to Background

### ISSUE THREAD

**Issue by HenryPorternew** [msasanmh/SecureDNSClient#125]
When the app is running in the background and you enter a game with lower DPI settings, a display-changing notification appears. Despite clicking 'OK' and returning to the game, it consistently reverts to the background. Each time you access the game, the DPI changes, and the notification reappears.

موقع وارد شدن به بازی که رزولوشن آن با رزولوشن اسکرین فرق داشته باشه نوتیفیکیشن تغییر رزولوش میاد بالا و بازی را میفرسته بک گراند اگه هم اوکی را بزنیم و برگردیم به بازی دوباره رزولوشن که تغییر میکنه نوتیفیکشن میاد بالا و بازی میره بکگراند

**Comment by msasanmh** [comment]
I thought everyone play games on full screen, there's nothing you can do about it right now.
I'm gonna make this optional through settings to avoid this issue.
On next version of course.

**Comment by msasanmh** [comment]
Applied.
