### ISSUE TITLE
add these features 

### ISSUE THREAD

**Issue by nonbarbari** [msasanmh/SecureDNSClient#126]
1. کلید خروج از برنامه داخل برنامه 
2. آیکون کنار ساعت این چیز ها رو نشون بده (به کدام گروه از سرور های کاستوم وصل شده یا به بیلت این ها وصل شده . موقعی که برنامه در حال وصل شدن هست موقعیتش رو هم بگه مثلا بگه در حال چک کردنه یا در حال ست کردن DNS هستش)
3. اضافه کردن قابلیت ری اسکن کردن یا چک کردن مجدد خود کار سرور ها (تب 1) برای پیدا کردن و جایگزین کردن سرور های بیشتر و سریع تر(موقعی که برنامه کانکت هست قراره فعال باشه تا لیست ورکینگ سرور ها بروز باشه)

### برای حل مشکلات تحریم ها
1. کلید برای دادن یه IP نامعتبر و سابنت نامعتبر + DNS و Proxy نا معتبر برای قطع سریع تر اینترنت داخل تب 3 (0.0.0.0) میتونه برای همه شون استفاده شه
2. استفاده نکردن از DNS سیستم و ست بودن 0.0.0.0 برای DNS و Proxy  داخل سیسم موقع اسکن(چک کردن سرور ها) برای قطع نگه داشتن اینترنت از موقع بالا اومدن ویندوز تا موقع وصل شدن
2.1. وقتی از DNS سیستم استفاده نشه این قابلیت رو میشه اضافه کرد که برنامه برای چک کردن DNS سرور ها از یه لیست خاصی از سرور ها استفاده کنه مزییت هاش : استفاده از سرور های بیشتر از 2 تا . استفاده از سرور های خاص و قاطی نشدن با سرور های تحریم شکن . وابسته نبودن برنامه به DNS سیستم و کار کردن برنامه در مواقعی که سیستم DNS سالم نداره . چک کردن سرور ها با چندین DNS و افزایش شانس پیدا کردن IP درست برای سرور ها 
3. مثل کلید Check DPI Bypass یه کلید باشه که چک کنه تحریم شکن به درستی داره کار میکنه یا ن میتونه برنامه یه دامنه تحریم شده بگیره(داخل تنظیمات) و وقتی روی این کلید کلیک شد چک کنه که DNS سرور داره اینو پروکسی میکنه یا ن
4. اضافه کردن این ویژگی که همون دامنه مورد قبلی یا یه لیست از دامنه ها رو بگیره و مدام پروکسی شدن شون رو چک کنه یا مواقع خاص مثلا موقع تغییر سرور یا قطع و وصل کردن پروکسی شدن شون رو چک کنه و اگر دید پروکسی نمیشن هشدار بده که تحریم شکن کار نمیکنه

**Comment by nonbarbari** [comment]
برای مورد اول برنامه میتونه قانون های فایروال هم تغییر بده

**Comment by msasanmh** [comment]
> 1. کلید خروج از برنامه داخل برنامه 

پیدا کردن جای مناسب برای گذاشتن دکمه برام واقعا مشکل بحساب میاد، اگر پیشنهادی داری بده.

> 2. آیکون کنار ساعت این چیز ها رو نشون بده (به کدام گروه از سرور های کاستوم وصل شده یا به بیلت این ها وصل شده . موقعی که برنامه در حال وصل شدن هست موقعیتش رو هم بگه مثلا بگه در حال چک کردنه یا در حال ست کردن DNS هستش)

قسمت اول اگه اسم گروه طولانی باشه بخاطر محدودیت گذاشتن متن روی آیکن ممکنه هیچ متنی نشون داده نشه.
قسمت دوم رو میشه انجام داد که درحال انجام چه کاریه.

> 3. اضافه کردن قابلیت ری اسکن کردن یا چک کردن مجدد خود کار سرور ها (تب 1) برای پیدا کردن و جایگزین کردن سرور های بیشتر و سریع تر(موقعی که برنامه کانکت هست قراره فعال باشه تا لیست ورکینگ سرور ها بروز باشه)
> 

این کار بطور اتوماتیک هر ۶ ساعت یک بار در بکگراند انجام میشه.

> ### برای حل مشکلات تحریم ها
> 1. کلید برای دادن یه IP نامعتبر و سابنت نامعتبر + DNS و Proxy نا معتبر برای قطع سریع تر اینترنت داخل تب 3 (0.0.0.0) میتونه برای همه شون استفاده شه

براساس تحقیقات خودم همه روش‌ها قابل دور زدنه بغیر از غیرفعال کردن آداپتر

> 2. استفاده نکردن از DNS سیستم و ست بودن 0.0.0.0 برای DNS و Proxy  داخل سیسم موقع اسکن(چک کردن سرور ها) برای قطع نگه داشتن اینترنت از موقع بالا اومدن ویندوز تا موقع وصل شدن

میشه از موقع بالا اومدن برنامه تا زمان وصل شدن این کار رو انجام داد نه از زمان بالا اومدن ویندوز، چون بدون نصب سرویس نمیشه.

> 2.1. وقتی از DNS سیستم استفاده نشه این قابلیت رو میشه اضافه کرد که برنامه برای چک کردن DNS سرور ها از یه لیست خاصی از سرور ها استفاده کنه مزییت هاش : استفاده از سرور های بیشتر از 2 تا . استفاده از سرور های خاص و قاطی نشدن با سرور های تحریم شکن . وابسته نبودن برنامه به DNS سیستم و کار کردن برنامه در مواقعی که سیستم DNS سالم نداره . چک کردن سرور ها با چندین DNS و افزایش شانس پیدا کردن IP درست برای سرور ها 

این میشه همون استفاده از Bootstrap که باید منتظر بمونیم تا dnslookup ساپورتش کنه.
البته الانم برنامه به dns سیستم وابسته نیست و برای گرفتن ip از همه سرورهایی که بهش متصله استفاده میکنه.

> 3. مثل کلید Check DPI Bypass یه کلید باشه که چک کنه تحریم شکن به درستی داره کار میکنه یا ن میتونه برنامه یه دامنه تحریم شده بگیره(داخل تنظیمات) و وقتی روی این کلید کلیک شد چک کنه که DNS سرور داره اینو پروکسی میکنه یا ن

میتونم در قسمتی مثل tools اضافه کنم.

> 4. اضافه کردن این ویژگی که همون دامنه مورد قبلی یا یه لیست از دامنه ها رو بگیره و مدام پروکسی شدن شون رو چک کنه یا مواقع خاص مثلا موقع تغییر سرور یا قطع و وصل کردن پروکسی شدن شون رو چک کنه و اگر دید پروکسی نمیشن هشدار بده که تحریم شکن کار نمیکنه

انجام این کار چون سنگین بود به قسمت dns scanner اضافه شد اما چک کردن یک دامنه نباید مشکلی باشه

**Comment by nonbarbari** [comment]
> > 1. کلید خروج از برنامه داخل برنامه
> 
> پیدا کردن جای مناسب برای گذاشتن دکمه برام واقعا مشکل بحساب میاد، اگر پیشنهادی داری بده.
> 
کنار بنچ مارک توی استاتوس 😅
> > 2. آیکون کنار ساعت این چیز ها رو نشون بده (به کدام گروه از سرور های کاستوم وصل شده یا به بیلت این ها وصل شده . موقعی که برنامه در حال وصل شدن هست موقعیتش رو هم بگه مثلا بگه در حال چک کردنه یا در حال ست کردن DNS هستش)
> 
> قسمت اول اگه اسم گروه طولانی باشه بخاطر محدودیت گذاشتن متن روی آیکن ممکنه هیچ متنی نشون داده نشه. قسمت دوم رو میشه انجام داد که درحال انجام چه کاریه.
> 
واسه اسم های طولانی یه بخشیش رو نشون بده بقیش سه نقطه
> > 3. اضافه کردن قابلیت ری اسکن کردن یا چک کردن مجدد خود کار سرور ها (تب 1) برای پیدا کردن و جایگزین کردن سرور های بیشتر و سریع تر(موقعی که برنامه کانکت هست قراره فعال باشه تا لیست ورکینگ سرور ها بروز باشه)
> 
> این کار بطور اتوماتیک هر ۶ ساعت یک بار در بکگراند انجام میشه.
> 
👍
> > ### برای حل مشکلات تحریم ها
> > 
> > 1. کلید برای دادن یه IP نامعتبر و سابنت نامعتبر + DNS و Proxy نا معتبر برای قطع سریع تر اینترنت داخل تب 3 (0.0.0.0) میتونه برای همه شون استفاده شه
> 
> براساس تحقیقات خودم همه روش‌ها قابل دور زدنه بغیر از غیرفعال کردن آداپتر
> 
والا حالا خیلی سخت گیری هم نیاز نیست واسه کرک و گذر از تحریم و اینا جوابه همینا (از طریق فایر وال هم میشه اینترنت رو نابود کرد یه جوری که فقط خود SDC اینترنت داشته باشه)
> > 2. استفاده نکردن از DNS سیستم و ست بودن 0.0.0.0 برای DNS و Proxy  داخل سیسم موقع اسکن(چک کردن سرور ها) برای قطع نگه داشتن اینترنت از موقع بالا اومدن ویندوز تا موقع وصل شدن
> 
> میشه از موقع بالا اومدن برنامه تا زمان وصل شدن این کار رو انجام داد نه از زمان بالا اومدن ویندوز، چون بدون نصب سرویس نمیشه.
> 
میشه سرویس اضافه کرد که موقع خاموش شدن ویندوز این کارا انجام بشه که موقع بالا اومدن همه چی ردیف باشه و نت وجود نداشته باشه واسه چیز های دیگه ؟
> > 2.1. وقتی از DNS سیستم استفاده نشه این قابلیت رو میشه اضافه کرد که برنامه برای چک کردن DNS سرور ها از یه لیست خاصی از سرور ها استفاده کنه مزییت هاش : استفاده از سرور های بیشتر از 2 تا . استفاده از سرور های خاص و قاطی نشدن با سرور های تحریم شکن . وابسته نبودن برنامه به DNS سیستم و کار کردن برنامه در مواقعی که سیستم DNS سالم نداره . چک کردن سرور ها با چندین DNS و افزایش شانس پیدا کردن IP درست برای سرور ها
> 
> این میشه همون استفاده از Bootstrap که باید منتظر بمونیم تا dnslookup ساپورتش کنه. البته الانم برنامه به dns سیستم وابسته نیست و برای گرفتن ip از همه سرورهایی که بهش متصله استفاده میکنه.
> 
یعنی فعلا که ساپورت نمیکنه نمیشه کاریش کرد؟
> > 3. مثل کلید Check DPI Bypass یه کلید باشه که چک کنه تحریم شکن به درستی داره کار میکنه یا ن میتونه برنامه یه دامنه تحریم شده بگیره(داخل تنظیمات) و وقتی روی این کلید کلیک شد چک کنه که DNS سرور داره اینو پروکسی میکنه یا ن
> 
> میتونم در قسمتی مثل tools اضافه کنم.
>
اون وقت نتیجه پاپ آپ نباشه ها تو همون لاگ نوشته شه کلا اون جا همه ابزار ها پاپ آپ هستن ممکنه کاربرا گیج بشن هی کلیک کنن ببینن چیزی باز نمیشه فکر کنن سیستم شون هنگ کرده
میتونی به لاگ اضافه کنی که خود کار بعد از وصل شدن برسی بشه و این که داخل استاتوس هم یه نشونه ای باشه از این که به تحریم شکن وصل شده 
> > 4. اضافه کردن این ویژگی که همون دامنه مورد قبلی یا یه لیست از دامنه ها رو بگیره و مدام پروکسی شدن شون رو چک کنه یا مواقع خاص مثلا موقع تغییر سرور یا قطع و وصل کردن پروکسی شدن شون رو چک کنه و اگر دید پروکسی نمیشن هشدار بده که تحریم شکن کار نمیکنه
> 
> انجام این کار چون سنگین بود به قسمت dns scanner اضافه شد اما چک کردن یک دامنه نباید مشکلی باشه

آره خوبه مثلا یه گزینه باشه که هر چند وقت یک بار این کار انجام بشه

**Comment by msasanmh** [comment]
> > > 1. کلید خروج از برنامه داخل برنامه
> > 
> > پیدا کردن جای مناسب برای گذاشتن دکمه برام واقعا مشکل بحساب میاد، اگر پیشنهادی داری بده.
> > 
> کنار بنچ مارک توی استاتوس 😅

ببینم جا میشه یا نه 😄

> > > 2. آیکون کنار ساعت این چیز ها رو نشون بده (به کدام گروه از سرور های کاستوم وصل شده یا به بیلت این ها وصل شده . موقعی که برنامه در حال وصل شدن هست موقعیتش رو هم بگه مثلا بگه در حال چک کردنه یا در حال ست کردن DNS هستش)
> > 
> > قسمت اول اگه اسم گروه طولانی باشه بخاطر محدودیت گذاشتن متن روی آیکن ممکنه هیچ متنی نشون داده نشه. قسمت دوم رو میشه انجام داد که درحال انجام چه کاریه.
> > 
> واسه اسم های طولانی یه بخشیش رو نشون بده بقیش سه نقطه

باشه.

> > > 3. اضافه کردن قابلیت ری اسکن کردن یا چک کردن مجدد خود کار سرور ها (تب 1) برای پیدا کردن و جایگزین کردن سرور های بیشتر و سریع تر(موقعی که برنامه کانکت هست قراره فعال باشه تا لیست ورکینگ سرور ها بروز باشه)
> > 
> > این کار بطور اتوماتیک هر ۶ ساعت یک بار در بکگراند انجام میشه.
> > 
> 👍
> > > ### برای حل مشکلات تحریم ها
> > > 
> > > 1. کلید برای دادن یه IP نامعتبر و سابنت نامعتبر + DNS و Proxy نا معتبر برای قطع سریع تر اینترنت داخل تب 3 (0.0.0.0) میتونه برای همه شون استفاده شه
> > 
> > براساس تحقیقات خودم همه روش‌ها قابل دور زدنه بغیر از غیرفعال کردن آداپتر
> > 
> والا حالا خیلی سخت گیری هم نیاز نیست واسه کرک و گذر از تحریم و اینا جوابه همینا (از طریق فایر وال هم میشه اینترنت رو نابود کرد یه جوری که فقط خود SDC اینترنت داشته باشه)

همه که از فایروال ویندوز استفاده نمی‌کنن

> > > 2. استفاده نکردن از DNS سیستم و ست بودن 0.0.0.0 برای DNS و Proxy  داخل سیسم موقع اسکن(چک کردن سرور ها) برای قطع نگه داشتن اینترنت از موقع بالا اومدن ویندوز تا موقع وصل شدن
> > 
> > میشه از موقع بالا اومدن برنامه تا زمان وصل شدن این کار رو انجام داد نه از زمان بالا اومدن ویندوز، چون بدون نصب سرویس نمیشه.
> > 
> میشه سرویس اضافه کرد که موقع خاموش شدن ویندوز این کارا انجام بشه که موقع بالا اومدن همه چی ردیف باشه و نت وجود نداشته باشه واسه چیز های دیگه ؟

مایکروسافت سالهاست که این امکان رو از ما گرفته، یعنی موقع خاموش شدن ما فقط ۵۰۰ میلی‌ثانیه فرصت داریم کاری انجام بدیم و به گفته خود مایکروسافت اگه کاربر برنامه‌ای رو exit نکنه و یهو شات‌داون کنه هر مشکلی پیش بیاد مسئولیتش با کاربره نه برنامه‌نویس.
این کار رو کرده تا هیچ ویروسی نتونه جلوی خاموش شدن ویندوز رو بگیره.
تنها تفاوت سرویس اینه که زودتر از برنامه اجرا میشه.

> > > 2.1. وقتی از DNS سیستم استفاده نشه این قابلیت رو میشه اضافه کرد که برنامه برای چک کردن DNS سرور ها از یه لیست خاصی از سرور ها استفاده کنه مزییت هاش : استفاده از سرور های بیشتر از 2 تا . استفاده از سرور های خاص و قاطی نشدن با سرور های تحریم شکن . وابسته نبودن برنامه به DNS سیستم و کار کردن برنامه در مواقعی که سیستم DNS سالم نداره . چک کردن سرور ها با چندین DNS و افزایش شانس پیدا کردن IP درست برای سرور ها
> > 
> > این میشه همون استفاده از Bootstrap که باید منتظر بمونیم تا dnslookup ساپورتش کنه. البته الانم برنامه به dns سیستم وابسته نیست و برای گرفتن ip از همه سرورهایی که بهش متصله استفاده میکنه.
> > 
> یعنی فعلا که ساپورت نمیکنه نمیشه کاریش کرد؟

قبلا یه کاریش کرده بودم اما حدود ۴۰ درصد احتمال داشت سرور رو failed بزنه که به دلم ننشست و حذفش کردم.
راستی چک کردن سرور با بیش از یک dns اصلا کاربردی نیست، چون موقع کانکت و استفاده میتونه مشکل در اتصال ایجاد کنه با اینکه dnsproxy بیش از یک Bootstrap رو ساپورت می‌کنه. 

> > > 3. مثل کلید Check DPI Bypass یه کلید باشه که چک کنه تحریم شکن به درستی داره کار میکنه یا ن میتونه برنامه یه دامنه تحریم شده بگیره(داخل تنظیمات) و وقتی روی این کلید کلیک شد چک کنه که DNS سرور داره اینو پروکسی میکنه یا ن
> > 
> > میتونم در قسمتی مثل tools اضافه کنم.
> >
> اون وقت نتیجه پاپ آپ نباشه ها تو همون لاگ نوشته شه کلا اون جا همه ابزار ها پاپ آپ هستن ممکنه کاربرا گیج بشن هی کلیک کنن ببینن چیزی باز نمیشه فکر کنن سیستم شون هنگ کرده
> میتونی به لاگ اضافه کنی که خود کار بعد از وصل شدن برسی بشه و این که داخل استاتوس هم یه نشونه ای باشه از این که به تحریم شکن وصل شده 

بصورت status باشه چطوره؟ پایین‌تر توضیح میدم

> > > 4. اضافه کردن این ویژگی که همون دامنه مورد قبلی یا یه لیست از دامنه ها رو بگیره و مدام پروکسی شدن شون رو چک کنه یا مواقع خاص مثلا موقع تغییر سرور یا قطع و وصل کردن پروکسی شدن شون رو چک کنه و اگر دید پروکسی نمیشن هشدار بده که تحریم شکن کار نمیکنه
> > 
> > انجام این کار چون سنگین بود به قسمت dns scanner اضافه شد اما چک کردن یک دامنه نباید مشکلی باشه
> 
> آره خوبه مثلا یه گزینه باشه که هر چند وقت یک بار این کار انجام بشه
> 

میگم چطوره که به قسمت status اضافه شه. مثلا میشه برای وبسایتی که داخل تنظیمات می‌ذاری یه status مثل Act as Smart DNS: True اضافه کنه

اما اگه از قانونی که میخوام به fake dns پراکسی اضافه کنم استفاده کنی دیگه اینجا نمی‌تونه true بزنه

**Comment by nonbarbari** [comment]
> > > > 1. کلید خروج از برنامه داخل برنامه
> > > 
> > > 
> > > پیدا کردن جای مناسب برای گذاشتن دکمه برام واقعا مشکل بحساب میاد، اگر پیشنهادی داری بده.
> > 
> > 
> > کنار بنچ مارک توی استاتوس 😅
> 
> ببینم جا میشه یا نه 😄
> 
> > > > 2. آیکون کنار ساعت این چیز ها رو نشون بده (به کدام گروه از سرور های کاستوم وصل شده یا به بیلت این ها وصل شده . موقعی که برنامه در حال وصل شدن هست موقعیتش رو هم بگه مثلا بگه در حال چک کردنه یا در حال ست کردن DNS هستش)
> > > 
> > > 
> > > قسمت اول اگه اسم گروه طولانی باشه بخاطر محدودیت گذاشتن متن روی آیکن ممکنه هیچ متنی نشون داده نشه. قسمت دوم رو میشه انجام داد که درحال انجام چه کاریه.
> > 
> > 
> > واسه اسم های طولانی یه بخشیش رو نشون بده بقیش سه نقطه
> 
> باشه.
> 
> > > > 3. اضافه کردن قابلیت ری اسکن کردن یا چک کردن مجدد خود کار سرور ها (تب 1) برای پیدا کردن و جایگزین کردن سرور های بیشتر و سریع تر(موقعی که برنامه کانکت هست قراره فعال باشه تا لیست ورکینگ سرور ها بروز باشه)
> > > 
> > > 
> > > این کار بطور اتوماتیک هر ۶ ساعت یک بار در بکگراند انجام میشه.
> > 
> > 
> > 👍
> > > > ### برای حل مشکلات تحریم ها
> > > > 
> > > > 1. کلید برای دادن یه IP نامعتبر و سابنت نامعتبر + DNS و Proxy نا معتبر برای قطع سریع تر اینترنت داخل تب 3 (0.0.0.0) میتونه برای همه شون استفاده شه
> > > 
> > > 
> > > براساس تحقیقات خودم همه روش‌ها قابل دور زدنه بغیر از غیرفعال کردن آداپتر
> > 
> > 
> > والا حالا خیلی سخت گیری هم نیاز نیست واسه کرک و گذر از تحریم و اینا جوابه همینا (از طریق فایر وال هم میشه اینترنت رو نابود کرد یه جوری که فقط خود SDC اینترنت داشته باشه)
> 
> همه که از فایروال ویندوز استفاده نمی‌کنن
> 
> > > > 2. استفاده نکردن از DNS سیستم و ست بودن 0.0.0.0 برای DNS و Proxy  داخل سیسم موقع اسکن(چک کردن سرور ها) برای قطع نگه داشتن اینترنت از موقع بالا اومدن ویندوز تا موقع وصل شدن
> > > 
> > > 
> > > میشه از موقع بالا اومدن برنامه تا زمان وصل شدن این کار رو انجام داد نه از زمان بالا اومدن ویندوز، چون بدون نصب سرویس نمیشه.
> > 
> > 
> > میشه سرویس اضافه کرد که موقع خاموش شدن ویندوز این کارا انجام بشه که موقع بالا اومدن همه چی ردیف باشه و نت وجود نداشته باشه واسه چیز های دیگه ؟
> 
> مایکروسافت سالهاست که این امکان رو از ما گرفته، یعنی موقع خاموش شدن ما فقط ۵۰۰ میلی‌ثانیه فرصت داریم کاری انجام بدیم و به گفته خود مایکروسافت اگه کاربر برنامه‌ای رو exit نکنه و یهو شات‌داون کنه هر مشکلی پیش بیاد مسئولیتش با کاربره نه برنامه‌نویس. این کار رو کرده تا هیچ ویروسی نتونه جلوی خاموش شدن ویندوز رو بگیره. تنها تفاوت سرویس اینه که زودتر از برنامه اجرا میشه.
> 
سرویسی که موقع بالا اومدن ویندوز اجرا میشه میتونه زود تر از آماده شدن آداپتر شبکه این کار ها رو انجام بده ؟ اگه میتونه که همون فاصله فعال شدن سروس تا وصل شدن هم نت وجود نداشته باشه خوبه . میشه هم کاری کرد که با بستن برنامه این کارا انجام بشه .
> > > > 2.1. وقتی از DNS سیستم استفاده نشه این قابلیت رو میشه اضافه کرد که برنامه برای چک کردن DNS سرور ها از یه لیست خاصی از سرور ها استفاده کنه مزییت هاش : استفاده از سرور های بیشتر از 2 تا . استفاده از سرور های خاص و قاطی نشدن با سرور های تحریم شکن . وابسته نبودن برنامه به DNS سیستم و کار کردن برنامه در مواقعی که سیستم DNS سالم نداره . چک کردن سرور ها با چندین DNS و افزایش شانس پیدا کردن IP درست برای سرور ها
> > > 
> > > 
> > > این میشه همون استفاده از Bootstrap که باید منتظر بمونیم تا dnslookup ساپورتش کنه. البته الانم برنامه به dns سیستم وابسته نیست و برای گرفتن ip از همه سرورهایی که بهش متصله استفاده میکنه.
> > 
> > 
> > یعنی فعلا که ساپورت نمیکنه نمیشه کاریش کرد؟
> 
> قبلا یه کاریش کرده بودم اما حدود ۴۰ درصد احتمال داشت سرور رو failed بزنه که به دلم ننشست و حذفش کردم. راستی چک کردن سرور با بیش از یک dns اصلا کاربردی نیست، چون موقع کانکت و استفاده میتونه مشکل در اتصال ایجاد کنه با اینکه dnsproxy بیش از یک Bootstrap رو ساپورت می‌کنه.
> 
آها حالا اگه تونستی بیشتر روش تست انجام بده
> > > > 3. مثل کلید Check DPI Bypass یه کلید باشه که چک کنه تحریم شکن به درستی داره کار میکنه یا ن میتونه برنامه یه دامنه تحریم شده بگیره(داخل تنظیمات) و وقتی روی این کلید کلیک شد چک کنه که DNS سرور داره اینو پروکسی میکنه یا ن
> > > 
> > > 
> > > میتونم در قسمتی مثل tools اضافه کنم.
> > 
> > 
> > اون وقت نتیجه پاپ آپ نباشه ها تو همون لاگ نوشته شه کلا اون جا همه ابزار ها پاپ آپ هستن ممکنه کاربرا گیج بشن هی کلیک کنن ببینن چیزی باز نمیشه فکر کنن سیستم شون هنگ کرده
> > میتونی به لاگ اضافه کنی که خود کار بعد از وصل شدن برسی بشه و این که داخل استاتوس هم یه نشونه ای باشه از این که به تحریم شکن وصل شده
> 
> بصورت status باشه چطوره؟ پایین‌تر توضیح میدم
> 
> > > > 4. اضافه کردن این ویژگی که همون دامنه مورد قبلی یا یه لیست از دامنه ها رو بگیره و مدام پروکسی شدن شون رو چک کنه یا مواقع خاص مثلا موقع تغییر سرور یا قطع و وصل کردن پروکسی شدن شون رو چک کنه و اگر دید پروکسی نمیشن هشدار بده که تحریم شکن کار نمیکنه
> > > 
> > > 
> > > انجام این کار چون سنگین بود به قسمت dns scanner اضافه شد اما چک کردن یک دامنه نباید مشکلی باشه
> > 
> > 
> > آره خوبه مثلا یه گزینه باشه که هر چند وقت یک بار این کار انجام بشه
> 
> میگم چطوره که به قسمت status اضافه شه. مثلا میشه برای وبسایتی که داخل تنظیمات می‌ذاری یه status مثل Act as Smart DNS: True اضافه کنه
> 
> اما اگه از قانونی که میخوام به fake dns پراکسی اضافه کنم استفاده کنی دیگه اینجا نمی‌تونه true بزنه



خوبه . ولی می خوام کاربردی تر باشه مثلا چند تا دامنه بدیم بعد اگه یه تحریم شکنی از همه دامنه ها به جز یکی پشتیبانی می کرد برنامه تشخیص بده که یکی از دامنه ها پروکسی نشده و هشدار بده از طرفی داخل استاتوس هم همینی که گفتین باشه که یه نگاه کلی هم داشته باشیم که به تحریم شکن وصل هستیم یا ن.
اینم جالب میشه که تعداد دامنه هایی که پروکسی شدن رو هم نشون بده (میتونه داخل Net info باشه)یا این که داخل تب 4 با فعال کردن یه چک باکسی تمام دامنه هایی که پروکسی شدن رو نشون بده

**Comment by nonbarbari** [comment]
جدا از موارد بالا هر ابزاری که بشه باهاش از تحریم شکن ها بنچ مارک گرفت میتونه خیلی کمک کننده باشه مثلا تست سرعت (منظور تست سرعت دانلود و آپلود از اینترنت به پروکسی سرور تحریم شکن تا کلاینت هست) یا تست تاخیر (اینم مثل قبل چون تاخیر خود DNS سرور میتونه خیلی متفاوت باشه با تاخیر پروکسی سرور هاشون)
یا تست پایداری و ...

**Comment by msasanmh** [comment]
> جدا از موارد بالا هر ابزاری که بشه باهاش از تحریم شکن ها بنچ مارک گرفت میتونه خیلی کمک کننده باشه مثلا تست سرعت (منظور تست سرعت دانلود و آپلود از اینترنت به پروکسی سرور تحریم شکن تا کلاینت هست) یا تست تاخیر (اینم مثل قبل چون تاخیر خود DNS سرور میتونه خیلی متفاوت باشه با تاخیر پروکسی سرور هاشون)
> یا تست پایداری و ...
> 

میگم که نمیخوای این برنامه که ویندوز ۷ به بالا رو ساپورت میکنه فقط برای برطرف شدن باگ‌ها بروز بشه و برای اضافه شدن امکانات جدید به پلتفرم UWP برم که ویندوز ۱۰ به بالا رو ساپورت میکنه و فقط ۶۴ بیتیه اما میشه باهاش خیلی کارها انجام داد بخاطر Performance بالاش.
میترسم این ورژن از برنامه با اضافه شدن امکانات کند بشه.
نظرت چیه؟

**Comment by nonbarbari** [comment]
> > جدا از موارد بالا هر ابزاری که بشه باهاش از تحریم شکن ها بنچ مارک گرفت میتونه خیلی کمک کننده باشه مثلا تست سرعت (منظور تست سرعت دانلود و آپلود از اینترنت به پروکسی سرور تحریم شکن تا کلاینت هست) یا تست تاخیر (اینم مثل قبل چون تاخیر خود DNS سرور میتونه خیلی متفاوت باشه با تاخیر پروکسی سرور هاشون)
> > یا تست پایداری و ...
> 
> میگم که نمیخوای این برنامه که ویندوز ۷ به بالا رو ساپورت میکنه فقط برای برطرف شدن باگ‌ها بروز بشه و برای اضافه شدن امکانات جدید به پلتفرم UWP برم که ویندوز ۱۰ به بالا رو ساپورت میکنه و فقط ۶۴ بیتیه اما میشه باهاش خیلی کارها انجام داد بخاطر Performance بالاش. میترسم این ورژن از برنامه با اضافه شدن امکانات کند بشه. نظرت چیه؟

عالیه

**Comment by msasanmh** [comment]
> سرویسی که موقع بالا اومدن ویندوز اجرا میشه میتونه زود تر از آماده شدن آداپتر شبکه این کار ها رو انجام بده ؟ اگه میتونه که همون فاصله فعال شدن سروس تا وصل شدن هم نت وجود نداشته باشه خوبه . میشه هم کاری کرد که با بستن برنامه این کارا انجام بشه .

نه، تا آداپتر شبکه آماده نشه نمیشه روش کاری انجام داد.
یه کاریش میکنم. اما اول به یه ui بهتر نیازه که بتونه امکانات بیشتری رو توی خودش جا بده
