### ISSUE TITLE
Loopback IP set

### ISSUE THREAD

**Issue by Noob2Pr0** [msasanmh/SecureDNSClient#127]
Hi dear friend
Sometimes, naturally, I forget to close the tool properly and shut down the system
which causes the dns settings to remain as they are on the loopback ip: 127.0.0.1
If possible, put a key on the software to get the desired IP (8.8.8.8) and set it for the refresh section, and this key should be separate from the automatic discussion of the tool behind the scenes.
I think it can be helpful
Indeed, if you could, replace those suspicious IPs in your next update

سلام دوست عزیز
بعضی وقت ها طبیعتاً فراموش میکنم ابزار رو به درستی ببندم و سیستم رو خاموش می کنم
که باعث میشه تنظیمات dns به همون شکلی که هست روی loopback ip : 127.0.0.1 تنظیم مونده باشه
اگه بشه یه کلید روی نرم افزار قرار بدی که ip مورد نظر مارو بگیره (8.8.8.8) و ست کنه برای بخش refresh و این کلید جدا از بحث خودکار ابزار در پشت صحنه باشه
بنظرم می تونه کمک کننده باشه
راستی اون ip های مشکوک هم اگه تونستی جا به جا کن توی بروز رسانی بعدیت

**Comment by nonbarbari** [comment]
داخل نسخه جدید این مشکل برطرف شده 
![image](https://github.com/msasanmh/SecureDNSClient/assets/123904563/9b7e8319-0a9a-4a08-bf99-2169d3a86427)
داخل قسمت تنظیمات بخش ست DNS این تک رو بزنید

**Comment by msasanmh** [comment]
> داخل نسخه جدید این مشکل برطرف شده 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/123904563/9b7e8319-0a9a-4a08-bf99-2169d3a86427)
> داخل قسمت تنظیمات بخش ست DNS این تک رو بزنید

آفرین، واقعا یادم نبود 😆

**Comment by msasanmh** [comment]
اون گزینه‌ای که آقای @nonbarbari گفتن رو فعال کنید، اونوقت دکمه set dns تبدیل به unset میشه.
اون سرورهای مشکوک رو حتما در ورژن بعد برمی‌دارم.
شاید ورژن بعد بیشتر زمان ببره چون یه سری تغییرات کلی در راهه.
@Noob2Pr0

**Comment by Noob2Pr0** [comment]
پس بهتره توی نسخه بعضی اگه صلاح می بینید اون بخش رو فعال کنید تیکشو که اینتینرت پس از قطع به مشکل بر نخوره
خیلی هم عالی
از این به بعد، بعد از هر نسخه میشینم تغییرات رو مرور می کنم
ممنون از شما

**Comment by msasanmh** [comment]
> پس بهتره توی نسخه بعضی اگه صلاح می بینید اون بخش رو فعال کنید تیکشو که اینتینرت پس از قطع به مشکل بر نخوره
> خیلی هم عالی
> از این به بعد، بعد از هر نسخه میشینم تغییرات رو مرور می کنم
> ممنون از شما

اگه بصورت پیش‌فرض فعال نذاشتم بخاطر گزارش یکی از کاربرا بود که می‌گفت روی ویندوز ۱۰ وقتی اون گزینه فعاله برنامه نمیتونه dns رو ست کنه که البته بعدا به این نتیجه رسیدم که اشتباه می‌کرده. به هر حال محض اطمینان غیرفعال گذاشتمش.

**Comment by Noob2Pr0** [comment]
والا نمیدونم، ولی هر دفعه که من خاموش میکنم (البته اگه یادم بره نرم افزار رو ببندم) loopback ست میشه روی dns که باعث میشه اینترنت نداشته باشم عملاً و باید دستی به یه dns دیگه تنظیمش کنم وقتی اینترنت اومد بعد بیام سراغ این
اگه صلاح دیدین توی بروز رسانی بعدی فعال کنید
ممنون

**Comment by msasanmh** [comment]
Applied.
