### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Hos2k** [msasanmh/SecureDNSClient#128]
سلام و درود.نمیدونم جای درسته برای سوال یا نه
اگه امکانش 
![Screenshot (14)](https://github.com/msasanmh/SecureDNSClient/assets/156706252/8e18cddd-c4c1-4f08-8594-440dc552e9d9)
هست راهنمایی کنید برای این ارور

**Comment by msasanmh** [comment]
شما یه برنامه dns دیگه دارید که اجراست و پورت 53 رو اشغال کرده. 
مسلما نمیشه دو برنامه dns رو همزمان اجرا کرد. اون یکی رو ببندی مشکل حل میشه
