### ISSUE TITLE
Port 53 is occupied by "DnsService". 

### ISSUE THREAD

**Issue by mrggpop** [msasanmh/SecureDNSClient#130]
![image_2024-01-22_001920559](https://github.com/msasanmh/SecureDNSClient/assets/157319693/0ce069b0-33f4-465a-8413-29ae50ac7542)
من این مشکل رو دارم این گزینه detect check رو هم زدم چی کارش کنم؟

**Comment by mrggpop** [comment]
میدونم میگه پورت ۵۳ اشغاله ، اما چطوری بفهمم کدوم برنامه اشغال کرده ؟

**Comment by msasanmh** [comment]
> میدونم میگه پورت ۵۳ اشغاله ، اما چطوری بفهمم کدوم برنامه اشغال کرده ؟

داخل تسک منیجر ویندوز یه پراسس داری به اسم DnsService.exe روش کلیک راست کن و open file location رو انتخاب کن، اونوقت از مسیر فایل میتونی بفهمی مربوط به چه برنامه‌ای هست.

**Comment by mrggpop** [comment]
مرسی حل شد یکی از برنامه های dns بود که حتی با وجود این این که ران نمیشه و توی لست  استارت اپ نیست باز تو لیست پروسس میومد بالا . حل شد مرسی.
