### ISSUE TITLE
SDC روی ویندوز 7

### ISSUE THREAD

**Issue by Edris133** [msasanmh/SecureDNSClient#131]
سلام، ببخشید این برنامه روی ویندوز 7 هم کار میکنه؟ ممنون از شما.

**Comment by msasanmh** [comment]
> سلام، ببخشید این برنامه روی ویندوز 7 هم کار میکنه؟ ممنون از شما.

آره، از ویندوز 7 به بالا

**Comment by Edris133** [comment]
خیلی ممنون!
