### ISSUE TITLE
مشکل شناسایی کارت شبکه در تب set dns

### ISSUE THREAD

**Issue by reykins** [msasanmh/SecureDNSClient#132]
تو نسخه های مختلف ویندوز تست کردم فقط در نسخه Windows 10 2016 LTSB این مشکلو دارم حتی نسخه پایینترش یعنی ویندوز 8.1 هم اوکی بود
درایورهام همه آپدیتن.
![Screenshot (2)](https://github.com/msasanmh/SecureDNSClient/assets/126799560/f36f67bc-ba0a-4ba3-8a14-f29962ae0824)

**Comment by msasanmh** [comment]
> تو نسخه های مختلف ویندوز تست کردم فقط در نسخه Windows 10 2016 LTSB این مشکلو دارم حتی نسخه پایینترش یعنی ویندوز 8.1 هم اوکی بود
> درایورهام همه آپدیتن.
> ![Screenshot (2)](https://github.com/msasanmh/SecureDNSClient/assets/126799560/f36f67bc-ba0a-4ba3-8a14-f29962ae0824)
> 

مایکروسافت برای لیست کردن آداپترها دو تا API داره، من دارم از API اول استفاده می‌کنم، در ورژن بعد میذارم اگه API اول چیزی پیدا نکرد از API دوم استفاده کنه.
پس اگه در ورژن بعد هم برنامه نتونه آداپتر شما رو در این نسخه از ویندوز پیدا کنه یعنی دیگه مایکروسافت ساپورتش نمی‌کنه و راهی براش نیست.
ممنون بابت اطلاع.
