### ISSUE TITLE
asp.net version error redirects to the wrong file

### ISSUE THREAD

**Issue by mat48** [msasanmh/SecureDNSClient#133]
### Issue:

![image](https://github.com/msasanmh/SecureDNSClient/assets/89838549/f4e9db05-9dee-47c5-b043-69908e69dff5)

Hi, I had an issue with the app when I installed it. 
It showed an error saying that I should update ".net" a and asked if I wanna download it. When I clicked on yes and installed [this link](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.26-windows-x64-installer?cid=getdotnetcore) it did not fix the issue. 

### additional info:
the size of the downloaded file was 8 MB which I guess should be more than that (?) . Guess it redirects me to the wrong file. 

### Fix method:
I downloaded [this ](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.418-windows-x64-installer)version from Microsoft's website and the the issue was solved.
I know it might be a default error and not your custom error but it would save new user's time if there's a way to fix it. 

---

Thanks for this awesome app and all the hard work !!
And btw, do you prefer that the issues are written in Persian or English?

**Comment by msasanmh** [comment]
> ### Issue:
> 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/89838549/f4e9db05-9dee-47c5-b043-69908e69dff5)
> 
> Hi, I had an issue with the app when I installed it. 
> It showed an error saying that I should update ".net" a and asked if I wanna download it. When I clicked on yes and installed [this link](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.26-windows-x64-installer?cid=getdotnetcore) it did not fix the issue. 
> 
> ### additional info:
> the size of the downloaded file was 8 MB which I guess should be more than that (?) . Guess it redirects me to the wrong file. 

It wasn't the wrong file, but it's not standalone, the prerequisite is **.Net Destop Runtime 6**.
You can always find the latest version on [this page](https://dotnet.microsoft.com/en-us/download/dotnet/6.0).

> 
> ### Fix method:
> I downloaded [this ](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.418-windows-x64-installer)version from Microsoft's website and the the issue was solved.

There was no need to install the sdk version, but of course, sdk also will do the job.

> I know it might be a default error and not your custom error but it would save new user's time if there's a way to fix it. 

I'm using _Advanced Installer_ to create the installer version of sdc and it gives me zero options to change Runtime download link.

> 
> ---
> 
> Thanks for this awesome app and all the hard work !!

Thanks, it gets better in time.

> And btw, do you prefer that the issues are written in Persian or English? 
> 

I really have no idea, whatever you guys are more comfortable with.

**Comment by rohitghali** [comment]
I installed both .86 and x64. Still the same issue. Any solution?

**Comment by msasanmh** [comment]
> I installed both .86 and x64. Still the same issue. Any solution?

If you are using x64 version, 
First install:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.27-windows-x64-installer

Then Install:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.27-windows-x64-installer

**Comment by rohitghali** [comment]
> > I installed both .86 and x64. Still the same issue. Any solution?
> 
> If you are using x64 version, First install: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.27-windows-x64-installer
> 
> Then Install: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.27-windows-x64-installer

Worked. Thanks.
