### ISSUE TITLE
Telegram-proxy

### ISSUE THREAD

**Issue by joiniran** [msasanmh/SecureDNSClient#134]
درود مهندس... پروکسی که برنامه میده 127.0.0.1:8080رو حالت ساکس 5 رو تلگرام ست کردم چه با اون و بدون اون متصل نمیشه ... ولی یوتیوب اینا اوکی هست... سوال دوم ای پی میخوام ببینم سایتهای که وا میکنم این ارور رو میده 403 Forbidden  ای پی رو کجا چک کنم ؟ سوال سوم سرعت لود  از اینی که هست بیشتر هم میشه ؟؟؟

**Comment by msasanmh** [comment]
> درود مهندس... پروکسی که برنامه میده 127.0.0.1:8080رو حالت ساکس 5 رو تلگرام ست کردم چه با اون و بدون اون متصل نمیشه ... ولی یوتیوب اینا اوکی هست... سوال دوم ای پی میخوام ببینم سایتهای که وا میکنم این ارور رو میده 403 Forbidden  ای پی رو کجا چک کنم ؟ سوال سوم سرعت لود  از اینی که هست بیشتر هم میشه ؟؟؟

درود. هر جایی که این برنامه رو معرفی کردن باید ذکر میکردن که این برنامه یه vpn نیست، یه کلاینت dns هستش درنتیجه فقط میتونه وبسایت‌هایی که براساس IP فیلتر نیستن رو باز کنه و از اونجایی که تلگرام براساس IP فیلتر شده این برنامه نمیتونه بازش کنه.

ارور 403 یعنی تحریم بودن برای باز کردن اونا باید به برنامه smart dns بدید تا باز کنه، در ورژن بعد امکان دادن dns بصورت جدا برای هر وبسایت وجود داره.

سرعت لود.. اگه منظور یوتیوب هست برای من روی حالت ssl decryption سرعت بهتری داره

**Comment by joiniran** [comment]
من  شما قبلا تو  یه مررورگی بود که پروکسی ست میکردیناسمش یادم نیست میشناختم با هم دیگه چت هم کرده بودیم تو فیسبوک بود  یه نسخه ایی و پیشنهاد سرور اروپایی داده بودم ، تو توییتر دوستا لطف داشتن ... ظاهر شما توییری ندارین شما رو منشن کنن ، فکر کنم این فضا رو دوست ندارین لطفا بیاین تا از بتونییم از  وجودتان کارایی لازم رو ببیرم ... بر هر رو ی سپاس

**Comment by msasanmh** [comment]
> من  شما قبلا تو  یه مررورگری بود که پروکسی ست میکردین اسمش یادم نیست میشناختم با هم دیگه چت هم کرده بودیم تو فیسبوک بود  یه نسخه ایی و پیشنهاد سرور اروپایی داده بودم ، تو توییتر دوستا لطف داشتن معرفی کردن ... ظاهر شما توییری ندارین شما رو منشن کنن ، فکر کنم این فضا رو دوست ندارین لطفا بیاین تا از بتونییم از  وجودتان کارایی و دانش لازم رو ببیرم ... بر هر رو ی سپاس

متاسفانه اون پراکسی‌ها بخاطر فشار بیش از حد از بین رفتن.
خبرهای بدی که توی توییتر هست آرامشم رو ازم می‌گیره. بچه‌های it رو هم که بازداشت میکنن.
