### ISSUE TITLE
getting  ready bug

### ISSUE THREAD

**Issue by wolfkingal2000** [msasanmh/SecureDNSClient#135]
سلام  توی این بخش توی اپدیت جدید گیر کرده  و خیلی طول میکشه نشون بده خودش رو 
![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/d73ca4bc-e881-4b21-9898-318aa8aa3625)

**Comment by msasanmh** [comment]
>  سلام  توی این بخش توی اپدیت جدید گیر کرده  و خیلی طول میکشه نشون بده خودش رو 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/d73ca4bc-e881-4b21-9898-318aa8aa3625)
> 

بالاخره از این بخش رد شد یا کلا رد نمیشه؟

**Comment by wolfkingal2000** [comment]
> >  سلام  توی این بخش توی اپدیت جدید گیر کرده  و خیلی طول میکشه نشون بده خودش رو 
> > ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/d73ca4bc-e881-4b21-9898-318aa8aa3625)
> > 
> 
> بالاخره از این بخش رد شد یا کلا رد نمیشه؟

رد میشه ولی طول میکشه مثل قبل سریع بالا نمیاد

**Comment by wolfkingal2000** [comment]
> > > >  سلام  توی این بخش توی اپدیت جدید گیر کرده  و خیلی طول میکشه نشون بده خودش رو 
> > > > ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/d73ca4bc-e881-4b21-9898-318aa8aa3625)
> > > > 
> > > 
> > > بالاخره از این بخش رد شد یا کلا رد نمیشه؟
> > 
> > رد میشه ولی طول میکشه مثل قبل سریع بالا نمیاد 
> 
> این قسمت بخاطر تغییرات ui تغییر کرد، اگر بتونم سرعتش رو می‌برم بالاتر.
> و حدودا چند ثانیه نسبت به قبل بیشتر زمان می‌بره؟

یه یک دقیقه طول میکشه

**Comment by joiniran** [comment]
درود  مهندس ،تو نسخه جدید این ارور چیه بعد این ارور جلوتر نمیشه رفت گیرمیکنه سرهمین
 ERROR: Some of binary files are missing!
![Capturesns](https://github.com/msasanmh/SecureDNSClient/assets/123999344/c1f32307-e6d9-4792-be03-39e0240029cd)

**Comment by msasanmh** [comment]
> درود  مهندس ،تو نسخه جدید این ارور چیه بعد این ارور جلوتر نمیشه رفت گیرمیکنه سرهمین
>  ERROR: Some of binary files are missing!
> ![Capturesns](https://github.com/msasanmh/SecureDNSClient/assets/123999344/c1f32307-e6d9-4792-be03-39e0240029cd)
> 

آنتی‌ویروس یک یا چندتا از فایل‌های اجرایی برنامه رو پاک کرده. این آلارم False positive هستش.
اول برنامه رو داخل آنتی‌ویروس استثنا کن و بعد دوباره برنامه رو اجرا کن
