### ISSUE TITLE
Dns flushed successfully bug.

### ISSUE THREAD

**Issue by DogancanYr** [msasanmh/SecureDNSClient#136]
There is nothing in the event log.

**Comment by msasanmh** [comment]
> There is nothing in the event log.

When this occurs?

**Comment by DogancanYr** [comment]
In previous versions, I did it as in the guide, but it does not work in the current version.

> > There is nothing in the event log.
> 
> When this occurs?

**Comment by msasanmh** [comment]
This is what I've got by pressing quick connect:
```
Connecting... Please wait...

Connected.
Waiting for DNS to get online...
Local DNS Server started using 5 fastest servers in parallel.
Local DNS:
127.0.0.1
192.168.1.112

Connect Task: RanToCompletion
Setting DNS...
Local DNS 127.0.0.1 set to Wi Fi (D-Link DWA-525 Wireless N 150 Desktop Adapter)

Flushing Dns...
Flush: Successfully flushed the DNS Resolver Cache.
Register: Registration of the DNS resource records for all adapters of this computer has been initiated. Any errors will be reported in the Event Viewer in 15 minutes.
Dns flushed successfully.
Starting Proxy Server...
Local Proxy Server (HTTP, HTTPS, SOCKS4, SOCKS4A, SOCKS5):
127.0.0.1:8080
192.168.1.112:8080
Proxy Server http://127.0.0.1:8080 set to system.
Quick Connect finished (using "Saved Servers") in 26 Seconds, 709 Milliseconds
```
Is yours any different than this?

**Comment by DogancanYr** [comment]
`Connecting... Please wait...

Checking dns.cloudflare.com...
It's available. Connecting...
Connected to dns.cloudflare.com.
Server delay: 301 ms.
Local DNS:
127.0.0.1
192.168.1.110

Connect Task: RanToCompletion
Setting DNS...
Local DNS 127.0.0.1 set to Ethernet (Realtek PCIe 2.5GbE Family Controller)

Flushing Dns...
Flush: Successfully flushed the DNS Resolver Cache.
Register: Registration of the DNS resource records for all adapters of this computer has been initiated. Any errors will be reported in the Event Viewer in 15 minutes.
Dns flushed successfully.
`

No matter how long I wait, it doesn't continue.

Also, I had a problem with it not starting automatically at startup, it's still the same.

**Comment by DogancanYr** [comment]
Now it says couldnt set dns.
Most likely it timed out.

**Comment by msasanmh** [comment]
Did you select your Network Adapter in quick connect settings?

If you want to debug your issue, first disconnect by clicking on "Disconnect All".
2. Go to "Connect" tab select the first option and connect. 
3. Go to "Set DNS" tab and find your active network adapter and try to set dns on it.
Then let me know what happened. 

Also Cloudflare is not blocked in your country, you don't need to bypass it.

If you want to use Cloudflare DoH, just add it to custom servers, change quick connect settings to working servers and check "Use custom servers" from check tab.
This is Cloudflare DoH address:
https://dns.cloudflare.com/dns-query

**Comment by msasanmh** [comment]
> Now it says couldnt set dns.
> Most likely it timed out.

Are you using Cable or WiFi?

**Comment by DogancanYr** [comment]
I have used this software before and even reported problems with other issues.
It definitely works in previous versions but not in this version.
I'm using wired and it's the correct interface.

**Comment by msasanmh** [comment]
> I have used this software before and even reported problems with other issues.
> It definitely works in previous versions but not in this version.
> I'm using wired and it's the correct interface.

Good. Do you have same issue even when you choose "Working servers" in quick connect settings?

**Comment by DogancanYr** [comment]
Yes .

**Comment by msasanmh** [comment]
> Yes .

And I need to know when it reaches where it get stuck, what's the status of tray icon, is it blinking? And what does it say if you hover mouse on it?
(The Icon next to windows clock)

**Comment by DogancanYr** [comment]
> > Yes .
> 
> And I need to know when it reaches where it get stuck, what's the status of tray icon, is it blinking? And what does it say if you hover mouse on it? (The Icon next to windows clock)

Quick connect is in action .

**Comment by msasanmh** [comment]
> > > Yes .
> > 
> > And I need to know when it reaches where it get stuck, what's the status of tray icon, is it blinking? And what does it say if you hover mouse on it? (The Icon next to windows clock)
> 
> Quick connect is in action .

So obviously one the options is causing that issue.
I need you to go step by step.
In quick connect settings uncheck everything, then try to connect by clicking "Quick Connect" in check tab.
If it was successful then check the very next option in Quick connect settings and try again.
Repeat this until you find the option is causing this.

**Comment by DogancanYr** [comment]
I set it to default settings and removed the use saved servers if available tick and it worked that way.
Yes, all the problem is solved and I can make the settings I want. Much obliged .

**Comment by DogancanYr** [comment]
But I still haven't been able to solve the problem of it not starting automatically.It works 2 versions ago.

**Comment by msasanmh** [comment]
> But I still haven't been able to solve the problem of it not starting automatically.It works 2 versions ago.
> (The execute quick connect on startup button does not work.)

Do you click on application icon on windows startup? Because it will cancel the Quick connect, it thinks you want to connect manually.

**Comment by DogancanYr** [comment]
> > I set it to default settings and removed the use saved servers if available tick and it worked that way.
> > Yes, all the problem is solved and I can make the settings I want. Much obliged .
> 
> Where was the problem? The GoodbyeDPI? Because some antivirus are sensitive to it. I suggest use proxy it's way powerful than GoodbyeDPI.

Use saved servers if available feature remains open without exception.
It doesn't uncheck itself. Even if I make another selection.

**Comment by msasanmh** [comment]
> > > I set it to default settings and removed the use saved servers if available tick and it worked that way.
> > > Yes, all the problem is solved and I can make the settings I want. Much obliged .
> > 
> > Where was the problem? The GoodbyeDPI? Because some antivirus are sensitive to it. I suggest use proxy it's way powerful than GoodbyeDPI.
> 
> Use saved servers if available feature remains open without exception.
> It doesn't uncheck itself. Even if I make another selection.
> 

It doesn't need to, application won't use it if you choose another section or another method to connect.

**Comment by msasanmh** [comment]
> > But I still haven't been able to solve the problem of it not starting automatically.It works 2 versions ago.
> > (The execute quick connect on startup button does not work.)
> 
> Do you click on application icon on windows startup? Because it will cancel the Quick connect, it thinks you want to connect manually. 

This is important,  Don't click on app icon on windows startup.

**Comment by DogancanYr** [comment]
> > > > I set it to default settings and removed the use saved servers if available tick and it worked that way.
> > > > Yes, all the problem is solved and I can make the settings I want. Much obliged .
> > > 
> > > 
> > > Where was the problem? The GoodbyeDPI? Because some antivirus are sensitive to it. I suggest use proxy it's way powerful than GoodbyeDPI.
> > 
> > 
> > Use saved servers if available feature remains open without exception.
> > It doesn't uncheck itself. Even if I make another selection.
> 
> It doesn't need to, application won't use it if you choose another section or another method to connect.

But the software uses it.

**Comment by DogancanYr** [comment]
Instead of removing the tick,it renders the box useless. always uses the visible one.

**Comment by msasanmh** [comment]
> > > > > I set it to default settings and removed the use saved servers if available tick and it worked that way.
> > > > > Yes, all the problem is solved and I can make the settings I want. Much obliged .
> > > > 
> > > > 
> > > > Where was the problem? The GoodbyeDPI? Because some antivirus are sensitive to it. I suggest use proxy it's way powerful than GoodbyeDPI.
> > > 
> > > 
> > > Use saved servers if available feature remains open without exception.
> > > It doesn't uncheck itself. Even if I make another selection.
> > 
> > It doesn't need to, application won't use it if you choose another section or another method to connect.
> 
> But the software uses it.

It can be use by app when only connect mode is set to "Working Servers", other than that it's not even capable of using saved servers. I assure you.

**Comment by DogancanYr** [comment]
> > > > > > I set it to default settings and removed the use saved servers if available tick and it worked that way.
> > > > > > Yes, all the problem is solved and I can make the settings I want. Much obliged .
> > > > > 
> > > > > 
> > > > > Where was the problem? The GoodbyeDPI? Because some antivirus are sensitive to it. I suggest use proxy it's way powerful than GoodbyeDPI.
> > > > 
> > > > 
> > > > Use saved servers if available feature remains open without exception.
> > > > It doesn't uncheck itself. Even if I make another selection.
> > > 
> > > 
> > > It doesn't need to, application won't use it if you choose another section or another method to connect.
> > 
> > 
> > But the software uses it.
> 
> It can be use by app when only connect mode is set to "Working Servers", other than that it's not even capable of using saved servers. I assure you.

![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/68cb1c26-a3cd-4605-9b65-3ed9a1cf6001)
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/37820c67-e89b-473d-b97d-38e70b9c4290)
It just prevents me from changing the value, it's always ticked. Then you explain how it works when I turn that tick off.

**Comment by msasanmh** [comment]
> > > > > > > I set it to default settings and removed the use saved servers if available tick and it worked that way.
> > > > > > > Yes, all the problem is solved and I can make the settings I want. Much obliged .
> > > > > > 
> > > > > > 
> > > > > > Where was the problem? The GoodbyeDPI? Because some antivirus are sensitive to it. I suggest use proxy it's way powerful than GoodbyeDPI.
> > > > > 
> > > > > 
> > > > > Use saved servers if available feature remains open without exception.
> > > > > It doesn't uncheck itself. Even if I make another selection.
> > > > 
> > > > 
> > > > It doesn't need to, application won't use it if you choose another section or another method to connect.
> > > 
> > > 
> > > But the software uses it.
> > 
> > It can be use by app when only connect mode is set to "Working Servers", other than that it's not even capable of using saved servers. I assure you.
> 
> ![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/68cb1c26-a3cd-4605-9b65-3ed9a1cf6001)
> ![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/37820c67-e89b-473d-b97d-38e70b9c4290)
> It just prevents me from changing the value, it's always ticked. Then you explain how it works when I turn that tick off.
> 

It prevents you from changing it because that option is not belong to "Fake Proxy Via Proxy DPI Bypass".
It means it doesn't matter that option is ticked or not.
If you turn it off, there would be no difference.

**Comment by msasanmh** [comment]
And it works by connecting to "Fake Proxy" settings.

**Comment by DogancanYr** [comment]
In the previous version it doesn't matter but in this version it is broken and always accepts it as ticked.

**Comment by DogancanYr** [comment]
Apply the above settings.

**Comment by DogancanYr** [comment]
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/247c64d5-e6cf-48e7-9f01-6bd3bce0df58)

**Comment by msasanmh** [comment]
> In the previous version it doesn't matter but in this version it is broken and always accepts it as ticked.

I just tested it right now. Look at my QC settings. 
In log you can't see anything related to saved server.
What makes you say that?
![20240224_010918.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/00e40373-8ece-411b-873d-e95d76ec3948)

![20240224_011057.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/f0e2e3ca-b696-48b6-bfba-2f2c907db7f2)

**Comment by DogancanYr** [comment]
I don't quite understand.
```
Connecting... Please wait...

Checking dns.cloudflare.com...
It's available. Connecting...
Connected to dns.cloudflare.com.
Server delay: 68 ms.
Local DNS:
127.0.0.1
192.168.1.110

Connect Task: RanToCompletion
GoodbyeDPI is active, mode: Medium
Quick Connect finished (using "Fake Proxy Via Proxy DPI Bypass") in 13 Seconds, 948 Milliseconds

```

**Comment by DogancanYr** [comment]
Also make the settings one to one .
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/3467f4e1-0d43-4ae8-8010-179095194fff)

**Comment by msasanmh** [comment]
> I don't quite understand.
> ```
> Connecting... Please wait...
> 
> Checking dns.cloudflare.com...
> It's available. Connecting...
> Connected to dns.cloudflare.com.
> Server delay: 68 ms.
> Local DNS:
> 127.0.0.1
> 192.168.1.110
> 
> Connect Task: RanToCompletion
> GoodbyeDPI is active, mode: Medium
> Quick Connect finished (using "Fake Proxy Via Proxy DPI Bypass") in 13 Seconds, 948 Milliseconds
> 
> ```

It's easy, just read the log, it says checking for cloudflare dns and it just connected to it not the saved servers. 

(using "Fake Proxy Via Proxy DPI Bypass") uses "Fake Proxy" settings. 
This page 👇
![20240224_012334.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/e32887c3-2714-419a-a539-eb0c0b9d8ef3)

Saved servers are something else, don't get confused. 
We are working on full documentation but app is a bit advanced and requires more time.

**Comment by DogancanYr** [comment]
So should I make your settings ?
I just changed the values ​​on that page and it connects every time.
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/3467f4e1-0d43-4ae8-8010-179095194fff)

This is what's written.
```
Connecting... Please wait...

Checking dns.cloudflare.com...
It's available. Connecting...
Connected to dns.cloudflare.com.
Server delay: 68 ms.
Local DNS:
127.0.0.1
192.168.1.110

Connect Task: RanToCompletion
GoodbyeDPI is active, mode: Medium
Quick Connect finished (using "Fake Proxy Via Proxy DPI Bypass") in 13 Seconds, 948 Milliseconds

```

**Comment by msasanmh** [comment]
> So should I make your settings ?
> I just changed the values ​​on that page and it connects every time.

You need to find the best settings on your own ISP. The best settings is the one can get you connected everytime and easily. 

> ![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/3467f4e1-0d43-4ae8-8010-179095194fff)
> 

Don't forget to tick the "Set DNS to".
Without setting dns app can help you.

> This is what's written.
> ```
> Connecting... Please wait...
> 
> Checking dns.cloudflare.com...
> It's available. Connecting...
> Connected to dns.cloudflare.com.
> Server delay: 68 ms.
> Local DNS:
> 127.0.0.1
> 192.168.1.110
> 
> Connect Task: RanToCompletion
> GoodbyeDPI is active, mode: Medium
> Quick Connect finished (using "Fake Proxy Via Proxy DPI Bypass") in 13 Seconds, 948 Milliseconds
> 
> ```
> 
> 

Log I completely OK just don't forget to set dns on system.

**Comment by DogancanYr** [comment]
> > So should I make your settings ?
> > I just changed the values ​​on that page and it connects every time.
> 
> You need to find the best settings on your own ISP. The best settings is the one can get you connected everytime and easily.
> 
> > ![resim](https://private-user-images.githubusercontent.com/90002969/307459864-3467f4e1-0d43-4ae8-8010-179095194fff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjY3MzksIm5iZiI6MTcwODcyNjQzOSwicGF0aCI6Ii85MDAwMjk2OS8zMDc0NTk4NjQtMzQ2N2Y0ZTEtMGQ0My00YWU4LTgwMTAtMTc5MDk1MTk0ZmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIyMTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZmY4NGRmNjE2ZWVjNzM3NGFjZjRiMTNhYmJkMjA5MDllMjUzMGM4Yzg4MGFiYjYzOTJjYmI3YTBjYTcyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUGlVAb4jFWW2KFPGlLsKCIg3FbKv7iKDAS2E4VvFwk)
> 
> Don't forget to tick the "Set DNS to". Without setting dns app can help you.
> 
> > This is what's written.
> > ```
> > Connecting... Please wait...
> > 
> > Checking dns.cloudflare.com...
> > It's available. Connecting...
> > Connected to dns.cloudflare.com.
> > Server delay: 68 ms.
> > Local DNS:
> > 127.0.0.1
> > 192.168.1.110
> > 
> > Connect Task: RanToCompletion
> > GoodbyeDPI is active, mode: Medium
> > Quick Connect finished (using "Fake Proxy Via Proxy DPI Bypass") in 13 Seconds, 948 Milliseconds
> > ```
> 
> Log I completely OK just don't forget to set dns on system.

Same bug . (It is not related to the set dns, it only sets 8.8.8.8 or 1.1.1.1, it does not really matter in our topic.)
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/f3acf3d4-f864-4800-8e62-9a2c92e81223)

**Comment by DogancanYr** [comment]
I understand the problem now, set dns to is problematic.

![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/560b09fa-5b08-4162-9ff5-f9ca1d7c72d9)

**Comment by DogancanYr** [comment]
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/604456ec-bcde-4d0a-99db-123f2518494f)

**Comment by msasanmh** [comment]
The problem is that your Network Adapter doesn't give any feedback about dns is being set or not.
I need you to do me a favor. 
When app is stuck open a CMD window and execute this command:
nslookup 0.0.0.0
Exactly like the image below: 
![20240224_021355.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/a23567e8-7ccb-43bc-9e64-cb209c4292f4)

And get an Screenshot of the result and send it to me.
You can do it tomorrow if it's too late.

**Comment by msasanmh** [comment]
Also watch this video and tell me the result:
https://github.com/msasanmh/SecureDNSClient/assets/1586825/bcfb3eea-29ac-4d8b-8eb2-00c45bb5f5d2

**Comment by DogancanYr** [comment]
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/c0900850-9d7a-4218-8c19-b4c3a7104f54)
I never thought of it.🤣😂🤣

**Comment by msasanmh** [comment]
> ![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/c0900850-9d7a-4218-8c19-b4c3a7104f54)
> I never thought of it.🤣😂🤣

Me neither 😁

**Comment by DogancanYr** [comment]
Now that you have opened the source code, can you also make it so that it does not notify every time the application is minimized ?

**Comment by msasanmh** [comment]
> Now that you have opened the source code, can you also make it so that it does not notify every time the application is minimized ?  😊😊😊

I can make it to popup only for new users.
