### ISSUE TITLE
 کار نکردن برنامه به صورت جدا

### ISSUE THREAD

**Issue by arvin944** [msasanmh/SecureDNSClient#139]
سلام
وقت بخیر 
طبق آموزش جلو رفتم و آخر سر هم میزنه : Proxy Server http://127.0.0.1:8080 set to system
اما عملا کار نمیکنه و یوتیوب رو باز نمیکنه
اما وقتی در کنار v2ray ازش استفاده میکنم پینگ رو پایین میاره

**Comment by msasanmh** [comment]
> سلام
> وقت بخیر 
> طبق آموزش جلو رفتم و آخر سر هم میزنه : Proxy Server http://127.0.0.1:8080 set to system
> اما عملا کار نمیکنه و یوتیوب رو باز نمیکنه
> اما وقتی در کنار v2ray ازش استفاده میکنم پینگ رو پایین میاره
> 

طبق کدوم آموزش؟
برای bypass کردن DPI از کدوم یک از روش‌های پایین استفاده کردی؟
Proxy fragment
Proxy ssl decryption 
GoodbyeDPI 
و از کدوم isp استفاده میکنی؟

**Comment by arvin944** [comment]
یه آموزش هست داخل این همین پیج گیت هاب من طبق اون جلو رفتم

در مورد سوال دومت زیاد اطلاع ندارم فقط اینو میدونم یه تب هست داخل برنامه به اسم GoodbyeDPI که اونو فعال کردم رو حالت mode1


از نت مخابرات استفاده میکنم

**Comment by arvin944** [comment]
یه آموزش هست داخل این همین پیج گیت هاب من طبق اون جلو رفتم

در مورد سوال دومت زیاد اطلاع ندارم فقط اینو میدونم یه تب هست داخل برنامه به اسم GoodbyeDPI که اونو فعال کردم رو حالت mode1

از نت مخابرات استفاده میکنم
