### ISSUE TITLE
dpi / doh / certificate

### ISSUE THREAD

**Issue by HajAmir9** [msasanmh/SecureDNSClient#14]
سلام خسته نباشی عزیز دل بابت همه ی زحماتتم دستت درد نکنه
DPI Check: The SSL connection could not be established, see inner exception.
Unable to check. Try open [www.youtube.com](http://www.youtube.com/) in your browser.
 همچین اروری میده
بعلاوه اینکه چیزی برای نصب سرتیفیکیت نمیاره برام دسترسی فایروالم دادم بش
doh که بخاطر همین موضوع فعال نمیشه
اما با همین تفاسیر روی نت مخابرات یوتوب بالا میاد همه چیش اما ویدیو ها و تامب نیل هاش بالا نمیاد
کامنت ها  اینا بالا میاد اما خب ..
متشکر

**Comment by msasanmh** [comment]
> سلام خسته نباشی عزیز دل بابت همه ی زحماتتم دستت درد نکنه
> DPI Check: The SSL connection could not be established, see inner exception.
> Unable to check. Try open [www.youtube.com](http://www.youtube.com/) in your browser.
>  همچین اروری میده
> بعلاوه اینکه چیزی برای نصب سرتیفیکیت نمیاره برام دسترسی فایروالم دادم بش
> doh که بخاطر همین موضوع فعال نمیشه
> اما با همین تفاسیر روی نت مخابرات یوتوب بالا میاد همه چیش اما ویدیو ها و تامب نیل هاش بالا نمیاد
> کامنت ها  اینا بالا میاد اما خب ..
> متشکر

نصب سرتیفیکیت برای راه‌اندازی سرور لوکال DoH هستش، من بطور پیش‌فرض خاموشش کردم چون خیلی نیاز نیست.
این ارور جریانش چیز دیگه ایه. برنامه نتونسته بروی ISP شما کارش رو به درستی انجام بده.
از قسمت Bypass DPI مود های مختلف رو امتحان کنید، شاید یکیش با ISP شما سازگار بود.

**Comment by msasanmh** [comment]
> سلام خسته نباشی عزیز دل بابت همه ی زحماتتم دستت درد نکنه
> DPI Check: The SSL connection could not be established, see inner exception.
> Unable to check. Try open [www.youtube.com](http://www.youtube.com/) in your browser.
>  همچین اروری میده
> بعلاوه اینکه چیزی برای نصب سرتیفیکیت نمیاره برام دسترسی فایروالم دادم بش
> doh که بخاطر همین موضوع فعال نمیشه
> اما با همین تفاسیر روی نت مخابرات یوتوب بالا میاد همه چیش اما ویدیو ها و تامب نیل هاش بالا نمیاد
> کامنت ها  اینا بالا میاد اما خب ..
> متشکر

مشکل دور زدن همراه اول در ورژن جدید برطرف شد.
