### ISSUE TITLE
کار نکردن برنامه به صورت جدا

### ISSUE THREAD

**Issue by arvin944** [msasanmh/SecureDNSClient#140]
یه آموزش هست داخل این همین پیج گیت هاب من طبق اون جلو رفتم

در مورد سوال دومت زیاد اطلاع ندارم فقط اینو میدونم یه تب هست داخل برنامه به اسم GoodbyeDPI که اونو فعال کردم رو حالت mode1

از نت مخابرات استفاده میکنم

_Originally posted by @arvin944 in https://github.com/msasanmh/SecureDNSClient/issues/139#issuecomment-1975090068_

**Comment by msasanmh** [comment]
>               یه آموزش هست داخل این همین پیج گیت هاب من طبق اون جلو رفتم
> 
> در مورد سوال دومت زیاد اطلاع ندارم فقط اینو میدونم یه تب هست داخل برنامه به اسم GoodbyeDPI که اونو فعال کردم رو حالت mode1
> 
> از نت مخابرات استفاده میکنم
> 
> _Originally posted by @arvin944 in https://github.com/msasanmh/SecureDNSClient/issues/139#issuecomment-1975090068_
>             
خب GoodbyeDPI که بروی مخابرات یعنی ۹۹ درصد موارد کار نمی‌کنه. پس اون رو فعال نکن.
و تنها گزینه‌ای که می‌تونه مخابرات رو Bypass کنه استفاده از SSL Decryption هستش.
این کارها رو به ترتیب انجام بدی راحت میتونی یوتیوب رو باز کنی:
۱. از تب چک یه سری dns اسکن کن.
۲. از تب کانکت، گزینه اول رو انتخاب کن و بروی کانکت کلیک کن.
۳. وقتی dns آنلاین شد از تب سوم آداپتر خودت رو انتخاب کن و روی Set DNS کلیک کن.
۴. از تب Share + Bypass DPI اول چک گزینه 
Enable SSL Decryption 
رو بزن تا برنامه سرتیفیکیت رو نصب کنه، یه پنجره ظاهر میشه که باید روی Yes کلیک کنی.

قسمت SSL Decryption Options باید گزینه Change SNI تیک داشته باشه.
برای قسمت Default SNI یک دامین بذار که فیلتر نیست، مثل speedtest.net یا google.com

بروی Start Proxy کلیک کن تا پراکسی ران بشه.
بروی Set Proxy کلیک کن تا پراکسی روی ویندوز ست بشه.

دیگه GoodbyeDPI رو فعال نکن.

حالا اگه مرورگرت باز هست باید ببندی و دوباره بازش کنی، چون سرتیفیکیت تغییر کرده و نیازه که مرورگر ری‌استارت بشه.

اگر در مرورگرت از افزونه‌های پراکسی استفاده میکنی بروی System Proxy قرارش بده.

حالا میتونی یوتیوب رو باز کنی.

و باید بگم این روش می‌تونه یوتیوب رو در هر کشوری که وبسایت google.com فیلتر نیست باز کنه.

اگه نتونستی باز کنی یعنی یه جای کار رو اشتباه انجام دادی، اونوقت برام اسکرین شات از تب‌های مختلف و همینطور قسمت status و log بفرست تا ببینم جریان چیه.

**Comment by AmirhosseinBrooklyn** [comment]
سلام ساسان عزیز، روزت بخیر
اول از همه ممنونم بابت برنامه‌ی خوبت، وقتی ریپازیتوریت رو مطالعه می‌کردم باورم نمیشد یه ایرانی چنین برنامه‌ی خوب و کاربردی هم برای امنیت و هم برای دسترسی به برخی سایت‌های فیلتر شده از طریق SNI طراحی کرده باشه.
اما متاسفانه از وقتی نصبش کردم تا الان یکبارم موفق به اتصال باهاش نشدم...

طبق همین راهنمایی که گفتم پیش رفتم

> ۲. از تب کانکت، گزینه اول رو انتخاب کن و بروی کانکت کلیک کن.

امّا متاسفانه به DNS کانکت نمیشه و پیام زیر در لاگ ثبت میشه:
```
Checking For ICS Service Port Conflict...
Connecting... Please Wait...

Msmh Agnostic Server v3.0.9.0
Type "Help" To Get Help.

Profile Set To DNS

Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: False
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53

Profile Set To DoH

Settings:
Port: 443
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: False
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53

SSL Settings:
Enabled: True
RootCA_Path:
C:\Users\Brooklyn\AppData\Local\SecureDNSClient\UserData\certificate\rootCA.crt
RootCA_KeyPath:
C:\Users\Brooklyn\AppData\Local\SecureDNSClient\UserData\certificate\rootCA.key
Cert_Path:
C:\Users\Brooklyn\AppData\Local\SecureDNSClient\UserData\certificate\localhost.crt
Cert_KeyPath:
C:\Users\Brooklyn\AppData\Local\SecureDNSClient\UserData\certificate\localhost.key
Change SNI: False
Default SNI: Empty (Original SNI Will Be Used)
WriteRequestsToLog: True

Parent Process ID: 85380

Starting DNS...
DNS Started

Starting DoH...
DoH Started
Confirmed
Connected.
Waiting For DNS To Get Online...
DNS Can't Get Online (Check Domain: youtube.com). Check Servers.

Connect Task: False
```
همچنین وضعیت استاتوس هم به شرح زیر هست:
![2024-07-25_04-07-42](https://github.com/user-attachments/assets/2914c3e2-89ae-493e-a993-fddad9018528)
لازم به ذکره که به جز نصب سرتیفیکیت SSL Decryption اقدام دیگه‌ای انجام ندادم.
همچنین با GoodbyeDPI هم در مودهای مختلف تست کردم متصل نشد.
اینترنتم هم TD-LTE برروی اپراتور ایرانسل هست.
ممنون میشم راهنماییم کنی تا بتونم از اپ خوبت استفاده کنم چون هیچ آموزش جامع و خوبی براش پیدا نکردم این زیر گفتم اعلامش کنم.
