### ISSUE TITLE
NS_BINDING_CANCELLED_OLD_LOAD" and "NS_BINDING_ABORTED

### ISSUE THREAD

**Issue by DogancanYr** [msasanmh/SecureDNSClient#141]
Sometimes I encounter such errors: either the site does not open at all or I have to wait.

**Comment by msasanmh** [comment]
This is a firefox issue, it has nothing to do with SDC, you need to clear or disable cache in firefox. 
But leave this issue open, I want to dig more about it later, currently I'm super busy.

**Comment by DogancanYr** [comment]
Even though I deleted the cache, nothing changed and when I open it from Chrome, the site looks like this. 
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/2f8ff3bd-d28a-410f-bd9b-59526635b181)

**Comment by msasanmh** [comment]
OK, if also chrome gives you the same error, it means proxy couldn't load the website. there was  no send and receive data so proxy cancelled the request on timeout. 
Maybe it can't just bypass it.
On which websites you are facing this issue?

**Comment by DogancanYr** [comment]
and distrowatch.com

**Comment by msasanmh** [comment]
I have no problem with those websites. I can't be helpful when i can't replicate your issue. 
![20240310_233551.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/0150465e-4718-4ebf-9dfc-36706736b3ae)

![20240310_233841.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/a9ea7fcf-e433-45de-9153-20d6d5aeda88)

**Comment by DogancanYr** [comment]
With which setting did you enable the software to issue the certificate?

**Comment by msasanmh** [comment]
> With which setting did you enable the software to issue the certificate?
> 

I'm using Proxy SSL Decryption. 
Because GoodbyeDPI doesn't work on most ISPs in my country. 
Settings like below:
![20240311_005915.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/b4e46892-87eb-456b-92ff-5d72144d87b2)

![20240311_005941.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/e1c30036-4ae0-4bd4-a0cf-7e58282f1a0a)

**Comment by DogancanYr** [comment]
I found out why it gives these errors. The site has been categorized as infected, but it has not been banned. Is there a way to overcome this ? 

![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/ab59d129-9983-4ebe-bfda-0cf6f96452c6)
![resim](https://github.com/msasanmh/SecureDNSClient/assets/90002969/d5ff2e8d-b6af-4d08-91f1-33997d2858e1)

**Comment by msasanmh** [comment]
Based on my research, your antivirus (Internet Security software) is canceling the request to this website. 
Usually, using a VPN can solve this problem.

And again, for the readers of this thread, SDC has nothing to do with this error.

**Comment by DogancanYr** [comment]
Yes, it has nothing to do with the software, I'm just writing because it can't bypass it. Continues even after turning off antivirus  .

**Comment by msasanmh** [comment]
> Yes, it has nothing to do with the software, I'm just writing because it can't bypass it. Continues even after turning off antivirus  .

I heard usually disabling antivirus won't be enough, they say uninstall it or try opening the website on another device.

**Comment by DogancanYr** [comment]
I tried it from another computer, another browser, and a computer without antivirus, but nothing changes.

**Comment by msasanmh** [comment]
> I tried it from another computer, another browser, and a computer without antivirus, but nothing changes.

Maybe it's about your ISP. Try a VPN.

**Comment by DogancanYr** [comment]
When I select Turkey from VPN and try it, the site opens also, when I open the secure DNS client, it accesses banned sites.


I can already bypass all bans by choosing a different location from the VPN.

**Comment by msasanmh** [comment]
> When I select Turkey from VPN and try it, the site opens also, when I open the secure DNS client, it accesses banned sites.
> 
> 
> I can already bypass all bans by choosing a different location from the VPN.
> 

Because a VPN encrypts your connection and your ISP can't find out which websites or even IPs you are connecting to, but SDC only hides the websites addresses from ISP not their IPs.

**Comment by DogancanYr** [comment]
It means it doesn't work because they do IP-based blocking. 😊

**Comment by msasanmh** [comment]
> It means it doesn't work because they do IP-based blocking. 😊

Ouch, glad you found out the reason.
