### ISSUE TITLE
Unable to start GoodbyeDPI in advanced mode

### ISSUE THREAD

**Issue by Katzenwerfer** [msasanmh/SecureDNSClient#142]
Getting this error when starting the tool in advanced mode.
Couldn't find if the app reports any sort of logs, so can't really tell what is causing that.
```
GoodbyeDPI couldn't start, try again.
```

**Comment by Katzenwerfer** [comment]
> Try white list it in your antivirus.

I am not convinced that would help in any way. Tried it in any case and the problem still persists.
I did found that clicking the start button many times eventually works, but it stops some seconds after.

**Comment by msasanmh** [comment]
> > Try white list it in your antivirus.
> 
> I am not convinced that would help in any way. Tried it in any case and the problem still persists.
> I did found that clicking the start button many times eventually works, but it stops some seconds after.

Unfortunately I can't do anything about external apps, if they have any bugs I cannot fix it, it would be their developers job. For example if you enable an option a bug may occur. For basic section I chose only stable options. 
Anyway why don't you use proxy instead, it's way powerful than GoodbyeDPI.

**Comment by Katzenwerfer** [comment]
> Anyway why don't you use proxy instead, it's way powerful than GoodbyeDPI.
I don't know how to use it, and I'm already used to GDPI.
In any case, I hope there is something I can do to try and have this fixed :/

**Comment by msasanmh** [comment]
> > Anyway why don't you use proxy instead, it's way powerful than GoodbyeDPI.
> 
> I don't know how to use it, and I'm already used to GDPI. 
> In any case, I hope there is something I can do to try and have this fixed :/

Try 32 bit version of gdpi, just replace it in binary folder.
