### ISSUE TITLE
پیشنهاد برای ست کردن DNS IPv6

### ISSUE THREAD

**Issue by matpat9191** [msasanmh/SecureDNSClient#143]
سلام
من مدتها نمیتونستم از این برنامه روی سیستم خودم استفاده کنم ولی چند جای دیگه به راحتی وصل میشد، الان تونستم مشکل را پیدا کنم، مودم من huawei B622 هست و وقتی DNS را روی IPv4 ست میکردم از دستور nslookup وقتی تست میگرفتم میدیدم یچیز دیگه نشون میده تا اینکه متوجه شدم باید حتما IPv6 را هم ست کنم. فکر کنم خود مودم پیشفرض IPv6 را ست میکنه. اول هم فکر میکردم مشکل از سیستمم باشه ولی وقتی ی سیستم جدید خریدم دیدم همون ایراد قبلی کماکان هست!!!
الان برنامه شمارو اجرا کردم همه چیز وصل شد ولی طبق معمول کار نمیکرد اومدم 127.0.0.1 که روی IPv4 DNS ست شده بود را به IPv6 تبدیل کردم و خودم دستی روی ویندوز روی IPv6 ست کردم و YouTube به راحتی باز شد
خواستم اگر امکانش باشه این قابلیت هم به برنامه اضافه کنید .
با تشکر بخاطر این برنامه بسیار حرفه ای

**Comment by msasanmh** [comment]
این مشکل در ورژن بعد رفع میشه.
اما ورژن بعد زمان بیشتری میبره تا release بشه چون آپدیت بزرگی تو راهه.

**Comment by msasanmh** [comment]
انجام شد

**Comment by matpat9191** [comment]
نسخه جدید عالی شده
ممنون بخاطر زحماتی که میکشید
