### ISSUE TITLE
Change SNI Doesn't Work Without Activating "Proxy Rules" From Settings.

### ISSUE THREAD

**Issue by msasanmh** [msasanmh/SecureDNSClient#144]
In Proxy Rules Add This Line To Make Change SNI Work:
*|+;

Will Be Solved...

**Comment by amoahmad** [comment]
سلام داداش خوبی . یه دنیا ممنون بابت برنامه که ساختی کلی از مشکلات منو حل کرده فقط یه سوال واسم پیش امده ورژن قدیمی وصل میشه اما ورژن جدید وصل نمیشه من مبینت دارم طبق روش قبلی که گفته بودی  enable ssl با Change SNI  می زدم مشکل حل میشد اما تو ورژن جدید کار نمی کنه این روشی که گفتی تغییر بده رو پیدا نمی کنم کجاش میشه ممنون میشم با عکس توضیح بدی تشکر

**Comment by msasanmh** [comment]
> سلام داداش خوبی . یه دنیا ممنون بابت برنامه که ساختی کلی از مشکلات منو حل کرده فقط یه سوال واسم پیش امده ورژن قدیمی وصل میشه اما ورژن جدید وصل نمیشه من مبینت دارم طبق روش قبلی که گفته بودی  enable ssl با Change SNI  می زدم مشکل حل میشد اما تو ورژن جدید کار نمی کنه این روشی که گفتی تغییر بده رو پیدا نمی کنم کجاش میشه ممنون میشم با عکس توضیح بدی تشکر 

سلام، متاسفانه دو تا سوتی دادم توی ورژن آخر، یکی همین مورد و اون یکی تم برنامه است.
برای حل این مشکل برو به تنظیمات: 
Settings -> Share -> Advanced 
و گزینه Enable Proxy Rules رو چک بزن.
حالا بروی Edit Proxy Rules کلیک کن. یه فایل متنی باز میشه.
داخل فایل متنی اینو بنویس:
*|+;
فایل رو سیو کن و بعد طبق ورژن قبل میتونی وصل بشی.

**Comment by msasanmh** [comment]
*|+;

**Comment by amoahmad** [comment]
حل شد دادا دمت گرم
