### ISSUE TITLE
this panel make connection disconnected 

### ISSUE THREAD

**Issue by wolfkingal2000** [msasanmh/SecureDNSClient#145]
![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/ea7e112d-0a31-444e-a8af-6676e32d3623)

سلام خوبی . این پلن بالا میاد کلا قطع میشه اینترنت  این ها اگه میشه یه تنظیمات اضافه کن بشه این بخش رو غیر فعال کرد  چون من از proxy  این برنامه استفاده نمیکنم بشه قطع ش کرد خوبه

**Comment by msasanmh** [comment]
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/ea7e112d-0a31-444e-a8af-6676e32d3623)
> 
> سلام خوبی . این پلن بالا میاد کلا قطع میشه اینترنت  این ها اگه میشه یه تنظیمات اضافه کن بشه این بخش رو غیر فعال کرد  چون من از proxy  این برنامه استفاده نمیکنم بشه قطع ش کرد خوبه 

پراکسی اتوماتیک فعال نمیشه، این فقط یه هشداره، میگه روی سیستمت یه پراکسی ست کردی که نمی‌تونه گوگل رو باز کنه.
اگه اینترنت قطع میشه بخاطر همون پراکسی‌ایه که ست کردی، چون کار نمیکنه و از پورتش پیداست که برای v2ray هستش.
پس یا باید v2ray رو اجرا کنی یا پراکسیش رو آن‌ست کنی تا اینترنت داشته باشی.

**Comment by wolfkingal2000** [comment]
> > ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/ea7e112d-0a31-444e-a8af-6676e32d3623)
> > 
> > سلام خوبی . این پلن بالا میاد کلا قطع میشه اینترنت  این ها اگه میشه یه تنظیمات اضافه کن بشه این بخش رو غیر فعال کرد  چون من از proxy  این برنامه استفاده نمیکنم بشه قطع ش کرد خوبه 
> 
> پراکسی اتوماتیک فعال نمیشه، این فقط یه هشداره، میگه روی سیستمت یه پراکسی ست کردی که نمی‌تونه گوگل رو باز کنه.
> اگه اینترنت قطع میشه بخاطر همون پراکسی‌ایه که ست کردی، چون کار نمیکنه و از پورتش پیداست که برای v2ray هستش.
> پس یا باید v2ray رو اجرا کنی یا پراکسیش رو آن‌ست کنی تا اینترنت داشته باشی.

اون میدونم ولی چک کردم از اون نبود وقتی آمدم این هشدارها رو قطع کردم برگشت  نتم

**Comment by msasanmh** [comment]
> > > ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/ea7e112d-0a31-444e-a8af-6676e32d3623)
> > > 
> > > سلام خوبی . این پلن بالا میاد کلا قطع میشه اینترنت  این ها اگه میشه یه تنظیمات اضافه کن بشه این بخش رو غیر فعال کرد  چون من از proxy  این برنامه استفاده نمیکنم بشه قطع ش کرد خوبه 
> > 
> > پراکسی اتوماتیک فعال نمیشه، این فقط یه هشداره، میگه روی سیستمت یه پراکسی ست کردی که نمی‌تونه گوگل رو باز کنه.
> > اگه اینترنت قطع میشه بخاطر همون پراکسی‌ایه که ست کردی، چون کار نمیکنه و از پورتش پیداست که برای v2ray هستش.
> > پس یا باید v2ray رو اجرا کنی یا پراکسیش رو آن‌ست کنی تا اینترنت داشته باشی.
> 
> اون میدونم ولی چک کردم از اون نبود وقتی آمدم این هشدارها رو قطع کردم برگشت  نتم 

آها، کلا میخوای هشدار نباشه، میتونم بذارم موقع چک سرورها نشون بده. چون اگه پراکسی نتونه گوگل رو باز کنه سرورها failed میشن.

**Comment by wolfkingal2000** [comment]
> > > > ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/ea7e112d-0a31-444e-a8af-6676e32d3623)
> > > > 
> > > > سلام خوبی . این پلن بالا میاد کلا قطع میشه اینترنت  این ها اگه میشه یه تنظیمات اضافه کن بشه این بخش رو غیر فعال کرد  چون من از proxy  این برنامه استفاده نمیکنم بشه قطع ش کرد خوبه 
> > > 
> > > پراکسی اتوماتیک فعال نمیشه، این فقط یه هشداره، میگه روی سیستمت یه پراکسی ست کردی که نمی‌تونه گوگل رو باز کنه.
> > > اگه اینترنت قطع میشه بخاطر همون پراکسی‌ایه که ست کردی، چون کار نمیکنه و از پورتش پیداست که برای v2ray هستش.
> > > پس یا باید v2ray رو اجرا کنی یا پراکسیش رو آن‌ست کنی تا اینترنت داشته باشی.
> > 
> > اون میدونم ولی چک کردم از اون نبود وقتی آمدم این هشدارها رو قطع کردم برگشت  نتم 
> 
> آها، کلا میخوای هشدار نباشه، میتونم بذارم موقع چک سرورها نشون بده. چون اگه پراکسی نتونه گوگل رو باز کنه سرورها failed میشن.

اره همین منظورم

**Comment by msasanmh** [comment]
اعمال شد
