### ISSUE TITLE
Problem with the software

### ISSUE THREAD

**Issue by retired-ambassador** [msasanmh/SecureDNSClient#147]
مشکلي که بقيه دوستان بهش اشاره کردن براي من هم پيش اومد و مطابق توضيحاتي که دادين (فعال کردن SSL و مابقي موارد) پيش رفتم اما ارور زير رو نشون ميده :

Check DPI Bypass:An error occurred while sending the request.

**Comment by msasanmh** [comment]
> مشکلي که بقيه دوستان بهش اشاره کردن براي من هم پيش اومد و مطابق توضيحاتي که دادين (فعال کردن SSL و مابقي موارد) پيش رفتم اما ارور زير رو نشون ميده :
> 
> Check DPI Bypass:An error occurred while sending the request.

‐ یعنی Proxy Rules رو فعال کردید؟
- اگه فعال هست ممکنه بخاطر فعال بودن ipv6 باشه که در ورژن بعد ساپورتش می‌کنم تا اون موقع میتونید ipv6 رو غیرفعال کنید.
- نام SNI حتما باید ست باشه.
- سرتیفیکیت حتما باید نصب باشه.
- و DNS حتما باید روشن و ست باشه.
موارد بالا رو بررسی کن و دوباره تست کن.

**Comment by retired-ambassador** [comment]
موارد بالا رو اعمال کردم ولي کماکان مشکل پابرجاست (عکسا رو به پيوست ميفرستم):
![SDC1](https://github.com/msasanmh/SecureDNSClient/assets/91376644/9fa79859-35c2-43e4-a52f-9083db790ddc)
![SDC2](https://github.com/msasanmh/SecureDNSClient/assets/91376644/841104c4-05fa-45df-a1b6-dcfa01823ec6)
![SDC3](https://github.com/msasanmh/SecureDNSClient/assets/91376644/89f13e40-9fb9-48e1-9f55-7650870cd841)
![SDC4](https://github.com/msasanmh/SecureDNSClient/assets/91376644/883fcc29-1ee9-4e29-91ac-6b501bffa3ff)

**Comment by msasanmh** [comment]
خب تا اینجا همه چی درسته، اما proxy rules رو نگفتی.
Settings -> Share -> Advanced 
فعالش کردی؟ و داخلش *|+; رو نوشتی؟

**Comment by msasanmh** [comment]
*|+;

**Comment by retired-ambassador** [comment]
حل شد. دم شما گرم

**Comment by msasanmh** [comment]
برطرف شد

**Comment by retired-ambassador** [comment]
وقت بخیر. نرم افزار رو برای یه سیستم دیگه میخوام راه بندازم. تمامی مراحل به درستی پیش میره و حتی پیام تست اتصال به youtube هم بدون مشکل میاد اما موقع باز کردن youtube توو مرورگر، میزنه  You're offline. Check your connection . برای لینک بقیه سایتا هم همینه. اشکال کار کجاست؟

![SDC](https://github.com/msasanmh/SecureDNSClient/assets/91376644/238a9533-d4c8-4401-8833-eb5597607d4c)

**Comment by msasanmh** [comment]
> وقت بخیر. نرم افزار رو برای یه سیستم دیگه میخوام راه بندازم. تمامی مراحل به درستی پیش میره و حتی پیام تست اتصال به youtube هم بدون مشکل میاد اما موقع باز کردن youtube توو مرورگر، میزنه  You're offline. Check your connection . برای لینک بقیه سایتا هم همینه. اشکال کار کجاست؟
> 
> ![SDC](https://github.com/msasanmh/SecureDNSClient/assets/91376644/238a9533-d4c8-4401-8833-eb5597607d4c)
> 

در همین صفحه‌ای که توی عکس هست گزینه
Write requests to log
رو چک بزن، اگه دیدی تعدادی خط به رنگ زرد وجود داره به احتمال زیاد مرورگر داره تعداد زیادی درخواست active portal می‌فرسته. 
گاهی اوقات مرورگرها فکر میکنن که پراکسی نیاز به لاگین داره و کلی درخواست active portal می‌فرستن. 

برنامه و مرورگر رو ری‌استارت کنید. مرورگر رو بعد از اینکه برنامه به طور کامل اجرا شد باز کنید.
در صورت امکان از آخرین نسخه برنامه استفاده کنید.

**Comment by retired-ambassador** [comment]
مراحل بالا رو اجرا کردم، تعداد زیادی پیام زرد پشت سر هم میاد (هم برای firefox و هم برای chrome). چطوری میشه این مشکل رو برطرف کرد؟
![SDC_2](https://github.com/msasanmh/SecureDNSClient/assets/91376644/b8bd512e-a20a-4f22-ae3f-35509643ee0f)

**Comment by msasanmh** [comment]
> مراحل بالا رو اجرا کردم، تعداد زیادی پیام زرد پشت سر هم میاد (هم برای firefox و هم برای chrome). چطوری میشه این مشکل رو برطرف کرد؟
> ![SDC_2](https://github.com/msasanmh/SecureDNSClient/assets/91376644/b8bd512e-a20a-4f22-ae3f-35509643ee0f)
> 
> 

اگه با ری‌استارت کردن برنامه و مرورگر مشکل حل نشد، از داخل تنظیمات 
Settings -> Share -> Basic
تیک گزینه Block port 80 رو بردارید و دوباره تست کنید.
متاسفانه راه حل خاصی برای رفع این مشکل نیست، فقط باید مرورگر بی‌خیال فرستادن درخواست active portal بشه.

معمولا با یکی دو بار ری‌استارت مرورگر این مشکل حل میشه.
