### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by pipitivi** [msasanmh/SecureDNSClient#15]
I have problem. The GUI was crashed when connecting via http-proxy-server but everything still working fine.
I'm using latest version v2.0.9.

**Comment by italy2010** [comment]
روی ویندوز 11 بعد از چند دقیقه برنامه میپره بیرون و باید دوباره اجرا کرد.

**Comment by msasanmh** [comment]
> روی ویندوز 11 بعد از چند دقیقه برنامه میپره بیرون و باید دوباره اجرا کرد.

این اتفاق فقط زمانی میوفته که HTTP Proxy روشن باشه، این قسمت هنوز آزمایشیه و این مشکل پیش میاد.

**Comment by msasanmh** [comment]
Issue fixed.
