### ISSUE TITLE
problem with smart dns (not bypassing boycotted websites)

### ISSUE THREAD

**Issue by rti2** [msasanmh/SecureDNSClient#150]
سلام و تشکر بابت برنامه ی خوبتون .
من قبلا طبق داکیومنت proxy rule این rule های زیر رو نوشتم (برای استفاده از شکن برای سایت های تحریم  ) ولی کار نمی کنن :
// Use Smart DNS For These Domains
gemini.google.com|--;dns:SmartDns1,SmartDns2,SmartDns3;
*.openai.com|--;dns:SmartDns1;
claude.ai|--;dns:SmartDns1,SmartDns2,SmartDns3;
*.spotify.com|--;dns:SmartDns1,SmartDns2,SmartDns3;
و اینکه امکانش هست برای برنامه تعریف کنیم که واسه سایت هایی که نمی تونه عبور بده از این پراکسی خاص استفاده کنه ؟
 (اون socks از V2rayN/Nekoray باشه)
و اینکه بگیم این برنامه هارو exclude کن (برای V2rayN/Nekoray که در کانکشن اختلال ایجاد نشه )

**Comment by msasanmh** [comment]
همین الان تست کردم قوانین شما رو و کار کردن، یادتون باشه این قوانین برای پراکسی هستن یعنی حتما پراکسی باید اجرا و ست باشه.
در ورژن بعد این قوانین میتونه در سطح dns اجرا بشه که دیگه نیازی به اجرا و ست پراکسی نباشه.
و DNS هم که همیشه باید Online و ست باشه.
قوانینت یه کوچولو اشکال داشت این پایین درستش رو می‌نویسم:

**Comment by rti2** [comment]
منظورت بخش variables ؟ اون تو خود فایل بود من بخش سایتش رو گذاشتم 
و ممنون بخاطر رسیدگی و سرعت عمل 3>

**Comment by msasanmh** [comment]
> و اینکه امکانش هست برای برنامه تعریف کنیم که واسه سایت هایی که نمی تونه عبور بده از این پراکسی خاص استفاده کنه ؟
>  (اون socks از V2rayN/Nekoray باشه)
> و اینکه بگیم این برنامه هارو exclude کن (برای V2rayN/Nekoray که در کانکشن اختلال ایجاد نشه )

برای این کار v2ray رو باید بروی پراکسی مود قرار بدید. بعد به قسمت 
Settings -> Share -> Basic
برید و use upstream proxy رو فعال کنید.
برای اینکه فقط وبسایت‌هایی که خودش نمیتونه باز کنه رو از v2ray استفاده کنه گزینه apply only to blocked ips باید چک داشته باشه.
و در کادر پایین هم Host رو بروی 127.0.0.1 بذارید و پورت v2ray هم در قسمت پورت بذارید.
حالا v2ray اجرا باشه و بعد پراکسی برنامه رو اجرا کنید

**Comment by msasanmh** [comment]
> منظورت بخش variables ؟ اون تو خود فایل بود من بخش سایتش رو گذاشتم 
> و ممنون بخاطر رسیدگی و سرعت عمل 3>

خب پراکسی رو از تب Share + Bypass DPI اجرا کردی؟

**Comment by rti2** [comment]
بله کامل کامل اجرا کردم

**Comment by rti2** [comment]
و از بخش share + bypass DPI  ،  
rule status chat.openai.com :> Domain:
chat.openai.com
Is Match: True
Is Black List: False
Is Port Block: False
DNS Server:
https://free.shecan.ir/dns-query
Query Domain:
chat.openai.com
Act As Smart DNS: True
IP: 107.150.34.98
Apply DPI Bypass: False
Apply UpStream Proxy: False
Can Get Headers: True

**Comment by msasanmh** [comment]
> بله تیک گزینه Enable Proxy Rules فعاله
> بله  از طریق برنامه 

خب دراینصورت باید راحت کار کنه، وقتی میگی کار نمیکنه دقیقا منظورت چیه، یعنی یکی از وبسایت‌هایی که داخل proxy rules هستن رو باز میکنی مرورگر چی نشون میده؟

**Comment by rti2** [comment]
یکی از سایت های داخل لیست مثلا  chat.openai.com
میرم توش ارور 403 acces denid  میده و  آی پی ایرانم رو هم می نویسه

**Comment by msasanmh** [comment]
> یکی از سایت های داخل لیست مثلا  chat.openai.com
> میرم توش ارور 403 acces denid  میده و  آی پی ایرانم رو هم می نویسه

مگه مرورگر رو بعد اجرای پراکسی ری‌استارت نکردی؟

**Comment by rti2** [comment]
چرا کلا به یه مرورگر دیگه هم اومدم همین بود

**Comment by msasanmh** [comment]
فهمیدم شما باید Enable SSL Decryption رو فعال کنی و بعد دیگه ip ایران نشون نمیده.
این یه باگ هست باید در ورژن بعد برطرف کنم.

**Comment by msasanmh** [comment]
> اوکی ممنون 
> برنامه ای برای ورژن اندروید داری ؟

نه متاسفانه. من فقط برنامه‌نویس ویندوز هستم

**Comment by msasanmh** [comment]
> یه سوال .
> توی check کردن  معمولی همه ی سرور ها چک میشن ؟
> 

در قسمت 
Settings -> Check
میتونید تعیین کنید که چه پروتکل‌هایی چک بشن.
اگه در قسمت Select Protocol همه رو تیک بزنید و در قسمت sdns همه تیک‌ها رو بردارید اونوقت همه سرورها چک میشن

**Comment by rti2** [comment]
برای دانلود از تورنت پیشنهاد میکنید SDC رو ؟

**Comment by msasanmh** [comment]
> برای دانلود از تورنت پیشنهاد میکنید SDC رو ؟

نه، هیچ تاثیری بروی p2p نداره

**Comment by Rahjooyan** [comment]
سلام. برای رفع تحریم تارنماهایی که شکن و 403 و ... کمک نمی‌کنند ممکن است در SDC راه‌حلی فراهم کنید؟ مثلا:
[https://wetv.vip/en/play/o0hsesf2uqo9a6k-The%20Four%20Daughters%20of%20Luoyang/k0042bx471b-EP2%3A%20The%20Four%20Daughters%20of%20Luoyang](url)

**Comment by msasanmh** [comment]
> سلام. برای رفع تحریم تارنماهایی که شکن و 403 و ... کمک نمی‌کنند ممکن است در SDC راه‌حلی فراهم کنید؟ مثلا:
> [https://wetv.vip/en/play/o0hsesf2uqo9a6k-The%20Four%20Daughters%20of%20Luoyang/k0042bx471b-EP2%3A%20The%20Four%20Daughters%20of%20Luoyang](url)

متاسفانه این وبسایت براساس IP فیلتر شده و هیچ راهی بجز استفاده از فیلترشکن نیست.

**Comment by shahabparisa** [comment]
سلام خسته نباشید ببخشید تو ورژن جدید برنامه کانکت نمیشه و این خطا رو میده : 
port 53 is occupied by "svchost". you need to resolve the conflict.
ممنون میشم بطور ساده بگید چطوری باید حلش کنم

**Comment by msasanmh** [comment]
> سلام خسته نباشید ببخشید تو ورژن جدید برنامه کانکت نمیشه و این خطا رو میده : 
> port 53 is occupied by "svchost". you need to resolve the conflict.
> ممنون میشم بطور ساده بگید چطوری باید حلش کنم 

این آموزش ویدیویی رو ببینید
https://github.com/msasanmh/SecureDNSClient/issues/154
