### ISSUE TITLE
افزایش دی ان اس های معتبر

### ISSUE THREAD

**Issue by Noob2Pr0** [msasanmh/SecureDNSClient#151]
سلام به دوست عزیزم
داداش چه کردن با ما که به اینجا رسیدیم
یک ماه پیش اسکن میکردم از 132 تا 93 تا کارمیکرد
الان نوشته 20 تا !!!! تازه تاخیر رو می بینی خون گریه میکنی (پیوست کردم)
اپراتور ایرانسلم
میشه dns هایی رو پیدا کرد که معتبر و امن باشن ؟
میشه کاری کرد که dns رو از لیست خاصی رمز نگاری شده ای چیزی بگیره ؟
<img width="493" alt="sssa" src="https://github.com/msasanmh/SecureDNSClient/assets/127764068/8e8bb608-88f7-47be-81fc-c0f8a5b617cb">

**Comment by msasanmh** [comment]
> سلام به دوست عزیزم
> داداش چه کردن با ما که به اینجا رسیدیم
> یک ماه پیش اسکن میکردم از 132 تا 93 تا کارمیکرد
> الان نوشته 20 تا !!!! تازه تاخیر رو می بینی خون گریه میکنی (پیوست کردم)
> اپراتور ایرانسلم
> میشه dns هایی رو پیدا کرد که معتبر و امن باشن ؟
> میشه کاری کرد که dns رو از لیست خاصی رمز نگاری شده ای چیزی بگیره ؟
> <img width="493" alt="sssa" src="https://github.com/msasanmh/SecureDNSClient/assets/127764068/8e8bb608-88f7-47be-81fc-c0f8a5b617cb">
> 

سلام، دیگه dns جدیدی وجود نداره، هر چی که وجود داشت و بروی بیشتر ISP ها فیلتر نبود رو داخل برنامه گذاشتم.
اما اصلا جای نگرانی نیست، من به همین دلیل و دلایل دیگه مجبور شدم یه سرور چندکاره بنویسم، الان ۲ ماهه که دارم روزی ۸ تا ۱۰ ساعت روش کار میکنم.
ورژن بعد با سرور جدید میتونید از آشغال‌ترین سرورهای DNS دنیا هم تاخیر تک رقمی بگیرید.
حدودا یک تا دو هفته دیگه ورژن جدید میدم.

فعلا از داخل تنظیمات برنامه
Settings - Check
گزینه Plain DNS رو تیک بزنید با اینکه Plain هستن برنامه میتونه ازشون ip های اصلی بیرون بکشه و تاخیر رو کاهش میده.

**Comment by hamid20244** [comment]
امیدوارم روز به روز موفق تر از گذشته باشی و به مراد دلت برسی

واقعا زبان از بزرگواری و محبت شما قاصر هستش

خیلی بزرگواری میکنید که چراغی در زندگی ما روشن میکنید.

**Comment by Noob2Pr0** [comment]
ممنون، همیشه منتظر ورژن جدیدت بودم

راهی نیست وگرنه از هیچ اپراتوری استفاده نمیکردم، همه اشون لاشین
پول packet lost شونم میگیرن
یه نت خوب داغش رو دلمون موند که مثل ادم بریم وب گردی
بعد از استفاده از نرم افزارت چون هنوز ip ایرانه، رفتم وب گردی فهمیدم چقدر از کشور ها زدن ایران رو تحریم کردن
نکه فیلتر شکن همیشه استفاده میکردیم حس نمیکردیم

داداش من نمیدونم چطوری میتونم حمایتت کنم، خودت بگو و بنویس توی گیت هابت تا بقیه هم بدونن
همیشه که حمایت ها مالی نیست
شاید یکی سرور داشت کمک کرد، یکی دیگه برنامه نویسی تجربه داشت کمک کرد
یکی روشی داشت، یکی امنیتش و...

**Comment by msasanmh** [comment]
> ممنون، همیشه منتظر ورژن جدیدت بودم
> 
> راهی نیست وگرنه از هیچ اپراتوری استفاده نمیکردم، همه اشون لاشین
> پول packet lost شونم میگیرن
> یه نت خوب داغش رو دلمون موند که مثل ادم بریم وب گردی
> بعد از استفاده از نرم افزارت چون هنوز ip ایرانه، رفتم وب گردی فهمیدم چقدر از کشور ها زدن ایران رو تحریم کردن
> نکه فیلتر شکن همیشه استفاده میکردیم حس نمیکردیم

متاسفانه میفهمم، از داخل فیلتریم و از خارج تحریم.

> 
> داداش من نمیدونم چطوری میتونم حمایتت کنم، خودت بگو و بنویس توی گیت هابت تا بقیه هم بدونن
> همیشه که حمایت ها مالی نیست
> شاید یکی سرور داشت کمک کرد، یکی دیگه برنامه نویسی تجربه داشت کمک کرد

زدن هر نوع سرور مساویست با زندان، آخه امنیت اینجا جرمه.

> یکی روشی داشت، یکی امنیتش و...

بعدا کتابخونه ای که نوشتم رو به اشتراک میذارم، تا هر کی علاقه‌مند بود روی نسخه اندروید کار کنه که بعید میدونم چون نیاز ملت ما اینه که همه وبسایت‌ها باز بشن، یه کلاینت dns خیلی به کارشون نمیاد

**Comment by msasanmh** [comment]
> سلام به دوست عزیزم
> داداش چه کردن با ما که به اینجا رسیدیم
> یک ماه پیش اسکن میکردم از 132 تا 93 تا کارمیکرد
> الان نوشته 20 تا !!!! تازه تاخیر رو می بینی خون گریه میکنی (پیوست کردم)
> اپراتور ایرانسلم
> میشه dns هایی رو پیدا کرد که معتبر و امن باشن ؟
> میشه کاری کرد که dns رو از لیست خاصی رمز نگاری شده ای چیزی بگیره ؟
> <img width="493" alt="sssa" src="https://github.com/msasanmh/SecureDNSClient/assets/127764068/8e8bb608-88f7-47be-81fc-c0f8a5b617cb">
> 

چند سرور Insecure اضافه شد اگه تیک Allow Insecure فعال باشه، اما باز با این حال برنامه هایجک رو تشخیص میده و میشه ازشون بصورت ایمن استفاده کرد
