### ISSUE TITLE
*|+;

### ISSUE THREAD

**Issue by hamid20244** [msasanmh/SecureDNSClient#152]
*|+;

_Originally posted by @msasanmh in https://github.com/msasanmh/SecureDNSClient/issues/147#issuecomment-2028089211_
            میشه دقیقتر بگید در بخش ادیت پروکسی چه چیزی باید اضافه بشه
من مورد ذکر شده رو اضافه کردم به نظرم تغییری حاصل نشد.
ممنونم

**Comment by msasanmh** [comment]
>               *|+;
> 
> _Originally posted by @msasanmh in https://github.com/msasanmh/SecureDNSClient/issues/147#issuecomment-2028089211_
>             میشه دقیقتر بگید در بخش ادیت پروکسی چه چیزی باید اضافه بشه
> من مورد ذکر شده رو اضافه کردم به نظرم تغییری حاصل نشد.
> ممنونم

همینی که نوشتید درسته، برای رفع باگ SSL Decryption هستش.
بعد اینکه این Proxy Rule رو فعال کردید اونوقت  SSL Decryption رو فعال کنید.
باید dns آنلاین و ست باشه.
پراکسی با SSL Decryption فعال، روشن و ست بشه.
در انتها اگه مرورگر اجراست باید ری‌استارت بشه.
اونوقت مشکل باز نشدن یوتیوب شما حل میشه.

مراحل رو طی کنید، هر قسمت مشکلی داشتید بگید تا راهنمایی کنم.

**Comment by hamid20244** [comment]
![Untitled](https://github.com/msasanmh/SecureDNSClient/assets/167010121/3f5e3ce2-4ee4-4696-898b-d614c62977b0)

**Comment by hamid20244** [comment]
مطابق دستورالعمل شما انجام دادم و تصویر پیوست وضعیت اتصال رو نشون میده

ضمنا از چند روز پیش وقتی نرم افزار رو اجرا میکنم پیام زیر روی مرورگر ظاهر میشه:
No Internet Connection

باز هم از اینکه منت میذاری و وقتت رو در اختیار من قرار میدی، بینهایت سپاسگزارم

**Comment by msasanmh** [comment]
> مطابق دستورالعمل شما انجام دادم و تصویر پیوست وضعیت اتصال رو نشون میده
> 
> ضمنا از چند روز پیش وقتی نرم افزار رو اجرا میکنم پیام زیر روی مرورگر ظاهر میشه:
> No Internet Connection
> 
> باز هم از اینکه منت میذاری و وقتت رو در اختیار من قرار میدی، بینهایت سپاسگزارم

شما Change SNI رو فعال نکردید. دقت کنید در قسمت Status روبروی Proxy DPI Bypass باید Active نوشته بشه.
در قسمت SSL Decryption Option باید Change SNI رو فعال کنید.
عکسش رو این پایین میذارم.
درضمن GoodbyeDPI بروی نت شما کار نمیکنه، بیخود فعالش نکنید، GoodbyeDPI بروی بیشتر ISP ها دستش رو شده.
![20240415_231622.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/cebe4520-4600-4627-b0d5-95c5faf56d38)

**Comment by msasanmh** [comment]
> ضمنا از چند روز پیش وقتی نرم افزار رو اجرا میکنم پیام زیر روی مرورگر ظاهر میشه:
> No Internet Connection
> 

یه چند روزی هست روی اینترنت اختلال بیشتر انداختن، وقتی برنامه نمیتونه وحود اینترنت رو تشخیص بده اون رو مینویسه.

> باز هم از اینکه منت میذاری و وقتت رو در اختیار من قرار میدی، بینهایت سپاسگزارم

خواهش میکنم

**Comment by hamid20244** [comment]
بسیار عالی و ازتون ممنونم

**Comment by msasanmh** [comment]
مشکل در ورژن جدید برطرف شد
