### ISSUE TITLE
Port 53 Is Occupied By "svchost" error

### ISSUE THREAD

**Issue by wolfkingal2000** [msasanmh/SecureDNSClient#153]
سلام این ارور رو میده توی نسخه جدید چی کار باید کنم درست شده ؟
Connect Task: RanToCompletion
Connecting... Please Wait...

Port 53 Is Occupied By "svchost". You Need To Resolve The Conflict.

Connect Task: RanToCompletion

**Comment by msasanmh** [comment]
از این به بعد برنامه پورت‌ها رو به طور کامل چک میکنه تا تداخل پورت پیش نیاد.
پورت 53 که پورت پیش‌فرض dns هستش در حال استفاده توسط svchost.exe هستش. این یعنی اینترنت connection sharing شما روشنه.
بروی آداپتر راست کلیک کن، properties رو بزن.
به تب Sharing برو و هر دو تیک رو بردار و OK کن

**Comment by msasanmh** [comment]
> > از این به بعد برنامه پورت‌ها رو به طور کامل چک میکنه تا تداخل پورت پیش نیاد. پورت 53 که پورت پیش‌فرض dns هستش در حال استفاده توسط svchost.exe هستش. این یعنی اینترنت connection sharing شما روشنه. بروی آداپتر راست کلیک کن، properties رو بزن. به تب Sharing برو و هر دو تیک رو بردار و OK کن
> 
> این رو میگی 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/131250049/f4e807d9-b8e7-4765-ab4b-d0b8737d227e)
> 

آره دقیقا همین، قبلا برنامه این تداخل رو نادیده می‌گرفت و با ترفند خودش رو اجرا می‌کرد اما بعد از کلی تحقیق فهمیدم این کار درستی نیست و تداخل میتونه مشکلات کانکشن و تاخیر بالا بوجود بیاره

**Comment by wolfkingal2000** [comment]
> > > از این به بعد برنامه پورت‌ها رو به طور کامل چک میکنه تا تداخل پورت پیش نیاد. پورت 53 که پورت پیش‌فرض dns هستش در حال استفاده توسط svchost.exe هستش. این یعنی اینترنت connection sharing شما روشنه. بروی آداپتر راست کلیک کن، properties رو بزن. به تب Sharing برو و هر دو تیک رو بردار و OK کن
> > 
> > 
> > این رو میگی
> > ![image](https://private-user-images.githubusercontent.com/131250049/323303684-f4e807d9-b8e7-4765-ab4b-d0b8737d227e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzE0NzEsIm5iZiI6MTcxMzM3MTE3MSwicGF0aCI6Ii8xMzEyNTAwNDkvMzIzMzAzNjg0LWY0ZTgwN2Q5LWI4ZTctNDc2NS1hYjRiLWQwYjg3MzdkMjI3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjI2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzlmNWQ0ZmY4NmJhNzhmYjVhYTI3ZDIxZGJiYjQ0N2VjMGNhNTNiYjBlN2IzYzMxZDJjMWFhMDU3OWYxZGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nSahqVUNDJk5bQ7iwSG6E9QIPAUZmGdQexf2NV9zexY)
> 
> آره دقیقا همین، قبلا برنامه این تداخل رو نادیده می‌گرفت و با ترفند خودش رو اجرا می‌کرد اما بعد از کلی تحقیق فهمیدم این کار درستی نیست و تداخل میتونه مشکلات کانکشن و تاخیر بالا بوجود بیاره

ورداشتم ولی هنوز همون ارور رو میده

**Comment by msasanmh** [comment]
حالا برو داخل Services ویندوز و این دو تا سرویس پایین رو stop کن:
Host Network Service 
Internet Connection Sharing (ICS)

پیدا نکردی بگو اسکرین بدم

**Comment by wolfkingal2000** [comment]
> حالا برو داخل Services ویندوز و این دو تا سرویس پایین رو stop کن: Host Network Service Internet Connection Sharing (ICS)
> 
> پیدا نکردی بگو اسکرین بدم

درست


اون درست شد فکر کنم ولی الان یه ارور دیگه میده 
Connected.
Waiting For DNS To Get Online...
DNS Can't Get Online. Check Servers.

Connect Task: RanToCompletion

این رو میده

**Comment by DogancanYr** [comment]
Same :( :(

**Comment by msasanmh** [comment]
> Same :( :(

Disable your Internet Connection Sharing.

**Comment by msasanmh** [comment]
> > حالا برو داخل Services ویندوز و این دو تا سرویس پایین رو stop کن: Host Network Service Internet Connection Sharing (ICS)
> > پیدا نکردی بگو اسکرین بدم
> 
> درست
> 
> اون درست شد فکر کنم ولی الان یه ارور دیگه میده Connected. Waiting For DNS To Get Online... DNS Can't Get Online. Check Servers.
> 
> Connect Task: RanToCompletion
> 
> این رو میده

موقت غیرفعالش کردی، اون سرویس ها دوباره اجرا شدن. کلا غیرفعالشون کن از طریق properties گزینه disable رو انتخاب کن

**Comment by wolfkingal2000** [comment]
> > > حالا برو داخل Services ویندوز و این دو تا سرویس پایین رو stop کن: Host Network Service Internet Connection Sharing (ICS)
> > > پیدا نکردی بگو اسکرین بدم
> > 
> > 
> > درست
> > اون درست شد فکر کنم ولی الان یه ارور دیگه میده Connected. Waiting For DNS To Get Online... DNS Can't Get Online. Check Servers.
> > Connect Task: RanToCompletion
> > این رو میده
> 
> موقت غیرفعالش کردی، اون سرویس ها دوباره اجرا شدن. کلا غیرفعالشون کن از طریق properties گزینه disable رو انتخاب کن

مشکلی پیش نمیاد کلا غیر فعالشون کنم ؟

**Comment by msasanmh** [comment]
> > > > حالا برو داخل Services ویندوز و این دو تا سرویس پایین رو stop کن: Host Network Service Internet Connection Sharing (ICS)
> > > > پیدا نکردی بگو اسکرین بدم
> > > 
> > > 
> > > درست
> > > اون درست شد فکر کنم ولی الان یه ارور دیگه میده Connected. Waiting For DNS To Get Online... DNS Can't Get Online. Check Servers.
> > > Connect Task: RanToCompletion
> > > این رو میده
> > 
> > 
> > موقت غیرفعالش کردی، اون سرویس ها دوباره اجرا شدن. کلا غیرفعالشون کن از طریق properties گزینه disable رو انتخاب کن
> 
> مشکلی پیش نمیاد کلا غیر فعالشون کنم ؟

به هیچ عنوان مشکلی پیش نمیاد. چون شما داری به اشتراک گذاری اینترنت انجام نمیدی. من بجای disable روی manual گذاشتم

**Comment by msasanmh** [comment]
> > > > > > حالا برو داخل Services ویندوز و این دو تا سرویس پایین رو stop کن: Host Network Service Internet Connection Sharing (ICS)
> > > > > > پیدا نکردی بگو اسکرین بدم
> > > > > 
> > > > > 
> > > > > درست
> > > > > اون درست شد فکر کنم ولی الان یه ارور دیگه میده Connected. Waiting For DNS To Get Online... DNS Can't Get Online. Check Servers.
> > > > > Connect Task: RanToCompletion
> > > > > این رو میده
> > > > 
> > > > 
> > > > موقت غیرفعالش کردی، اون سرویس ها دوباره اجرا شدن. کلا غیرفعالشون کن از طریق properties گزینه disable رو انتخاب کن
> > > 
> > > 
> > > مشکلی پیش نمیاد کلا غیر فعالشون کنم ؟
> > 
> > 
> > به هیچ عنوان مشکلی پیش نمیاد. چون شما داری به اشتراک گذاری اینترنت انجام نمیدی. من بجای disable روی manual گذاشتم
> 
> ویه چیز دیگه یه بار بستم باز کردم الان این رو همش نشون میده 2024/04/17 20:26:05 Initializing... Waiting for Network... ولی نتم وصل بدون مشکل

این قسمت فقط پینگ میگیره. اگه برنامه پینگ دریافت نکنه فکر میکنه اینترنت نیست.
با این دستور netstat -ano چک کن پورت 53 اشغال نباشه

**Comment by msasanmh** [comment]
مجبور میشم ورژن بعد بذارم برنامه خودش غیرفعالش کنه، اینشکلی سخت میشه برای کاربرها.

**Comment by DogancanYr** [comment]
Can't another port be used?

**Comment by msasanmh** [comment]
> Can't another port be used?

No, Windows only accepts port 53.
I'm gonna make a video to show you guys how to disable Internet Connection Sharing.

**Comment by DogancanYr** [comment]
My operating system is corrupted and won't let me turn it off. 🥲🥲
I will continue with the old version.

**Comment by msasanmh** [comment]
> My operating system is corrupted and won't let me turn it off. 🥲🥲
> I will continue with the old version.

You just don't know how to turn it off. Let me upload the video.

**Comment by bramvera** [comment]
I don't have any internet connection sharing and got the same error after updated to v3.0.0
Port 53 Is Occupied By "svchost". You Need To Resolve The Conflict.

**Comment by msasanmh** [comment]
> I don't have any internet connection sharing and got the same error after updated to v3.0.0 Port 53 Is Occupied By "svchost". You Need To Resolve The Conflict.

You Have. [See this](https://github.com/msasanmh/SecureDNSClient/issues/154)

**Comment by msasanmh** [comment]
> My operating system is corrupted and won't let me turn it off. 🥲🥲 I will continue with the old version.

Video is ready, watch it please in [here](https://github.com/msasanmh/SecureDNSClient/issues/154)

**Comment by DogancanYr** [comment]
My operating system is corrupted.😭😭

**Comment by msasanmh** [comment]
> My operating system is corrupted.😭😭

It's not. Just as I did in the video.
You can't disable ICS without disabling "Host Network Service" first.

It's easy, just let me know where did you get stuck.

**Comment by bramvera** [comment]
> > I don't have any internet connection sharing and got the same error after updated to v3.0.0 Port 53 Is Occupied By "svchost". You Need To Resolve The Conflict.
> 
> You Have. [See this](https://github.com/msasanmh/SecureDNSClient/issues/154)

thank, for me disabling HNS solved the problem

**Comment by msasanmh** [comment]
> > > I don't have any internet connection sharing and got the same error after updated to v3.0.0 Port 53 Is Occupied By "svchost". You Need To Resolve The Conflict.
> > 
> > You Have. [See this](https://github.com/msasanmh/SecureDNSClient/issues/154)
> 
> thank, for me disabling HNS solved the problem

Glad to hear it.

**Comment by DogancanYr** [comment]
Ics was not shutting down because I turned off another service instead of the host network service. 😊😊💀

**Comment by msasanmh** [comment]
> Ics was not shutting down because I turned off another service instead of the host network service. 😊😊💀

So, the new version works for you now?

**Comment by DogancanYr** [comment]
Working. 👍
