### ISSUE TITLE
How To Solve Port 53 Is Occupied By "svchost"

### ISSUE THREAD

**Issue by msasanmh** [msasanmh/SecureDNSClient#154]
That means your Internet Connection Sharing (ICS) is enabled and you need to disable it.
Video tutorial: [How To Disable ICS](https://github.com/msasanmh/SecureDNSClient/raw/main/Help/How%20to%20disable%20Internet%20Connection%20Sharing%20(ICS).mp4)

**Comment by msasanmh** [comment]
The reason I have enabled checking for Port conflict in version 3.0.0

Me:
My Windows DNS Server which is written in c# is running on port 53 and if I enable Internet Connection Sharing (ICS) it also uses port 53, now I can set my local DNS Server (127.0.0.1:53) to my network adapter, I wanted to know if there would be a port conflict or it's ok to have them both running?

Chat GPT:
When you have two services configured to use the same port on the same network interface, a port conflict will occur. In your case, both your Windows DNS server and Internet Connection Sharing (ICS) are set to use port 53 on your local machine. This will likely result in a conflict because a port can only be used by one service at a time on a given IP address.

Me:
So there's no way to keep them both running without any issue?

Chat GPT:
Unfortunately, due to the way networking and port assignments work, you cannot have two services actively listening on the same port on the same network interface without causing a conflict. Each port can only be used by one service at a time to ensure proper traffic routing and avoid conflicts.

**Comment by MAHBOZ** [comment]
سلام من مراحل ویدیو رو انجام دادم ولی متاسفانه هنوز همین مشکل 53 رو داررم. البته در سرویس ها گزینه ی host .... برای من وجود نداشت

**Comment by msasanmh** [comment]
> سلام من مراحل ویدیو رو انجام دادم ولی متاسفانه هنوز همین مشکل 53 رو داررم. البته در سرویس ها گزینه ی host .... برای من وجود نداشت

سرویس Host Network Service بروی همه ویندوزها هست، یه بار دیگه با دقت نگاه کن.
در انتها اگه باز نتونستی پورت 53 رو آزاد کنی باید منتظر ورژن بعد باشی، یه امکانی اضافه می‌کنم که برنامه خودش این مشکل رو برطرف کنه.
تا اون موقع میتونید از ورژن قبل‌تر استفاده کنید.

**Comment by MAHBOZ** [comment]
نه برای من host network service وجود نداره. 
![Screenshot 2023-12-17 112512](https://github.com/msasanmh/SecureDNSClient/assets/114846902/72413363-f1e5-4960-b09a-bdfd07cd07fa)

**Comment by msasanmh** [comment]
> نه برای من host network service وجود نداره. 
> ![Screenshot 2023-12-17 112512](https://github.com/msasanmh/SecureDNSClient/assets/114846902/72413363-f1e5-4960-b09a-bdfd07cd07fa)
> 

عجیبه!
فعلا از ورژن قبل‌تر استفاده کنید. ورژن بعد خودش برطرف میکنه این تداخل رو.
