### ISSUE TITLE
How to set upstream proxy for a specific domain ?

### ISSUE THREAD

**Issue by rti2** [msasanmh/SecureDNSClient#155]
سلام 
چجوری میشه برای یک وبسای خاص upstream proxy گذاشت ؟ (مثلا برای چک کردن upstream proxy)

**Comment by msasanmh** [comment]
> سلام 
> چجوری میشه برای یک وبسای خاص upstream proxy گذاشت ؟ (مثلا برای چک کردن upstream proxy) 

باید Proxy Rules رو فعال کنید.
Settings -> Share - Advanced
و داخل فایل قانونش رو بنوسید و سیو کنید
نمونه‌اش رو مینویسم:

**Comment by msasanmh** [comment]
example.com|proxy:socks5://192.168.1.88:10808;
*.example.com|proxy:socks5://192.168.1.88:10808;
