### ISSUE TITLE
Could you please share the library (for android )

### ISSUE THREAD

**Issue by rti2** [msasanmh/SecureDNSClient#156]
بعدا کتابخونه ای که نوشتم رو به اشتراک میذارم، تا هر کی علاقه‌مند بود روی نسخه اندروید کار کنه که بعید میدونم چون نیاز ملت ما اینه که همه وبسایت‌ها باز بشن، یه کلاینت dns خیلی به کارشون نمیاد

**Comment by msasanmh** [comment]
بصورت یه Repository جدا میذارمش. البته تا چند روز دیگه چون واقعا نیاز به استراحت دارم

**Comment by rti2** [comment]
دستت درد نکنه 
موفق باشی ♥️
