### ISSUE TITLE
ارتباط بهتر

### ISSUE THREAD

**Issue by GFW-knocker** [msasanmh/SecureDNSClient#16]
سلام
یک گروه تلگرامی زدیم جهت ارتباط بهتر برنامه نویسایی که تو این شرایط دارن زحمت میکشند
خوشحال میشیم شما هم ملحق شوید
در صورت تمایل جهت رعایت مسایل امنیتی با یک username  و اسم مستعار عضو شوید
درود و سپاس فراوان
https://t.me/advanced_programmers

**Comment by msasanmh** [comment]
سلام، باشه، حتما.
اول باید یوزرنیم رو تغییر بدم

**Comment by Maani53** [comment]
سلام . ممنون از روشی که معرفی کردید .عالی جواب میده. میشه ارتباط بدون سرور با یوتیوب رو برای باقی سایتها هم اجرا کرد؟ دوم اینکه میشه اسکریپت رو روی هاست اجرا کرد ؟
