### ISSUE TITLE
issue 153

### ISSUE THREAD

**Issue by AtilaFirouzmand** [msasanmh/SecureDNSClient#160]
ba arz salam va khaste nabashi 
dadash man in barnamaro faghat baraye Youtube estefade mikardam va kheyli awliye hich moshkeli ham nadare vali vaghti ke dns va proxy va in chiz haro set mikonim az site hayi mesl spotify va in chiza nemitonam estefade bokonam shoma ye rah o charei dari baraye in moshkel ? ba estefade az (rule) nemitonim site'i ro ezafe bokonim ke hengam kar kardane barname betoonim filter on site haro ham beshkonim (be joz Youtube) masalan site lenovo ham alan filter hast aslan nemitonim estefade bokonim .
va babat barnamei ke dorost kardi kheyli mamnonim azat awlie awlie <3<3

**Comment by msasanmh** [comment]
خب این برنامه فقط میتونه وبسایت‌هایی که بر اساس نام دامنه فیلتر شدن رو باز کنه.
اونایی که تحریم هستن رو میتونید با اسمارت dns باز کنید که مثالش رو داخل ورژن آهر گذاشتم، اگه همون dns rule هارو کپی کنید سایتهای spotify و چندتا دیگه باز میشه.
البته باید بدونید که سرور پراکسی اون اسمارت dns ها ممکنه همیشه کار نکنه بخاطر رایگان بودنش و ممکنه پیام service unavailable رو نشون بده که مربوط به خود اون اسمارت dns میشه نه برنامه.
و برای وبسایت‌هایی که براساس IP فیلتر هستن تنها راه دادن upstream proxy هستش، مثلا میتونید Bypass های برنامه رو فعال کنید، اسمارت dns ها رو هم اضافه کنید و از v2ray هم بعنوان upstream proxy استفاده کنید.
اینشکلی برنامه یوتیوب و هر وبسایتی که بتونه رو خودش مستقیم باز میکنه و برای اون وبسایت‌هایی که بهش معرفی کردید از اسمارت dns و برای مابقی که با ip فیلترن از upstream استفاده میکنه.
این جوری میشه بهترین سرعت و کارایی رو دریافت کرد.
