### ISSUE TITLE
Conflict with WSL Interference due to disabling Host Network Service & ICS services 

### ISSUE THREAD

**Issue by Noob2Pr0** [msasanmh/SecureDNSClient#161]
Hello again, my dear friend
I write this post in two languages because I think it can be useful for others
After changing **port 53** in **version 3.0 of your software**
Apart from the problems of service interference, it brings new problems for those who have computer science and special skills like you and use different Microsoft services.
For example, my problem after disabling service "**Host Network Service**" and "**Internet Connection Sharing**" to avoid interference with the software port was that due to the use of service **Linux subsystem (WSL)**, I could no longer access my Ubuntu distro, and **_I had to activate those services to gain access. do_**
This is vital for me and I think it will be very good for professionals if you put the functionality of the previous version as a **check box**.
Thankful

**Comment by Noob2Pr0** [comment]
سلام مجدد به دوست عزیزم
این پست رو به ۲ تا زبان می نویسم چون بنظرم میتونه مفید باشه برای بقیه
پس از تغییر پورت ۵۳ در نسخه ۳ نرم افزارت
جدا از مشکلات تداخل سرویس، برای کسانی که مثل خودت دارای علم کامپیوتر و مهارت های خاصی هستند و از سرویس های مختلفی استفاده می کنند مشکلات جدیدی به همراه داره
برای مثال مشکل من پس از غیر فعال کردن سرویس "**Host Network Service**" و "**Internet Connection Sharing**" برای جلوگیری از تداخل با پورت نرم افزار این بود که به دلیل استفاده از سرویس ایکس دیگر دسترسی به توزیع اوبونتو خودم نداشتم و مجبور به فعال کردن اون سرویس ها شدم تا مجدد دسترسی پیدا کنم
این مورد برای من حیاتی هستش و فکر میکنم اگه قابلیت ورژن قبلی رو به عنوان یک باکس چک قرار بدی برای حرفه ای ها خیلی خوب میشه.
مثلا من با burpsuite که روی پورت 8080 هست کار میکنم و چون تنظیماتشو گذاشتی تغییر میدم و راحت میشم
ممنون

**Comment by Noob2Pr0** [comment]
![error1](https://github.com/msasanmh/SecureDNSClient/assets/127764068/e1bff4fc-7250-4823-b82d-a05ec14dcd80)
![error2](https://github.com/msasanmh/SecureDNSClient/assets/127764068/72a734b4-4b83-4800-8259-749133ff497e)

**Comment by msasanmh** [comment]
ورژن‌های قبل همراه با تداخل کار می‌کردن. فرض کن دو تا سرویس روی پورت 53 داره listening میشه و ما می‌آییم روی آداپتر خودمون 127.0.0.1:53 رو ست می‌کنیم. حالا ویندوز میخواد درخواست بفرسته اما نمیدونه به کدوم پورت 53 باید درخواستش رو بفرسته، این مشکلاتی از قبیل بالا رفتن تاخیر، ناپایداری کانکشن و در بعضی موارد کلا قطعی اینترنت ایجاد میکنه.
حالا برای من کاری نداره یه آپشن بذارم که برنامه تداخل رو نادیده بگیره اما خودت در این زمینه بیشتر تحقیق کن، در مورد مشکلاتی که ممکنه ایجاد بشه از گوگل و هوش‌های مصنوعی بپرس شاید منصرف شدی.

اگه نشدی من اون آپشن رو در ورژن بعد اضافه می‌کنم.

**Comment by Noob2Pr0** [comment]
بحث منصرف شدن یا نشدن نیست، نامرد نمیزاره wsl  کار کنم اصلا باز نمیکنه، تو عکس واست فرستادم
من فقط رو ویندوز مانور نمیدم و هر روز با wsl کار دارم
خلاصه دیشب اومدم سرویس رو خاموش کردم بعد که نرم افزارت وصل شد اومدم باز روشنش کردم تا wsl کار کنه
که فعلا با موفقیت انجام شده
ولی اره اگه زحمتی نیست گذینه اشو بزار پیش فرض هم همونی باشه که خودت میگی، تا بعدا کاربری که خواست خودش تیکشو بزنه نخواستم نزنه بزاره پیشفرض همون طور که میگی درسته کار کنه

**Comment by msasanmh** [comment]
> بحث منصرف شدن یا نشدن نیست، نامرد نمیزاره wsl  کار کنم اصلا باز نمیکنه، تو عکس واست فرستادم

متوجه‌ام چی میگی

> من فقط رو ویندوز مانور نمیدم و هر روز با wsl کار دارم
> خلاصه دیشب اومدم سرویس رو خاموش کردم بعد که نرم افزارت وصل شد اومدم باز روشنش کردم تا wsl کار کنه
> که فعلا با موفقیت انجام شده

فقط احتمال کرش شدن sdc در این حالت وجود داره.

> ولی اره اگه زحمتی نیست گذینه اشو بزار پیش فرض هم همونی باشه که خودت میگی، تا بعدا کاربری که خواست خودش تیکشو بزنه نخواستم نزنه بزاره پیشفرض همون طور که میگی درسته کار کنه

باشه می‌ذارم.
