### ISSUE TITLE
Question About The Sound Files

### ISSUE THREAD

**Issue by GoodErnest64** [msasanmh/SecureDNSClient#164]
I was just wondering how were the sound files made. they are surely not generated by code every time (I checked the files). I would be happy to know which TTS model and which voice model you used for generating the voice files ...

**Comment by msasanmh** [comment]
> I was just wondering how were the sound files made. they are surely not generated by code every time (I checked the files). I would be happy to know which TTS model and which voice model you used for generating the voice files ...

They are prerecorded. 
I'm using NextUp Ivona natural TTS engine. 
Model voice is Salli.

**Comment by GoodErnest64** [comment]
Thanks for
