### ISSUE TITLE
Flagged as malicious

### ISSUE THREAD

**Issue by stillrinzler** [msasanmh/SecureDNSClient#166]
I ran the file through hybrid analysis and it got flagged as malicious in a sandbox
https://www.hybrid-analysis.com/sample/cc3334777a69790de3e9b79a8ce0ed6227d233e0ee10980e252278e51978f0d2/662d28ae194c60f16502e82b
Is it a false positive?

**Comment by msasanmh** [comment]
![Screenshot_20240427_202446_Chrome.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/ea9f161f-eded-4976-9fe8-ec68b00626eb)

Task Scheduler: I need it to put the app on Windows startup.

Write data to remote: I write unique but random characters to a server to count active users.

And some other stuff that the antivirus couldn't find out.
For example: changing user data that is required for setting the DNS on system. 
And some modifications to bypass DPI.

The app is full open-source and it's cleaner than my entire life.
Any programmer can confirm it by reading the source code.

Conclusion: It's False Positive.

**Comment by stillrinzler** [comment]
> The app is full open-source and it's cleaner than my entire life.
> Any programmer can confirm it by reading the source code.
> 
> Conclusion: It's False Positive. 

I was pretty sure it had nothing malicious since it's open source but just wanted to be on the safer side, thanks for making it clear 👍
