### ISSUE TITLE
pip doesn't work

### ISSUE THREAD

**Issue by GoodErnest64** [msasanmh/SecureDNSClient#167]
it seems like after enabling the DNS, pip stops working and it throws this error at me :

`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:985: The handshake operation timed out'))': /simple/pyqt6/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:985: The handshake operation timed out'))': /simple/pyqt6/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:985: The handshake operation timed out'))': /simple/pyqt6/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:985: The handshake operation timed out'))': /simple/pyqt6/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)'))': /simple/pyqt6/`

and sometimes this one : 

`  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/06/b6/e0497ae753b7b01d9e6f39488daf3cb90fb5c197861eb4d4f2ccd3c13a95/PyQt6-6.7.0-cp38-abi3-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/06/b6/e0497ae753b7b01d9e6f39488daf3cb90fb5c197861eb4d4f2ccd3c13a95/PyQt6-6.7.0-cp38-abi3-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/06/b6/e0497ae753b7b01d9e6f39488daf3cb90fb5c197861eb4d4f2ccd3c13a95/PyQt6-6.7.0-cp38-abi3-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/06/b6/e0497ae753b7b01d9e6f39488daf3cb90fb5c197861eb4d4f2ccd3c13a95/PyQt6-6.7.0-cp38-abi3-win_amd64.whl.metadata
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/06/b6/e0497ae753b7b01d9e6f39488daf3cb90fb5c197861eb4d4f2ccd3c13a95/PyQt6-6.7.0-cp38-abi3-win_amd64.whl.metadata
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/06/b6/e0497ae753b7b01d9e6f39488daf3cb90fb5c197861eb4d4f2ccd3c13a95/PyQt6-6.7.0-cp38-abi3-win_amd64.whl.metadata (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)"))`

it seems to be a proxy error but I'm not sure about it...

**Comment by msasanmh** [comment]
It seems it's pip known issue. 
pip doesn't work if you're using a proxy server.
Check this out:
https://stackoverflow.com/questions/30992717/proxy-awareness-with-pip

If you're using SDC Proxy server and DPI bypass is enabled, you can try this:
Edit Proxy Rules:
Settings -> Share -> Advanced 

Write these lines:
pythonhosted.org|--;
*.pythonhosted.org|--;

and save the file.
