### ISSUE TITLE
من دیگه برام یوتیوب درست کار نمیکنه (بالا نمیاد یا خیلی کنده)

### ISSUE THREAD

**Issue by TMFera** [msasanmh/SecureDNSClient#168]

**Comment by TMFera** [comment]
راه حلی داره تا همین صبح خیلی خوب بود

**Comment by msasanmh** [comment]
> راه حلی داره تا همین صبح خیلی خوب بود

از چه روشی استفاده می‌کردید؟ 
یک. گودبای دی‌پی‌آی
دو. پراکسی فرگمنت 
سه. پراکسی ssl
و isp شما چیه؟

**Comment by TMFera** [comment]
من همیشه اینطور کانکت میشم که اول اسکن میکنم بعد کانکت بعد ست دی ان اس بعد ست پروکسی بعد ستارت پروسکی والا دیئه بیشتر این بلد نیستم باهاش کار کنم اگه جواب سوالات نیست

**Comment by TMFera** [comment]
> > راه حلی داره تا همین صبح خیلی خوب بود
> 
> از چه روشی استفاده می‌کردید؟ یک. گودبای دی‌پی‌آی دو. پراکسی فرگمنت سه. پراکسی ssl و isp شما چیه؟

روش های دیگه ای جز پروکسی مگه هست ؟

**Comment by msasanmh** [comment]
> من همیشه اینطور کانکت میشم که اول اسکن میکنم بعد کانکت بعد ست دی ان اس بعد ست پروکسی بعد ستارت پروسکی والا دیگه بیشتر این بلد نیستم باهاش کار کنم اگه جواب سوالات نیست

این یعنی شما از فرگمنت پراکسی استفاده می‌کنید. 
اگه سرعتش پایین اومده میتونی ssl decryption رو امتحان کنی.
از تب Share گزینه ssl decryption رو چک بزن و از قسمت پایینترش یعنی ssl decryption options گزینه change sni رو تیک بزن.

این روش نیاز به نصب سرتیفیکیت داره، برات پیام میاد که باید روی yes کلیک کنی.

بعدش دوباره همون ترتیبی که قبلا طی میکردی رو انجام بده.

هرچند اگه از شاتل یا مخابرات استفاده نمی‌کنید به احتمال زیاد مشکل شما دائمی نیست

**Comment by khordady** [comment]
گزینه use custom server را بزنین سرعت خیلی بهتر میشه(بدون هیچ تغییر اضافه ای)، اینترنت مخابرات دارم
نیازی هم نیست هر بار اسکن کنین
