### ISSUE TITLE
add rules

### ISSUE THREAD

**Issue by khordady** [msasanmh/SecureDNSClient#169]
thank you for your great app.
how and where to add rules for dns?
مثل شکن که توضیحات را در ریلیز نوشتین

**Comment by msasanmh** [comment]
> thank you for your great app.
> how and where to add rules for dns?
> مثل شکن که توضیحات را در ریلیز نوشتین

در قسمت 
Settings -> Connect
قرار داره، dns rules رو چک بزنید و بروی edit dns rules کلیک کنید.
یه فایل متنی باز میشه که اونجا میتونید قوانین رو بنوسید. در انتها فایل رو save کنید.
همون قسمت بری پیداش میکنی،آسونه. پیدا نکردی بگو تا توضیحات کامل‌تری بدم.

**Comment by khordady** [comment]
همان ruleهای صفحه ریلیز را گذاشتم اما دیگه به developer.android.com وصل نشد. گزینه enable rule را هم زدم. goodbydpi را هم خاموش کردم اما تاثیری نداشت. خود google.com ولی میومد
اگر dnsهای شکن را دستی در ویندوز اضافه کنم (بدون استفاده از SDC) صفحه دولوپر اندروید میاد

**Comment by khordady** [comment]
کلا صفحه ای لود نمیشد(صفحه 403 هم نمیومد) یا برای dl.google ارور 404 میداد

**Comment by msasanmh** [comment]
> همان ruleهای صفحه ریلیز را گذاشتم اما دیگه به developer.android.com وصل نشد. گزینه enable rule را هم زدم. goodbydpi را هم خاموش کردم اما تاثیری نداشت. خود google.com ولی میومد
> اگر dnsهای شکن را دستی در ویندوز اضافه کنم (بدون استفاده از SDC) صفحه دولوپر اندروید میاد

برنامه داره برای اون سایت‌ها واقعا از شکن استفاده میکنه، تا جاییکه من تست کردم سرویس‌های شکن همیشه در دسترس نیستن، مثلا ممکنه صفحه Service Unavailable ببینی یا 404 که اشکال از خود سرویس شکن هست.
رول‌های قسمت ریلز داره از DoH های شکن استفاده میکنه اگه شما plain dns شکن رو مستقیم رو ویندوز زدی و کار کرد، میتونی همون‌ها رو داخل برنامه بدی و با DoH ها جایگزین کنی.
مثلا آدرس plain dns گوگل رو به این شکل باید بنویسی udp://8.8.8.8 حالا این ip گوگل رو با ip شکن عوض کن.

**Comment by khordady** [comment]
آقا دمت گرم، مثه اینکه فقط روی لینک دولوپر اندروید مشکل داشت. چندبار قطع و وصل کردم و لینک های دیگه را رفتم تا بالاخره این هم اکی شد.
برای هرکسی که بعدا میاد، این رول های من هست. 
// Variables
SmartDns1 = tcp://178.22.122.100;
SmartDns2 = tcp://185.51.200.2;

developer.android.com|dns:SmartDns1,SmartDns2;
