### ISSUE TITLE
linux ?

### ISSUE THREAD

**Issue by abbaszahiri** [msasanmh/SecureDNSClient#17]
I have a linux server in home.
Can you give me a hint how i can use your great idea on a linux environment?

**Comment by msasanmh** [comment]
> I have a linux server in home.
> Can you give me a hint how i can use your great idea on a linux environment?

There is a project called SpoofDPI for Linux environment.

**Comment by abbaszahiri** [comment]
thank you. can you please give me a link?

**Comment by msasanmh** [comment]
> thank you. can you please give me a link?

https://github.com/xvzc/SpoofDPI

**Comment by abbaszahiri** [comment]
thank you sir. I'll look at it.

**Comment by abbaszahiri** [comment]
Can you please provide us a simple script which runs on linux by any chance ?

**Comment by abbaszahiri** [comment]
I mean the whole procedure in one linux script.
I know thats a lot .

From running a service which is always looking up the best dns servers,

To setting the best DNS,

with or without a DPI Spoofing.

Thank you for your great and useful work.

Give us a donation link.

**Comment by msasanmh** [comment]
> I mean the whole procedure in one linux script.
> I know thats a lot .
> 
> From running a service which is always looking up the best dns servers,
> 
> To setting the best DNS,
> 
> with or without a DPI Spoofing.
> 
> Thank you for your great and useful work.
> 
> Give us a donation link.

Writing cross-platform application is something different, all methods and algorithms must support both platforms. Since I'm using many methods which are only available to Windows, it makes the project impossible to compile for Linux.

**Comment by abbaszahiri** [comment]
i know.
i mean just a script to chain those already available algorithms

**Comment by abbaszahiri** [comment]
Just if I knew whats your bottleneck!

I've been a C++ programmer (and a llittle familiar with pcap library in linux)  in case of any help you may need ...

**Comment by msasanmh** [comment]
> Just if I knew whats your bottleneck!
> 
> I've been a C++ programmer (and a llittle familiar with pcap library in linux)  in case of any help you may need ...
> 
> 

It's networking!
Thanks for the offer. 
By any chance can you speak in persian?

**Comment by abbaszahiri** [comment]
بله و آی پی تلگرام من هست: @analyst_abbas

**Comment by msasanmh** [comment]
خسته نباشی 😄 چرا مجبورم کردی انگلیسی حرف بزنم با این حال و روز داغونم، چون به شدت مشغول برنامه‌نویسی‌ام.

**Comment by abbaszahiri** [comment]
ببخش. چون با چینیها سر reality حرف میزدم اولین بار مکالمه رو انگلیسی شروع کردم دیگه ادامه پیدا کرد. حالا شما که مسلط هستید به انگلیسی چه بهتر شد.

**Comment by msasanmh** [comment]
> ببخش. چون با چینیها سر reality حرف میزدم اولین بار مکالمه رو انگلیسی شروع کردم دیگه ادامه پیدا کرد. حالا شما که مسلط هستید به انگلیسی چه بهتر شد.

من از سطح basic هم پایین‌ترم 😄

**Comment by abbaszahiri** [comment]
اولین بار دقت نکردم زیاد که شما ایرانی ممکنه باشید. بیشتر باعث افتخار من هستید
