### ISSUE TITLE
Rule to use Upstream proxy for a specific domain 

### ISSUE THREAD

**Issue by rti2** [msasanmh/SecureDNSClient#170]
سلام
بعضی سایت های تحریمی هستن که برنامه با upstream proxy ردشون نمیکنه 
چجوری میشه rule تعریف کرد که برای اون سایت ها از upstream proxy استفاده بشه ؟

**Comment by msasanmh** [comment]
> سلام
> بعضی سایت های تحریمی هستن که برنامه با upstream proxy ردشون نمیکنه 
> چجوری میشه rule تعریف کرد که برای اون سایت ها از upstream proxy استفاده بشه ؟

این issue رو مطالعه کن:
https://github.com/msasanmh/SecureDNSClient/issues/155

**Comment by rti2** [comment]
فراموش کرده بودم ببخشید

**Comment by msasanmh** [comment]
> فراموش کرده بودم ببخشید

خواهش میکنم، مشکلی نیست
