### ISSUE TITLE
first try fail, second try connect successfuly

### ISSUE THREAD

**Issue by Noob2Pr0** [msasanmh/SecureDNSClient#172]
English:
Hello again to my good friend
First of all, thank you for the changes you made, especially adding the port change section
The problem I have from version 3.0 to the new version 3.04 is that it gives an error (**DNS Can't Get Online. Check Servers**
) when connecting for the first time, but as soon as you try for the second time, it connects successfully.
I did not find the reason
Image attached

فارسی:
سلام مجدد به دوست خوبم
اول تشکر کنم بابت تغییراتی که دادی بخصوص گذاشتن بخش تغییر پورت
مشکلی که از نسخه ۳ تا نسخه جدید ۳.۰۴ دارم اینه که برای بار اول متصل شدن خطا میده  (**DNS Can't Get Online. Check Servers**
)  ولی همین که برای بار دوم تلاش میکنی با موفقیت وصل میشه
دلیلشو پیدا نکردم
تصویر پیوست شده
![try 2](https://github.com/msasanmh/SecureDNSClient/assets/127764068/b4fb1b77-b89e-410f-8149-28d1618fcb5a)

**Comment by msasanmh** [comment]
ممنون بابت اطلاع، برای من همچین اتفاقی نمی‌افته اما شرایط برای هر کسی متفاوته. باید روش کار کنم ببینم مشکل کجاست.
لطفا این issue باز بمونه.
