### ISSUE TITLE
Question about dnscrypt with relays

### ISSUE THREAD

**Issue by stillrinzler** [msasanmh/SecureDNSClient#175]
Is it possible to use dnscrypt with relays?
And is there a way to import dnscrypt servers with descriptions attached to each server?
The public resolvers listed in dnscrypt GitHub page have the sdns link as well as a description for it but I haven't really found a way to properly import it to the app

**Comment by msasanmh** [comment]
> Is it possible to use dnscrypt with relays?

No, but I may support it in the future. 

> And is there a way to import dnscrypt servers with descriptions attached to each server?
> The public resolvers listed in dnscrypt GitHub page have the sdns link as well as a description for it but I haven't really found a way to properly import it to the app

It's not designed to import servers from .md files, but the app can find and import any link in a text file (without description).

Download "public-resolvers.md" and rename the extension to .txt

Create a group in Custom Servers, click "Add Servers" --> "Add multiple (browse)" and choose your .txt file.

**Comment by stillrinzler** [comment]
> No, but I may support it in the future. 

Cool
 
> It's not designed to import servers from .md files, but the app can find and import any link in a text file (without description).
> 
> Download "public-resolvers.md" and rename the extension to .txt
> 
> Create a group in Custom Servers, click "Add Servers" --> "Add multiple (browse)" and choose your .txt file.

Ohh cool, but is there a way to use only dnscrypt servers from it or do I need to filter out servers that aren't dnscrypt?

And is there a way to select servers with dnssec, no log, no filter?

**Comment by msasanmh** [comment]
> > No, but I may support it in the future. 
> 
> Cool
>  
> > It's not designed to import servers from .md files, but the app can find and import any link in a text file (without description).
> > 
> > Download "public-resolvers.md" and rename the extension to .txt
> > 
> > Create a group in Custom Servers, click "Add Servers" --> "Add multiple (browse)" and choose your .txt file.
> 
> Ohh cool, but is there a way to use only dnscrypt servers from it or do I need to filter out servers that aren't dnscrypt?

You can filter out servers by Protocol: 
Settings -> Check -> Select Protocol

> 
> And is there a way to select servers with dnssec, no log, no filter?

And by sdns properties: 
Settings -> Check -> sdns:// servers must have

> 
>

**Comment by stillrinzler** [comment]
> > > No, but I may support it in the future. 
> > 
> > Cool
> >  
> > > It's not designed to import servers from .md files, but the app can find and import any link in a text file (without description).
> > > 
> > > Download "public-resolvers.md" and rename the extension to .txt
> > > 
> > > Create a group in Custom Servers, click "Add Servers" --> "Add multiple (browse)" and choose your .txt file.
> > 
> > Ohh cool, but is there a way to use only dnscrypt servers from it or do I need to filter out servers that aren't dnscrypt?
> 
> You can filter out servers by Protocol: 
> Settings -> Check -> Select Protocol
> 
> > 
> > And is there a way to select servers with dnssec, no log, no filter?
> 
> And by sdns properties: 
> Settings -> Check -> sdns:// servers must have
> 
> > 
> > 
> 
> 

Ohh okay, but one last question 
Is there an option to not use certain servers like cloudflare, adguard etc?

**Comment by msasanmh** [comment]
> Ohh okay, but one last question 
> Is there an option to not use certain servers like cloudflare, adguard etc?

No, I'm afraid there's not.

Alternatively you can decode sdns urls and read the content by
Tools -> Stamp Reader

**Comment by stillrinzler** [comment]
> > Ohh okay, but one last question 
> > Is there an option to not use certain servers like cloudflare, adguard etc?
> 
> No, I'm afraid there's not.
> 
> Alternatively you can decode sdns urls and read the content by
> Tools -> Stamp Reader

Got it, thanks so much 😄👍
