### ISSUE TITLE
انتخاب خودکار بهترین تنظیمات فرگمنت

### ISSUE THREAD

**Issue by coldwater-10** [msasanmh/SecureDNSClient#177]
بنظرم اگه بشه این قابلیت رو اضافه کنی که خودکار تست بگیره بهترین نوع تنظیمات فرگمنت رو با توجه به اون اینترنت پیدا کنه عالی میشه

**Comment by msasanmh** [comment]
> بنظرم اگه بشه این قابلیت رو اضافه کنی که خودکار تست بگیره بهترین نوع تنظیمات فرگمنت رو با توجه به اون اینترنت پیدا کنه عالی میشه

تنظیمات فرگمنت برای GoodbyeDPI که خیلی فرقی نداره چی باشه چون بروی بیشتر ISP ها شناسایی شده و جواب نمیده.

تنظیمات فرگمنت پراکسی سرور واقعا قویه و مثل فرگمنت برنامه‌های اندرویدی نیست که نیاز به تغییرات برای وصل شدن داشته باشه، با همون تنظیمات پیش‌فرضش میتونه ۸۰ درصد isp ها رو دور بزنه.
اون ۲۰ درصد باقی‌مونده میان فرگنت‌ها رو اسمبل می‌کنن و در نتیجه تنظیمات هرچی که باشه بروی اون ۲۰ درصد کار نمی‌کنه. 

و از طرفی تشخیص اتوماتیک بهترین تنظیمات، هم برنامه‌نویسی خیلی زیادی میخواد و اگه اجراش کنید هم خیلی زمان میبره چون باید همه احتمالات رو چک کنه و نزدیک به یک میلیون احتمال وجود داره، در نتیجه واقعا ارزش کار نداره.

پس اگه تنظیمات پیش‌فرض داره برای شما کار میکنه یعنی همون بهترینه، هم سبک برای cpu و هم سریع برای نتورک. 
و اگه فرگمنت کار نمیده، اونوقت باید از SSL Decryption استفاده کنید که همون تغییر SNI هستش و بروی ۱۰۰ درصد ISP ها کار می‌کنه.

**Comment by coldwater-10** [comment]
مرسی از پاسخ گویی
فرگمنت پراکسی سرور همون تب چهارمه؟
نه متاسفانه کار نمیکنه
SSL Decryption
رو فعال کردم تو خود تست نرم افزار میگه یوتیوب بالا میاد ولی وقتی با مرورگر میزنم باز نمیشه

**Comment by msasanmh** [comment]
> مرسی از پاسخ گویی
> فرگمنت پراکسی سرور همون تب چهارمه؟

آره، همون تب چهارم.

> نه متاسفانه کار نمیکنه
> SSL Decryption
> رو فعال کردم تو خود تست نرم افزار میگه یوتیوب بالا میاد ولی وقتی با مرورگر میزنم باز نمیشه

بعد اینکه پراکسی رو اجرا کردی بروی سیستم ستش کردی؟

**Comment by coldwater-10** [comment]
نه ست نکرده بودم درست شد دمت گرم
بعد اگه بخوام همزمان با هایدیفای اجراش کنم تنظیمات خاصی نیاز داره؟

**Comment by msasanmh** [comment]
> نه ست نکرده بودم درست شد دمت گرم

عالیه. 

> بعد اگه بخوام همزمان با هایدیفای اجراش کنم تنظیمات خاصی نیاز داره؟

مخلوط کردن دو تا برنامه باهم نیازمند یه سری امکانات هست که فرقی نمیکنه هیدیفای باشه یا کلاینت دیگه.

بصورت کلی توضیح میدم و هیدیفای رو بعنوان مثال در نظر میگیرم:

برنامه هیدیفای باید تنظیمات upstream proxy داشته باشه، یعنی شما آدرس پراکسی sdc رو بروی هیدیفای باید ست کنی.

برنامه هیدیفای اگه بخواد کانکشن VPN ایجاد کنه باید قسمت exclude داشته باشه، یعنی بتونی بهش بگی فلان برنامه رو از vpn عبور نده. در اینجا باید برنامه sdc و فایل‌هایی که در فولدر binary برنامه sdc قرار دارن رو در هیدیفای exclude کنی.

حالا فرض میکنیم هیدیفای این امکانات رو نداره، در اینجا تنها راه مخلوط کردن این دو برنامه به این شکله:

برنامه sdc رو طبق معمول اجرا میکنی و پراکسیش رو روی سیستم ست میکنی.
اینجوری هیدیفای از sdc استفاده میکنه اما دیگه نباید از حالت vpn mode هیدیفای استفاده کنی.
باید از هیدیفای بروی حالت proxy mode استفاده کنی و آدرس پراکسی هیدیفای رو داخل مرورگرها یا داخل تلگرام دسکتاپ ست کنی.

**Comment by msasanmh** [comment]
> نه ست نکرده بودم درست شد دمت گرم
> بعد اگه بخوام همزمان با هایدیفای اجراش کنم تنظیمات خاصی نیاز داره؟

یه حسی بهم میگه وقتی شما گزینه Enable SSL Decryption رو چک زدی دیگه از قسمت SSL Decryption Options گزینه Change SNI رو تیک نزدی.
برای باز شدن یوتیوب با SSL گزینه Change SNI باید تیک داشته باشه.
اگه تیک نداشت و یوتیوب باز شد یعنی فقط با فرگمنت باز کردید.
همه این گزینه‌ها در تب چهارم هست.

**Comment by coldwater-10** [comment]
مرسی که اینقدر پیگیری
نه اونو زده بودم
فقط نمیدونستم بعد از اکتیو کردن پروکسی باید ستش هم بکنم بعد که گفتی زدم اوکی شد ممنون
