### ISSUE TITLE
مشکل در اتصال از نسخه 2.9.2

### ISSUE THREAD

**Issue by aavso5997** [msasanmh/SecureDNSClient#178]
سلام من از نسخه 2.9.2 به بعد با این ارور مواجه میشم، با نسخه های قبلی مشکلی ندارم
ویندوز 7
![Capture](https://github.com/msasanmh/SecureDNSClient/assets/122816653/97f2a718-7455-4cf3-a11a-2ec94eb438fd)

**Comment by msasanmh** [comment]
> سلام من از نسخه 2.9.2 به بعد با این ارور مواجه میشم، با نسخه های قبلی مشکلی ندارم
> ویندوز 7
> ![Capture](https://github.com/msasanmh/SecureDNSClient/assets/122816653/97f2a718-7455-4cf3-a11a-2ec94eb438fd)
> 

سلام، این نسخه خیلی قدیمیه، از آخرین نسخه استفاده کن و اگه باز مشکلی بود از آخرین نسخه اسکرین شات بده.

**Comment by aavso5997** [comment]
![Capture](https://github.com/msasanmh/SecureDNSClient/assets/122816653/c8e73fdb-b2e5-46f5-9577-fc3063f252b5)
این آخرین نسخه که کار نمیکنه
![Capture1](https://github.com/msasanmh/SecureDNSClient/assets/122816653/cc9eaad7-fd16-4edb-9f40-d4dcb25938e0)
اینم نسخه 2.8.5 که کار میکنه

**Comment by msasanmh** [comment]
خب یه چیزی رو بی‌زحمت تست کن.
از quick connect استفاده نکن.
اول سرورها رو چک کن و بعد از تب کانکت روی connect کلیک کن.
اگه نشد یه بار دیگه هم روش کلیک کن و نتیجه‌اش رو بهم بگو.

**Comment by msasanmh** [comment]
> System DNS Flushed
> DNS Can't Get Online. Check Servers.
> 
> Connect Task: False

ممنون، یه سوال جاییکه این جمله رو مینویسه:
DNS Can't Get Online. Check Servers.
این جمله با تاخیر و بعد از حدود ۱۵ ثانیه میاد یا بلافاصله نوشته میشه؟

**Comment by TheRealNE0** [comment]
منم دقیقا همین مشکلو با نسخه جدید دارم، الان از نسخه 2.8.5 استفاده میکنم که وصل میشه الان هم با فابل بتا تست کردم بدون حذف سرتیفیکیت قبلی وصل شد بعد از اینکه داخل تنطیمات این مورد داخل عکس رو به حالت پایین گذاشتم و سرتیفیکیت جدیدو نصب کرد دیگه وصل نشد، سرتیفیکیت رو با خود برنامه پاک کردم و همون بخش تنظیمو به حالت پیشفرضش برگردوندم الان وصل شد به نظر میاد که مشکل از سمت سزتیفیکیت باشه...

![image](https://github.com/msasanmh/SecureDNSClient/assets/46984761/76fd565c-37c9-45e3-a417-278c316e8f6f)

> > System DNS Flushed
> > DNS Can't Get Online. Check Servers.
> > Connect Task: False
> 
> ممنون، یه سوال جاییکه این جمله رو مینویسه: DNS Can't Get Online. Check Servers. این جمله با تاخیر و بعد از حدود ۱۵ ثانیه میاد یا بلافاصله نوشته میشه؟


و در جواب این سوال اره بلافاصله پیغام میده.

راستی من داخل تنظیمات اسکن هم Allow in secure هم فعال کردم ولی داخل لاگ میزنه false، میدونم ربطی به این issue نداره ولی نتونستم جلو خودمو بگیرم :)

**Comment by msasanmh** [comment]
> منم دقیقا همین مشکلو با نسخه جدید دارم، الان از نسخه 2.8.5 استفاده میکنم که وصل میشه الان هم با فابل بتا تست کردم بدون حذف سرتیفیکیت قبلی وصل شد بعد از اینکه داخل تنطیمات این مورد داخل عکس رو به حالت پایین گذاشتم و سرتیفیکیت جدیدو نصب کرد دیگه وصل نشد، سرتیفیکیت رو با خود برنامه پاک کردم و همون بخش تنظیمو به حالت پیشفرضش برگردوندم الان وصل شد به نظر میاد که مشکل از سمت سزتیفیکیت باشه... (الان که داخل عکس وصله قبل از اینه که رو این حالت تنظیمو بذارم، برای رفع ابهام دوباره با حالت legacy dns server داخل نسخه جدید وصل تونستم بشم نه اونی که داخل عکس مشخص کردم)

یعنی برای شما DNS وصل میشد اما DoH وصل نمیشد؟ یا اینکه جفت شون وصل نمی شدن؟

و الان که در نسخه بتا تنظیمات رو ریست کردی دیگه مشکل برطرف شد؟ و میتونی از نسخه جدید استفاده کنی؟

> 
> ![image](https://private-user-images.githubusercontent.com/46984761/335823248-76fd565c-37c9-45e3-a417-278c316e8f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzE0NTIsIm5iZiI6MTcxNzI3MTE1MiwicGF0aCI6Ii80Njk4NDc2MS8zMzU4MjMyNDgtNzZmZDU2NWMtMzdjOS00NWUzLWE0MTctMjc4YzMxNmU4ZjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE5NDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYWRiMjdhYmVkZWU0MzQwZGNhYWYyYjRlODA3MTE2YzcyYTVhMjFkZGUxZjE0OTRhYTNmZTRkMzY5NDQ4NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mr2XGTEjQCa6NrYgs-p6W0S58xDEBEwE-IWoi6tpMgA)
> 
> > > System DNS Flushed
> > > DNS Can't Get Online. Check Servers.
> > > Connect Task: False
> > 
> > 
> > ممنون، یه سوال جاییکه این جمله رو مینویسه: DNS Can't Get Online. Check Servers. این جمله با تاخیر و بعد از حدود ۱۵ ثانیه میاد یا بلافاصله نوشته میشه؟
> 
> و در جواب این سوال اره بلافاصله پیغام میده.

پیام DNS Can't Get Online نباید سریع بیاد، عجیبه!
> 
> راستی من داخل تنظیمات اسکن هم Allow in secure هم فعال کردم ولی داخل لاگ میزنه false، میدونم ربطی به این issue نداره ولی نتونستم جلو خودمو بگیرم :)

آخه چطور ممکنه، همین الان تستش کردم. مطمئنی؟

![insecure](https://github.com/msasanmh/SecureDNSClient/assets/1586825/b7a146b6-7246-4b06-b714-14317794248f)

**Comment by TheRealNE0** [comment]
این مورد اخر اشتباه من بود تصحیح میکنم اوکی بود. و اینکه اگه بخوام یذره با جزپیات در مورد مشکل اصلی بگم بعد از عوض کردن Working mode به حالات غیر پیشفرض و نصب سرتیفیکیت حدود 8 ثانیه طول میکشه تا ارور (خوب کامنتتو نخونده بودم تازه دیدم حدود 15 ثانیه رو). پایین لاگ هم میزارم.

**Comment by TheRealNE0** [comment]
Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
WriteRequestsToLog: True
Parent Process ID: 26200
Starting DNS...
DNS Started
Flushing System DNS...
System DNS Flushed
Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH
Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH
Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH

**Comment by msasanmh** [comment]
لاگ کات شده است، کامل نذاشتی، اینجوری چیزی دستگیرم نمیشه.
@TheRealNE0

**Comment by TheRealNE0** [comment]
قبلی کل محتوای فابل ErrorLog بود الانم یه دوبار دیگه تست کردم بازم هموطور که میگی کات شده... 

![image](https://github.com/msasanmh/SecureDNSClient/assets/46984761/7c4fa38e-14ab-4ff2-b9af-88e4e9f364c8)

Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
WriteRequestsToLog: True
Parent Process ID: 5248
Starting DNS...
DNS Started
Flushing System DNS...
System DNS Flushed
Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH
Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH


نمیدونم روش دیگه ای هست بتونم لاگ بهتری برات تولید کنم ؟؟

**Comment by msasanmh** [comment]
> قبلی کل محتوای فابل ErrorLog بود الانم یه دوبار دیگه تست کردم بازم هموطور که میگی کات شده... 
> 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/46984761/7c4fa38e-14ab-4ff2-b9af-88e4e9f364c8)
> 
> Msmh Agnostic Server v3.0.5.0
> Type "Help" To Get Help.
> Profile Set To DNS
> Settings:
> Port: 53
> Working Mode: Dns
> Max Requests: 1000000
> DNS Timeout: 10 Seconds
> Proxy Timeout: 0 Seconds
> Kill On Cpu Usage: 40%
> Block Port 80: False
> Allow Insecure: True
> DNS Servers Count: 5
> Bootstrap IP Address: 8.8.8.8
> Bootstrap Port: 53
> WriteRequestsToLog: True
> Parent Process ID: 5248
> Starting DNS...
> DNS Started
> Flushing System DNS...
> System DNS Flushed
> Msmh Agnostic Server v3.0.5.0
> Type "Help" To Get Help.
> Profile Set To DNS
> Settings:
> Port: 53
> Working Mode: Dns
> Max Requests: 1000000
> DNS Timeout: 10 Seconds
> Proxy Timeout: 0 Seconds
> Kill On Cpu Usage: 40%
> Block Port 80: False
> Allow Insecure: True
> DNS Servers Count: 5
> Bootstrap IP Address: 8.8.8.8
> Bootstrap Port: 53
> Profile Set To DoH
> Msmh Agnostic Server v3.0.5.0
> Type "Help" To Get Help.
> Profile Set To DNS
> Settings:
> Port: 53
> Working Mode: Dns
> Max Requests: 1000000
> DNS Timeout: 10 Seconds
> Proxy Timeout: 0 Seconds
> Kill On Cpu Usage: 40%
> Block Port 80: False
> Allow Insecure: True
> DNS Servers Count: 5
> Bootstrap IP Address: 8.8.8.8
> Bootstrap Port: 53
> Profile Set To DoH
> 
> 
> نمیدونم روش دیگه ای هست بتونم لاگ بهتری برات تولید کنم ؟؟
> 
> 

آها از فایل برداشتی، نه منظورم این بود که از لاگ داخل برنامه یه select all کنی و بعد کپی کنی

**Comment by TheRealNE0** [comment]
اوه، اوکی اینم لاگ داخل برنلمه

2024/06/02 00:07:40 Initializing...
Waiting For Network...
Network Detected (Up Time: 4 Seconds, 658 Milliseconds)
Connecting... Please Wait...

Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Connected.
Waiting For DNS To Get Online...
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH
DNS Can't Get Online. Check Servers.

Connect Task: False
Connecting... Please Wait...

Msmh Agnostic Server v3.0.5.0
Type "Help" To Get Help.
Profile Set To DNS
Connected.
Waiting For DNS To Get Online...
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 5
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH
DNS Can't Get Online. Check Servers.

Connect Task: False

**Comment by TheRealNE0** [comment]
محض احتیاط این سه تا قسمت تنها قسمتایی هستن که با حالت پیشفرض فرق دارن 

![image](https://github.com/msasanmh/SecureDNSClient/assets/46984761/4046e98c-ed0c-4411-a532-b91f472fa2d5)
![image](https://github.com/msasanmh/SecureDNSClient/assets/46984761/e730f030-ab25-4e71-b095-db47ed41d0bd)
![image](https://github.com/msasanmh/SecureDNSClient/assets/46984761/7621b628-5257-4977-8b46-1827fc3125c4)

**Comment by msasanmh** [comment]
> اوه، اوکی اینم لاگ داخل برنلمه
> 
> 2024/06/02 00:07:40 Initializing...
> Waiting For Network...
> Network Detected (Up Time: 4 Seconds, 658 Milliseconds)
> Connecting... Please Wait...
> 
> Msmh Agnostic Server v3.0.5.0
> Type "Help" To Get Help.
> Profile Set To DNS
> Connected.
> Waiting For DNS To Get Online...
> Settings:
> Port: 53
> Working Mode: Dns
> Max Requests: 1000000
> DNS Timeout: 10 Seconds
> Proxy Timeout: 0 Seconds
> Kill On Cpu Usage: 40%
> Block Port 80: False
> Allow Insecure: True
> DNS Servers Count: 5
> Bootstrap IP Address: 8.8.8.8
> Bootstrap Port: 53
> Profile Set To DoH
> DNS Can't Get Online. Check Servers.
> 
> Connect Task: False
> Connecting... Please Wait...
> 
> Msmh Agnostic Server v3.0.5.0
> Type "Help" To Get Help.
> Profile Set To DNS
> Connected.
> Waiting For DNS To Get Online...
> Settings:
> Port: 53
> Working Mode: Dns
> Max Requests: 1000000
> DNS Timeout: 10 Seconds
> Proxy Timeout: 0 Seconds
> Kill On Cpu Usage: 40%
> Block Port 80: False
> Allow Insecure: True
> DNS Servers Count: 5
> Bootstrap IP Address: 8.8.8.8
> Bootstrap Port: 53
> Profile Set To DoH
> DNS Can't Get Online. Check Servers.
> 
> Connect Task: False
> 
> 

ممنون، مشخص شد، دستورات مربوط به تنظیمات DoH روی سیستم شما به کنسول ارسال نمیشه.
باید تحقیق کنم ببینم جریان چیه.

**Comment by msasanmh** [comment]
وقت کردی اینم یه تست بزن و لاگش رو مثل قبلی برام بفرست:
https://drive.google.com/file/d/19radhq4CNOYLaK0YveQzUPZvh8dbnZaG/view?usp=drivesdk

@TheRealNE0

**Comment by TheRealNE0** [comment]
@msasanmh 

2024/06/02 01:25:49 Initializing...
Waiting For Network...
Network Detected (Up Time: 4 Seconds, 724 Milliseconds)
Checking For ICS Service Port Conflict...
Connecting... Please Wait...

Msmh Agnostic Server v3.0.6.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 8
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH
Couldn't Get Confirm Message From Console.

Connect Task: False
Checking For ICS Service Port Conflict...
Connecting... Please Wait...

Msmh Agnostic Server v3.0.6.0
Type "Help" To Get Help.
Profile Set To DNS
Settings:
Port: 53
Working Mode: Dns
Max Requests: 1000000
DNS Timeout: 10 Seconds
Proxy Timeout: 0 Seconds
Kill On Cpu Usage: 40%
Block Port 80: False
Allow Insecure: True
DNS Servers Count: 8
Bootstrap IP Address: 8.8.8.8
Bootstrap Port: 53
Profile Set To DoH
Couldn't Get Confirm Message From Console.

Connect Task: False

**Comment by msasanmh** [comment]
لطفا آخرین نسخه رو تست کن و بهم اطلاع بده. ورژن 3.2.0
اگه مشکل داشت لاگ رو بفرست. ممنون
@TheRealNE0

**Comment by msasanmh** [comment]
> @msasanmh 
> &rlm;ممنون از زحماتت مشکل اتصال رفع شده و داره خوب کار میکنه، خیلی خوب میشه اگه بتونیم بخش  Discussion هم برای ریپو داشته باشیم فک کنم نصف این issue هایی که واقعا issue نیستونو (مثل نحوه کارکردو این چیزا) اونور خود کاربرا رفع کنن یا حداقل از رو اشتراکشون issue بهتری برات تولید کنن &rlm;

ممنون بابت اطلاع.
خوشحالم که دیگه نیازی نیست از ورژن‌های قدیمی استفاده کنی.
ببینم چطور میشه فعال کرد discussion رو، انجامش میدم.
