### ISSUE TITLE
نسخه مک

### ISSUE THREAD

**Issue by tinkerbell1268** [msasanmh/SecureDNSClient#18]
با عرض سلام و خسته نباشید..
آیا امکانش هست که این برنامه رو برای سیستم عامل مک هم پورت کنید؟
چون dnscrypt-proxy خوب کار میکنه در مک و برای DPI هم spoof  رو تست کردم ولی متاسفانه این خطا رو میگیرم:
[HTTPS DOH] Error looking up for domain: [www.google.com](http://www.google.com/) Post "https://8.8.8.8/dns-query": net/http: TLS handshake timeout
و توی ویندوز هم اگه امکانش هست گزینه ای توی تنظیمات بذارید که با startup ویندوز اجرا بشه و متصل .

**Comment by msasanmh** [comment]
> با عرض سلام و خسته نباشید..
> آیا امکانش هست که این برنامه رو برای سیستم عامل مک هم پورت کنید؟
> چون dnscrypt-proxy خوب کار میکنه در مک و برای DPI هم spoof  رو تست کردم ولی متاسفانه این خطا رو میگیرم:
> [HTTPS DOH] Error looking up for domain: [www.google.com](http://www.google.com/) Post "https://8.8.8.8/dns-query": net/http: TLS handshake timeout
> و توی ویندوز هم اگه امکانش هست گزینه ای توی تنظیمات بذارید که با startup ویندوز اجرا بشه و متصل .

سلام، داخل این برنامه از متدهایی استفاده شده که متاسفانه cross platform نیستن درنتیجه امکان نداره برنامه بتونه برای مک پورت بشه.
اون پیام خطا... برنامه میخواد به DoH گوگل وصل بشه اما از اونجایی که این آدرس فیلتره نمی‌تونه. 
تنظیمات start up رو هم در چند تا ورژن بعدی اعمال میکنم.

**Comment by tinkerbell1268** [comment]
من این دستور رو زدم
./spoof-dpi  --dns=dns.electrotm.org
و یوتیوب باز میشه برام...خیلی ممنون
ببخشید که وقتتم میگیرم ولی این dns که کار کرد رو از کجا پیدا کنم؟ با dnscrypt-proxy؟(وقتی اجراش میکنم ادرس اینجوری بهم میده
quad9-dnscrypt-ip4-nofilter-pri

 Server with the lowest initial latency: quad9-dnscrypt-ip4-nofilter-pri (rtt: 116ms))

**Comment by msasanmh** [comment]
> من این دستور رو زدم
> ./spoof-dpi  --dns=dns.electrotm.org
> و یوتیوب باز میشه برام...خیلی ممنون
> ببخشید که وقتتم میگیرم ولی این dns که کار کرد رو از کجا پیدا کنم؟ با dnscrypt-proxy؟(وقتی اجراش میکنم ادرس اینجوری بهم میده
> quad9-dnscrypt-ip4-nofilter-pri
> 
>  Server with the lowest initial latency: quad9-dnscrypt-ip4-nofilter-pri (rtt: 116ms))

آره dnscrypt جریانش فرق داره. من خودم همه آدرس‌ها رو از نت میگیرم و بعد میدم به این برنامه خودم اسکن میکنه و اونایی که فیلتر نیستن رو پیدا میکنه

**Comment by tinkerbell1268** [comment]
اهان متوجه شدم...بازم ممنونم ازت
موفق و پیروز باشی
