### ISSUE TITLE
Security Alert: Malware detection 3.0.4

### ISSUE THREAD

**Issue by khak313** [msasanmh/SecureDNSClient#181]
Antivirus programs are identifying version 3.0.4 as a potential malware downloader and installer. Here are some of the reports:

https://opentip.kaspersky.com/C4673993120C2D8A5E7290BD9D8B4BAD853007006ACEDB5FDC4E5BACEED1CBE4/results?tab=upload

https://gridinsoft.com/online-virus-scanner/id/c4673993120c2d8a5e7290bd9d8b4bad853007006acedb5fdc4e5baceed1cbe4

**Comment by TheRealNE0** [comment]
@khak313 

https://github.com/msasanmh/SecureDNSClient/tree/v3.0.0#:~:text=Secure%20DNS%20Client-,Note%3A%20some%20antivirus%20apps%20raise%20alert%20as%20PUA%20(Potentially%20Unwanted%20Application)%20for%20WinDivert%20which%20is%20used%20by%20GoodbyeDPI.%20If%20your%20antivirus%20detects%20WinDivert%20as%20a%20threat%2C%20add%20it%20to%20your%20exclusion%20list%20to%20ensure%20SDC%20functions%20as%20expected.,-Help%20(How%20to
