### ISSUE TITLE
کندی سرعت

### ISSUE THREAD

**Issue by H0ssein2211** [msasanmh/SecureDNSClient#183]
نتم شاتل تو یوتیوب یا وصل نمیشه یا وصل که میشه خیلی کنده

**Comment by msasanmh** [comment]
> نتم شاتل تو یوتیوب یا وصل نمیشه یا وصل که میشه خیلی کنده

با چه متدی وصل شدید؟
سه متد وجود داره:
GoodbyeDPI 
Proxy Fragment
Proxy SSL Decryption

**Comment by H0ssein2211** [comment]
> > نتم شاتل تو یوتیوب یا وصل نمیشه یا وصل که میشه خیلی کنده
> 
> با چه متدی وصل شدید؟ سه متد وجود داره: GoodbyeDPI Proxy Fragment Proxy SSL Decryption

GoodbyDPI

**Comment by msasanmh** [comment]
> > > نتم شاتل تو یوتیوب یا وصل نمیشه یا وصل که میشه خیلی کنده
> > 
> > با چه متدی وصل شدید؟ سه متد وجود داره: GoodbyeDPI Proxy Fragment Proxy SSL Decryption
> 
> GoodbyDPI

شما خیلی خوش‌شانس بودید که تونستید بروی شاتل با GoodbyeDPI وصل بشید.
باید بدونید GoodbyeDPI دیگه روش‌هاش لو رفته و بروی بیشتر ISP ها مخصوصا شاتل و مخابرات کار نمیکنه.

از تب چهارم همون Proxy + DPI Bypass گزینه‌های 
Enable Fragment 
و 
Enable SSL Decryption 
رو فعال کنید.
از قسمت SSL Decryption Options گزینه
Change SNI
رو تیک بزنید.
با استفاده از دکمه‌های Start Proxy و Set Proxy پراکسی رو اجرا و بروی سیستم ست کنید و از یوتیوب پرسرعت لذت ببر.
مسلما قبل اجرای پراکسی DNS رو هم اجرا و ست میکنید.

**Comment by H0ssein2211** [comment]
> > > > نتم شاتل تو یوتیوب یا وصل نمیشه یا وصل که میشه خیلی کنده
> > > 
> > > 
> > > با چه متدی وصل شدید؟ سه متد وجود داره: GoodbyeDPI Proxy Fragment Proxy SSL Decryption
> > 
> > 
> > GoodbyDPI
> 
> شما خیلی خوش‌شانس بودید که تونستید بروی شاتل با GoodbyeDPI وصل بشید. باید بدونید GoodbyeDPI دیگه روش‌هاش لو رفته و بروی بیشتر ISP ها مخصوصا شاتل و مخابرات کار نمیکنه.
> 
> از تب چهارم همون Proxy + DPI Bypass گزینه‌های Enable Fragment و Enable SSL Decryption رو فعال کنید. از قسمت SSL Decryption Options گزینه Change SNI رو تیک بزنید. با استفاده از دکمه‌های Start Proxy و Set Proxy پراکسی رو اجرا و بروی سیستم ست کنید و از یوتیوب پرسرعت لذت ببر. مسلما قبل اجرای پراکسی DNS رو هم اجرا و ست میکنید.

هنوز وصل نمیشه
وارد یوتیوب میشه ولی ارور چک اینترنت میده یوتیوب

**Comment by msasanmh** [comment]
از قسمت status برنامه یه اسکرین بده تا بدونم چه چیزایی فعال شده.

گزینه Write Proxy requests to log رو هم چک بزن تا مطمئن بشی خط‌هایی به رنگ زرد داخل لاگ نباشه.

و مطمئن باش که سرتیفیکیت برنامه رو نصب کرده باشی.

**Comment by H0ssein2211** [comment]
> از قسمت status برنامه یه اسکرین بده تا بدونم چه چیزایی فعال شده.
> 
> گزینه Write Proxy requests to log رو هم چک بزن تا مطمئن بشی خط‌هایی به رنگ زرد داخل لاگ نباشه.
> 
> و مطمئن باش که سرتیفیکیت برنامه رو نصب کرده باشی.

سرتیفیکت برنامه از کجا میتونم بفهم 
![Uploading IMG_20240603_213753.jpg…]()

**Comment by msasanmh** [comment]
> > از قسمت status برنامه یه اسکرین بده تا بدونم چه چیزایی فعال شده.
> > 
> > گزینه Write Proxy requests to log رو هم چک بزن تا مطمئن بشی خط‌هایی به رنگ زرد داخل لاگ نباشه.
> > 
> > و مطمئن باش که سرتیفیکیت برنامه رو نصب کرده باشی.
> 
> سرتیفیکت برنامه از کجا میتونم بفهم 

وقتی چک Enable SSL Decryption رو میزنی یه پیام میاد که باید روی Yes کلیک کنی.
> ![Uploading IMG_20240603_213753.jpg…]()
> 
عکس هم آپلود نشده، باید بمونی آپلود تموم بشه و بعد پیام رو بفرستی

**Comment by H0ssein2211** [comment]
![photo11802457156](https://github.com/msasanmh/SecureDNSClient/assets/171591819/f932fcb9-9cdf-41b0-9a76-2974239e9c31)

**Comment by msasanmh** [comment]
> ![photo11802457156](https://github.com/msasanmh/SecureDNSClient/assets/171591819/f932fcb9-9cdf-41b0-9a76-2974239e9c31)
> الان قسمت log یک چنتاییش زرده

خب داخل همین صفحه از عکس بروی Check DPI Bypass کلیک کن تا ببینیم برنامه میتونه یوتیوب رو باز کنه یا نه.

بعدش اگه مرورگر بازه، ببندش و دوباره باز کن و یوتیوب رو در مرورگر هم تست کن.

نتیجه رو بهم بگو

**Comment by H0ssein2211** [comment]
> > ![photo11802457156](https://private-user-images.githubusercontent.com/171591819/336178854-f932fcb9-9cdf-41b0-9a76-2974239e9c31.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0Mzk4NDcsIm5iZiI6MTcxNzQzOTU0NywicGF0aCI6Ii8xNzE1OTE4MTkvMzM2MTc4ODU0LWY5MzJmY2I5LTljZGYtNDFiMC05YTc2LTI5NzQyMzllOWMzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxODMyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjQyYmU5NTZjNTczZTI1NTU5ODMxN2ZjZDdhOWNhZjJhMWYxNmFmZTZkNWNhNDgyZDg0ZWQ5MDc1NmI4ZGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-IAAV02p9L201xhRJm4BS0zvMdLtvoiSqYUY-UJil9c)
> > الان قسمت log یک چنتاییش زرده
> 
> خب داخل همین صفحه از عکس بروی Check DPI Bypass کلیک کن تا ببینیم برنامه میتونه یوتیوب رو باز کنه یا نه.
> 
> بعدش اگه مرورگر بازه، ببندش و دوباره باز کن و یوتیوب رو در مرورگر هم تست کن.
> 
> نتیجه رو بهم بگو

تو برنامه میزنه میتون یوتیوبو باز کنه 
تو مرورگرم اینو میاره
![Opera Snapshot_2024-06-03_220129_www youtube com](https://github.com/msasanmh/SecureDNSClient/assets/171591819/ebc12745-19f1-4e44-b229-43917608075a)

**Comment by msasanmh** [comment]
> 
> تو برنامه میزنه میتون یوتیوبو باز کنه 

وقتی برنامه OK بده یعنی حتما باز میکنه.

> تو مرورگرم اینو میاره
> ![Opera Snapshot_2024-06-03_220129_www youtube com](https://github.com/msasanmh/SecureDNSClient/assets/171591819/ebc12745-19f1-4e44-b229-43917608075a)
> 

مرورگرت چی هست؟
و مطمئنی مرورگر داره از پراکسی سیستم استفاده میکنه؟
چون بعضی مرورگرها تنظیمات پراکسی دارن که میتونه بروی Direct ست باشه اینجوری از پراکسی سیستم استفاده نمیکنه و نمیتونه یوتیوب رو باز کنه.

اگه بروی Direct قرار داره تغییر بده و بروی System Proxy بذار.

اگه مرورگر دیگه‌ای هم داری باهاش تست کن

**Comment by H0ssein2211** [comment]
> > تو برنامه میزنه میتون یوتیوبو باز کنه
> 
> وقتی برنامه OK بده یعنی حتما باز میکنه.
> 
> > تو مرورگرم اینو میاره
> > ![Opera Snapshot_2024-06-03_220129_www youtube com](https://private-user-images.githubusercontent.com/171591819/336187483-ebc12745-19f1-4e44-b229-43917608075a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NDQyMzEsIm5iZiI6MTcxNzQ0MzkzMSwicGF0aCI6Ii8xNzE1OTE4MTkvMzM2MTg3NDgzLWViYzEyNzQ1LTE5ZjEtNGU0NC1iMjI5LTQzOTE3NjA4MDc1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxOTQ1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODY0ZjVmMzJiOTVmNDZjZTA1MmFhMGEzNTIyMDljMGI2YmQ3MjZkNzQyYTk1MDk2MGZjZmE4ZDdjNzgyOGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FBCcS11ITgCLelawDHSW5C_NmfzaM6xNMTwcP5hXixI)
> 
> مرورگرت چی هست؟ و مطمئنی مرورگر داره از پراکسی سیستم استفاده میکنه؟ چون بعضی مرورگرها تنظیمات پراکسی دارن که میتونه بروی Direct ست باشه اینجوری از پراکسی سیستم استفاده نمیکنه و نمیتونه یوتیوب رو باز کنه.
> 
> اگه بروی Direct قرار داره تغییر بده و بروی System Proxy بذار.
> 
> اگه مرورگر دیگه‌ای هم داری باهاش تست کن

درست شد
 از پروکسی سیستم استفاده نمیکرد
ممنون
