### ISSUE TITLE
مشکل با internet download manager

### ISSUE THREAD

**Issue by ashaghal** [msasanmh/SecureDNSClient#184]
سلام
یکی دو روزی هست که فقط تو نرم افزار IDM مشکل resolve شدن dns ها وجود داره.
وقتی sdc رو خاموش میکنم بدون مشکل کار میکنه.
تو خود idm پروکسی ست نشده وصل نمیشه. اما وقتی به پروکسی sdc وصل میشم به خوبی کانکشن برقرار میشه.
راهی هست بشه بدون ست کردن پروکسی توی idm مثل قبل عمل کنه؟

**Comment by msasanmh** [comment]
> سلام
> یکی دو روزی هست که فقط تو نرم افزار IDM مشکل resolve شدن dns ها وجود داره.
> وقتی sdc رو خاموش میکنم بدون مشکل کار میکنه.
> تو خود idm پروکسی ست نشده وصل نمیشه. اما وقتی به پروکسی sdc وصل میشم به خوبی کانکشن برقرار میشه.

این اتفاق زمانی میوفته که دارید از یوتیوب دانلود میکنید یا هر لینک دانلودی؟

> راهی هست بشه بدون ست کردن پروکسی توی idm مثل قبل عمل کنه؟

برای دانلود از یوتیوب که حتما پراکسی باید باید ست باشه داخل IDM اما لینک‌هایی که فیلتر نیستن باید بدون نیاز به ست شدن پراکسی کار کنن.
فعلا IDM ندارم تست کنم

**Comment by ashaghal** [comment]
نه همه لینک های دانلود همینجوری شدن 
تا چند روز پیش این حالت نبود و رو همون حالت goodbyedpi همه چیز خوب بود. 
الان هم همه چیزهای دیگه خوب کار میکنن و مشکلی ندارن اما توی idm این داستان پیش اومده که فقط با ست کردن پرومسی رو idm کارکردش عادی میشه
![image](https://github.com/msasanmh/SecureDNSClient/assets/39614484/0d2e1e56-c77b-4c6e-858b-afca73a74032)

**Comment by msasanmh** [comment]
> نه همه لینک های دانلود همینجوری شدن 
> تا چند روز پیش این حالت نبود و رو همون حالت goodbyedpi همه چیز خوب بود. 

اگه GoodbyeDPI رو خاموش کنی لینک‌هایی که فیلتر نیستن راحت دانلود میشن؟

> الان هم همه چیزهای دیگه خوب کار میکنن و مشکلی ندارن اما توی idm این داستان پیش اومده که فقط با ست کردن پرومسی رو idm کارکردش عادی میشه
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/39614484/0d2e1e56-c77b-4c6e-858b-afca73a74032)
> 

بی‌زحمت اول یه تست کن، GoodbyeDPI و پراکسی خاموش باشن و فقط dns روشن و ست باشه، اونوقت ببین idm درست کار میکنه یا نه و بهم اطلاع بده.
میخوام بفهمم مشکل از dns هست یا GoodbyeDPI

**Comment by ashaghal** [comment]
نه با خاموش کردن goodbyedpi هم تفاوتی ایجاد نمیشه و مشکل از dns. لینک های بدون فیلتر هم دانلود نمیشن
![image](https://github.com/msasanmh/SecureDNSClient/assets/39614484/0e5a5181-f276-420c-a78d-8654fdc98664)

**Comment by msasanmh** [comment]
> نه با خاموش کردن goodbyedpi هم تفاوتی ایجاد نمیشه و مشکل از dns. لینک های بدون فیلتر هم دانلود نمیشن
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/39614484/0e5a5181-f276-420c-a78d-8654fdc98664)
> 
> 

بخاطر شما برنامه IDM رو دانلود و نصب کردم، برای من بخوبی کار میکنه. اسکرین:
![IDM_SDC.png](https://github.com/msasanmh/SecureDNSClient/assets/1586825/9eb2c17b-f271-49f5-887e-ec2837c6f087)

و شما گفتی، یکی دو روزی هست که اینطور شده... واقعا نمیدونم مشکل شما از چی میتونه باشه.
فعلا چیزی به ذهنم نمی‌رسه.

**Comment by ashaghal** [comment]
ممنونم وقت گذاشتی 
امروز همین پترن روی terabox هم اتفاق افتاد. 
حالا خودم بازم تلاش میکنم اگه به نتیجه رسیدم اعلام میکنم

**Comment by ashaghal** [comment]
مقصر پیدا شد.
نرم افزار notion با این که پروکسی شده بود تا بتونم بهش وصل بشم یجوری دیتکت میکرد که ایرانم و بعد از لوگین مدام لوگ اوت میشد.
برای حلش از dns leak prevention نرم افزار  proxifier استفاده میکردم که یک سری اتصالات udp رو بلاک میکرد و این اختلال درست میکرد تو بعضی نرم افزارها.

**Comment by msasanmh** [comment]
> مقصر پیدا شد.
> نرم افزار notion با این که پروکسی شده بود تا بتونم بهش وصل بشم یجوری دیتکت میکرد که ایرانم و بعد از لوگین مدام لوگ اوت میشد.
> برای حلش از dns leak prevention نرم افزار  proxifier استفاده میکردم که یک سری اتصالات udp رو بلاک میکرد و این اختلال درست میکرد تو بعضی نرم افزارها.

خوشحالم که مشکل حل شد و ممنون که اطلاع دادی.
