### ISSUE TITLE
قطعی هر چند ثانیع یکبار در نسخه 3.2.0

### ISSUE THREAD

**Issue by hamid20244** [msasanmh/SecureDNSClient#188]
ضمن تشکر از زحمات بی دریغ شما
میخواستم کمک کنید تا بتونم به صورت پایدار متصل بشم. تقریبا هر چند ثانیه یکبار توقف در پخش دارم.
خیلی طول میکشه تا صفحه اول یوتیوب لود بشه 
خیلی طول میکشه تا فیلمی شروع به پخش بشه
در مورد برنامه های پخش زنده هم به هیچ وجه شرایط مناسب نیست.

![1](https://github.com/msasanmh/SecureDNSClient/assets/167010121/2916518f-02ab-48bb-9215-516c6c457157)
ضمن تشکر مجدد اگر راهکاری دارید بفرمایید

**Comment by msasanmh** [comment]
> ضمن تشکر از زحمات بی دریغ شما
> میخواستم کمک کنید تا بتونم به صورت پایدار متصل بشم. تقریبا هر چند ثانیه یکبار توقف در پخش دارم.
> خیلی طول میکشه تا صفحه اول یوتیوب لود بشه 
> خیلی طول میکشه تا فیلمی شروع به پخش بشه
> در مورد برنامه های پخش زنده هم به هیچ وجه شرایط مناسب نیست.
> 
> ![1](https://github.com/msasanmh/SecureDNSClient/assets/167010121/2916518f-02ab-48bb-9215-516c6c457157)
> ضمن تشکر مجدد اگر راهکاری دارید بفرمایید

وقتی پراکسی روشنه دیگه GoodbyeDPI رو خاموش کنید بیشتر اختلال میندازه.
