### ISSUE TITLE
error on ssl connection

### ISSUE THREAD

**Issue by san6749** [msasanmh/SecureDNSClient#19]
DPI Check: The SSL connection could not be established, see inner exception

**Comment by msasanmh** [comment]
> من به اینترنت مخابرات متصلم
> 

این تنظیمات رو بروی تب Advanced اعمال کن شاید جواب داد.
![Screenshot_20230514_232942_Gallery.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/b6cad48f-cb50-4c52-a09d-060cfde42079)
