### ISSUE TITLE
DNS Loopback

### ISSUE THREAD

**Issue by Noob2Pr0** [msasanmh/SecureDNSClient#192]
سلام داشم
مطمئنم در نسخه های قبلی این مشکل فیکس شده بود
ولی متاسفانه در این نسخه من با این که خودم unset dns میزنم بعدش disconnect میزنم
پس از اون exit میدم برنامه رو و بعد سیستم رو خاموش میکنم
فرداش مشکل اینتنرت دارم که میرم چک میکنم کارت شبکه رو می بینم 127.0.0.1 روی dns ست شده
فرقی هم نداره با روش بالا دستی موارد رو بردارم بعد exit بدم یا در همون حالت که وصله exit بدم خودش اوتوماتیک مینویسه unset شدو ...
که در واقع 127.0.0.1 میمونه
قبلا یادمه 8.8.8.8 و یه آدرس دیگه ست می شد وقتی خارج می شد از برنامه
احتمال داره نسخه portable باشه دسترسی خاصی نداشته باشه ؟ یا مورد دیگه ای دخیله ؟

**Comment by msasanmh** [comment]
> سلام داشم مطمئنم در نسخه های قبلی این مشکل فیکس شده بود ولی متاسفانه در این نسخه من با این که خودم unset dns میزنم بعدش disconnect میزنم پس از اون exit میدم برنامه رو و بعد سیستم رو خاموش میکنم فرداش مشکل اینتنرت دارم که میرم چک میکنم کارت شبکه رو می بینم 127.0.0.1 روی dns ست شده فرقی هم نداره با روش بالا دستی موارد رو بردارم بعد exit بدم یا در همون حالت که وصله exit بدم خودش اوتوماتیک مینویسه unset شدو ... که در واقع 127.0.0.1 میمونه قبلا یادمه 8.8.8.8 و یه آدرس دیگه ست می شد وقتی خارج می شد از برنامه احتمال داره نسخه portable باشه دسترسی خاصی نداشته باشه ؟ یا مورد دیگه ای دخیله ؟

وقتی DNS ست شده باشه داخل تب سوم اطلاعات مربوط به آداپتر باید مثل عکس پایین باشه - اون قسمت رو هایلایت کردم
![Set](https://github.com/msasanmh/SecureDNSClient/assets/1586825/77a0443b-a354-43f1-a6f6-265e61b1da2c)

حالا اگه بروی Unset کلیک کنی باید به شکل پایین تغییر کنه
![Unset](https://github.com/msasanmh/SecureDNSClient/assets/1586825/64b22a5f-dfff-4c16-858e-dea474435f76)

این قسمت رو بررسی کن. روی Set و Unset کلیک کن ببین مثل تصاویر بالا تغییر میکنه یا نه.
قبلا داخل یکی از لاگ هایی که فرستاده بودی نوشته بود که دفعه قبل برنامه رو Exit نکردی:
![NotClosed](https://github.com/msasanmh/SecureDNSClient/assets/1586825/c13b507c-c435-4ed9-86c0-234f9e8f4170)
اگه برنامه یهو بسته بشه قطعا DNS آن ست نمیشه.

و تفاوتی هم بین Portable و Installer نیست. موارد بالا رو چک کن بهم اطلاع بده.

**Comment by Noob2Pr0** [comment]
موارد بالا رو طی این دو روز چک کردم طبق گفته خودت اوکی هستش و تغییر میده dns رو برمیگردونه به همون 2 ایپی google dns و نوشته ای از اون خطای ایی که گفتی در لاگ نیست
مجدد اتفاق نی افتاده چک کنم همون چند بار پشت سر هم منو به شک انداخت
احتمال داره به خاطر استفاده ترکیبی یه conflict خورده باشه

**Comment by msasanmh** [comment]
> موارد بالا رو طی این دو روز چک کردم طبق گفته خودت اوکی هستش و تغییر میده dns رو برمیگردونه به همون 2 ایپی google dns و نوشته ای از اون خطای ایی که گفتی در لاگ نیست
> مجدد اتفاق نی افتاده چک کنم همون چند بار پشت سر هم منو به شک انداخت
> احتمال داره به خاطر استفاده ترکیبی یه conflict خورده باشه

آره احتمالش هست توسط یه برنامه دیگه ست شده باشه.

در مورد اون اطلاعاتی که توی تب سوم نشون میده خیالت راحت باشه، اون دقیقا اطلاعات خود آداپتر رو میخونه و از API رسمی مایکروسافت استفاده میکنه.
یعنی اگه dns آن‌ست نشده باشه اونجا بیخود ip گوگل رو نشون نمیده.
در کل هیچ شکی در Unset شدن dns نداشته باش.

فقط یادت باشه قبل Shutdown برنامه رو Exit کنی.

**Comment by Noob2Pr0** [comment]
حله
