### ISSUE TITLE
browser doh disabled

### ISSUE THREAD

**Issue by Ahoura0** [msasanmh/SecureDNSClient#193]
سلام من وقتی برنامه رو نصب کردم certificate هم نصب کردم بعدش که برنامه رو پاک کردم داخل مرورگر این پیام اومده our [browser is managed](edge://management/) by your organization. میخوام secure dns هم فعال کنم میگه this setting is turned off for managed browser

**Comment by msasanmh** [comment]
> سلام من وقتی برنامه رو نصب کردم certificate هم نصب کردم بعدش که برنامه رو پاک کردم داخل مرورگر این پیام اومده our browser is managed by your organization. میخوام secure dns هم فعال کنم میگه this setting is turned off for managed browser

این پیام یعنی Policy مرورگر Edge شما دستکاری شده که هیچ دخلی به برنامه SDC نداره.
داخل این دو اسکرین شات پایین میبینید که وقتی SDC روشنه تنظیمات Edge به چه صورته:
![On_1](https://github.com/msasanmh/SecureDNSClient/assets/1586825/eabaa213-cfce-4c74-8f6f-13f0bd53edf8)
![On_2](https://github.com/msasanmh/SecureDNSClient/assets/1586825/5ac31a1a-f640-4865-86a7-438ee2317634)
داخل این دو اسکرین شات پایین میبینید که وقتی SDC خاموشه تنظیمات Edge به چه صورته:
![Off_1](https://github.com/msasanmh/SecureDNSClient/assets/1586825/f63629c5-bc13-4fb0-9117-e0ad3c62b1d0)
![Off_2](https://github.com/msasanmh/SecureDNSClient/assets/1586825/df27ad1f-7e15-4481-bf21-42282d8d292c)

همونطور که دیدی برنامه SDC کاری با تنظیمات مرورگر نداره.
درواقع برنامه SDC هرگز هیچ Policy ای رو ویرایش یا تغییر نمیده. من هرگز به خودم اجازه نمیدم که چنین کاری کنم. دیگه برنامه رو متن باز گذاشتم تا همه به چشم خودشون سالم بودن برنامه رو ببینن.

شما یا یه کار دیگه ای انجام دادی یا اینکه بروی لینک های Malware کلیک کردی و سیستمت آلوده شده، یا میتونه بخاطر نصب یه سایدبار یا افزونه در مرورگر این مشکل ایجاد شده باشه.

راه حل:
داخل مرورگر Edge به آدرس edge://policy برید و ببینید هیچ Policy اضافه ای ست نشده باشه.
باید مثل اسکرین شات پایین باشه:
![Edge_Policy](https://github.com/msasanmh/SecureDNSClient/assets/1586825/1542d0b7-2eca-4102-a90a-f05df2a0e991)

مثلا در این آدرس پایین در ساپورت مایکروسافت یکی مشکل شما رو داشته که بخاطر نصب یک سایدبار بوده:
https://answers.microsoft.com/en-us/microsoftedge/forum/all/how-to-stop-edge-from-being-managed-by-an/a1c181a0-9601-4f72-8d10-88fcd678fc36

پس لطفا خواهش میکنم هر اتفاقی که برای سیستم تون میوفته رو به برنامه SDC نسبت ندید، برنامه که متن بازه و دیگه واقعا نمیدونم به چه شکلی من باید سالم بودن این برنامه رو اثبات کنم.
در ابتدا این برنامه رو برای استفاده شخصی خودم نوشتم و بعد چند ماه گفتم این برنامه به کار من اومده بهتره به اشتراکش بذارم تا شاید بدرد یه هموطن خورد.

اگه برنامه من آلوده بود وبسایت رسمی DNSCrypt هرگز برنامه SDC رو در لیست کلاینت هاش نمیذاشت و معرفی نمیکرد:
https://dnscrypt.info/implementations/

در نهایت پیشنهاد من به شما و هر کس دیگه ای اینه که هرگز از برنامه هایی که بهشون اعتماد ندارید استفاده نکنید.
و معذرت میخوام که مجبور شدم بی رودربایستی و مستقیم صحبت کنم، امیدوارم درک کنی.

**Comment by Ahoura0** [comment]
میخواستم آخرش بپرسم که بخاطر حذف برنامه هست یا نه؟ وگرنه منظوری نداشتم
چک کردم این policy فعاله https://docs.microsoft.com/DeployEdge/microsoft-edge-policies#webwidgetallowed ولی نمیدونم چطور غیرفعالش کنم

**Comment by msasanmh** [comment]
> میخواستم آخرش بپرسم که بخاطر حذف برنامه هست یا نه؟ وگرنه منظوری نداشتم چک کردم این policy فعاله https://docs.microsoft.com/DeployEdge/microsoft-edge-policies#webwidgetallowed ولی نمیدونم چطور غیرفعالش کنم

نه به حذف برنامه هم ربطی نداره.
برای حذف کردن Policy های مرورگر edge باید از طریق رجیستری اقدام کنید.
اگه خودتون با رجستری آشنا هستید، به صورت ادمین اجراش کنید و دو آدرس پایین رو حذف کنید:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge
HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge

اگه از رجستری چیزی نمیدونی بهتره بهش دست نزنی و به جاش از CMD استفاده کنی.
یک CMD بصورت ادمین اجرا کن و دستورات پایین رو داخلش اجرا کن:

taskkill /im msedge.exe /f
reg delete "HKCU\Software\Policies\Microsoft\Edge" /f
reg delete "HKLM\Software\Policies\Microsoft\Edge" /f

در این پیج توضیحات کاملتری داده شده:
https://www.tenforums.com/browsers-email/209701-your-browser-edge-managed-your-organization.html

**Comment by Ahoura0** [comment]
آخه webwidget چه ربطی به dns داره؟؟😂🤦‍♂️
اوکی شد. دمت گرم ❤️
