### ISSUE TITLE
share on hotspot

### ISSUE THREAD

**Issue by siabash** [msasanmh/SecureDNSClient#196]
سلام اول تشکر بسیار بابت این کارتون خیلی عالی روی ویندوز واسه من جواب میده
سوالی که داشتم اینه که میتونم اینو مثل وی پی ان روی هاتسپات لپ تاپم شیر کنم که بقیه کلاینت ها بتونن ازش استفاده کنن ؟؟ چون اون راهی که پراکسی ست کنم رو کلاینت های روی همون وای فای رو تست کردم و جواب نداد متاسفانه

**Comment by msasanmh** [comment]
> سلام اول تشکر بسیار بابت این کارتون خیلی عالی روی ویندوز واسه من جواب میده

سلام، ممنون.

> سوالی که داشتم اینه که میتونم اینو مثل وی پی ان روی هاتسپات لپ تاپم شیر کنم که بقیه کلاینت ها بتونن ازش استفاده کنن ؟؟ چون اون راهی که پراکسی ست کنم رو کلاینت های روی همون وای فای رو تست کردم و جواب نداد متاسفانه 

با هاتسپات نمیشه، چون مستقیم از خود آداپتر اینترنت میگیره و از پراکسی ست شده روی ویندوز استفاده نمی‌کنه.
من که پراکسی برنامه رو بروی وای‌فای گوشی ست کردم کار کرد. وبسایت‌هایی مثل یوتیوب بدون هیچ برنامه اضافه‌ای باز میشدن.
اگه برای شما جواب نداده باید فایروال رو چک کنید و مطمئن بشید به outbound و inbound پراکسی اجازه داده شده باشه.

**Comment by siabash** [comment]
جسارتا پراکسی برنامه همون 127.0.0.1 روی پورت 8080 رو میفرمایید دیگه ؟؟

**Comment by msasanmh** [comment]
> جسارتا پراکسی برنامه همون 127.0.0.1 روی پورت 8080 رو میفرمایید دیگه ؟؟ 

پورت همینه اما این ip برای لوکال هستش باید از ip شبکه استفاده کنی، همونی که با 192.168 شروع میشه.
اگه ip شبکه خودت رو نمیدونی، در قسمت Net Info برنامه نوشته شده

**Comment by siabash** [comment]
یعنی تو بخش proxy داخل وایفای گوشی بخش هاست نیم رو همین ...192.168 که لوکال پراکسی ادرس داخل net info نرم افزار نوشترو وارد کنم و در بخش پورت هم 8080 ؟؟ تو بخش اینباند و اوتباند فایروال ویندوز هم خود نرم افزار رو رد کردم ازش هم پورت 8080 رو ولی عجیبه که کار نمیکنه

**Comment by msasanmh** [comment]
> یعنی تو بخش proxy داخل وایفای گوشی بخش هاست نیم رو همین ...192.168 که لوکال پراکسی ادرس داخل net info نرم افزار نوشترو وارد کنم و در بخش پورت هم 8080 ؟؟ تو بخش اینباند و اوتباند فایروال ویندوز هم خود نرم افزار رو رد کردم ازش هم پورت 8080 رو ولی عجیبه که کار نمیکنه 

دقیقا به همین شکل و یادت باشه که انتظار نداشته باشی با GoodbyeDPI کار کنه، چون بروی شبکه تاثیر نمیذاره.
باید DPI Bypass خود پراکسی فعال باشه، مثل فرگمنت یا SSL Decryption و یا هر دو.
و اگه در تب چهارم، تیک گزینه Show proxy requests رو بزنی، اونوقت وقتی از گوشی به پراکسی وصل هستی داخل لاگ درخواست‌ها رو نشون میده.
اینطوری میتونی بفهمی به پراکسی وصل هستی یا نه.

**Comment by siabash** [comment]
واقعا ممنونم بخاطر راهنماییات،خیلی خیلی کمکم کرد
