### ISSUE TITLE
a little gap freeze

### ISSUE THREAD

**Issue by Noob2Pr0** [msasanmh/SecureDNSClient#197]
سلام چطوری ؟
داشتم یه اکشنی پیدا کردم که توش ابزارت برای من حداقل فریز کرد
توی تصویری که زیر میزارم دقت کن
لحظه ای که دیدم پیام (اینترنت وصل نیست) روی برنامه (هنوز کانکت نشدم)
رفتم دوباره وای فای رو وصل کردم و قبل از نمایش پیام back online روی دکمه connect کلیک کردم، اتفاقی که افتاد این بود دکمه خاکستری شد و همین طوری موند. البته قطعا برنامه رو ببندم باز کنم مشکل حله ولی گفتم گزارششو بهت بگم فیکسش کنی

**Comment by Noob2Pr0** [comment]
![image](https://github.com/user-attachments/assets/c0d0eed1-c254-491b-8198-f1cb11c6c2b1)

**Comment by msasanmh** [comment]
سلام،
مرسی بابت گزارش، حتما بررسی می‌کنم.
فقط رو این حالت مقدار Working Servers صفر که نبود، درسته؟

**Comment by Noob2Pr0** [comment]
معمولا وقتی که اینترنت باشه مقدار working server 5 تاش و همه اشون پینگ میده
الانم یه لحظه وای فای سیستم رو قطع کردم که ببینم وقتی اینترنت نیست working server چی میاره
که دیدم 

Contains 5 Servers:

There Is No Internet Connectivity.
DNS 2: -1 ms.
DNS 3: -1 ms.
DNS 4: -1 ms.
DNS 1: -1 ms.
DNS 5: -1 ms.


و بنظر میرسه روی 0 نیست و هر 5 تا هستن

**Comment by msasanmh** [comment]
مرسی، حله.

**Comment by msasanmh** [comment]
درسته، حق با تو بود، هر وقت اینترنت نباشه و بروی کانکت کلیک بشه، دکمه غیرفعال میشه و دیگه فعال نمیشه. ورژن بعد فیکس میشه.

**Comment by Noob2Pr0** [comment]
یه چیز دیگه هم پیدا کردم انقدر تنبلی کردم سر ویدیو گرفتنش که طول کشید ورژن جدید رو دادی
یادته dns بعضی وقت ها روی loopback می موند ؟ فهمیدم داستانش چیه
من 2 تا اینترنت دارم یکی Iranjail :) اون یکی Adsl Sepanta
بعدش وقتی ابزارت رو میزنم درواقع اون لحظه روی یکی از اینا connect هستم و در طول روز شاید برم روی اون یکی یه کاری رو انجام بدم و وقتی عوض میکنم مجدد باید set dns بزنم تا تنظیمات اعمال بشه و از اونجایی که ویندوز تنظیمات هر wifi رو انگار در wifi profile مخصوص هر کدوم نگهداری میکنه وقتی در اخر شب سیستم رو خاموش میکنم با اونی که خاموش میکنم dns rest میشه و اونی که متصل قبلا بودم و در اون لحظه متصل نیستم dns rest نمیشه و اشتباهمون این بود فکر میکردیم تنظیمات روی خود nic و ربطی به wifi profile نداره ! پروفایل وای فای هم export میگیرم باز خبری از dns اینا نیستا ولی نمیدونم چی رو تو ویندوز تغییر دادن قبلا این طوری بوده یا تو ویندوز 11 این طوری شده ! خلاصه خواستی ویدیو میگیرم

**Comment by msasanmh** [comment]
> یه چیز دیگه هم پیدا کردم انقدر تنبلی کردم سر ویدیو گرفتنش که طول کشید ورژن جدید رو دادی
> یادته dns بعضی وقت ها روی loopback می موند ؟ فهمیدم داستانش چیه
> من 2 تا اینترنت دارم یکی Iranjail :) اون یکی Adsl Sepanta
> بعدش وقتی ابزارت رو میزنم درواقع اون لحظه روی یکی از اینا connect هستم و در طول روز شاید برم روی اون یکی یه کاری رو انجام بدم و وقتی عوض میکنم مجدد باید set dns بزنم تا تنظیمات اعمال بشه و از اونجایی که ویندوز تنظیمات هر wifi رو انگار در wifi profile مخصوص هر کدوم نگهداری میکنه وقتی در اخر شب سیستم رو خاموش میکنم با اونی که خاموش میکنم dns rest میشه و اونی که متصل قبلا بودم و در اون لحظه متصل نیستم dns rest نمیشه و اشتباهمون این بود فکر میکردیم تنظیمات روی خود nic و ربطی به wifi profile نداره ! پروفایل وای فای هم export میگیرم باز خبری از dns اینا نیستا ولی نمیدونم چی رو تو ویندوز تغییر دادن قبلا این طوری بوده یا تو ویندوز 11 این طوری شده ! خلاصه خواستی ویدیو میگیرم

تمامی اطلاعات در nic میمونه. 
این مشکلی که میگی کاملا منطقی و حل نشدنیه.
چون وقتی یه nic غیرفعال میشه دیگه برنامه بهش دسترسی نداره تا بخواد dns رو از روش unset کنه.
بهتره قبل از تعویض کانکشن، اول خودت unset کنی.

و روی Loopback موندن هم الان منطقیه، باید ببینم راه‌کاری به ذهنم میرسه یا نه.

راستی این issue بسته شده. پیام جدید داشتی یه issue جدید باز کن، این جوری سریعتر پیامت رو می‌بینم.
