### ISSUE TITLE
قطع شدن دی ان اس بعد از چند ثانیه

### ISSUE THREAD

**Issue by hamid20244** [msasanmh/SecureDNSClient#199]
از زحمات بی شائبه شما نهایت تشکر و قدردانی رو دارم

میشه لطف کنید و نظر بدید، چند روزه که اصلا نمیتونم وصل بشم. نه مخابرات و نه ایرانسل

تووی این چند روز یه مشکلی برام پی اومده، اینکه خیلی وقتا بعد از چند ثانیه از فشردن SET Proxy خود به خود قطع میشه

![1](https://github.com/user-attachments/assets/ee849da2-4d8e-45a2-9641-086586688675)

ممنونم از بابت وقتی که گذاشتین

**Comment by msasanmh** [comment]
استفاده همزمان GoodbyeDPI با پراکسی درست نیست، فقط یکی شون باید فعال باشه.
پیشنهاد میکنم GoodbyeDPI رو خاموش کنید، مخصوصا اینکه بروی مود High قرار داره و میتونه باعث break شدن خیلی از سایت‌ها بشه و در نتیجه سرورهای دی‌ان‌اس.

اگه باز هم این مشکل پیش اومد می‌تونه بخاطر تاخیر بالای اینترنت باشه که میتونید از تنظیمات 
Settings  ->  Check
گزینه Plain DNS رو تیک بزنید که تاخیر پایین‌تر دارن و دوباره سرورها رو اسکن کنید.
چون برنامه از پروتکل TCP برای Plain DNS استفاده میکنه IP ها هایجک نمیشن و ارتباط ایمن باقی می‌مونه.
