### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by shabda7** [msasanmh/SecureDNSClient#2]
Hi, after running the program for several minutes, the laptop became unusable due to high CPU usage. The laptop has a Core i7 12700H CPU, 16GB of RAM, and runs on Windows 11.

**Comment by msasanmh** [comment]
میدونم فارسی بلدی. پس فارسی مینویسم. در زمانی که برنامه داره سرورها رو اسکن میکنه استفاده از حدود 50 درصد سی پی یو طبیعیه.
اگه بعد اسکن سرورها این مشکل رو داری چک کن ببین کدوم یک از پروسس های پایین داره سی پی یو میکشه و بهم اطلاع بده:
DNSLookup.exe, DNSProxy.exe, GoodbyeDPI.exe

**Comment by shabda7** [comment]
> میدونم فارسی بلدی. پس فارسی مینویسم. در زمانی که برنامه داره سرورها رو اسکن میکنه استفاده از حدود 50 درصد سی پی یو طبیعیه. اگه بعد اسکن سرورها این مشکل رو داری چک کن ببین کدوم یک از پروسس های پایین داره سی پی یو میکشه و بهم اطلاع بده: DNSLookup.exe, DNSProxy.exe, GoodbyeDPI.exe

به خاطر قاطی شدن کلمات فارسی و انگلیسی و ناخوانا شدن متن، انگلیسی نوشتم.
DNSProxy.exe 
مشکل درست می‌کنه. البته به شکل بار اول نبود ولی بازم هنگ کرد سیستم.

**Comment by msasanmh** [comment]
> 

بروی سیستم من مصرف سی پی یوش 0.2 هستش. فکر کنم با سیستمت سازگاری نداره
اما میتونی این دو مورد رو بررسی کنی:
اول آخرین نسخه
dnsproxy.exe
رو از آدرس پایین دانلود کن و توی فولدر برنامه به این آدرس
SecureDNSClient\binary
جایگذاری کن. لینک دانلود:
https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.49.1

بعد برنامه رو از ابتدا راه اندازی کن و اگه دیدی باز هم مشکل سی پی یو داره، از داخل
Task manager
بروی پروسس
dnsproxy.exe
راست کلیک کن و از منوی
set prority
گزینه نرمال رو انتخاب کن.
با اینکه این برنامه یه رابط کاربری هست اما توی ورژن بعدی سعی میکنم کاری کنم این پروسس ملایم تر بروی سی پی یو اجرا شه

**Comment by shabda7** [comment]
> > 
> 
> بروی سیستم من مصرف سی پی یوش 0.2 هستش. فکر کنم با سیستمت سازگاری نداره اما میتونی این دو مورد رو بررسی کنی: اول آخرین نسخه dnsproxy.exe رو از آدرس پایین دانلود کن و توی فولدر برنامه به این آدرس SecureDNSClient\binary جایگذاری کن. لینک دانلود: https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.49.1
> 
> بعد برنامه رو از ابتدا راه اندازی کن و اگه دیدی باز هم مشکل سی پی یو داره، از داخل Task manager بروی پروسس dnsproxy.exe راست کلیک کن و از منوی set prority گزینه نرمال رو انتخاب کن. با اینکه این برنامه یه رابط کاربری هست اما توی ورژن بعدی سعی میکنم کاری کنم این پروسس ملایم تر بروی سی پی یو اجرا شه

باشه، حتما انجام می‌دم این کارها رو، ولی در کل برنامه‌ی خیلی خوب و کاربردی درست کردی. ممنون

**Comment by msasanmh** [comment]
ممنونم، لطف داری. امیدوارم ورژن بعدی روی سیستمت بی‌نقص اجرا بشه.
