### ISSUE TITLE
Request for improvements in future updates

### ISSUE THREAD

**Issue by SonyaCore** [msasanmh/SecureDNSClient#201]
Hello dear Sasan,

First of all, thank you for this amazing program. I have been using it for a long time and most of the time I have been really satisfied. However, there are some issues I have encountered, and I would be grateful if you could address them in future updates.

1- Receiving ERR_CONNECTION_REFUSED and ERR_DNS_PROBLEM errors on some websites, especially internal sites, even though I have added the rules.

2- Inability to use the new smart DNS feature. I have tested various blocked sites, but unfortunately, it still does not work and I receive a 403 error.

3- Severe browsing slowdown, which I kindly request to improve as much as possible in future updates. I have also seen this issue reported previously.

4- Adding tips and guidance next to options for amateur users. Personally, I had to experiment a lot to understand how many of the program's features work. If you could add an ℹ️ icon with brief guidance (both in Persian and English) for each option, it would be fantastic.

5- Adding import and export settings feature, so that when we report an issue, you can understand the problem by receiving this file. Also, it would be very helpful for setting up the program for friends and family who are not proficient; by importing this file, all our settings can be applied for them as well.

Thank you for your great program, SDC. Please don’t forget about it.

**Comment by msasanmh** [comment]
> Hello dear Sasan,
> 
> First of all, thank you for this amazing program. I have been using it for a long time and most of the time I have been really satisfied. However, there are some issues I have encountered, and I would be grateful if you could address them in future updates.
> 
> 1- Receiving ERR_CONNECTION_REFUSED and ERR_DNS_PROBLEM errors on some websites, especially internal sites, even though I have added the rules.

Many reasons can cause these issues, the main reason is the incompatibility of DPI Bypass methods.
If a website is not blocked, you can write a rule for it to not apply DPI Bypass methods.
For example for all .ir domains you need to add this rule in Proxy Rules not DNS Rules: 
```
*.ir|--;
```

> 
> 2- Inability to use the new smart DNS feature. I have tested various blocked sites, but unfortunately, it still does not work and I receive a 403 error.

You need to restart your browser to clear the DNS cache. 
In this video you can see I'm opening Gemini and ChatGPT with smart DNS:

https://github.com/user-attachments/assets/76088e4c-de3d-4973-8055-7e12f597a376

> 
> 3- Severe browsing slowdown, which I kindly request to improve as much as possible in future updates. I have also seen this issue reported previously.

There's a 3 - 6 seconds delay for proxy to determine which DPI methods it should use to bypass the website. 
If I remove this auto detection you will not have any delay but you will get more errors like the one you mentioned in number 1.

Although the proxy cache these results for 15 minutes to avoid unnecessary delay for reopening the same website. 

> 
> 4- Adding tips and guidance next to options for amateur users. Personally, I had to experiment a lot to understand how many of the program's features work. If you could add an ℹ️ icon with brief guidance (both in Persian and English) for each option, it would be fantastic.

I will add this to SDC Plus.

> 
> 5- Adding import and export settings feature, so that when we report an issue, you can understand the problem by receiving this file. Also, it would be very helpful for setting up the program for friends and family who are not proficient; by importing this file, all our settings can be applied for them as well.

This feature already exist.
Settings  ->  Others 

You can use "Export user data" and import it to any other SDC on any PC with "Import user data" button. 

> 
> Thank you for your great program, SDC. Please don’t forget about it.

I'm sure these text based Rules are making users a bit confused. 
I'll make it GUI based in SDC Plus.

But it takes time to write the Plus version. 
Thank you for your patience.
