### ISSUE TITLE
مشکل وصل شدن با همراه اول

### ISSUE THREAD

**Issue by javadkhademi7** [msasanmh/SecureDNSClient#203]
سلام بابت زحمات تون ممنونم. با اینترنت آسیاتک به خوبی وصل میشه ولی با همراه اول اصلا نمی تونم کانکت بشم.

**Comment by msasanmh** [comment]
> سلام بابت زحمات تون ممنونم. با اینترنت آسیاتک به خوبی وصل میشه ولی با همراه اول اصلا نمی تونم کانکت بشم. 

برای ISP هایی که فیلترینگ شدیدتری دارن باید از SSL Decryption استفاده کنید.
در اینجا توضیحاتش نوشته شده:
https://github.com/msasanmh/SecureDNSClient/issues/140#issuecomment-1975107459

البته پخش لایو سیو شده در یوتیوب باگ داره که در ورژن بعد برطرف میشه.

**Comment by javadkhademi7** [comment]
> > سلام بابت زحمات تون ممنونم. با اینترنت آسیاتک به خوبی وصل میشه ولی با همراه اول اصلا نمی تونم کانکت بشم.
> 
> برای ISP هایی که فیلترینگ شدیدتری دارن باید از SSL Decryption استفاده کنید. در اینجا توضیحاتش نوشته شده: [#140 (comment)](https://github.com/msasanmh/SecureDNSClient/issues/140#issuecomment-1975107459)
> 
> البته پخش لایو سیو شده در یوتیوب باگ داره که در ورژن بعد برطرف میشه.

ممنون
