### ISSUE TITLE
عدم اتصال به اینترنت مخابرات

### ISSUE THREAD

**Issue by SaeedNaderii** [msasanmh/SecureDNSClient#206]
سلام . وقت بخیر دوست عزیز
علیرغم انجام دادن تمام تنظیماتی که فرموده بودید ، کماکان نمی تونم با اینترنت مخابرات به یوتیوب متصل بشم . 

لطفا راهنمایی بفرمایید . با تشکر

**Comment by shahabparisa** [comment]
سلام بی زحمت این مشکل لایو یوتیوب رو هم حل کنین خیلی وقته آپدیتی نمیدین

**Comment by msasanmh** [comment]
> سلام . وقت بخیر دوست عزیز
> علیرغم انجام دادن تمام تنظیماتی که فرموده بودید ، کماکان نمی تونم با اینترنت مخابرات به یوتیوب متصل بشم . 
> 
> لطفا راهنمایی بفرمایید . با تشکر 

برای اینترنت مخابرات SSL Decryption با فعال بودن Change SNI میتونه جواب بده اما باید فورس بشه که این فورس شدن در ورژن بعد با غیرفعال کردن Fragment میتونه انجام بشه.

**Comment by msasanmh** [comment]
> سلام بی زحمت این مشکل لایو یوتیوب رو هم حل کنین خیلی وقته آپدیتی نمیدین

لایو یوتیوب رو بررسی کردم. این مشکل باگ برنامه نیست. اخیرا گوگل بروی لود نشدن تبلیغات حساس شده و حتما میخواد تبلیغات لود بشه.
حالا خود یوتیوب به ایران تبلیغات نمیده و از طرفی هم وقتی تبلیغات لود نشه پخش لایو رو قطع می‌کنه. 
در واقع این یه باگ یا مشکل از سمت گوگله. 

بروی ورژن  بعد دارم کار می‌کنم. پراکسی سریعتر میشه، وبسایت‌های ایرانی دایرکت میشن و میشه SSL Decryption و یا Fragment رو بصورت فورس اجرا کرد.

**Comment by SaeedNaderii** [comment]
> > سلام . وقت بخیر دوست عزیز
> > علیرغم انجام دادن تمام تنظیماتی که فرموده بودید ، کماکان نمی تونم با اینترنت مخابرات به یوتیوب متصل بشم .
> > لطفا راهنمایی بفرمایید . با تشکر
> 
> برای اینترنت مخابرات SSL Decryption با فعال بودن Change SNI میتونه جواب بده اما باید فورس بشه که این فورس شدن در ورژن بعد با غیرفعال کردن Fragment میتونه انجام بشه.

--------------------------------------------------------------------------------------------------------------------------------------------

با تشکر از پاسخگوییتون .

گزینه SSL Decryption و Change SNI را فعال و ٍ Enable Fragment را غیر فعال کردم . با توجه به اینکه اینترنت من فیبر نوری است ، صفحه یوتیوب با کندی زیاد باز می شه اما بعد از کلیک روی ویدیو ها ، اصلا اجرا نمی شن .

**Comment by msasanmh** [comment]
> > > سلام . وقت بخیر دوست عزیز
> > > علیرغم انجام دادن تمام تنظیماتی که فرموده بودید ، کماکان نمی تونم با اینترنت مخابرات به یوتیوب متصل بشم .
> > > لطفا راهنمایی بفرمایید . با تشکر
> > 
> > برای اینترنت مخابرات SSL Decryption با فعال بودن Change SNI میتونه جواب بده اما باید فورس بشه که این فورس شدن در ورژن بعد با غیرفعال کردن Fragment میتونه انجام بشه.
> 
> --------------------------------------------------------------------------------------------------------------------------------------------
> 
> با تشکر از پاسخگوییتون .
> 
> گزینه SSL Decryption و Change SNI را فعال و ٍ Enable Fragment را غیر فعال کردم . با توجه به اینکه اینترنت من فیبر نوری است ، صفحه یوتیوب با کندی زیاد باز می شه اما بعد از کلیک روی ویدیو ها ، اصلا اجرا نمی شن . 
> 
> 
> 

واسه همین گفتم در ورژن بعد 🙂
الان برنامه بعضی از لینک‌های یوتیوب رو فکر می‌کنه SSL Decryption باهاش سازگار نیست میزنه اتوماتیک خاموش می‌کنه.
واسه همین کلا این اتوماتیک بودن تشخیص رو در ورژن بعد میذارم برای زمانی که هر دو متد روشن باشن.
کند بودن هم در ورژن بعد برطرف می‌شه.

**Comment by msasanmh** [comment]
> > > سلام . وقت بخیر دوست عزیز
> > > علیرغم انجام دادن تمام تنظیماتی که فرموده بودید ، کماکان نمی تونم با اینترنت مخابرات به یوتیوب متصل بشم .
> > > لطفا راهنمایی بفرمایید . با تشکر
> > 
> > برای اینترنت مخابرات SSL Decryption با فعال بودن Change SNI میتونه جواب بده اما باید فورس بشه که این فورس شدن در ورژن بعد با غیرفعال کردن Fragment میتونه انجام بشه.
> 
> --------------------------------------------------------------------------------------------------------------------------------------------
> 
> با تشکر از پاسخگوییتون .
> 
> گزینه SSL Decryption و Change SNI را فعال و ٍ Enable Fragment را غیر فعال کردم . با توجه به اینکه اینترنت من فیبر نوری است ، صفحه یوتیوب با کندی زیاد باز می شه اما بعد از کلیک روی ویدیو ها ، اصلا اجرا نمی شن . 
> 
> 
> 

ورژن جدید رو تست کنید.
اگر فعال بودن همزمان هر دو متد ضد DPI جواب نداد اونوقت فقط SSL Decryption رو روشن کنید و Fragment و GoodbyeDPI خاموش باشه.
