### ISSUE TITLE
save dns

### ISSUE THREAD

**Issue by leoson95** [msasanmh/SecureDNSClient#22]
سلام
من مساله م این هست که وقتی چک میکنه dns هارو ... اونهارو سیو نمیکنه یا گزینه ای برای اینکار هست نمیدونم
view هم میزنم  خالی هست فایل های تکست
و اگر ببندم و باز کنم برنامه رو صفر میشه و باید از اول چک بزنم تا بررسی کنه

راهی هست یا باگ هست ؟

**Comment by msasanmh** [comment]
نه، باگ نیست. متاسفانه مجبور بودم این امکان رو ازش بردارم والا همه سرورها زودی فیلتر میشن.
