### ISSUE TITLE
what's the problem on MCI, shatel...

### ISSUE THREAD

**Issue by HamidZaeri** [msasanmh/SecureDNSClient#23]
سلام
مشکل همراه اول و شاتل الان چیه؟ ریسالو نمیشه یا آی‌پی 10.10.34.34 برمیگرودنه.

با rethink آی‌پی درست رو برمیگردونه ولی باز یوتیوب و توییتر لود نمیشن!  یعنی آی‌پی فیلتر شده با مشکل دیگه ای هست؟

یه سوال دیگه هم دارم این که آیا تو مرحله سرتیفیکیت https هم میتونن اختلال ایجاد کنن؟ یعنی تشخیص بدن چه سایتی در حال اتصال هستیم و سرتیفیکیت فیک برگردونن و رو مرورگر هم طبعا ca تایید نکنه و اتصال انجام نشه؟

**Comment by msasanmh** [comment]
> سلام
> مشکل همراه اول و شاتل الان چیه؟ ریسالو نمیشه یا آی‌پی 10.10.34.34 برمیگرودنه.
> 
> با rethink آی‌پی درست رو برمیگردونه ولی باز یوتیوب و توییتر لود نمیشن!  یعنی آی‌پی فیلتر شده با مشکل دیگه ای هست؟
> 
> یه سوال دیگه هم دارم این که آیا تو مرحله سرتیفیکیت https هم میتونن اختلال ایجاد کنن؟ یعنی تشخیص بدن چه سایتی در حال اتصال هستیم و سرتیفیکیت فیک برگردونن و رو مرورگر هم طبعا ca تایید نکنه و اتصال انجام نشه؟

سلام، مشکل همراه اول و شاتل اینه که دیگه بیش از حد پیشرو در ضمینه فیلترینگ هستن. 
توی این نوع از فیلترینگ که براساس dpi هستش قدرت سخت افزاری ISP خیلی مهمه، ظاهرا این دو ISP سخت‌افزار قوی‌تری دارن.
هرچی ISP کوچیکتر باشه دورزدنش راحت‌تره.
اما بالاخره موفق شدم یه راه حل برای همراه اول پیدا کنم که توی ورژن بعدی اعمال می‌کنم، فقط کاربر باید پراکسی ای که برنامه بهش میده رو ست کنه روی مرورگر یا ویندوز.
یعنی همراه اولی ها فقط نیاز دارن این قسمت پراکسی رو انجام بدن، برای بقیه این مرحله نیاز نیست.
سوال دوم، نه همچین کاری نمی‌کنن چون نیاز به این کار ندارن اصلا.

**Comment by HamidZaeri** [comment]
خوب dpi تو مرحله اتصال به ip انجام میشه؟ درسته؟

چون تو مرحله dns که آی‌پی رو درست برمی گردونه! Resolve اوکیه

یعنی یه جورایی دارن ترافیک یوتیوب رو تشخیص میدن بلاک میکنن؟ بدون این که کل آی‌پی رو ببندن؟

**Comment by msasanmh** [comment]
> خوب dpi تو مرحله اتصال به ip انجام میشه؟ درسته؟
> 
> چون تو مرحله dns که آی‌پی رو درست برمی گردونه! Resolve اوکیه
> 
> یعنی یه جورایی دارن ترافیک یوتیوب رو تشخیص میدن بلاک میکنن؟ بدون این که کل آی‌پی رو ببندن؟

آره، بطور کلی به سه بخش تقسیم میشه، اول dns رو ویرایش میکنن که ip اصلی رو ندن که این قسمت رو با استفاده از DoH حل می‌کنیم. 
قسمت بعد میان اسم سایت رو از پکت هایی که ارسال میشه می‌خونن و جلوی اتصال رو میگیرن که برای حل این قسمت باید dpi رو دور بزنیم.
قسمت سوم هم که کلا ip رو میبندن که اینجا تنها راه استفاده از vpn هستش.

**Comment by msasanmh** [comment]
> سلام
> مشکل همراه اول و شاتل الان چیه؟ ریسالو نمیشه یا آی‌پی 10.10.34.34 برمیگرودنه.
> 
> با rethink آی‌پی درست رو برمیگردونه ولی باز یوتیوب و توییتر لود نمیشن!  یعنی آی‌پی فیلتر شده با مشکل دیگه ای هست؟
> 
> یه سوال دیگه هم دارم این که آیا تو مرحله سرتیفیکیت https هم میتونن اختلال ایجاد کنن؟ یعنی تشخیص بدن چه سایتی در حال اتصال هستیم و سرتیفیکیت فیک برگردونن و رو مرورگر هم طبعا ca تایید نکنه و اتصال انجام نشه؟

سلام، مشکل همراه اول در ورژن جدید حل شد.
از تب سوم dpi bypass رو بروی حالت light قرار بدید و در تب پنجم پراکسی رو کانکت و ست کنید.

**Comment by msasanmh** [comment]
دی ان اس هم فعال و ست باشه.
