### ISSUE TITLE
CustomServers_Working بعد از تست کامل هم خالی هست 

### ISSUE THREAD

**Issue by SMDARKSIREN** [msasanmh/SecureDNSClient#24]
وقت بخیر.
CustomServers_Working.txt
 خالی هست حتی وقتی بصورت کامل هم چک کردن تمام میشه و برای من تا وقتی گزینه set dns نزنم کانکت نمیشه و اصلا هم توییتر باز نمیکنه

**Comment by msasanmh** [comment]
> وقت بخیر.
> CustomServers_Working.txt
>  خالی هست حتی وقتی بصورت کامل هم چک کردن تمام میشه و برای من تا وقتی گزینه set dns نزنم کانکت نمیشه و اصلا هم توییتر باز نمیکنه

سرورهای داخل برنامه برای اینکه فیلتر نشن داخل اون لیست ذخیره نمیشن، اون لیست مخصوص سرورهای شخصیه شماست. یعنی داخل custom servers یه سری سرور وارد کنید و بذارید چک بشه، برنامه سرورهای سالم رو میذاره داخل اون لیست.

قسمت دوم رو متوجه نشدم که اگه set dns نزنید چه چیزی کانکت نمیشه.
هر ۵ مرحله باید به ترتیب انجام بشه.

**Comment by SMDARKSIREN** [comment]
> > وقت بخیر.
> > CustomServers_Working.txt
> > خالی هست حتی وقتی بصورت کامل هم چک کردن تمام میشه و برای من تا وقتی گزینه set dns نزنم کانکت نمیشه و اصلا هم توییتر باز نمیکنه
> 
> سرورهای داخل برنامه برای اینکه فیلتر نشن داخل اون لیست ذخیره نمیشن، اون لیست مخصوص سرورهای شخصیه شماست. یعنی داخل custom servers یه سری سرور وارد کنید و بذارید چک بشه، برنامه سرورهای سالم رو میذاره داخل اون لیست.
> 
> قسمت دوم رو متوجه نشدم که اگه set dns نزنید چه چیزی کانکت نمیشه. هر ۵ مرحله باید به ترتیب انجام بشه.

مرسی از توضیحتون.

ببینید وقتی set dns زده میشه ای پی سیستم و ای پی لوکال وارد قسمت  dns کانکشن ویندوز میشه مثلا thernet4  و بعد از اون یوتیوب باز میشه ولی اصلا نه توییتر نه فیسبوک اصلا باز نمیشه

**Comment by msasanmh** [comment]
> > > وقت بخیر.
> > > CustomServers_Working.txt
> > > خالی هست حتی وقتی بصورت کامل هم چک کردن تمام میشه و برای من تا وقتی گزینه set dns نزنم کانکت نمیشه و اصلا هم توییتر باز نمیکنه
> > 
> > سرورهای داخل برنامه برای اینکه فیلتر نشن داخل اون لیست ذخیره نمیشن، اون لیست مخصوص سرورهای شخصیه شماست. یعنی داخل custom servers یه سری سرور وارد کنید و بذارید چک بشه، برنامه سرورهای سالم رو میذاره داخل اون لیست.
> > 
> > قسمت دوم رو متوجه نشدم که اگه set dns نزنید چه چیزی کانکت نمیشه. هر ۵ مرحله باید به ترتیب انجام بشه.
> 
> مرسی از توضیحتون.
> 
> ببینید وقتی set dns زده میشه ای پی سیستم و ای پی لوکال وارد قسمت  dns کانکشن ویندوز میشه مثلا thernet4  و بعد از اون یوتیوب باز میشه ولی اصلا نه توییتر نه فیسبوک اصلا باز نمیشه

آها، خب dns که حتما باید ست بشه و برنامه موقع خروج خودش unset میکنه.
فیسبوک که اصلا به ip فیلتر شده و به این روش باز نمیشه، این برنامه فقط میتونه سایت‌هایی که براساس DNS/SNI فیلتر شدن رو باز کنه نه آی‌پی.
اما جای تعجبه که یوتیوب باز شد اما توییتر باز نمیشه، باید این مورد رو بررسی کنم.
ممنون بابت اطلاع.

**Comment by alidxdydz** [comment]
> > > > وقت بخیر.
> > > > CustomServers_Working.txt
> > > > خالی هست حتی وقتی بصورت کامل هم چک کردن تمام میشه و برای من تا وقتی گزینه set dns نزنم کانکت نمیشه و اصلا هم توییتر باز نمیکنه
> > > 
> > > سرورهای داخل برنامه برای اینکه فیلتر نشن داخل اون لیست ذخیره نمیشن، اون لیست مخصوص سرورهای شخصیه شماست. یعنی داخل custom servers یه سری سرور وارد کنید و بذارید چک بشه، برنامه سرورهای سالم رو میذاره داخل اون لیست.
> > > 
> > > قسمت دوم رو متوجه نشدم که اگه set dns نزنید چه چیزی کانکت نمیشه. هر ۵ مرحله باید به ترتیب انجام بشه.
> > 
> > مرسی از توضیحتون.
> > 
> > ببینید وقتی set dns زده میشه ای پی سیستم و ای پی لوکال وارد قسمت  dns کانکشن ویندوز میشه مثلا thernet4  و بعد از اون یوتیوب باز میشه ولی اصلا نه توییتر نه فیسبوک اصلا باز نمیشه
> 
> آها، خب dns که حتما باید ست بشه و برنامه موقع خروج خودش unset میکنه.
> فیسبوک که اصلا به ip فیلتر شده و به این روش باز نمیشه، این برنامه فقط میتونه سایت‌هایی که براساس DNS/SNI فیلتر شدن رو باز کنه نه آی‌پی.
> اما جای تعجبه که یوتیوب باز شد اما توییتر باز نمیشه، باید این مورد رو بررسی کنم.
> ممنون بابت اطلاع.

من هر توییتر رو از هر سرویسی چک میکنم، بدون CDN نشون میده. احتمالا IP ها بلاک شدن

**Comment by alidxdydz** [comment]
> > > > وقت بخیر.
> > > > CustomServers_Working.txt
> > > > خالی هست حتی وقتی بصورت کامل هم چک کردن تمام میشه و برای من تا وقتی گزینه set dns نزنم کانکت نمیشه و اصلا هم توییتر باز نمیکنه
> > > 
> > > سرورهای داخل برنامه برای اینکه فیلتر نشن داخل اون لیست ذخیره نمیشن، اون لیست مخصوص سرورهای شخصیه شماست. یعنی داخل custom servers یه سری سرور وارد کنید و بذارید چک بشه، برنامه سرورهای سالم رو میذاره داخل اون لیست.
> > > 
> > > قسمت دوم رو متوجه نشدم که اگه set dns نزنید چه چیزی کانکت نمیشه. هر ۵ مرحله باید به ترتیب انجام بشه.
> > 
> > مرسی از توضیحتون.
> > 
> > ببینید وقتی set dns زده میشه ای پی سیستم و ای پی لوکال وارد قسمت  dns کانکشن ویندوز میشه مثلا thernet4  و بعد از اون یوتیوب باز میشه ولی اصلا نه توییتر نه فیسبوک اصلا باز نمیشه
> 
> آها، خب dns که حتما باید ست بشه و برنامه موقع خروج خودش unset میکنه.
> فیسبوک که اصلا به ip فیلتر شده و به این روش باز نمیشه، این برنامه فقط میتونه سایت‌هایی که براساس DNS/SNI فیلتر شدن رو باز کنه نه آی‌پی.
> اما جای تعجبه که یوتیوب باز شد اما توییتر باز نمیشه، باید این مورد رو بررسی کنم.
> ممنون بابت اطلاع.

من توییترو از هر سرویسی چک میکنم، بدون CDN نشون میده. احتمالا IP هاش بلاک شدن
