### ISSUE TITLE
Port 53 is occupied. Is SecureDNS already running?!

### ISSUE THREAD

**Issue by Seenamm** [msasanmh/SecureDNSClient#26]
سلام من به این برخوردم

![image_2023-05-21_033101823](https://github.com/msasanmh/SecureDNSClient/assets/134177008/8d6bd8bb-62b5-4936-964d-04b5421c5148)

**Comment by msasanmh** [comment]
> سلام من به این برخوردم
> 
> ![image_2023-05-21_033101823](https://github.com/msasanmh/SecureDNSClient/assets/134177008/8d6bd8bb-62b5-4936-964d-04b5421c5148)
> 

میگه پورت ۵۳ اشغال هستش، از آخرین ورژن برنامه استفاده کنید تا بهتون بگه چه برنامه‌ای پورت ۵۳ رو اشغال کرده، اونوقت می‌تونید از task manager اون برنامه رو ببندید.

**Comment by Seenamm** [comment]
دیروز نصبش کردم باید آخرین ورژن باشه

**Comment by msasanmh** [comment]
> دیروز نصبش کردم باید آخرین ورژن باشه

آخرین ورژن 2.1.0 هستش. لینک دانلود:
https://github.com/msasanmh/SecureDNSClient/releases/tag/v2.1.0

**Comment by Seenamm** [comment]
مشکل جدید

![image_2023-05-22_015058995](https://github.com/msasanmh/SecureDNSClient/assets/134177008/d86903d1-bbbb-433c-a614-271124dc31dd)

**Comment by msasanmh** [comment]
> مشکل جدید
> 
> ![image_2023-05-22_015058995](https://github.com/msasanmh/SecureDNSClient/assets/134177008/d86903d1-bbbb-433c-a614-271124dc31dd)
> 

خب این همون پیام خطاست، شما یه برنامه دیگه‌ای مربوط به dns اجرا داری که پورت ۵۳ رو اشغال کرده.
اسم پراسس DnsService هستش. اگه میدونی این پراسس واسه چه برنامه‌ایه میتونی اون برنامه رو stop کنی. اگه نمیدونی این پراسس رو از task manager ببند.

**Comment by Seenamm** [comment]
برای برنامه Technitium DNS بود
پاکش کردم و از قسمت سرویس هم پاک شده حالا اما باز خطای Unkown رو میگیرم

**Comment by msasanmh** [comment]
> برای برنامه Technitium DNS بود
> پاکش کردم و از قسمت سرویس هم پاک شده حالا اما باز خطای Unkown رو میگیرم

چون پورت هنوز اشغاله اما برنامه نتونسته اسم پراسس رو پیدا کنه، شاید نیاز باشه سیستم رو ری‌استارت کنی

**Comment by Seenamm** [comment]
بله 2 بار هم ریستارت کردم اما همچنان مشکل باقیه
به نظر میاد نتونم برنامه رو تستش کنم متاسفانه

**Comment by msasanmh** [comment]
> بله 2 بار هم ریستارت کردم اما همچنان مشکل باقیه
> به نظر میاد نتونم برنامه رو تستش کنم متاسفانه

پیدا کردن پراسس کاری نداره، داخل CMD دستور پایین رو تایپ کن:
netstat -ano | find "LISTEN"
بعدش ببین مقابل عدد ۵۳ چه عدد دیگه‌ای نوشته شده، اون عدد رو به یاد بسپار و برو داخل تسک منیجر، براساس PID مرتب کن و اون عدد رو پیدا کن، اونوقت راحت میتونی پراسس رو ببندی.

**Comment by msasanmh** [comment]
netstat -ano | find "LISTEN"

**Comment by Seenamm** [comment]
> > بله 2 بار هم ریستارت کردم اما همچنان مشکل باقیه
> > به نظر میاد نتونم برنامه رو تستش کنم متاسفانه
> 
> پیدا کردن پراسس کاری نداره، داخل CMD دستور پایین رو تایپ کن: netstat -ano | find "LISTEN" بعدش ببین مقابل عدد ۵۳ چه عدد دیگه‌ای نوشته شده، اون عدد رو به یاد بسپار و برو داخل تسک منیجر، براساس PID مرتب کن و اون عدد رو پیدا کن، اونوقت راحت میتونی پراسس رو ببندی.

اینطوری، درسته؟
![image](https://github.com/msasanmh/SecureDNSClient/assets/134177008/cc77e5fe-98ad-4507-bd21-cc1d0df2cf81)

**Comment by msasanmh** [comment]
> > > بله 2 بار هم ریستارت کردم اما همچنان مشکل باقیه
> > > به نظر میاد نتونم برنامه رو تستش کنم متاسفانه
> > 
> > پیدا کردن پراسس کاری نداره، داخل CMD دستور پایین رو تایپ کن: netstat -ano | find "LISTEN" بعدش ببین مقابل عدد ۵۳ چه عدد دیگه‌ای نوشته شده، اون عدد رو به یاد بسپار و برو داخل تسک منیجر، براساس PID مرتب کن و اون عدد رو پیدا کن، اونوقت راحت میتونی پراسس رو ببندی.
> 
> اینطوری، درسته؟
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/134177008/cc77e5fe-98ad-4507-bd21-cc1d0df2cf81)
> 

نه، اون نیست، کاری به اون پراسس نداشته باش.
ظاهرا از نوع listening نیست. باید دستور پایین رو تایپ کنی:
netstat -ano

**Comment by Seenamm** [comment]
> > > > بله 2 بار هم ریستارت کردم اما همچنان مشکل باقیه
> > > > به نظر میاد نتونم برنامه رو تستش کنم متاسفانه
> > > 
> > > 
> > > پیدا کردن پراسس کاری نداره، داخل CMD دستور پایین رو تایپ کن: netstat -ano | find "LISTEN" بعدش ببین مقابل عدد ۵۳ چه عدد دیگه‌ای نوشته شده، اون عدد رو به یاد بسپار و برو داخل تسک منیجر، براساس PID مرتب کن و اون عدد رو پیدا کن، اونوقت راحت میتونی پراسس رو ببندی.
> > 
> > 
> > اینطوری، درسته؟
> > ![image](https://user-images.githubusercontent.com/134177008/239771766-cc77e5fe-98ad-4507-bd21-cc1d0df2cf81.png)
> 
> نه، اون نیست، کاری به اون پراسس نداشته باش. ظاهرا از نوع listening نیست. باید دستور پایین رو تایپ کنی: netstat -ano

تو این یکی لیست با PIDهای زیادی برمیخورم که یا از svchost.exe هستن یا براوزرم
بستنشون هم باز ارور رو رفع نمیکنه

**Comment by msasanmh** [comment]
> > > > > بله 2 بار هم ریستارت کردم اما همچنان مشکل باقیه
> > > > > به نظر میاد نتونم برنامه رو تستش کنم متاسفانه
> > > > 
> > > > 
> > > > پیدا کردن پراسس کاری نداره، داخل CMD دستور پایین رو تایپ کن: netstat -ano | find "LISTEN" بعدش ببین مقابل عدد ۵۳ چه عدد دیگه‌ای نوشته شده، اون عدد رو به یاد بسپار و برو داخل تسک منیجر، براساس PID مرتب کن و اون عدد رو پیدا کن، اونوقت راحت میتونی پراسس رو ببندی.
> > > 
> > > 
> > > اینطوری، درسته؟
> > > ![image](https://user-images.githubusercontent.com/134177008/239771766-cc77e5fe-98ad-4507-bd21-cc1d0df2cf81.png)
> > 
> > نه، اون نیست، کاری به اون پراسس نداشته باش. ظاهرا از نوع listening نیست. باید دستور پایین رو تایپ کنی: netstat -ano
> 
> تو این یکی لیست با PIDهای زیادی برمیخورم که یا از svchost.exe هستن یا براوزرم
> بستنشون هم باز ارور رو رفع نمیکنه

توی این اسکرین شات اون عدد ۵۳۵۷ هستش، باید فقط دنبال عدد ۵۳ باشی.
اگه به svchost ربطش داده باید بدونی این مورد خیلی غیر عادیه، ممکنه ویروس داشته باشی.
پیشنهاد میکنم حتما این مشکل رو حل کنی.

**Comment by msasanmh** [comment]
دو تا دلیل ایجاد این مشکل اجرا بودن این دوتاست:
Host Network Service 
Internet Connection Sharing service
فکر نمی‌کنم ویروس باشه.
