### ISSUE TITLE
Requires .Net Destop Runtime 6 x86

### ISSUE THREAD

**Issue by wvxwxvw** [msasanmh/SecureDNSClient#27]
Requires .Net Destop Runtime 6 x86 to be installed. Why? You don't know what the requirements of your program are? ;)

**Comment by msasanmh** [comment]
> By the way, in Firefox it works even if trr is set to 5.  
>   
> It is not clear how to make autorun.  
> _Does not set local DNS. You either have to do it manually or use something like [https://www.sordum.org/7952/dns-jumper-v2-2/](url)_  Got it figured out.
>   
> I have Windows 7 x64, system DNS cache is disabled.  
>   
> Thanks for the program, I think over time you will finalize it, most importantly, do not transfer it to .NET 7.

I didn't implement autorun yet.
Setting local dns: I've only tested it on win 10 and 11, the only problem is I don't have access to every os and ISPs, but I'm gonna dig on this, thanks.

**Comment by wvxwxvw** [comment]
Well, add a link to the main page.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x86-installer
There seems to be no combined installer, but there is a script. It can be screwed directly into the program, with a request.
https://dotnet.microsoft.com/en-us/download/dotnet/scripts

**Comment by msasanmh** [comment]
> By the way, in Firefox it works even if trr is set to 5.  
>   
> It is not clear how to make autorun.  
> _Does not set local DNS. You either have to do it manually or use something like [https://www.sordum.org/7952/dns-jumper-v2-2/](url)_  Got it figured out.
>   
> I have Windows 7 x64, system DNS cache is disabled.  
>   
> Thanks for the program, I think over time you will finalize it, most importantly, do not transfer it to .NET 7.

I've made some changes, I think now it can set and unset dns on Windows 7 properly. 
Give me your feedback on this if possible.

**Comment by msasanmh** [comment]
> @msasanmh 
> Normally set, unset.
> We should teach it to restore DNS, i.e. Before changing, make a backup of the addresses used, and restore those addresses when disconnected.
> 
> How to disable GoodbyeDPI auto-connection? It doesn't work for me at all. Most ISP blockages are bypassed by changing the DNS, and others (recognized as extremist) are bypassed only by VPN or TOP.  Just in case - I have been familiar with this project since its inception.
> GoodbyeDPI's auto-connection interferes with me.

About the first I can make it to pick up set dns servers first but apparently the method doesn't work on all type of windows, so I'm gonna add an option to settings to tell the app, set my preferred dns servers on "unset dns" instead of dhcp.

About the second. GoodbyeDPI don't activate by itself. 
Anyway to deactivate GoodbyeDPI just click on "Deactivate" on it's own tab.
If you're using share (proxy) tab, uncheck "Enabled dpi bypass".

**Comment by wvxwxvw** [comment]
Exactly "Enabled dpi bypass".

**Comment by wvxwxvw** [comment]
No, I hurried without checking. "Enabled dpi bypass" does not affect GoodbyeDPI in any way. It still turns on, which is very annoying.

**Comment by msasanmh** [comment]
> No, I hurried without checking. "Enabled dpi bypass" does not affect GoodbyeDPI in any way. It still turns on, which is very annoying.

"Enable DPI Bypass" is belong to http proxy, it has nothing to do with GoodbyeDPI. 
You can deactivate GoodbyeDPI by clicking on "Deactivate" on it's own tab.
Also uncheck "Enable DPI Bypass" on share tab, then you won't have any DPI Bypassing active.

**Comment by wvxwxvw** [comment]
But I don't need to turn it off when it's already unsuccessfully logged on youtube and the internet doesn't work, I need it to not turn on at all.

**Comment by msasanmh** [comment]
> But I don't need to turn it off when it's already unsuccessfully logged on youtube and the internet doesn't work, I need it to not turn on at all.

I've just told you, make your status like this:
![IMG_20230602_190714_105.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/30c05589-e640-4ae5-a0ad-af646a44cbf2)

**Comment by msasanmh** [comment]
> But I don't need to turn it off when it's already unsuccessfully logged on youtube and the internet doesn't work, I need it to not turn on at all.

Make you status like this:

**Comment by msasanmh** [comment]
Only DNS:
![Only DNS](https://github.com/msasanmh/SecureDNSClient/assets/1586825/d1e7a635-1a97-4996-aacb-c4f2292063b7)

**Comment by msasanmh** [comment]
DNS + Proxy:
![Only DNS + proxy](https://github.com/msasanmh/SecureDNSClient/assets/1586825/6dfa80c9-d706-49a8-a931-9d8043726040)

**Comment by msasanmh** [comment]
On your last screenshot

1. Uncheck "Enable DPI Bypass"
2. Click on "Enable/Disable"
3. Click on "Set/Unset"

about that setting DNS part, I've tested it on Windows 7, I really have no idea what's going on, but I'm gonna dig more about it.

**Comment by wvxwxvw** [comment]
No, that’s not good. Spontaneously turns off (why) and in addition drops the DNS address. Something is wrong.

**Comment by msasanmh** [comment]
what turns off spontaneously?

**Comment by wvxwxvw** [comment]
Spontaneously disconnects, goes offline. I checked the servers, most of the workers, connected, set the DNS address, worked a little and bam - yells that offline, and resets the DNS address. The previous version was not disconnect (I do not remember the version number). Pure DNSCrypt does not disconnect, it works stably.

**Comment by msasanmh** [comment]
> Spontaneously disconnects, goes offline. I checked the servers, most of the workers, connected, set the DNS address, worked a little and bam - yells that offline, and resets the DNS address. The previous version was not disconnect (I do not remember the version number). Pure DNSCrypt does not disconnect, it works stably.

I've added those built-in servers in case user's ISP blocks access to public DNS servers. Not all of them are stable. 

1. Once you have a few working servers, cancel the check operation by clicking on "Check/Cancel". Don't let the the application check all servers. 

2. In settings, in Connect tab, increase "Number of working servers to connect".

3. In settings, in Connect tab, check "Enable DNS cache"

4. "Disable audio alert" from settings. Because once you have DNS Cache enabled those little connection drops won't make any problems. 

Or if you have any stable DNS servers, you can use "Custom Mode" instead of "Built-in Mode".

I'll try to improve connection stability on the next version.

**Comment by wvxwxvw** [comment]
I'll look later, now it's not up to the tests.
