### ISSUE TITLE
Virus Dettected. (Chrome and 7Zip)

### ISSUE THREAD

**Issue by noyzen** [msasanmh/SecureDNSClient#29]
Hi,
Last version (2.1.1) I wanted to downlaod but Google Chrome don't let me download it because of virus or unwanted program.
I used download manager and downloaded 7z file.
But 7zip give me error for virus or unwanted program and don't let me extract it.
for previous version 2.1.0 and before I had no problem.

**Comment by msasanmh** [comment]
> Hi,
> Last version (2.1.1) I wanted to downlaod but Google Chrome don't let me download it because of virus or unwanted program.
> I used downlado manager and downloaded 7z file.
> But 7zip give me error for virus or unwanted program and dont let me extract it.
> for previous version 2.1.0 and before I had no problem.

It's totally weird, in new version (2.1.1) I just added local dns delay on status bar and fixed connecting via proxy, nothing more.
The app is open source, any programmer can look into it.
...I've looked into the VirusTotal result, you're right, It must be a false positive alert and probably it's gonna be fix by recompiling it. 
I'll have to release a new version soon.

**Comment by msasanmh** [comment]
Well, it's about WinDivert which is used by GoodbyeDPI. 
I added a not regarding this matter to readme:
https://github.com/msasanmh/SecureDNSClient/blob/main/README.md

I can't do anything about it, but I assure you it's completely safe and being used by many applications. 
You can safely add it to your exclude list.

**Comment by noyzen** [comment]
Hi again, I have downloaded new version 2.1.2 and It's working without problems and warnings.
دمت گرم عالیه
