### ISSUE TITLE
مشکل view working servers

### ISSUE THREAD

**Issue by alidxdydz** [msasanmh/SecureDNSClient#3]
سلام و جدا خسته نباشید
موردی که وجود داره اینه که مثلا 11 سرور پیدا شده که کار میکنن. گزینه کنسل رو میزنم ولی وقتی view working servers رو میزنم خالیه و ذخیره نشده. اگه بصورت https://dns.adguard.com/dns-query ، tls://dns.adguard.com و quic://dns.adguard.com ذخیره بشه میشه تو PowerTunnel استفاده کرد.
از لطف شما ممنونم

**Comment by msasanmh** [comment]
سلام، قسمت view working servers مربوط به سرورهای شخصی میشه یا همون custom servers.
وقتی از لیست سرورهای داخلی استفاده می‌کنید اونها رو توی view working servers نشون نمیده تا فیلتر نشن.
