### ISSUE TITLE
problem with Set DNS

### ISSUE THREAD

**Issue by sitsaz** [msasanmh/SecureDNSClient#30]
سلام ، لطفا Set Dns و تنظیمات مربوط به آن رو در تب اول قرار دهید ، یعنی نرم افزار ابتدا سوال کند که این DNS قرار هست روی کدام کانکشن ست بشود و سپس اقدام به جستجو و اعمال تنظیمات کند ، در حال حاضر هربار که روی اتصال میزنم DNS بجای وایفای بر روی vEthernet اعمال می شود در نتیجه کانکشن صورت نمیگیرد و هر موقع قصد تغییر و انتخاب کانکشن wifi رو دارم با پیام Connect first مواجه می شوم

**Comment by msasanmh** [comment]
> سلام ، لطفا Set Dns و تنظیمات مربوط به آن رو در تب اول قرار دهید ، یعنی نرم افزار ابتدا سوال کند که این DNS قرار هست روی کدام کانکشن ست بشود و سپس اقدام به جستجو و اعمال تنظیمات کند ، در حال حاضر هربار که روی اتصال میزنم DNS بجای وایفای بر روی vEthernet اعمال می شود در نتیجه کانکشن صورت نمیگیرد و هر موقع قصد تغییر و انتخاب کانکشن wifi رو دارم با پیام Connect first مواجه می شوم

جای این تب ها عوض بشه هیچ فرقی نمی‌کنه، چون بالاخره باید از لیست یه کانکشن رو انتخاب کنی و بعد ست رو بزنی. اصلا به حال شما تفاوتی ایجاد نمی‌کنه. 

و هم اینکه خیلی‌ها نمی‌خوان dns رو روی سیستم شون ست کنن و فقط قسمت check و connect رو انجام میدن تا از dns ایجاد شده بروی موبایل شون استفاده کنن. نمیتونم ست کردن  dns رو اجباری کنم.

پیام connect first میگه اول باید dns لوکال کانکت باشه تا بعد بتونی بروی سیستم ست کنی، چون اگه کانکت نباشه و ست بشه کل سیستم ارتباطش با اینترنت رو از دست میده.
