### ISSUE TITLE
دمت گرم خسته نباشی ولی برای مخابرات کلا همه چی بلاک شده 

### ISSUE THREAD

**Issue by motn12** [msasanmh/SecureDNSClient#31]
خیلی ممنون بابت کاری که انجام دادی خسته نباشی ولی برای مخابرات تو تست یدونه هم پیدا نمیکنه که کار کنه

**Comment by msasanmh** [comment]
> خیلی ممنون بابت کاری که انجام دادی خسته نباشی ولی برای مخابرات تو تست یدونه هم پیدا نمیکنه که کار کنه

سلام، من مخابرات ندارم اما بچه‌ها تست زدن گفتن حدود ۳۰ تا سرور با پینگ زیر یک ثانیه پیدا کرده.
گزارش بجه‌ها:
https://github.com/msasanmh/SecureDNSClient/issues/20#issuecomment-1550295599

اگه واقعا چیزی پیدا نشد، از تب connect گزینه دوم رو امتحان کن، اون نیاز به سرور نداره، البته اگه روی ISP مخابرات جواب بده.
یا دیگه فوقش میتونی یه DNS ایرانی به برنامه بدی.

**Comment by zoghal** [comment]
آقا دمت گرم! عجب چیزی شده!
روی های‌وب داره مثل هلو کار میکنه😍😍😍

**Comment by msasanmh** [comment]
> آقا دمت گرم! عجب چیزی شده!
> روی های‌وب داره مثل هلو کار میکنه😍😍😍

ممنون، کم کم بهتر هم میشه.

**Comment by mozeabi** [comment]
سلام دستتون درد نکنه خیلی عالیه   محشره
آیکون منیمایز هم بهش اضافه کن
نمیدونم چرا با fdm میشه ودیوها رو دانلود کرد ولی بعضی از روزها اصلا فایده نمیکنه اینترنتم مخابراته اگه مورد دانلود هم کامل حل بشه خیلی خوب میشه

**Comment by msasanmh** [comment]
> سلام دستتون درد نکنه خیلی عالیه   محشره
> آیکون منیمایز هم بهش اضافه کن
> نمیدونم چرا با fdm میشه ودیوها رو دانلود کرد ولی بعضی از روزها اصلا فایده نمیکنه اینترنتم مخابراته اگه مورد دانلود هم کامل حل بشه خیلی خوب میشه
> 
> 

سلام، ممنون. من کم کم دارم به درخواست‌های کاربرا رسیدگی می‌کنم، فقط زمان میبره و در هر آپدیت جدیدی که میدم فقط میتونم چند مورد رو اعمال کنم.
این مورد دانلود رو هم میذارم تو لیست و بررسی می‌کنم.

**Comment by ehsan-am** [comment]
سلام و درود بر شما
ممنون از این dnsclient باحال ، در مدت یک ماه استفاده خیلی لذت بردم فقط امروز یه مشکل پیش اومد برام که وقتی اون دکمه آخر ست پراکسی رو میزنم این ارور رو میده:dpi check: the ssl connection could not be established, see inner exception.   میتونید راهنماییم کنید.قبلا اینطور نبود .خیلی خیلی ممنون نمیدونم ویروسه یا چی.تقریبا تو یوتیوب اکثر  ویدیو هایی که راهکار میگفتن رو رفتم، مثل زدن بعضی تیکها تو internet options(advanced) یا clear certificate و... البته اکثر راه حل مشکل ssl که تو یوتیوب میگفتن، مربوط به بروزر یا گوگل کروم بودن و نه مشکل من که بتونم رفعش کنن. میشه لطفا بهم بگید چه کنم.واقعا ممنون

**Comment by msasanmh** [comment]
> سلام و درود بر شما
> ممنون از این dnsclient باحال ، در مدت یک ماه استفاده خیلی لذت بردم فقط امروز یه مشکل پیش اومد برام که وقتی اون دکمه آخر ست پراکسی رو میزنم این ارور رو میده:dpi check: the ssl connection could not be established, see inner exception.   میتونید راهنماییم کنید.قبلا اینطور نبود .خیلی خیلی ممنون نمیدونم ویروسه یا چی.تقریبا تو یوتیوب اکثر  ویدیو هایی که راهکار میگفتن رو رفتم، مثل زدن بعضی تیکها تو internet options(advanced) یا clear certificate و... البته اکثر راه حل مشکل ssl که تو یوتیوب میگفتن، مربوط به بروزر یا گوگل کروم بودن و نه مشکل من که بتونم رفعش کنم. میشه لطفا بهم بگید چه کنم.واقعا ممنون

ربطی به ویروس نداره، وقتی این پیام میاد یعنی برنامه نتونسته سیستم DPI رو دور بزنه.
که احتمالش خیلی پایینه که پراکسی نتونه DPI رو دور بزنه.
انجام این کارها میتونه کمک کنه:

داخل تنظیمات پراکسی Block port 80 تیک داشته باشه.
پراکسی مستقیم بروی مرورگر ست بشه بجای ویندوز.

از قسمت status نگاه کنید که تعداد proxy requests خیلی بالا نباشه، اگه بالاست یعنی برنامه‌ای داره از پراکسی استفاده میکنه که مزاحم کارش شده.

و تنظیمات مربوط به Bypass DPI از تب چهارم.
اعداد رو تغییر بدید، کمی بالا پایین کنید.
مثلا Fragment delay خیلی مهمه، برای بعضی isp ها نیازه که صفر باشه و برای بقیه بین ۱ تا ۳۰ باشه.

با هر بار تغییر تنظیمات Bypass روی Apply کلیک کنید تا چک کنه یوتیوب باز میشه یا نه.

متاسفانه من مخابرات ندارم تا تست کنم.

**Comment by ehsan-am** [comment]
خیلی ممنون از پاسخ سریعت اینو هم بگم در شروع برنامه این ارور رو که تا دیروز نیومد رو هم میده:gram can't start because api-ms-win-eventing-controller-l1-1-0.dll is missing که دی ال ال مربوطه رو نتونستم تو نت پیدا کنم تا در WINDOWS جایگزین کنم. نمیدونم از چیه که البته زیاد مهم نیست چون بهر حال برنامه بالا میاد.مشکل اصلیم همون پیغام SSL هست که استپ آخر میده و به شما گفتم و دیگه اینکه منظورت از تنظیمات پراکسی، تنظیمات برنامس یا جای دیگه؟ چون Block port 80  رو نتونستم پیدا کنم.

**Comment by msasanmh** [comment]
> خیلی ممنون از پاسخ سریعت اینو هم بگم در شروع برنامه این ارور رو که تا دیروز نیومد رو هم میده:the program can't start because api-ms-win-eventing-controller-l1-1-0.dll is missing که دی ال ال مربوطه رو نتونستم تو نت پیدا کنم تا در WINDOWS جایگزین کنم. نمیدونم از چیه که البته زیاد مهم نیست چون بهر حال برنامه بالا میاد.مشکل اصلیم همون پیغام SSL هست که استپ آخر میده و به شما گفتم

این ارور رو تابحال ندیده بودم، به هر حال یه سرچ زدم.

کارایی که اینجا نوشته شده رو انجام بده:

https://www.sts-tutorial.com/download/api-ms-win-core-path-l1-1-0

و اینجا هم ورژن های مختلفش برای دانلود هست:

https://www.dll-files.com/api-ms-win-eventing-controller-l1-1-0.dll.html

**Comment by ehsan-am** [comment]
خیلی ممنون از لینکها این دی ال ال ها رو یکی پس از دیگری ریختم به فولدر DNSCLIENT و خب ارور اول برنامه دیگه نمیاد ولی خب مشکل اصلیم همون ارور DPI CHECK برنامست طبق گفته شما اون پارامترهای FRAGMENT DELAY هم بالا پایین کردم بدون اثری!!  این برنامه شما واقعا خوراک یوتیوب هست و ویدیو ها رو بدون لگ با ماکسیمم buffer health (حتی ویدیوهای 60fps)اجرا میکنه و برای منی که اکثرا تو یوتیوبم، محشره ولی نمیدونم یه دفعه چه کوفتی گرفت سیستمم!

**Comment by ehsan-am** [comment]
امکانش هست ویندوز در یه جایی مشکلی براش اومده باشه( مثلا چه میدونم از اون مشکلات مزخرف که بعضی موقعها خود ویندوز هم نمیتونه دیاگنوز بکنه) بنظرت ویندوز عوض کنم؟!!!

**Comment by msasanmh** [comment]
> خیلی ممنون از لینکها این دی ال ال ها رو یکی پس از دیگری ریختم به فولدر DNSCLIENT و خب ارور اول برنامه دیگه نمیاد ولی خب مشکل اصلیم همون ارور DPI CHECK برنامست طبق گفته شما اون پارامترهای FRAGMENT DELAY هم بالا پایین کردم بدون اثری!!  این برنامه شما واقعا خوراک یوتیوب هست و ویدیو ها رو بدون لگ با ماکسیمم buffer health (حتی ویدیوهای 60fps)اجرا میکنه و برای منی که اکثرا تو یوتیوبم، محشره ولی نمیدونم یه دفعه چه کوفتی گرفت سیستمم! 

درواقع باید توی فولدرهای system32 و syswow64 می‌ریختی. 
نمی‌دونم چرا توی فولدر برنامه ریختی ارور برطرف شد، چون اصلا به اون ربط نداره.

آره یوتیوب واقعا خوب باز میشه، از ابتدا برنامه رو واسه دل خودم نوشته بودم بعد گفتم به اشتراک بذارم شاید به کار کسی دیگه‌ای هم اومد.

و این پیام inner exception واقعا مثل سرطان می‌مونه، یعنی اگه بیاد تنها دلیل تنظیمات dpi bypass هستش و واقعا چیز دیگه‌ای وجود نداره بخوام بگم تا مشکلت حل بشه.

حالا وقتی پراکسی ست هست خود گوگل و وبسایت‌های دیگه باز میشن؟ یا کلا هیچ چیز باز نمیشه؟

**Comment by msasanmh** [comment]
> امکانش هست ویندوز در یه جایی مشکلی براش اومده باشه( مثلا چه میدونم از اون مشکلات مزخرف که بعضی موقعها خود ویندوز هم نمیتونه دیاگنوز بکنه) بنظرت ویندوز عوض کنم؟!!!

خودم وقتی اروری ببینم، اول تحقیق میکنم و بعد برطرفش میکنم. هرگز اجازه نمیدم ارور ها روی هم انباشته شه و کار به تعویض ویندوز بکشه.
درواقع هرگز نیاز نشد که ویندوز عوض کنم.
وقتی سیستم‌عامل یه خطا میده یعنی ۱۰۰ درصد مشکل وجود داره، ارور ها بی‌دلیل نمیان.

پس کل فولدر برنامه رو پاک کن، البته اگه فایل WinDivert پاک نشد اول باید rename ش کنی و بعد از restart سیستم پاکش کنی.
و آخرین نسخه رو دوباره تمیز extract کن، اگه باز اون ارور اومد باید برطرفش کنی.
همه Runtime ها رو نصب کن.
از c++ گرفته تا .net 6 و هرچیز دیگه‌ای مثل codec های صدا و تصویر.
خود ویندوز رو بروزرسانی کن.
و اگه باز برطرف نشد، اون dll ها رو بریز داخل system32 و system32/syswow64 داخل هر دو فولدر بریز.
و باز اگه مشکل حل نشد دیگه راهی جز تعویض ویندوز نیست.

همه اینایی که گفتم بخاطر حل مشکل ارور بوده، دلیل نمیشه حتی بعد تعویض ویندوز برنامه بتونه یوتیوب رو باز کنه.
چون اون ارور میتونه هیچ ارتباطی به باز نشدن یوتیوب نداشته باشه یا شایدم داشته باشه. واقعا معلوم نیست.

**Comment by ehsan-am** [comment]
بله باید تو اون فولدرها میریختم بگزار روی سر در گمی من، من الان مثل یه معتاد به موادم 48 ساعته یوتیوب نرفتم تا این حدم معتادم به yt!  بله وقتی پراکسی ست هست باز میشن اون سایتایی که فیلتر نیستن

**Comment by msasanmh** [comment]
> بله باید تو اون فولدرها میریختم بگزار روی سر در گمی من، من الان مثل یه معتاد به موادم 48 ساعته یوتیوب نرفتم تا این حدم معتادم به yt!  بله وقتی پراکسی ست هست باز میشن اون سایتایی که فیلتر نیستن
> 

پس به احتمال زیاد یه تغییری توی نت ایجاد کردن که این مشکل پیش اومده و توی هر منطقه میتونه متفاوت باشه.
اگه بتونی با نت همراه اول یا ایرانسل تست کنی میتونی مطمئن شی که اشکال از مخابرات هست یا نه.
اگه برنامه مشکل پیدا کرده باشه نباید روی ایرانسل یا همراه اول هم جواب بده.

**Comment by ehsan-am** [comment]
بله. این c++ اوکین و اینکه پریروز چندتا مجدد نصب کردم.تاصیر داره تو این ارور؟!
![22](https://github.com/msasanmh/SecureDNSClient/assets/146124400/3b900b4e-71c3-423b-878b-3ebe9ec50947)

**Comment by ehsan-am** [comment]
اوکی خیلی ممنون از جواب .برم رو اونا امتحان کنم

**Comment by msasanmh** [comment]
> بله. این c++ اوکین و اینکه پریروز چندتا مجدد نصب کردم.تاثیر داره تو این ارور؟!
> ![22](https://github.com/msasanmh/SecureDNSClient/assets/146124400/3b900b4e-71c3-423b-878b-3ebe9ec50947)
> 

آره یه جا نوشته بود c++ میتونه به اون ارور ربط داشته باشه.
اگه restore point داری میتونی سیستم رو برگردونی به اون تاریخی که مشکلی وجود نداشته.
همیشه قبل از انجام کارهای مهم مثل نصب درایورها یه restore point بگیر

**Comment by ehsan-am** [comment]
نمیدونم والا یعنی این ارور رو وقتی تو سطح نت سرچ میکنم ( the ssl connection could not be) چیز خاصی نمیاد.همش راجع به ارورهای ssl گوگل کرومه و نه این مشکل بخصوص من.رستور پوینت هم نگرفتم

**Comment by ehsan-am** [comment]
سرتیفیکیت ssl و این جور چیزا میاد

**Comment by msasanmh** [comment]
> نمیدونم والا یعنی این ارور رو وقتی تو سطح نت سرچ میکنم ( the ssl connection could not be) چیز خاصی نمیاد.همش راجع به ارورهای ssl گوگل کرومه و نه این مشکل بخصوص من.رستور پوینت هم نگرفتم
> 

میدونم، اصلا این ارور رو نباید سرچ کنی، میتونه هزاران دلیل داشته باشه، اما در مورد این برنامه، این ارور یعنی عدم موفقیت در دور زدن سیستم dpi

**Comment by ehsan-am** [comment]
یه چیز هم یادم رفت بگم که من dnsclient رو چند بار پاک کردم و ریختم( ورژن فعلی و قبلی) افاقه نکرد پاک کردنش هم آسون بود و نیازی نبود اون فایل WinDivert رو کاری بکنم.راحت پاک شد و 2باره از وینرار اکسترکت کردکم رو دسکتاپ

**Comment by ehsan-am** [comment]
من بنظرم رو یه دیوایس دیگه امتحان کنم که کار میگنه یا نه

**Comment by msasanmh** [comment]
> یه چیز هم یادم رفت بگم که من dnsclient رو چند بار پاک کردم و ریختم( ورژن فعلی و قبلی) افاقه نکرد پاک کردنش هم آسون بود و نیازی نبود اون فایل WinDivert رو کاری بکنم.راحت پاک شد و 2باره از وینرار اکسترکت کردکم رو دسکتاپ

فعلا همون با نت های همراه تست کن تا مشخص شه مشکل از برنامه است یا اینترنت.

**Comment by ehsan-am** [comment]
بله خیلی خیلی ممنون از وقتت فعلا.

**Comment by ehsan-am** [comment]
مرسی که وقتت رو میزاری برای راهنمایی من.این چن وقته به دلایلی سیستمم آنتی ویروس نداشت.یه 360 SECURITY ریختم و یه اسکن گرفتم.اینها رو پیدا کرد.از dnsclient تروجان تشخیص داد.dnscrypt-proxy و dnslookup و چن تای دیگه.این پایین عکسشو گزاشتم. 2 تا هم تروجان در system 32 پیدا کرد که آنتی ویروس سریع حذف کرد.لطفا خودت ببین و اینکه برنامه همون ارور قبلی رو میده.

https://github.com/msasanmh/SecureDNSClient/assets/146124400/46c99c7a-b02e-439a-96a2-d4c38f20a1db

**Comment by msasanmh** [comment]
> مرسی که وقتت رو میزاری برای راهنمایی من.این چن وقته به دلایلی سیستمم آنتی ویروس نداشت.یه 360 SECURITY ریختم و یه اسکن گرفتم.اینها رو پیدا کرد.از dnsclient تروجان تشخیص داد.dnscrypt-proxy و dnslookup و چن تای دیگه.این پایین عکسشو گزاشتم. 2 تا هم تروجان در system 32 پیدا کرد که آنتی ویروس سریع حذف کرد.لطفا خودت ببین و اینکه برنامه همون ارور قبلی رو میده.
> 
> https://github.com/msasanmh/SecureDNSClient/assets/146124400/46c99c7a-b02e-439a-96a2-d4c38f20a1db
> 
> 

اینها ویروس نیستن، آلارم false positive هستن.
مثلا dnscrypt-proxy در نسخه‌های قبلیش اینطور نبود، توی آخرین ورژن بعضی از آنتی‌ویروس‌ها بهش حساس شدن.
مثلا برای این شخص هم پیش اومد:
https://github.com/msasanmh/SecureDNSClient/issues/77

و برنامه‌های dnscrypt-proxy و dnslookup و dnsproxy و GoodbyeDPI رو من نمی‌نویسم، درنتیجه در این مورد هیچ کاری از دستم بر نمیاد.

میتونید به پیج‌های خودشون issue بزنید تا موضوع رو بررسی کنن.

Dnscrypt-proxy:
https://github.com/DNSCrypt/dnscrypt-proxy

Dnslookup:
https://github.com/ameshkov/dnslookup

درهرصورت همه این برنامه‌ها متن باز هستن و من همه کد هاشون رو مطالعه کردم و مطمئنم که آلارم چیزی جز false positive نیست.

**Comment by ehsan-am** [comment]
با ایرانسل کانکت میشه وصل کردم به سیستمم،وصل میشه

**Comment by ehsan-am** [comment]
به نظرت چه کار باید کنم؟

**Comment by msasanmh** [comment]
> به نظرت چه کار باید کنم؟
> 

اینجور مواقع به طرف میگم متاسفانه برنامه با ISP شما سازگار نیست.
چون هیچ چیزی باقی نمیمونه که بخوام به طرف پیشنهاد بدم تا مشکلش حل شه.
الان برای شما با ایرانسل کار میکنه اما با مخابرات نه یعنی همون ناسازگاری برنامه.
متاسفم، هیچ چیز دیگه‌ای به ذهنم نمی‌رسه.

**Comment by ehsan-am** [comment]
فدات مرسی از برنامه باحالالت .من هر جور شده 2باره از این dnsclient استفاده میکنم!

**Comment by msasanmh** [comment]
> فدات مرسی از برنامه باحالت.من هر جور شده 2باره از این dnsclient استفاده میکنم!

روش جدید در ورژن 2.8.1 اضافه شد.
میتونی طبق این آموزش عمل کنی:
https://github.com/msasanmh/SecureDNSClient/blob/main/Help/How%20to%20use%20SSL%20Decryption_Farsi.mp4

**Comment by ehsan-am** [comment]
سلام مجدد. ممنون برای همه کارهایی که میکنی. ورژن 2.8.5 رو استفاده میکنم. کامل وصل میشه ولی مشکل از طرف منه که گوگل کروم این ویندوز رو میاره
![ScreenShot_20240116200404](https://github.com/msasanmh/SecureDNSClient/assets/146124400/0e30f54e-43c4-49e4-8fc6-e3cb59a7f09a)
اون دو تیک SSL و Change SNI هم زدم.

**Comment by msasanmh** [comment]
> سلام مجدد. ممنون برای همه کارهایی که میکنی. ورژن 2.8.5 رو استفاده میکنم. کامل وصل میشه ولی مشکل از طرف منه که گوگل کروم این ویندوز رو میاره
> ![ScreenShot_20240116200404](https://github.com/msasanmh/SecureDNSClient/assets/146124400/0e30f54e-43c4-49e4-8fc6-e3cb59a7f09a)
> اون دو تیک SSL و Change SNI هم زدم.

اول برنامه رو بطور کامل دیسکانکت کنید.
دوم. به تنظیمات working mode برید و بروی uninstall certificate کلیک کنید تا سرتیفیکیت بطور کامل پاک بشه.
سوم. به تب share برگردید و دوباره گزینه SSL Decryption رو بزنید و پیام نصب سرتیفیکیتی که میاد رو تایید کنید، یعنی بروی yes کلیک کنید.
چهارم. گزینه Change SNI رو هم اگر تیک نداره تیک بزنید.
پنجم. از ابتدا برنامه رو کانکت کنید، یعنی اول DNS آنلاین و SET بشه و بعد پراکسی رو روشن و SET کنید.

اگر مرورگرها باز هستن، باید بسته بشن و دوباره باز بشن.

این مشکل شما به احتمال زیاد بخاطر نصب نکردن Root Certificate پیش اومده.
اگه طبق روشی که گفتم پیش بری قطعا مشکلی نخواهی داشت.

**Comment by ehsan-am** [comment]
وصل نشد

**Comment by msasanmh** [comment]
> وصل نشد
> 

وقتی توی تب چهارم روی Check DPI Bypass کلیک میکنی چی می‌نویسه؟

**Comment by ehsan-am** [comment]
Check DPI BypassCheck DPI Bypass رو نمیزنم. استارت و ست پراکسی میزنم که خب ظاهرا برنامه وصل میشه و این رو نشون میده
![ScreenShot_20240119140239](https://github.com/msasanmh/SecureDNSClient/assets/146124400/826e484c-9780-4bf8-916d-c12ba018dc4a)
مشکل من همونه که قبلا خدممتت گفتم و هر جا که باز میکنم اون صفحه سرتیفیکیت (your connection is not private)تو گوگل کروم باز میشه

**Comment by msasanmh** [comment]
> Check DPI BypassCheck DPI Bypass رو نمیزنم. استارت و ست پراکسی میزنم که خب ظاهرا برنامه وصل میشه و این رو نشون میده
> ![ScreenShot_20240119140239](https://github.com/msasanmh/SecureDNSClient/assets/146124400/826e484c-9780-4bf8-916d-c12ba018dc4a)
> مشکل من همونه که قبلا خدممتت گفتم و هر جا که باز میکنم اون صفحه سرتیفیکیت (your connection is not private)تو گوگل کروم باز میشه 

میخوام در انتها خود Check DPI Bypass رو بزنی تا ببینم خود برنامه میتونه یوتیوب رو باز کنه یا نه.
اگه خودش بتونه اونوقت مرورگر رو هم میشه یه کاریش کرد

**Comment by ehsan-am** [comment]
باید قبل از Check DPI Bypass، GoodByeDPI رو تو تب پنجم فعال کنم؟

**Comment by ehsan-am** [comment]
Check DPI Bypass 
![check](https://github.com/msasanmh/SecureDNSClient/assets/146124400/c94fc4aa-3f1e-47d3-abcb-6d9f4d4e5589)

**Comment by msasanmh** [comment]
> باید قبل از Check DPI Bypass، GoodByeDPI رو تو تب پنجم فعال کنم؟

به گودبای dpi ربطی نداره، اون فقط چک میکنه برنامه میتونه یوتیوب رو باز کنه یا نه

**Comment by msasanmh** [comment]
> Check DPI Bypass 
> ![check](https://github.com/msasanmh/SecureDNSClient/assets/146124400/c94fc4aa-3f1e-47d3-abcb-6d9f4d4e5589)
> 

خب برنامه گفته یوتیوب باز شده، الان یه سری قوانین بهت میدم و بهت میگم کجا بذاریش.

**Comment by msasanmh** [comment]
اول پراکسی رو Stop کن و برو به:
Settings -> Share -> SSL Decryption
چک Enable Fake SNI رو فعال کن و روی Edit Fake SNI Rules کلیک کن.
یه فایل متنی باز میشه. محتویات پایین رو داخلش کپی کن:

```
youtube.com|google.com
ytimg.com|google.com
*.ytimg.com|google.com
ggpht.com|google.com
*.ggpht.com|*.googleusercontent.com
googleapis.com|google.com
*.googleapis.com|google.com
*.googlevideo.com|*.c.docs.google.com
```

حالا فایل رو سیو کن، پراکسی رو روشن کن، مرورگر رو ببند و دوباره باز کن.
و بهم اطلاع بده مرورگر یوتوب رو تونست باز کنه یا نه
@ehsan-am

**Comment by ehsan-am** [comment]
یوتیوب رو باز نمیکنه، ولی گوگل و سایتهایی دیگه رو بدون نشون دادن این پنجره(your connection is not private باز میکنه.

**Comment by msasanmh** [comment]
> یوتیوب رو باز نمیکنه، ولی گوگل و سایتهایی دیگه رو بدون نشون دادن این پنجره(your connection is not private باز میکنه.

با مرورگرهای دیگه تست کردی؟

**Comment by msasanmh** [comment]
> یوتیوب رو باز نمیکنه، ولی گوگل و سایتهایی دیگه رو بدون نشون دادن این پنجره(your connection is not private باز میکنه.

وقتی یوتیوب رو با مروگر باز میکنی، روی Advance که اون پایین نوشته کلیک کن و یه گزینه داره مثل continue روی اون کلیک کنی باز میشه

**Comment by ehsan-am** [comment]
وقتت بخیر من فکر کنم هر چی هست این سرتیفیکیتها مشکل باشه
![1](https://github.com/msasanmh/SecureDNSClient/assets/146124400/455f11a5-7e9f-4946-8424-bccf8db2266d)
 و برنامه نتونسته منطبق کنه با بروزر و روی هر ایتی میزنم همون پنجره ارور سرتیفکیت میاد (باز دقیق نمیدونم) اینا رو از internet properties,content و پنجره certificates گرفتم.  مثلا روی اون نوشته این سرتیفیکیت امضای دیجیتال نامعتبر  داره. لطفا یه نگاه میندازی؟! مرسی
![2](https://github.com/msasanmh/SecureDNSClient/assets/146124400/e1ddd601-4648-40d3-8fa5-1152f815be89)
![3](https://github.com/msasanmh/SecureDNSClient/assets/146124400/14731a15-0fb6-4d03-86bf-f3d39c08f26d)

**Comment by ehsan-am** [comment]
الان یادم اومد 2 3 ماه پیش  اینا رو از یوتیوب دیدم و ریختم فکر کردم شاید منقضی شده باشه سرتیفیکیت، این فایل رو
![dst](https://github.com/msasanmh/SecureDNSClient/assets/146124400/028aa6e7-a71a-4d2b-8e44-5223e3b7c837)
![dst 2](https://github.com/msasanmh/SecureDNSClient/assets/146124400/61e82738-4d3d-4f1b-bfbb-a08b5bda0731)

**Comment by msasanmh** [comment]
> وقتت بخیر من فکر کنم هر چی هست این سرتیفیکیتها مشکل باشه
> ![1](https://github.com/msasanmh/SecureDNSClient/assets/146124400/455f11a5-7e9f-4946-8424-bccf8db2266d)
>  و برنامه نتونسته منطبق کنه با بروزر و روی هر ایتی میزنم همون پنجره ارور سرتیفکیت میاد (باز دقیق نمیدونم) اینا رو از internet properties,content و پنجره certificates گرفتم.  مثلا روی اون نوشته این سرتیفیکیت امضای دیجیتال نامعتبر  داره. لطفا یه نگاه میندازی؟! مرسی
> ![2](https://github.com/msasanmh/SecureDNSClient/assets/146124400/e1ddd601-4648-40d3-8fa5-1152f815be89)
> ![3](https://github.com/msasanmh/SecureDNSClient/assets/146124400/14731a15-0fb6-4d03-86bf-f3d39c08f26d)
> 

سرتیفیکیت نباید داخل Other people نصب باشه، از اونجا حذفش کن.
درواقع فقط باید داخل Trusted Root Certification Authority نصب باشه که اونم خود برنامه انجام میده.
اگه خودت سرتیفیکیت رو دستی جایی نصب کردی پاکش کن.
فقط باید مثل عکس پایین باشه:
![20240124_015949.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/b1688693-f455-4490-b42b-a2cac2582b2e)

**Comment by ehsan-am** [comment]
گزینه remove برای SecureDNS Client توی other people غیر فعاله و اینکه SecureDNSClient Authotrity( اسکرین شات آخری) توی Trusted ....هست

**Comment by msasanmh** [comment]
> گزینه remove برای SecureDNS Client توی other people غیر فعاله و اینکه SecureDNSClient Authotrity( اسکرین شات آخری) توی Trusted ....هست 

درسته اسکرین شات آخر نشون داده داخل Trusted هست اما اون یکی باعث ایجاد تداخل میشه.
داخل Run اینو تایپ کن:
certmgr.msc
و از پنجره سمت چپ بروی فولدرها کلیک کن، داخل هر فولدر اگه سرتیفیکیت SecureDNSClient رو دیدی پاک کن، یعنی کلیک راست کن و Delete رو انتخاب کن و مطمئن شدی هر چی مربوط به SDC هست پاک شده.
اونوقت بذار خود برنامه یه بار درست سرتیفیکیت رو نصب کنه.

یادت باشه برای اعمال تغییرات مرورگرها باید ری‌استارت بشن.

**Comment by ehsan-am** [comment]
وقتت بخیر عزیز، خواستم 2باره تشکر کنم ازت برای این برنامه محشرت. این چنل یوتیوب منه، از این جور کانتنتها دوست دارم دیگه :) اگه مایل بودی سابسکرایب کن باعث افتخاره!
https://www.youtube.com/@WrestlingF3tish/featured

**Comment by msasanmh** [comment]
> وقتت بخیر عزیز، خواستم 2باره تشکر کنم ازت برای این برنامه محشرت. این چنل یوتیوب منه، از این جور کانتنتها دوست دارم دیگه :) اگه مایل بودی سابسکرایب کن باعث افتخاره!
> https://www.youtube.com/@WrestlingF3tish/featured

ممنون. دو تا سوال برام پیش اومد.
۱. مشکل سرتیفیکیت که داشتی حل شد؟
۲. کانال یوتیوبت منظور از فتیش همون فوت فتیشه، یعنی کشتی‌کج از نوع فتیش یا معمولیه؟ 😁

**Comment by ehsan-am** [comment]
نه اینجا فتیش یعنی شوق و اشتیاق وافر (و شاید غیرمعمولی) برای چیزی که اینجا اون چیز، کشتیه.البته خب پر و پاچه هم تو ویدیو هست😁😁
مشکل سرتیفیکیت هم حل شد وقتی گفتید از certmgr.msc برم و اون SecureDNSClient رو پاک کنم .دمت شما گرم.

**Comment by msasanmh** [comment]
> نه اینجا فتیش یعنی شوق و اشتیاق وافر (و شاید غیرمعمولی) برای چیزی که اینجا اون چیز، کشتیه.البته خب پر و پاچه هم تو ویدیو هست😁😁
> مشکل سرتیفیکیت هم حل شد وقتی گفتید از certmgr.msc برم و اون SecureDNSClient رو پاک کنم .دمت شما گرم.

آها، خب شور و اشتیاق خوبه 😄 حتما ساب می‌کنم. 
و خوشحالم که مشکل سرتیفیکیت هم حل شد 👍

**Comment by ehsan-am** [comment]
مشکل پیش اومد باز هم اینجا مزاحمت میشم. باز هم ممنون
