### ISSUE TITLE
The request was canceled

### ISSUE THREAD

**Issue by zandiarash** [msasanmh/SecureDNSClient#33]
ممنونم از زحماتتون
من تمام مراحل رو انجام دادم اما این خطا رو میده، امکانش هست بررسی بفرمایید و بهم کمک کنین ؟
ویندوز 11
اینترنت فرا ارتباط مبنا

![image](https://github.com/msasanmh/SecureDNSClient/assets/10775073/d6612241-7b9b-4bc3-8678-89775f093af5)

**Comment by msasanmh** [comment]
> ممنونم از زحماتتون
> من تمام مراحل رو انجام دادم اما این خطا رو میده، امکانش هست بررسی بفرمایید و بهم کمک کنین ؟
> ویندوز 11
> اینترنت فرا ارتباط مبنا
> 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/10775073/d6612241-7b9b-4bc3-8678-89775f093af5)
> 

از ویندوز ۷ استفاده می‌کنید؟

**Comment by zandiarash** [comment]
ویندوز 11
اینترنت فرا ارتباط مبنا

**Comment by alidxdydz** [comment]
> ویندوز 11
> اینترنت فرا ارتباط مبنا

@zandiarash 

با مرورگر هم چک میکنید؟
لطفا، این ۴ تا سایتو چک کنید.
varzesh3.com
digikala.com
youtube.com
vimeo.com/76979871

**Comment by alidxdydz** [comment]
> ویندوز 11
> اینترنت فرا ارتباط مبنا

@zandiarash 

با مرورگر هم چک میکنید؟
لطفا، این ۴ تا صفحه رو چک کنید.

https://www.varzesh3.com
https://www.digikala.com
https://youtu.be/InzDjH1-9Ns
https://vimeo.com/76979871

**Comment by zandiarash** [comment]
آقا درست فرمودین انگار اشکال از اینترنتم بود
الان با مبین نت امتحان کردم اوکی شد
خیلی خیلی ممنونم از زحماتتون
ای کاش تلگرام هم باز میکرد😅  (با کمال پررویی)
![image](https://github.com/msasanmh/SecureDNSClient/assets/10775073/c84d7f33-ca6d-4e70-ad05-8d7ed64d811b)

**Comment by alidxdydz** [comment]
> آقا درست فرمودین انگار اشکال از اینترنتم بود
> الان با مبین نت امتحان کردم اوکی شد
> خیلی خیلی ممنونم از زحماتتون
> ای کاش تلگرام هم باز میکرد😅  (با کمال پررویی)
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/10775073/c84d7f33-ca6d-4e70-ad05-8d7ed64d811b)
> 

نسخه جدیدتر 2.1.6 هم منتشر شده.
متاسفانه IP های تلگرام فیلتر هستن و حتما به سرور نیاز هست.
