### ISSUE TITLE
Google Play

### ISSUE THREAD

**Issue by aliultra** [msasanmh/SecureDNSClient#35]
is it possible to add Google Play store?

**Comment by msasanmh** [comment]
> is it possible to add Google Play store?

I set the SDC proxy address on my android, I could open YouTube without any problems, and then I tried to update my apps on Play store, but download speed was slow, I'm trying to fix it.
I guess it takes time though.

**Comment by aliultra** [comment]
Nice ;) hope thing turns out fine.

just one more thing... should I select my Hotspot adaptor (in set DNS section) for share to other devices?

**Comment by msasanmh** [comment]
> Nice ;) hope thing turns out fine.
> 
> just one more thing... should I select my Hotspot adaptor (in set DNS section) to share with other devices?  

Set DNS on your active adapter, then use proxy to share. (On Share + DPI Bypass tab)

**Comment by aliultra** [comment]
I got. thanks so much❤️
