### ISSUE TITLE
dev

### ISSUE THREAD

**Issue by githubdev7878** [msasanmh/SecureDNSClient#36]
سلام خسته نباشید
سازنده نرم افزار خودتون هستید ؟ یا نه مال شرکت مایکروسافت هست؟
چون بحث پیش اومد با کسی و گفتش نه این نرم افزار مال شما نیست و مال شرکت مایکروسافت هست

**Comment by msasanmh** [comment]
> سلام خسته نباشید
> سازنده نرم افزار خودتون هستید ؟ یا نه مال شرکت مایکروسافت هست؟
> چون بحث پیش اومد با کسی و گفتش نه این نرم افزار مال شما نیست و مال شرکت مایکروسافت هست

سلام، سازنده برنامه خودم هستم.
