### ISSUE TITLE
security

### ISSUE THREAD

**Issue by githubdev7878** [msasanmh/SecureDNSClient#37]
خسته نباشید امنیت نرم افزار چقدر هستش ؟ به dns هایی که وصل میشه میشه ادم اطمینان کرد یا نه امنیت نداره ؟
چون اکثر پروکسی و vpn ها رایگان امنیتشون کمه

**Comment by githubdev7878** [comment]
و تشکر میکنم از نرم افزار خوبتون که توی این وضعیت بد قطعی پروکسی ها . کار میکنه

**Comment by msasanmh** [comment]
>  خسته نباشید امنیت نرم افزار چقدر هستش ؟ به dns هایی که وصل میشه میشه ادم اطمینان کرد یا نه امنیت نداره ؟
> چون اکثر پروکسی و vpn ها رایگان امنیتشون کمه

همه سرورها public هستن و معروف تا نیمه معروف.
در برنامه هرگز از سرورهای شخصی، ایرانی یا چینی استفاده نمی‌کنم. 
درواقع حتی warning هم گذاشتم تا اگه یوزر قصد استفاده از سرورهای ناامن رو داشته باشه بهش هشدار بده.
این برنامه رو برای بالا بردن امنیت ساختم نه برعکس، خیال تون راحت.
