### ISSUE TITLE
Unbound

### ISSUE THREAD

**Issue by alidxdydz** [msasanmh/SecureDNSClient#4]
سلام مهندس جان.
با این Unbound میشه سمت سرور کاری کرد؟

[YouTube 1](https://youtu.be/XbbziN_H71U)
[YouTube 2](https://youtu.be/DOJ39lyx6Js)
[Unbound - GitHub](https://github.com/NLnetLabs/unbound)
[Unbound - Docs](https://unbound.docs.nlnetlabs.nl/en/latest/)
[Unbound - Official Webpage](https://nlnetlabs.nl/projects/unbound)

**Comment by msasanmh** [comment]
با Unbound میتونید روی سرور شخصی خودتون یک سرور DNS ایجاد کنید که البته راه‌های آسون‌تر دیگه‌ای هم هست. اما باید بدونید فقط یه سرور DNS انکریپت شده به شما میده و خودش به تنهایی نمیتونه یوتیوب رو باز کنه یا SNI ها رو فرگمنت کنه.

**Comment by alidxdydz** [comment]
بله متوجه هستم.
من سوال قبلی من بخاطر اینه که میخوام از قسمت DNS و DOH کلاینت PowerTunnel استفاده بکنم.

https://github.com/GFW-knocker/gfw_resist_tls_proxy/discussions/73#discussioncomment-5763695

**Comment by msasanmh** [comment]
منظورت اینه که نیاز به یه سرور DoH داری.
فقط یه پیشنهاد میتونم بدم اونم اینه که سرور شخصی خودت رو داخل کلودفلر ورکر رایگان ایجاد کنی. میتونی از این اسکریپت استفاده کنی:
https://github.com/msasanmh/cf-workers-dns-over-https
و واقعا معذرت میخوام که نمیتونم سرورهای داخل برنامه رو بهت بدم، مطمئنم درک میکنی 🙏

**Comment by alidxdydz** [comment]
بله. دقیقا منظورم همین بود. کاملا درک میکنم که چرا نباید عمومی بشن و همین گزینه custom یا worker خیلی بکارم میان.
فقط یه سوال آخر در ارتباط با اسکنر شما. با 2 تا ISP اسکن کردم. تو هر دو میشد DOH های یکسانی دید ولی پایین ترین latency رو ندارن و مثلا سومین گزینه هستن. ولی ندیدم بشه از نتیجه اسکنر انتخابی کرد که به کدوم یکی وصل شد. احتمالا پایین ترین latency رو انتخاب میکنه که با عوض کردن ISP، به مشکل میخوره

**Comment by msasanmh** [comment]
برنامه خودش بطور اتوماتیک به حداکثر ۱۰ تا از سریع‌ترین سرورها وصل میشه.
وقتی ISP تغییر کنه سرورها بهتره دوباره چک بشن.
اما معمولا سرورهایی که در ISP های مختلف فیلتر نیستن بین همون ۱۰ تا وجود دارن

**Comment by alidxdydz** [comment]
ممنون از توضیحتون
