### ISSUE TITLE
سایت های مهم و پربازدید

### ISSUE THREAD

**Issue by godofwar2006** [msasanmh/SecureDNSClient#40]
سلام خسته نباشی! 
سایت های مهمی چون Spotify , Twitch , Twitter و... نمیشه باز کرد! اگر این مشکل حل بشه واقعا کمک بزرگی هست. البته فعلا یوتوب خیلی راحت بالا میاد بدون هیچ مشکلی.

**Comment by Misfit-Ha** [comment]
تنظیمات مختلفو امتحان کن
من با اینترنت مخابرات وقتی bypass dpi رو روی medium میزارم بدون set proxy، یوتوب و تویتچ و تویتر و ردیت باز شدن (ولی ردیت ویدیو ها پخش نمیشه) اسپاتیفای هم توی مخابرات فیلتر نیست

**Comment by msasanmh** [comment]
> سلام خسته نباشی! 
> سایت های مهمی چون Spotify , Twitch , Twitter و... نمیشه باز کرد! اگر این مشکل حل بشه واقعا کمک بزرگی هست. البته فعلا یوتوب خیلی راحت بالا میاد بدون هیچ مشکلی.
> 

دارم همه تلاشم رو می‌کنم. فعلا تنظیمات مختلف رو امتحان کنید.

**Comment by godofwar2006** [comment]
> تنظیمات مختلفو امتحان کن من با اینترنت مخابرات وقتی bypass dpi رو روی medium میزارم بدون set proxy، یوتوب و تویتچ و تویتر و ردیت باز شدن اسپاتیفای هم توی مخابرات فیلتر نیست

دقیقا من هم همین ستاپ رو دارم! اما فقط یوتوب باز میشه برام. مد های مختلف رو هم امتحان کردم نتونستم موفق بشم این موضوع رو حل کنم.

**Comment by godofwar2006** [comment]
> > سلام خسته نباشی!
> > سایت های مهمی چون Spotify , Twitch , Twitter و... نمیشه باز کرد! اگر این مشکل حل بشه واقعا کمک بزرگی هست. البته فعلا یوتوب خیلی راحت بالا میاد بدون هیچ مشکلی.
> 
> دارم همه تلاشم رو می‌کنم. فعلا تنظیمات مختلف رو امتحان کنید.

تشکر از تلاش شما. 
برای همراه اول کلا کار نکرد برای من. (تمام مد ها رو امتحان کردم و   SSL مختلفی گذاشتم اما همچنان مشکل به قدرت خودش پابرجا بود.)

**Comment by msasanmh** [comment]
> > > سلام خسته نباشی!
> > > سایت های مهمی چون Spotify , Twitch , Twitter و... نمیشه باز کرد! اگر این مشکل حل بشه واقعا کمک بزرگی هست. البته فعلا یوتوب خیلی راحت بالا میاد بدون هیچ مشکلی.
> > 
> > دارم همه تلاشم رو می‌کنم. فعلا تنظیمات مختلف رو امتحان کنید.
> 
> تشکر از تلاش شما. 
> برای همراه اول کلا کار نکرد برای من. (تمام مد ها رو امتحان کردم و   SSL مختلفی گذاشتم اما همچنان مشکل به قدرت خودش پابرجا بود.)

برای همراه اول من GoodbyeDPI رو غیرفعال کردم و از پراکسی استفاده کردم با تنظیمات 60 - 2 - 60 جواب داد.
این GoodbyeDPI بروی همراه اول کار نمی‌کنه از پراکسی استفاده کن.

**Comment by godofwar2006** [comment]
> 

من تونستم بالاخره با تنظیمات پیشفرض و تنظیم کردن Fragment Delay به 10 میلی ثانیه ، یوتوب رو در مدت زمان 20 ثانیه باز کنم!
خیلی جای بهتر شدن داره. فعلا برای مخابرات خیلی خوب کار میکنه.
