### ISSUE TITLE
Select network interface 

### ISSUE THREAD

**Issue by fubax** [msasanmh/SecureDNSClient#41]
درود
در ویندوز 11 ؛ قسمت select network interface لیست دراپ دان کانکشن های شبکه رو نشون نمیده و فقط یه آیتم به نام wifi داره. به همین دلیل گزینه set/unset در این صفحه disable هستش
لطفا راهنمایی بفرمایید
![DNS](https://github.com/msasanmh/SecureDNSClient/assets/21304689/78646ecc-f11b-4cfd-886c-ffb2b2554804)

**Comment by msasanmh** [comment]
> درود
> در ویندوز 11 ؛ قسمت select network interface لیست دراپ دان کانکشن های شبکه رو نشون نمیده و فقط یه آیتم به نام wifi داره. به همین دلیل گزینه set/unset در این صفحه disable هستش
> لطفا راهنمایی بفرمایید
> ![DNS](https://github.com/msasanmh/SecureDNSClient/assets/21304689/78646ecc-f11b-4cfd-886c-ffb2b2554804)
> 
> 

برنامه فقط کانکشن‌های فعال رو نشون میده، الان نشون داده که شما یه کانکشن به اسم wifi دارید.
برای اینکه دکمه set فعال بشه باید بمونید تا dns آنلاین بشه.

**Comment by fubax** [comment]
تشکر که وقت میزارید و جواب میدید
حق با شما بود مقداری طول میکشه تا این گزینه فعال بشه
موردی که الان دارم اینه که با نت مخابر ات یوتیوب فقط تکست باز میشه و عناوین صفحه بدون تصویر هستن هم چنین هیچ کدوم از ویدیو ها پلی نمیشن (در حالت غیرفعال بودن DPI(
توضیح اینکه DPI رو هم وقتی فعال میکنم کلا نت قطع میشه و حتی گوگل هم باز نمیشه
اگه تنظیمات خاصی برای نت مخا برات داره لطفا راهنمایی بفرمایید
بازم ممنون که کمک میکنید

**Comment by alidxdydz** [comment]
> تشکر که وقت میزارید و جواب میدید
> حق با شما بود مقداری طول میکشه تا این گزینه فعال بشه
> موردی که الان دارم اینه که با نت مخابر ات یوتیوب فقط تکست باز میشه و عناوین صفحه بدون تصویر هستن هم چنین هیچ کدوم از ویدیو ها پلی نمیشن (در حالت غیرفعال بودن DPI(
> توضیح اینکه DPI رو هم وقتی فعال میکنم کلا نت قطع میشه و حتی گوگل هم باز نمیشه
> اگه تنظیمات خاصی برای نت مخا برات داره لطفا راهنمایی بفرمایید
> بازم ممنون که کمک میکنید 
> 

احتمالا فقط استفاده روش دور زدن DPI داخل تب Proxy کافی باشه.
پس GoodbyeDPI رو خاموش کنید و تنظیمات پراکسی رو روی "اولی 60 دومی 1 سومی 60" قرار بدین.
در ضمن امکانش هست که نتیجه log با مرورگر متفاوت باشه. پس حتما با مرورگر صفحه یوتیوب رو باز کنید.

اگر فقط روش موجود در پراکسی کافی نبود، هر دو روش رو فعال کنید و چک کنید. برا GoodbyeDPI حالتهای mode 5 و mode 6 و mode medium رو کنترل کنید (بهمراه روش پراکسی و حتی بدون پراکسی)
