### ISSUE TITLE
Command line integration

### ISSUE THREAD

**Issue by CyberSirJava** [msasanmh/SecureDNSClient#42]
سلام دوست من، خیلی ممنونم بابت این برنامه چون واقعا گل کاشتی و دسترسی یوتیوبی که به ناحق فیلتر شده رو محیا کردی. از اونجایی که من خیلی زیاد از این برنامه استفاده میکنم، نیاز دارم که هر دفعه تو استارت آپ ویندوز به صورت دستی بازش کنم. 2 پیشنهاد دارم که در عین سادگی آپشن های خفنی هستن.
1. کنترل با کامند لاین
مطمئنم برنامه های قابل اجرای (exe) زیادی رو دیدی که با Argument میشه بهشون دستور داد و هنگام اجرا بهشون پارامتر اضافه کرد برای کار های خاص. میشه برای اتوماسیون از Batch Script استفاده کرد که خیلی به درد بخور هستش.
2. تنظیمات استارت آپ
اینکه برنامه موقع روشن شدن کامپیوتر بالا بیاد، به طور خودکار وصل بشه و Minimize شه و ... .
در آخر باز هم ازت تشکر میکنم برای این برنامه فوق العاده که به طور رایگان در اختیارمون قرار دادی :)

**Comment by msasanmh** [comment]
سلام، خوشحالم که برنامه به کارت اومد، گذاشتن استارت آپ توی to-do list من هست، فقط قبلش باید یه سری کارها رو انجام بدم و بعد میرسم به استارت آپ.
