### ISSUE TITLE
انتخاب DNS

### ISSUE THREAD

**Issue by Mshian** [msasanmh/SecureDNSClient#45]
سلام و ارادت و دست مریزاد
مرسی بابت این نرم افزار عالی
یه سری از نرم افزارهای وی پی ان که در حالت عادی دیگه وصل نمیشدن وقتی به secure dns وصل میشم، دوباره وصل میشن. 
عالی
فقط یه سوالی. 
چطوری میتونم متوجه بشم که به کدوم dns وصل شده یا انتخاب کنم که از بین dnsهای قابل اتصال به کدوم وصل بشم؟

پ.ن: تغییرات آخرین نسخه هم واقعا کاربردیه. ندیده بودم. داشتم ورژن 2.0 رو استفاده میکردم تا امروز. الان دیدم که ورژن جدید رو دادین

**Comment by msasanmh** [comment]
> سلام و ارادت و دست مریزاد
> مرسی بابت این نرم افزار عالی
> یه سری از نرم افزارهای وی پی ان که در حالت عادی دیگه وصل نمیشدن وقتی به secure dns وصل میشم، دوباره وصل میشن. 
> عالی
> فقط یه سوالی. 
> چطوری میتونم متوجه بشم که به کدوم dns وصل شده یا انتخاب کنم که از بین dnsهای قابل اتصال به کدوم وصل بشم؟
> 
> 
> پ.ن: تغییرات آخرین نسخه هم واقعا کاربردیه. ندیده بودم. داشتم ورژن 2.0 رو استفاده میکردم تا امروز. الان دیدم که ورژن جدید رو دادین 

سلام، ممنون.
برنامه خودش به سریعترین dns ای که پیدا کنه وصل میشه.
قابلیت انتخاب سرور متاسفانه وجود نداره چون اونوقت سرورها لو میرن و فیلتر میشن.

**Comment by msasanmh** [comment]
> یه مساله ای که فراموش کردم بگم این بود که توی گزینه های 
> view working servers 
> edit custom servers 
> رو که میزنم، یه فایل نوتپد باز میکنه ولی خالیه فایل و چیزی توش ننوشته. 
> باز هم ممنون

قسمت 
Edit custom servers 
جایی که شما سرورهای شخصی خودتون رو قرار میدید. مثلا اگر چند تا سرور دارید در هر خط یک سرور وارد میکنید و فایل رو سیو میکنید.
و اگه در قسمت Check گزینه
Use custom servers 
رو انتخاب کنید، برنامه بجای سرورهای داخلی سرورهای شما رو اسکن میکنه، و هر کدوم که کار کنن رو داخل فایل
View working serves 
قرار میده.
