### ISSUE TITLE
سیو کردن  dns 

### ISSUE THREAD

**Issue by xplatformx** [msasanmh/SecureDNSClient#46]
یه قابلیتی اضافه کن که  dns  های اسکن شده رو بشه سیو کرد و برای دفعات بعدی بشه ایمپورت کنیم و استفاده کنیم بجای اسکن کردن دوباره . چون هر بار اسکن کردن تکراری وقت گیره .

**Comment by msasanmh** [comment]
> یه قابلیتی اضافه کن که  dns  های اسکن شده رو بشه سیو کرد و برای دفعات بعدی بشه ایمپورت کنیم و استفاده کنیم بجای اسکن کردن دوباره . چون هر بار اسکن کردن تکراری وقت گیره .

باید یه راهی پیدا کنم بدون اینکه سرورها لو برن این کار انجام بشه، چون اگه لو برن فیلتر میشن.

و اینم بگم با توجه به وضعیت بد اینترنت ایران، سروری که امروز برای شما کار میکنه ممکنه فردا کار نکنه و یا برعکس. 

و اینکه نیاز نیست بمونید تا برنامه اسکن رو تا آخر انجام بده، همینکه چندتا سرور پیدا کرد میتونید کنسلش کنید و به همونا کانکت بشید.

**Comment by msasanmh** [comment]
انجام شد.

**Comment by xplatformx** [comment]
دمت گرم
