### ISSUE TITLE
برای لینوکس چطور؟

### ISSUE THREAD

**Issue by realBombshock** [msasanmh/SecureDNSClient#47]
خیلی خوب داره کار میکنه ممنون
 اگه بتونی برای لینوکس هم بسازیش خیلی خوب میشه چون با لینوکس هم کار میکنم

**Comment by alidxdydz** [comment]
همه کلاینتهایی که در این GUI گردآوردی شده مبتنی بر ویندوز هستن.
برای پورت شدن این GUI به لینوکس ابتدا باید دولوپرهای کلاینت های مختلف، اونا رو بر روی لینوکس بازنویسی کنن.

**Comment by mfat** [comment]
لطفا برای لینوکس هم بساز با PyQT آسونه

**Comment by msasanmh** [comment]
> لطفا برای لینوکس هم بساز با PyQT آسونه

ای کاش امکانات داشتم، حداقل یه کامپیوتر دیگه، روش سیستم‌عامل‌های مختلف میذاشتم تا بتونم تست کنم. متاسفانه فقط یه PC دارم که main board و cpu ش برای ۲۰ سال پیشه و کلی محدودیت دیگه.
افسوس.
