### ISSUE TITLE
Not working with android TV

### ISSUE THREAD

**Issue by aliultra** [msasanmh/SecureDNSClient#48]
not working on android tv YouTube when sharing... it just downloads the thumbnail of videos. what to do ?

**Comment by msasanmh** [comment]
> not working on android tv YouTube when sharing... it just downloads the thumbnail of videos. what to do ?

Your android TV must support http proxy, you can't open YouTube by just setting a dns.
I don't have one so I can't be helpful on this. But if you're using http proxy you need to adjust dpi bypass variables.

**Comment by aliultra** [comment]
Ik. I'm using http proxy. it works with my android phone but not working with android tv 😢 thanks btw.

**Comment by msasanmh** [comment]
> Ik. I'm using http proxy. it works with my android phone but not working with android tv 😢 thanks btw.

Hmm, I'm guessing your phone can handle doh by itself but the android TV can't. 
If that's the issue the next version of SDC should work on your TV, because I'm adding direct support of DoH on HTTP Proxy.
