### ISSUE TITLE
DO NOT USE THIS SERVER

### ISSUE THREAD

**Issue by reykins** [msasanmh/SecureDNSClient#49]
سلام وقتی دی ان اس کاستوم Shecan رو چک میکنم اخطار DO NOT USE THIS SERVER میده حقیقتش نگران شدم، دلیلش چیه؟

**Comment by 002amir78** [comment]
از بین ایرانی ها فقط به شکن ایراد گرفت
الکترو به نظرم اوکی باشه از این نظر (ادمین های تلگرامش واسه """خ/ا/m/نَََ*ایَ""" ابرو نزاشتن با گیف هایی که میفرستن 😂)

**Comment by msasanmh** [comment]
> از بین ایرانی ها فقط به شکن ایراد گرفت
> الکترو به نظرم اوکی باشه از این نظر (ادمین های تلگرامش واسه """خ/ا/m/نَََ*ایَ""" ابرو نزاشتن با گیف هایی که میفرستن 😂)

حق شونه وقتی از اعتماد مردم سو استفاده میکنن.
براحتی میبینن مردم به چه سرورهایی وصل میشن و اونوقت سرورهاشون رو فیلتر میکنن.
نمیدونم چرا مردم ما اینقدر ساده‌اند.
