### ISSUE TITLE
ترافیک غیر عادی

### ISSUE THREAD

**Issue by AbbasVB** [msasanmh/SecureDNSClient#5]
سلام
این برنامه به خوبی برای من کار کرد ممنون از زحمات شما
ولی زمانی که هیچ برنامه ای از اینترنت استفاده نمی کند ترافیکی در حدود 60 کیلوبایت بر ثانیه ارسال و همین حدود هم دریافت دارد. این ترافیک مربوط به dnsproxy.exe هست.
به نظر شما علت چیست؟

**Comment by msasanmh** [comment]
چون این برنامه یه سرور DNS ایجاد میکنه و به همه درخواست‌های کامپیوتر جواب میده و این قطعا نیاز به رفت و آمد و دیتا داره.
درواقع وقتی شما از این برنامه استفاده نمی‌کنید هم تقریبا به همین مقدار ترافیک رد و بدل میشه فقط شما نمی‌بینیدش چون ویندوز DNS خودش رو جز ترافیک بحساب نمیاره.
این برنامه در حال حاضر دو تا سرور DNS و DoH می‌سازه که در ورژن بعدی کاری میکنم که DoH اختیاری باشه، این باعث میشه که ترافیک شما از ۶۰ کیلوبایت به ۳۰ کیلوبایت کاهش پیدا کنه.

**Comment by AbbasVB** [comment]
احتمالا همین طوره که شما می فرمایید.
من با GlassWire & DU meter چک کردم.

**Comment by msasanmh** [comment]
البته یه مورد دیگه هست که یادم رفت بگم، مربوط میشه به اون قسمتی که نشون میده DNS آنلاین هست یا نه. برنامه هر ۵ ثانیه یه درخواست جهت بررسی آنلاین بودن DNS میفرسته

**Comment by msasanmh** [comment]
برنامه آپدیت شد، مصرف ترافیک کاهش پیدا کرد.
