### ISSUE TITLE
فقط یک وبسایت؟

### ISSUE THREAD

**Issue by BarsamJahanvash** [msasanmh/SecureDNSClient#51]
درود بر شما
امیدوارم حالتون خوب باشد

ابتدا تشکر میکنم ازتون برای این بستری که برای ما فراهم کردید
یک سوال هم داشتم
فقط میشه برای یک وبسایتی که بلاک شده دی ان اس گرفت؟نمیشه چند تا وبسایت باشه؟
مثلا یوتوب و تویچ

**Comment by nonbarbari** [comment]
اگر منظور تون اینه که فیلترینگ چند تا سایت رو رفع کنه
همین کارو میکنه برنامه فقط برای یوتوب ساخته نشده شما باهاش میتونید فیلترینگ تمام سایت هایی که فیلترینگ شون SNI و DNS بیس هست رو دور بزنید به شرطی که IP سالم باشه یعنی یا پشت CDN باشه "مثل ردیت" یا IP با سایت خاصی مثل گوگل یکی باشه مثل مورد یوتوب همچنین امنیت تون رو بالا میبره و دامنه های سرور های پروکسی تون فیلتر نمیشن

اگر منظور تون اینه که برنامه چه سایتی رو میتونه تست کنه داخل لاگ . 
این رو شما میتونید داخل تنظیمات تغییر بدین

**Comment by msasanmh** [comment]
> درود مجدد
> منظور من این هست هم یوتوب رو رفع فیلتر کنه هم تویچ رو
> یا یوتوب و اینستاگرام رو

سلام، بروی یوتیوب فقط تست میزنه، وقتی یوتیوب باز بشه یعنی همه وبسایت‌هایی که براساس sni فیلتر شدن باز میشن.
تویچ باز میشه اما اینستاگرام اینطور نیست چون براساس IP فیلتر شده.
