### ISSUE TITLE
پیغام پورت 443

### ISSUE THREAD

**Issue by sheydooc** [msasanmh/SecureDNSClient#52]
Port 443 is occupied by "vpnserver_x64". You need to resolve the conflict.
سلام وقت بخیر
بعد از پیدا کردن  dns و زدن روی conect  این پیغام رو میده بهم

**Comment by msasanmh** [comment]
> Port 443 is occupied by "vpnserver_x64". You need to resolve the conflict.
> سلام وقت بخیر
> بعد از پیدا کردن  dns و زدن روی conect  این پیغام رو میده بهم

سلام، شما یه برنامه نصب دارید که اسم پراسسش "vpnserver_x64" هستش و پورت ۴۴۳ رو اشغال کرده.
یا باید اون برنامه رو stop کنید یا از task manager اسم پراسس رو پیدا کنید و end task ش کنید.
یا اینکه doh لوکال برنامه SDC رو غیرفعال کنید
از طریق 
Settings -> Working mode 
تا دیگه SDC نیازی به پورت ۴۴۳ نداشته باشه.

**Comment by sheydooc** [comment]
ممنون مشکل حل شد درست بود بخاطر نصب softether بود
دمت گرم twitch رو 1080 راحت باز میکنه خیلی عالیههههه
