### ISSUE TITLE
dpi check: the ssl connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by Aelurophile92** [msasanmh/SecureDNSClient#55]
سلام رفقا.من تا دو سه روز پیش از برنامه به راحتی استفاده میکردم اما الان با این ارور روبه رو میشم.میتونید کمکم کنید که مشکل رو حل کنم؟

**Comment by alidxdydz** [comment]
> سلام رفقا.من تا دو سه روز پیش از برنامه به راحتی استفاده میکردم اما الان با این ارور روبه رو میشم.میتونید کمکم کنید که مشکل رو حل کنم؟

مرورگرو هم چک میکنید؟
از کدوم روش استفاده میکنید؟ (فرگمنت از طریق پراکسی یا GoodbyeDPI)

**Comment by Aelurophile92** [comment]
> 

بله.از طریق goodbyeDPI

**Comment by msasanmh** [comment]
> > 
> 
> بله.از طریق goodbyeDPI

اون GoodbyeDPI دیگه روی اکثر ISP ها جواب نمیده، از تب شماره ۴ استفاده کن، راحت به کار میفته

**Comment by Aelurophile92** [comment]
> > > 
> > 
> > 
> > بله.از طریق goodbyeDPI
> 
> اون GoodbyeDPI دیگه روی اکثر ISP ها جواب نمیده، از تب شماره ۴ استفاده کن، راحت به کار میفته

بازم دوباره همون ارور رو میده

**Comment by msasanmh** [comment]
> > > > 
> > > 
> > > 
> > > بله.از طریق goodbyeDPI
> > 
> > اون GoodbyeDPI دیگه روی اکثر ISP ها جواب نمیده، از تب شماره ۴ استفاده کن، راحت به کار میفته
> 
> بازم دوباره همون ارور رو میده 

یه مقدار با اعداد تب ۴ بازی کن و بعد هر بار تغییر روی Apply کلیک کن تا چک کنه باز میشه یا نه.
یه مقدار ور بری حتما باز میشه، باید تنظیمات مربوط به ISP خودت رو پیدا کنی.
اعداد 100, 8, 100 رو امتحان کن

**Comment by mojidoji** [comment]
> > > > > 
> > > > 
> > > > 
> > > > بله.از طریق goodbyeDPI
> > > 
> > > 
> > > اون GoodbyeDPI دیگه روی اکثر ISP ها جواب نمیده، از تب شماره ۴ استفاده کن، راحت به کار میفته
> > 
> > 
> > بازم دوباره همون ارور رو میده
> 
> یه مقدار با اعداد تب ۴ بازی کن و بعد هر بار تغییر روی Apply کلیک کن تا چک کنه باز میشه یا نه. یه مقدار ور بری حتما باز میشه، باید تنظیمات مربوط به ISP خودت رو پیدا کنی. اعداد 100, 8, 100 رو امتحان کن

اقا یه اپدیتی چیزی نداره ک اوکی بشه؟ مال منم اوکی بود این سری چند روزه اینجوری میشه درست کار میکنه یهو میپره میره چند ساع ت بعد دوباره وصل میشه

**Comment by mojidoji** [comment]
> > > > > 
> > > > 
> > > > 
> > > > بله.از طریق goodbyeDPI
> > > 
> > > 
> > > اون GoodbyeDPI دیگه روی اکثر ISP ها جواب نمیده، از تب شماره ۴ استفاده کن، راحت به کار میفته
> > 
> > 
> > بازم دوباره همون ارور رو میده
> 
> یه مقدار با اعداد تب ۴ بازی کن و بعد هر بار تغییر روی Apply کلیک کن تا چک کنه باز میشه یا نه. یه مقدار ور بری حتما باز میشه، باید تنظیمات مربوط به ISP خودت رو پیدا کنی. اعداد 100, 8, 100 رو امتحان کن

 و اینکه راهی نداره این دی ان اس بتونه اینستاگرام یا برنامه های بیشتری رو باز کنه؟ خیلی خوبه این برنامه درود بر شما

**Comment by nonbarbari** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > بله.از طریق goodbyeDPI
> > > > 
> > > > 
> > > > اون GoodbyeDPI دیگه روی اکثر ISP ها جواب نمیده، از تب شماره ۴ استفاده کن، راحت به کار میفته
> > > 
> > > 
> > > بازم دوباره همون ارور رو میده
> > 
> > 
> > یه مقدار با اعداد تب ۴ بازی کن و بعد هر بار تغییر روی Apply کلیک کن تا چک کنه باز میشه یا نه. یه مقدار ور بری حتما باز میشه، باید تنظیمات مربوط به ISP خودت رو پیدا کنی. اعداد 100, 8, 100 رو امتحان کن
> 
> و اینکه راهی نداره این دی ان اس بتونه اینستاگرام یا برنامه های بیشتری رو باز کنه؟ خیلی خوبه این برنامه درود بر شما

ن مگر این که این برنامه کمک کنه پروکسی های گوگل کروم که کار نمیکردن کار کنن
