### ISSUE TITLE
لیست

### ISSUE THREAD

**Issue by leoson95** [msasanmh/SecureDNSClient#57]
سلام خسته نباشی 
میگم راهی نیست مثلا لیستی که بعد چک کردن سوا میکنه رو بصورت انکریپت شده ذخیره کنه تا اینکه بعد هربار باز کردن سیستم نیاز نشه دوباره از اول چک کنیم ؟

و اینکه از کجا میتونم خودم لیست گیر بیارم بزنم چک کنه تا اینکه ذخیره هم کرده باشه ؟ یسری لیست DOH پیدا کردم دادم چک کرد حدود 100 تا ولی همش fail شد 
dns خاصی نیازه ؟

**Comment by leoson95** [comment]
![image](https://github.com/msasanmh/SecureDNSClient/assets/40212922/62eff27d-2684-4042-a882-2126d596e00f)

**Comment by leoson95** [comment]
و اینکه sdns:// رو اصلا نشناخت

**Comment by leoson95** [comment]
بخش fakeproxy هم که بدون چک کردن سرور ها هست کار نمیکنه برام ( نت مخابرات )

![image](https://github.com/msasanmh/SecureDNSClient/assets/40212922/bc35a8e9-b296-4aac-af38-6ed32e40631d)

**Comment by msasanmh** [comment]
> سلام خسته نباشی 
> میگم راهی نیست مثلا لیستی که بعد چک کردن سوا میکنه رو بصورت انکریپت شده ذخیره کنه تا اینکه بعد هربار باز کردن سیستم نیاز نشه دوباره از اول چک کنیم ؟
> 
> و اینکه از کجا میتونم خودم لیست گیر بیارم بزنم چک کنه تا اینکه ذخیره هم کرده باشه ؟ یسری لیست DOH پیدا کردم دادم چک کرد حدود 100 تا ولی همش fail شد 
> dns خاصی نیازه ؟

این کار رو انجام دادم. ورژن بعد ذخیره میکنه.
پیدا کردن سرورهای عمومی هم فقط باید وقط گذاشت و گوگل کرد.

**Comment by msasanmh** [comment]
> و اینکه sdns:// رو اصلا نشناخت

میشناسه، اما بخاطر تنظیمات بخش Check ردشون کرده، چون از نوع family بودن و safe search گوگل رو فعال میکنن.
اگه میخوایید همه رو تشخیص بده به تنظیمات برید، بخش چک و بعد بخش sdns

**Comment by msasanmh** [comment]
> بخش fakeproxy هم که بدون چک کردن سرور ها هست کار نمیکنه برام ( نت مخابرات )
> 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/40212922/bc35a8e9-b296-4aac-af38-6ed32e40631d)
> 

این مشکل بخاطر dnscrypt هستش، خیلی کم پیش میاد، چند بار retry کنید درست میشه

**Comment by leoson95** [comment]
> 
> این کار رو انجام دادم. ورژن بعد ذخیره میکنه. پیدا کردن سرورهای عمومی هم فقط باید وقط گذاشت و گوگل کرد.


عالیه اگه ذخیره کنه ... منتظر رلیز هستم
