### ISSUE TITLE
Port 443 is occupied

### ISSUE THREAD

**Issue by AliShFar** [msasanmh/SecureDNSClient#6]
وقتی کانکت رو میزنم پیغام قرمز رنگ
Port 443 is occupied. Is SecureDNS already running?!
 میاد

**Comment by msasanmh** [comment]
برنامه برای کار یه سرور DNS ایجاد میکنه بروی پورت پیش‌فرض ۵۳ و یه سرور DoH ایجاد میکنه بروی پورت ۴۴۳.
من در ورژن بعدی کاری میکنم که استفاده از DoH اختیاری باشه.
الان که این پورت شما مشغوله یعنی یه برنامه دیگه‌ای دارید که داره از این پورت استفاده میکنه، مثل وب سرورها.
با دستورات پایین میتونی بفهمی کدوم برنامه است و ببندیش:
کلید ترکیبی Windows + R رو بزن
در پنجره باز شده cmd رو تایپ کن و اینتر بزن
در پنجره جدید عبارت پایین رو تایپ کن:
netstat -ano | find "443" | find "LISTEN"
اگه پروسسی پورت 443 رو اشغال کرده باشه میاد PID اون پروسس رو در سمت راستش نشون میده.
بعد به Task Manager برو و ببین اون PID متعلق به کدوم پروسس هستش و اون پروسس رو End Task کن
