### ISSUE TITLE
نسخه مناسب ویندوز 7 64 بیتی میخواستم

### ISSUE THREAD

**Issue by abbaszahiri** [msasanmh/SecureDNSClient#60]
درود بر شما . ضمن عرض ادب،
نسخه مناسب ویندوز 7 64 بیتی میخواستم.

**Comment by msasanmh** [comment]
> درود بر شما . ضمن عرض ادب،
> نسخه مناسب ویندوز 7 64 بیتی میخواستم.

درود.
همین برنامه با ویندوز ۷ هم تست شده و سازگاره.
پیش‌نیازهای برنامه رو نصب کنید.
آخرین ورژن ویندوز ۷ رو داشته باشید.

**Comment by abbaszahiri** [comment]
ok
شد.
همین کار کرد. خود برنامه یه دات نت دیگه درخواست دانلود کرد و نصب کردم و روی ویندوز ۷ هم کار کرد. ممنون
