### ISSUE TITLE
پارامترهای فرگمنت برای اینترنت فیبر نوری؟

### ISSUE THREAD

**Issue by abbaszahiri** [msasanmh/SecureDNSClient#61]
تنظیمات پیش فرض لایت در goodbye dpi  برای مخابرات adsl به راحتی کار میکنذ. برگه چهارم را من اصلا فعال نکردم. 

ولی برای اینترنت فیبر نوری حتی extreme هم کار نکرد 
و یوتیوب را باز نکرد. چیکار کنم؟

**Comment by msasanmh** [comment]
> تنظیمات پیش فرض لایت در goodbye dpi  برای مخابرات adsl به راحتی کار میکنذ. برگه چهارم را من اصلا فعال نکردم. 
> 
> ولی برای اینترنت فیبر نوری حتی extreme هم کار نکرد 
> و یوتیوب را باز نکرد. چیکار کنم؟

وقتی GoodbyeDPI جواب نمیده خاموشش کنید و بجاش از قسمت پراکسی یا همون تب چهارم استفاده کنید.
از تب چهارم
گزینه enable fragment تیک داشته باشه.
بعد روی دکمه enable/disable کلیک کنید تا پراکسی روشن شه.
بعد بروی set/unset کلیک کنید تا پراکسی بروی ویندوز ست بشه.

**Comment by msasanmh** [comment]
پارامترهای پیش‌فرض روی همه کار میکنه، اگه نشد کمی اعداد رو بالا پایین کن.

**Comment by abbaszahiri** [comment]
متاسفانه هر کار کردم وصل نشد که نشد :(

**Comment by abbaszahiri** [comment]
برگه آخر را که غیرفعال کردم.
رفتم برگه 4

**Comment by abbaszahiri** [comment]
تنظیمات پیش فرض رو نوشت در عرض 8 ثانیه تونسته وصل بشه به یوتیوب. تاخیر هم اضافه کردم در حد یک میلی ثانیه تا 10 میلی ثانیه. بدتر شد. فیبر نوری هم حدود 30 مگ سرعت داره متقارن سرعتش . کیفیتش خوبه اینترنت. فکر کنم روترهاشون جدیده این برنامه نمیتونه وصل کنه منو اینم شانس ماست :(

**Comment by abbaszahiri** [comment]
با ADSL خونه با همون برگه آخر DPI لوله میشه. ولی با فیبر نوری نمیشه. حتی با برگه 4 ام هم نمیشه. شایدم منطقه ما اینطوریه

**Comment by msasanmh** [comment]
> تنظیمات پیش فرض رو نوشت در عرض 8 ثانیه تونسته وصل بشه به یوتیوب. تاخیر هم اضافه کردم در حد یک میلی ثانیه تا 10 میلی ثانیه. بدتر شد. فیبر نوری هم حدود 30 مگ سرعت داره متقارن سرعتش . کیفیتش خوبه اینترنت. فکر کنم روترهاشون جدیده این برنامه نمیتونه وصل کنه منو اینم شانس ماست :(

اما اینجا نوشتی که تونست باز کنه، وقتی مینویسه یعنی میتونه صددرصد بازش کنه.
پیشنهاد میدم بجای ست کردن پراکسی روی ویندوز، پراکسی رو فقط روی مرورگر ست کنی.
برای کروم از افزونه Switchy omega و برای فایرفاکس از Foxy proxy استفاده کن.
تعداد درخواست‌های ویندوز زیاده و متاسفانه فعلا برنامه نمیتونه تعداد بالا رو پردازش کنه، اما مرورگر تعداد کمتری داره و احتمال بای‌پس شدن dpi بالا میره.
از مرورگر edge هم استفاده نکن. 
تاخیر هم استفاده نکن، صفر باشه.

**Comment by abbaszahiri** [comment]
میتونه باز کنه با DPI.
ولی میزنه بالای 7 ثانیه.
speed test
را مثلا تو فایرفاکس با پروکسی خود مرورگر بذاری کلا خطا میده و نمیتونه کار کنه.

در حالی که با اون goodbye که روی ADSL من وصل میشدم. سرعت کامل 10 مگ دانلود و 1.9 مگ آپلود میداد. ذوق کرده بودم. روی فیبر حالا هیچ جوری وصل نمیشه اصلا ضدحال خوردم بدجور

بحث تاخیر را درست میفرمایید. حداقل اینجا زیاد کردنش مفید نیست.

در کل فکر میکنم نمیتونه این فیبر نوری که جدیدا تو کردستان کشیدن را باز کنه . فکر میکنم روتر و تجهیزاتشون جدیده

**Comment by msasanmh** [comment]
> میتونه باز کنه با DPI.
> ولی میزنه بالای 7 ثانیه.
> speed test
> را مثلا تو فایرفاکس با پروکسی خود مرورگر بذاری کلا خطا میده و نمیتونه کار کنه.
> 
> در حالی که با اون goodbye که روی ADSL من وصل میشدم. سرعت کامل 10 مگ دانلود و 1.9 مگ آپلود میداد. ذوق کرده بودم. روی فیبر حالا هیچ جوری وصل نمیشه اصلا ضدحال خوردم بدجور
> 
> بحث تاخیر را درست میفرمایید. حداقل اینجا زیاد کردنش مفید نیست.
> 
> در کل فکر میکنم نمیتونه این فیبر نوری که جدیدا تو کردستان کشیدن را باز کنه . فکر میکنم روتر و تجهیزاتشون جدیده 

سرعت GoodbyeDPI به این علت بیشتره که فول چانک نمی‌کنه یعنی یک درخواست رو فقط ۲ تکه میکنه.
به همین دلیل نمیتونه روی فیبرنوری، همراه اول، شاتل و غیره کار کنه.
اما پراکسی یک درخواست رو به بیش از ۳۰۰ تکه تقسیم میکنه، به همین دلیل جواب میده.

**Comment by abbaszahiri** [comment]
رفیق الان سرعت 50 مگ روی فیبر لعنتی ها به من فروختند ولی عملا یک مگ میتونم بگیرم با این روش . اینجوری باشه باید یه فکر دیگه کنم کلا عملیاتی نیست برام. 
اگر اینجوری باشه که میفرمایید حق باشماست. شما تلاش خودتون را کردید دیگه. اگه روتر ها جدید باشه ، کلا نمیشه با فرگمنت ، DPI را خراب کرد.

**Comment by abbaszahiri** [comment]
گفتم در جریان باشید. ولی ناامید نباشید. همین الانشم روی شبکه های دیگه عالی جواب میگیرم. دمتون گرم. خدا براتون بخواد. به امید آزادی از چنگال اهریمن

**Comment by msasanmh** [comment]
> رفیق الان سرعت 50 مگ روی فیبر لعنتی ها به من فروختند ولی عملا یک مگ میتونم بگیرم با این روش . اینجوری باشه باید یه فکر دیگه کنم کلا عملیاتی نیست برام. 
> اگر اینجوری باشه که میفرمایید حق باشماست. شما تلاش خودتون را کردید دیگه. اگه روتر ها جدید باشه ، کلا نمیشه با فرگمنت ، DPI را خراب کرد.

من فیبر نوری ندارم، adsl دارم با سرعت ۸ مگابیت.
با همین پراکسی اصلا کاهش سرعت ندارم.
وقتی گفتم سرعت GoodbyeDPI بیشتره منظورم سرعت لود اولیه وبسایت‌ها بوده.
درهرصورت الان زمین و زمان برنامه رو بهم ریختم دارم از روش جدیدی برای پراکسی استفاده میکنم که باعث میشه سرعت بالاتر بره.
حتی اگه دیگه نمیخوای از این برنامه استفاده کنی، بی‌زحمت سرعت دانلود با ورژن بعدی رو یه تست بزن و بهم اطلاع بده. ممنون.

**Comment by abbaszahiri** [comment]
دمت گرم. چشم داداش. حتما. خوشحال میشم هر کاری بشه کرد براتون میکنم.
