### ISSUE TITLE
نسخه arm64 ؟

### ISSUE THREAD

**Issue by abbaszahiri** [msasanmh/SecureDNSClient#62]
درود و عرض ادب
ممکنه نسخه arm64 لینوکس را هم تهیه کنید یا راهنمایی کنید خودم بتونم با زبان go بنویسم کمک شما هم باهش. فقط کامل زیردیپلم بگید:)

**Comment by msasanmh** [comment]
> درود و عرض ادب
> ممکنه نسخه arm64 لینوکس را هم تهیه کنید یا راهنمایی کنید خودم بتونم با زبان go بنویسم کمک شما هم باهش. فقط کامل زیردیپلم بگید:)

من هرگز لینوکس کار نکردم، واقعا متاسفم اصلا نمیدونم از کجا باید شروع کرد
