### ISSUE TITLE
support yarn

### ISSUE THREAD

**Issue by shahabbasian** [msasanmh/SecureDNSClient#63]
سلام برادر

دمت گرم برای زحمتی که کشیدی و خیلی کار راه اندازه

میگم یک فکری هم برای خود مای برنامه نویس ها بکن

اینقدر این دپندنسی منیجرها و دانلود و اپدیت پکیج ها داره اذیت میکنه که شرمسار کدهایی که مینویسم شدم

برنامت بتونه yarn که تو ترمینال ران میشه رو هم ساپورت کنه عالی میشه

**Comment by msasanmh** [comment]
متاسفانه ویندوز اصلا هیچ کاماند لاینی رو از پراکسی عبور نمیده، حتی cmd خود ویندوز چه برسه به یارن.
اگه میتونستم حتما انجام می‌دادم چون به کار خودمم میاد.
