### ISSUE TITLE
کار نکردن برنامه با هر مرورگری به جز فایرفاکس

### ISSUE THREAD

**Issue by Mhmmd-h17m** [msasanmh/SecureDNSClient#64]
سلام من اخیرن به یه مشکلی خوردم و نمیدونم از چیه برنامه با هیچ مرورگری(کروم، اج، بریو) کار نمی کنه به جز فایرفاکس
یعنی توی اونا من بارها باید مراحل و از اول برم که کار کنه و گاها هم وسط قطع میشه یا خیلی کنده ولی هیچ کدوم از این مشکلات و با فایرفاکس نداره.
من تمام مرورگرها رو چک کردم و هیچ dns هم روشون ست نیست.

**Comment by msasanmh** [comment]
پراکسی برنامه رو روی ویندوز ست میکنید یا روی مرورگر؟ 
یا اینکه کلا از پراکسی استفاده نمیکنی؟

**Comment by Mhmmd-h17m** [comment]
من از تنظیمات دیفالت استفاده میکنم.
از کجا باید این و چک کنم؟

**Comment by msasanmh** [comment]
> من از تنظیمات دیفالت استفاده میکنم.
> از کجا باید این و چک کنم؟

یعنی توی تب چهار بروی set/unset کلیک میکنی؟

**Comment by Mhmmd-h17m** [comment]
بله کلیک میکنم

**Comment by msasanmh** [comment]
> بله کلیک میکنم

خب پس حدسم درست بود. وقتی روی set کلیک می‌کنید برنامه پراکسی رو روی کل ویندوز ست میکنه.
و چون تعداد درخواست‌‌های ویندوز از مرورگر بیشتره این باعث میشه درخواست در صف انتظار گیر کنن.
هم اینکه مجبور شدم تعداد پردازش درخواست‌ها رو کاهش بدم تا برنامه لگ نزنه.

اما ورژن بعد تصمیم دارم پراکسی رو بروی حالت non ui ببرم که باعث میشه برنامه به هیچ‌وجه لگ نزنه و درنتیجه میتونم تعداد پردازش درخواست‌ها رو زیاد کنم.

پس ورژن بعد این مشکل حل میشه.
فعلا که از برنامه استفاده میکنید میتونید بجای زدن اون دکمه set پراکسی رو فقط رو مرورگر ست کنید.

برای ست کردن پراکسی مستقیم روی مرورگر:
برای فایرفاکس از افزونه Foxy proxy و برای کروم از افزونه switchy omega استفاده کنید.

**Comment by Mhmmd-h17m** [comment]
حقیقتش سعی کردم از هر دو افزونه ای که گفتید سر در بیارم ولی نتونستم بفهمم چجوری باید پروکسی ها رو داخلشون ادد کنم ممنون میشم یه آموزش بزارید و البته تا نسخه بعدی صبر میکنم.
بازم ممنون بابت این اپ واقعا کمک کننده است توی این شرایط

**Comment by msasanmh** [comment]
> حقیقتش سعی کردم از هر دو افزونه ای که گفتید سر در بیارم ولی نتونستم بفهمم چجوری باید پروکسی ها رو داخلشون ادد کنم ممنون میشم یه آموزش بزارید و البته تا نسخه بعدی صبر میکنم.
> بازم ممنون بابت این اپ واقعا کمک کننده است توی این شرایط

تصمیم دارم یه سری ویدئو آموزشی برای قسمت‌های مختلف برنامه درست کنم، متاسفانه تا الان وقت نکردم.
بالاخره ویدئو هم می‌ذارم.

**Comment by alidxdydz** [comment]
> حقیقتش سعی کردم از هر دو افزونه ای که گفتید سر در بیارم ولی نتونستم بفهمم چجوری باید پروکسی ها رو داخلشون ادد کنم ممنون میشم یه آموزش بزارید و البته تا نسخه بعدی صبر میکنم.
> بازم ممنون بابت این اپ واقعا کمک کننده است توی این شرایط


@Mhmmd-h17m 
برای فایرفاکس به هیچ افزونه‌ای نیاز ندارید، وارد setting بشید و کلمه doh یا proxy رو جستجو کنید.
وارد قسمت پیشنهاد شده بشید و میبینید که تنظیمات پراکسی همونجاس. بعد مقدار 127.0.0.1:8080 رو داخل قسمت HTTP و HTTPS تایپ کنید.
