### ISSUE TITLE
پیشنهاد - سیو کردن سرور های چک شده

### ISSUE THREAD

**Issue by Ge64com** [msasanmh/SecureDNSClient#66]
خیلی عالی میشد که میتونست سرور هایی رو که چک میکنه داخل یه فایل txt یا هر چی سیو کنه تا دفعه بعدی که برنامه رو باز میکنیم دوباره چند دقیقه منتظر چک نباشیم.

**Comment by msasanmh** [comment]
> خیلی عالی میشد که میتونست سرور هایی رو که چک میکنه داخل یه فایل txt یا هر چی سیو کنه تا دفعه بعدی که برنامه رو باز میکنیم دوباره چند دقیقه منتظر چک نباشیم.

ورژن آخر برنامه، یعنی نسخه 2.2.2 همین کار رو انجام میده.
سریعترین سرورهایی که بهش وصل میشه رو ذخیره میکنه و بعد اجرای دوباره همونا رو لود میکنه و خودش هر ساعت در بکگراند چک میکنه که اگه سروری از کار افتاده با یکی که کار میکنه عوض میکنه.

به درخواست کاربرها اضافه شد.
