### ISSUE TITLE
یه پیشنهاد دیگه : تغییر اتوماتیک متغیر های بخش 4

### ISSUE THREAD

**Issue by Ge64com** [msasanmh/SecureDNSClient#67]
اگر میشد یه الگوریتمی نوشت که خودش با اعداد بخش چهار بازی میکرد تا اعداد مناسب ISP هر شخص رو در بیاره به نظرم خوب میشد.

**Comment by msasanmh** [comment]
> اگر میشد یه الگوریتمی نوشت که خودش با اعداد بخش چهار بازی میکرد تا اعداد مناسب ISP هر شخص رو در بیاره به نظرم خوب میشد.

این کار داخل todo لیستم هست، سر فرصت انجام میدم.
گرچند ورژن بعد بخش چهار تنظیمات خلاصه‌تری خواهد داشت به لطف الگوریتم جدید.

**Comment by Ge64com** [comment]
منتظر هستیم ❤️

**Comment by SharaMck** [comment]
سلام دمت گرم یوتیوب باز میشه اما خیلی از سایت ها دسترسی قطع میشه راهی هست ؟
