### ISSUE TITLE
ورژن 2.3.0 - تب 4 -error

### ISSUE THREAD

**Issue by mztd006** [msasanmh/SecureDNSClient#68]
با سلام ورژن 2.3.0 توی تب 4 این ارور رو میده
Couldn't communicate with Proxy Console. Please Try again.

![Screenshot 2023-07-19 103419](https://github.com/msasanmh/SecureDNSClient/assets/131897783/9a8efcce-961b-466a-a2d4-6c3bc7622269)

**Comment by nonbarbari** [comment]
من هر بار تب 4 به مشکل خوره از برنامه خارج شدم و دوباره باز کردم مشکلش درست شده شاید نیاز باشه تنظیمات نرم افزار رو به حالت دیفالت تغییر بدین

**Comment by mztd006** [comment]
> سلام. این ارور میگه نتونسته دستورات رو به کاماند لاین پراکسی بفرسته. در دو حالت ممکنه بوجود بیاد. اولی موقته مهم نیست. دومی رو چک کن. داخل فولدر برنامه یه فولدر هست به اسم binary و داخلش یه فایل به اسم SDCHttpProxy.exe این فایل رو جدا اجرا کن ببین یه صفحه مشکی کاماند لاین بالا میاد یا نه، اگه اومد داخلش واژه help رو بنویس ببین بهت جواب میده یا نه و بهم اطلاع بده. ممنون

سلام
1-نه برای SDCHttpProxy.exe کامند لاین باز نمیشه.
2-ورژن قبلی که این فایل رو نداره بدون مشکل کار میکنه

![image](https://github.com/msasanmh/SecureDNSClient/assets/131897783/deee2070-7d40-4f96-a15c-90af4971d195)




> من هر بار تب 4 به مشکل خوره از برنامه خارج شدم و دوباره باز کردم مشکلش درست شده شاید نیاز باشه تنظیمات نرم افزار رو به حالت دیفالت تغییر بدین

نه این مشکلش موقتی یا از تنظیمات نبود

**Comment by msasanmh** [comment]
> > سلام. این ارور میگه نتونسته دستورات رو به کاماند لاین پراکسی بفرسته. در دو حالت ممکنه بوجود بیاد. اولی موقته مهم نیست. دومی رو چک کن. داخل فولدر برنامه یه فولدر هست به اسم binary و داخلش یه فایل به اسم SDCHttpProxy.exe این فایل رو جدا اجرا کن ببین یه صفحه مشکی کاماند لاین بالا میاد یا نه، اگه اومد داخلش واژه help رو بنویس ببین بهت جواب میده یا نه و بهم اطلاع بده. ممنون
> 
> سلام
> 1-نه برای SDCHttpProxy.exe کامند لاین باز نمیشه.
> 2-ورژن قبلی که این فایل رو نداره بدون مشکل کار میکنه
> 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/131897783/deee2070-7d40-4f96-a15c-90af4971d195)
> 
> 
> 
> 
> > من هر بار تب 4 به مشکل خوره از برنامه خارج شدم و دوباره باز کردم مشکلش درست شده شاید نیاز باشه تنظیمات نرم افزار رو به حالت دیفالت تغییر بدین
> 
> نه این مشکلش موقتی یا از تنظیمات نبود 

ببین این پراکسی نیاز به نسخه ۳۲ بیت .net desktop  ورژن ۶ داره، مطمئنی نصب داری؟

**Comment by msasanmh** [comment]
چک کن این رانتایم رو حتما نصب داشته باشی:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x86-installer

و نسخه دقیق ویندوزت رو هم برام بفرست.
و همینطور بگو که با نصب رانتایم بالا SDCHttpProxy.exe اجرا شد یا نه

**Comment by mztd006** [comment]
با نصب نسخه 32 بیتی مشکل حل شد. من نسخه 64 بیتی رو نصب داشتم 
![image](https://github.com/msasanmh/SecureDNSClient/assets/131897783/8d5e8c1b-ea2e-4efb-82b3-b5caac3323e4)

**Comment by msasanmh** [comment]
> با نصب نسخه 32 بیتی مشکل حل شد. من نسخه 64 بیتی رو نصب داشتم 
> ![image](https://github.com/msasanmh/SecureDNSClient/assets/131897783/8d5e8c1b-ea2e-4efb-82b3-b5caac3323e4)
> 

عالیه، از نسخه جدید استفاده کن، سرعت پردازش بالاتری داره.
