### ISSUE TITLE
bypass dpi for integrated authentication

### ISSUE THREAD

**Issue by mztd006** [msasanmh/SecureDNSClient#69]
من از نرم افزار سی تریدر استفاده میکنم که برای ورود به حساب از اکانت گوگل استفاده میکنه برای باز کردن نرم افزار بایستی HTTPS fragmentations رو غیر فعال کنم و بعد از لاگین دوباره فعال بشه.
 اگرهم این مابین ارتباطم قطع بشه  تا وقتی که یک بار بصورت دستی این آپشن رو خاموش و روشن نکنم نرم افزار غیر فعاله (که این برای من  ریسک بالایی داره ).با اینکه توی ورژن جدید گزینه bypass dpi اضافه شده اما توی این مورد(integrated authentication) قابل استفاده نبود.
این مشکل هیچ راه حلی نداره؟

**Comment by msasanmh** [comment]
> من از نرم افزار سی تریدر استفاده میکنم که برای ورود به حساب از اکانت گوگل استفاده میکنه برای باز کردن نرم افزار بایستی HTTPS fragmentations رو غیر فعال کنم و بعد از لاگین دوباره فعال بشه.
>  اگرهم این مابین ارتباطم قطع بشه  تا وقتی که یک بار بصورت دستی این آپشن رو خاموش و روشن نکنم نرم افزار غیر فعاله (که این برای من  ریسک بالایی داره ).با اینکه توی ورژن جدید گزینه bypass dpi اضافه شده اما توی این مورد(integrated authentication) قابل استفاده نبود.
> این مشکل هیچ راه حلی نداره؟

برنامه راهی نداره که بتونه با IAP کار کنه، گفتی وقتی دستی DPI Bypass رو خاموش روشن میکنی چه مشکلی پیش میاد؟ این قسمت رو متوجه نشدم.

**Comment by mztd006** [comment]
> برنامه راهی نداره که بتونه با IAP کار کنه، گفتی وقتی دستی DPI Bypass رو خاموش روشن میکنی چه مشکلی پیش میاد؟ این قسمت رو متوجه نشدم.

توی حالت عادی اگر سی تریدر دیسکانکت بشه خودش اتوماتیک ریکانکت میشه .اما در صورتیکه HTTPS fragmentations روشن باشه از ریکانکت شدن اتوماتیک خبری نیست و باید دستی انجام بشه.
مشکل من اینه که راهی ندارم که وقتی سی تریدر دیسکانکت میشه مطلع بشم و دستی ریکانکت کنم و خب معامله باز داشتن و دیسکانکت بودن هم ریسک بالایی داره!

**Comment by msasanmh** [comment]
> > برنامه راهی نداره که بتونه با IAP کار کنه، گفتی وقتی دستی DPI Bypass رو خاموش روشن میکنی چه مشکلی پیش میاد؟ این قسمت رو متوجه نشدم.
> 
> توی حالت عادی اگر سی تریدر دیسکانکت بشه خودش اتوماتیک ریکانکت میشه .اما در صورتیکه HTTPS fragmentations روشن باشه از ریکانکت شدن اتوماتیک خبری نیست و باید دستی انجام بشه.
> مشکل من اینه که راهی ندارم که وقتی سی تریدر دیسکانکت میشه مطلع بشم و دستی ریکانکت کنم و خب معامله باز داشتن و دیسکانکت بودن هم ریسک بالایی داره!

متوجه شدم. متاسفانه راه حلی در این مورد ندارم.
