### ISSUE TITLE
DPI Check: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by MHR00** [msasanmh/SecureDNSClient#7]
تمام مراحل درست پیش میره بجز مرحله آخر 
قسمت 4 ( Set DNS ) این خطا رو میده . 
چک کردم DNS رو ست میکنه ولی درست کار نمیکنه ( یوتیوب و توییتر باز نمیشن ) 
DPI Check: The SSL connection could not be established, see inner exception.
Unable to check. Try open www.youtube.com in your browser.

**Comment by msasanmh** [comment]
این خطا داره میگه Bypass کردن DPI روی ISP شما جواب نداده.
میتونی از قسمت Bypass DPI مود های دیگه رو انتخاب کنی ببینی کدومش روی نت شما جواب میده.
تا به الان از بین ۱۰۰ تا کاربر دو نفر این مشکل رو گزارش کردن.
بی‌زحمت بگو از کدوم ISP استفاده میکنی تا خودم بتونم روش تست بزنم و ببینم مشکلش برطرف میشه یا نه.

**Comment by msasanmh** [comment]
راستی، بهتره اول DPI رو غیرفعال کنی اما DNS ست باشه و چک کن ببین گوگل باز میشه یا نه.
اگه گوگل باز شد یعنی اشکال همونیه که تو پیام قبلی گفتم.
اگه گوگل باز نشد یعنی برنامه یا سرورهای خوبی پیدا نکرده که نیازه دوباره چک بشن و یا اینکه فایروال سیستمت جلوش رو گرفته.

**Comment by MHR00** [comment]
> این خطا داره میگه Bypass کردن DPI روی ISP شما جواب نداده. میتونی از قسمت Bypass DPI مود های دیگه رو انتخاب کنی ببینی کدومش روی نت شما جواب میده. تا به الان از بین ۱۰۰ تا کاربر دو نفر این مشکل رو گزارش کردن. بی‌زحمت بگو از کدوم ISP استفاده میکنی تا خودم بتونم روش تست بزنم و ببینم مشکلش برطرف میشه یا نه.

از شاتل استفاده میکنم .
از مود های مختلف استفاده میکنم . یوتیوب رو هیچ کدوم باز نمیکنن ولی بعضی ها مثل High وقتی فعال میشه گوگل باز میشه  و گیت هاب رو باز نمیکنه DPI رو غیرفعال میکنم و DNS ست شده هستش باز میکنه

**Comment by MHR00** [comment]
> راستی، بهتره اول DPI رو غیرفعال کنی اما DNS ست باشه و چک کن ببین گوگل باز میشه یا نه. اگه گوگل باز شد یعنی اشکال همونیه که تو پیام قبلی گفتم. اگه گوگل باز نشد یعنی برنامه یا سرورهای خوبی پیدا نکرده که نیازه دوباره چک بشن و یا اینکه فایروال سیستمت جلوش رو گرفته.

تو هر حالت امتحان میکنم . گوگل رو باز میکنه .

**Comment by MHR00** [comment]
> پس مشکل همون ناسازگاری با ISP هستش. متاسفانه با نت شما سازگار نیست. سعی میکنم شاتل رو هم بای‌پس کنم، اگه شد در نسخه‌های بعدی اعمال میکنم.

با ایرانسل هم امتحان کردم همین خطا رو میداد .

**Comment by MHR00** [comment]
> > > پس مشکل همون ناسازگاری با ISP هستش. متاسفانه با نت شما سازگار نیست. سعی میکنم شاتل رو هم بای‌پس کنم، اگه شد در نسخه‌های بعدی اعمال میکنم.
> > 
> > 
> > با ایرانسل هم امتحان کردم همین خطا رو میداد .
> 
> خب بروی ایرانسل تست کردم و جواب داد، اما به شاتل دسترسی ندارم. مگه شما از ویندوز ۷ استفاده میکنی؟ چون برنامه با بعضی از ورژن‌های ویندوز سون سازگاری نداره و دارم تلاش می‌کنم تا روی اونها هم جواب بده.

Windows 11 Version 12H2 ( OS Build 22000.1817)

**Comment by MHR00** [comment]
فایل لاگی برای برنامه وجود نداره که لاگ های برنامه داخلش ثبت بشه ؟

**Comment by msasanmh** [comment]
لاگ فقط میتونه query های DNS باشه که بخاطر امنیت بالاتر داخل برنامه نذاشتم و ربطی هم به این موضوع نداره. این مشکل شما مربوط به goodbyeDPI میشه که اونم اصلا توی لاگش نشون نمیده که به چه علت نتونسته کارش رو انجام بده.
خودم یه الگوریتم نوشتم بجای goodbyeDPI میتونه کار کنه فعلا نیاز به تست‌های بیشتر داره، توی نسخه بعد از نسخه بعدی، یعنی دو تا نسخه بعدتر اعمال میکنم شاید تونست به بعضی‌ها که مشکل شما رو دارن کمک کنه.

**Comment by rezaip77** [comment]
برای منم همین مشکل با نت مخابرات تمام مود ها و حتی اون تنظیمات advanced هم به کار بردم نشد،وقتی اول دی ان اس ست میکنم گوگل باز میشه

**Comment by msasanmh** [comment]
> برای منم همین مشکل با نت مخابرات تمام مود ها و حتی اون تنظیمات advanced هم به کار بردم نشد،وقتی اول دی ان اس ست میکنم گوگل باز میشه 

ورژن جدید رو چند روز دیگه میذارم، احتمال باز شدن روی مخابرات، همراه اول و شاتل بیشتر شده، امیدوارم اون‌موقع جواب بده.

**Comment by rezaip77** [comment]
> > برای منم همین مشکل با نت مخابرات تمام مود ها و حتی اون تنظیمات advanced هم به کار بردم نشد،وقتی اول دی ان اس ست میکنم گوگل باز میشه
> 
> ورژن جدید رو چند روز دیگه میذارم، احتمال باز شدن روی مخابرات، همراه اول و شاتل بیشتر شده، امیدوارم اون‌موقع جواب بده.

ممنون از زحماتت مشتاقانه منتظریم

**Comment by msasanmh** [comment]
> > > برای منم همین مشکل با نت مخابرات تمام مود ها و حتی اون تنظیمات advanced هم به کار بردم نشد،وقتی اول دی ان اس ست میکنم گوگل باز میشه
> > 
> > ورژن جدید رو چند روز دیگه میذارم، احتمال باز شدن روی مخابرات، همراه اول و شاتل بیشتر شده، امیدوارم اون‌موقع جواب بده.
> 
> ممنون از زحماتت مشتاقانه منتظریم

مشکل دور زدن همراه اول برطرف شد.
۱. سرورها چک بشن.
۲. کانکت انجام بشه.
۳. قسمت dpi بروی حالت light فعال باشه.
۴. دی ان اس set بشه.
۵. قسمت پراکسی روشن و ست بشه.
برنامه فقط ۵ مرحله داره.

**Comment by rezaip77** [comment]
![Untitled](https://github.com/msasanmh/SecureDNSClient/assets/95145662/1800c12c-794c-4b77-b87a-d7c124b781b3)
سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!

**Comment by msasanmh** [comment]
> ![Untitled](https://github.com/msasanmh/SecureDNSClient/assets/95145662/1800c12c-794c-4b77-b87a-d7c124b781b3)
> سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!

من فقط به سه تا ISP دسترسی دارم، مخابرات ندارم تا تست کنم اما توی این ورژن جدید در بخش پراکسی از روشی استفاده کردم که بتونه هر ISP رو دور بزنه.
یعنی قوی و ضعیف عمل کردن برنامه الان دست خودتونه.
توی بخش پراکسی توی قسمت additional dpi bypass سه تا متغیر یا همون عدد وجود داره.
هرچقدر متغیر دوم پایین‌تر باشه (الان بروی ۲ هست، مثلا بذار روی یک) و متغیر سوم بالاتر باشه قدرت برنامه افزایش پیدا میکنه.
احتمال دور زدن ISP بیشتر میشه و البته از cpu هم بیشتر استفاده میکنه.
شما اگه تنظیمات مربوط به این قسمت رو متناسب با ISP مخابرات پیدا کنی، صددرصد میتونی دورش بزنی.
من هر وقت اینترنت مخابرات گیرم بیاد تنظیماتش رو پیدا میکنم و برات میفرستم.

**Comment by msasanmh** [comment]
> ![Untitled](https://github.com/msasanmh/SecureDNSClient/assets/95145662/1800c12c-794c-4b77-b87a-d7c124b781b3)
> سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!

الان به اسکرین شاتی که فرستادی دقت کردم، طبق پیام خطا یه چیزی جلوی برنامه رو گرفته، یا فایروال هستش تا یه پراکسی از قبل روی سیستم ست داشتید:

​If no connection could be made because the target machine actively refused it, this indicates that the Source or Destination system blocked the connection. This is likely due to firewall or web server settings. In some cases, an IP restriction may be in place.

**Comment by rezaip77** [comment]
> > ![Untitled](https://user-images.githubusercontent.com/95145662/239683362-1800c12c-794c-4b77-b87a-d7c124b781b3.png)
> > سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!
> 
> الان به اسکرین شاتی که فرستادی دقت کردم، طبق پیام خطا یه چیزی جلوی برنامه رو گرفته، یا فایروال هستش تا یه پراکسی از قبل روی سیستم ست داشتید:
> 
> ​If no connection could be made because the target machine actively refused it, this indicates that the Source or Destination system blocked the connection. This is likely due to firewall or web server settings. In some cases, an IP restriction may be in place.

![Untitled](https://github.com/msasanmh/SecureDNSClient/assets/95145662/7f107c55-7837-4a04-b9cb-6724dd4f493a)
مشکل قبلی برطرف شد ، ولی با اعدادم بازی کردم 10 تا 10 رفتم بالا تا 300 نشد(متغیر سوم)

**Comment by msasanmh** [comment]
> > > ![Untitled](https://user-images.githubusercontent.com/95145662/239683362-1800c12c-794c-4b77-b87a-d7c124b781b3.png)
> > > سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!
> > 
> > الان به اسکرین شاتی که فرستادی دقت کردم، طبق پیام خطا یه چیزی جلوی برنامه رو گرفته، یا فایروال هستش تا یه پراکسی از قبل روی سیستم ست داشتید:
> > 
> > ​If no connection could be made because the target machine actively refused it, this indicates that the Source or Destination system blocked the connection. This is likely due to firewall or web server settings. In some cases, an IP restriction may be in place.
> 
> ![Untitled](https://github.com/msasanmh/SecureDNSClient/assets/95145662/7f107c55-7837-4a04-b9cb-6724dd4f493a)
> مشکل قبلی برطرف شد ، ولی با اعدادم بازی کردم 10 تا 10 رفتم بالا تا 300 نشد(متغیر سوم)

الان با دوستان صحبت کردم، گفتن برای مخابرات تب سوم رو نباید فعال کنید.
پس مراحل رو به این شکل طی کن:
1 2 4 5

**Comment by rezaip77** [comment]
> > > > ![Untitled](https://user-images.githubusercontent.com/95145662/239683362-1800c12c-794c-4b77-b87a-d7c124b781b3.png)
> > > > سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!
> > > 
> > > 
> > > الان به اسکرین شاتی که فرستادی دقت کردم، طبق پیام خطا یه چیزی جلوی برنامه رو گرفته، یا فایروال هستش تا یه پراکسی از قبل روی سیستم ست داشتید:
> > > ​If no connection could be made because the target machine actively refused it, this indicates that the Source or Destination system blocked the connection. This is likely due to firewall or web server settings. In some cases, an IP restriction may be in place.
> > 
> > 
> > ![Untitled](https://user-images.githubusercontent.com/95145662/239685755-7f107c55-7837-4a04-b9cb-6724dd4f493a.png)
> > مشکل قبلی برطرف شد ، ولی با اعدادم بازی کردم 10 تا 10 رفتم بالا تا 300 نشد(متغیر سوم)
> 
> الان با دوستان صحبت کردم، گفتن برای مخابرات تب سوم رو نباید فعال کنید. پس مراحل رو به این شکل طی کن: 1 2 4 5

ممنون تست کردم جواب نگرفتم، امیدوارم زودتر به ISP مخابرات دسترسی پیدا کنی خودت  تا اینم حل بشه..

**Comment by alidxdydz** [comment]
> > > > > ![Untitled](https://user-images.githubusercontent.com/95145662/239683362-1800c12c-794c-4b77-b87a-d7c124b781b3.png)
> > > > > سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!
> > > > 
> > > > 
> > > > الان به اسکرین شاتی که فرستادی دقت کردم، طبق پیام خطا یه چیزی جلوی برنامه رو گرفته، یا فایروال هستش تا یه پراکسی از قبل روی سیستم ست داشتید:
> > > > ​If no connection could be made because the target machine actively refused it, this indicates that the Source or Destination system blocked the connection. This is likely due to firewall or web server settings. In some cases, an IP restriction may be in place.
> > > 
> > > 
> > > ![Untitled](https://user-images.githubusercontent.com/95145662/239685755-7f107c55-7837-4a04-b9cb-6724dd4f493a.png)
> > > مشکل قبلی برطرف شد ، ولی با اعدادم بازی کردم 10 تا 10 رفتم بالا تا 300 نشد(متغیر سوم)
> > 
> > الان با دوستان صحبت کردم، گفتن برای مخابرات تب سوم رو نباید فعال کنید. پس مراحل رو به این شکل طی کن: 1 2 4 5
> 
> ممنون تست کردم جواب نگرفتم، امیدوارم زودتر به ISP مخابرات دسترسی پیدا کنی خودت  تا اینم حل بشه..

سلام.
یا GoodbyeDPI رو خاموش کنید کلا. چون نیازی بهش نیست. یا در صورتی که میخواید فعال باشه، از منوی Advanced این گزینه‌ها رو انتخاب کنید و بعدا فعال کنید.
-e 2 --wrong-seq --reverse-frag --max-payload 1200

گزینه‌های DPI آخری به این صورت باشه. مهم‌ترین قسمت همینه.
اولی 60 ، دومی 1 و سومی 60

**Comment by amir-valizadeh** [comment]
سلام اقا خوبی خسته نباشی 
برای پارس انلاین چطوری باید کانفیگ بشه 
بای پس مود نیازه یا additional dpi رو چقدر باید کانفیگ کنم

**Comment by msasanmh** [comment]
> سلام اقا خوبی خسته نباشی 
> برای پارس انلاین چطوری باید کانفیگ بشه 
> بای پس مود نیازه یا additional dpi رو چقدر باید کانفیگ کنم 

سلام اگه من دستم به ISP های مختلف می‌رسید واسه هرکدوم یه گزینه میذاشتم که هرکسی با توجه به ISP ش انتخاب کنه.
قسمت dpi بروی تب share خیلی مهمه، چندتا از قوی‌ترین حالت‌ها رو برات مینویسم اما باید بدونی هرچقدر قوی‌تر یعنی مصرف cpu بیشتر:
حالت پیش‌فرض:
60, 2, 60
حالت قوی‌تر یک:
65536, 2, 65536
حالت قوی‌تر دوم:
65536, 1, 65536
حالت قوی‌تر سوم:
300, 40, 60000
با هرکدوم از انتخاب‌های بالا هم با dpi bypass خاموش که توی تب جدا قرار داره تست بگیر و هم با حالت روشن و مود رو light انتخاب کن.
جمعا میشه ۶ حالت، امیدوارم یکیش باعث بشه ISP ت دور زده شه. اگه شد بهم بگو کدوم حالت جواب داد.
اگه نداد هم که خودم باید دستم به این  ISP برسه.

**Comment by msasanmh** [comment]
> سلام اقا خوبی خسته نباشی 
> برای پارس انلاین چطوری باید کانفیگ بشه 
> بای پس مود نیازه یا additional dpi رو چقدر باید کانفیگ کنم 

فارسی باعث شد اعداد برعکس نشون داده بشن.
توی حالت سوم، عدد 300 اولین و 40 دومی هستش.

**Comment by githubgitbash** [comment]
سلام
1-شاتل همین مشکل را دارم پروکسی و فایروال را چک کردم خاموشه
2-اگر بخوام ورژن های قبلی کامل پاک کنم باید چکار کنم؟ انگار فایل WinDivert64.sys اجاز پاک کردن نمیده
ممنون

**Comment by msasanmh** [comment]
> سلام
> 1-شاتل همین مشکل را دارم پروکسی و فایروال را چک کردم خاموشه
> 2-اگر بخوام ورژن های قبلی کامل پاک کنم باید چکار کنم؟ انگار فایل WinDivert64.sys اجاز پاک کردن نمیده
> ممنون

فایل WinDivert64.sys برای GoodbyeDPI هستش، اگه اجازه پاک شدن نمیده، اول rename کن بعد سیستم رو ری‌استارت کن و پاکش کن.
درنهایت اگه باز هم پاک نشد مجبوری از طریق safe mode پاکش کنی.

**Comment by msasanmh** [comment]
> سلام من قبلا با مشکل
> DPI Check: The SSL connection could not be established, see inner exception
> روبرو بودم ولی تو نسخه جدید با همراه اول و ایرانسل تست گرفتم مشکل حل شد
> عالی هستی شما دمت گرم
> فقط ی سوال میشه ازین روش DNS برای موبایل هم استفاده کرد؟
> مثلا با برنامه Intra
> یعنی DNS سالم پیدا کرد با ISP ایرانسل، بعد لینک را قرار بدیم توبرنامه intra ؟ یا خیلی پیچیده تر از این حرفاست.

عالیه، فقط تنظیماتی که استفاده کردی یادت بمونه، چون هر ISP با یه تنظیمات متفاوت کار میکنه.
برای موبایل من گذاشتم برنامه dns و پراکسی رو بروی شبکه share کنه.

مثلا برای اینترا که DoH قبول میکنه از تنظیمات برنامه ابتدا باید این گزینه رو فعال کنی:
Settings -> Working mode -> Plain dns + DNS-Over-Https
تا برنامه بهت لینک DoH لوکال بده. مثلا میشه مثل آدرس پایین:
https://192.168.1.x/dns-query
و اونوقت میتونی این آدرس رو توی اینترا استفاده کنی.

راه دیگه استفاده از پراکسیه که توی تب Share فعال میشه. مثلا میتونی با برنامه Nekobox یا ماتسوری یه پروفایل از نوع http بسازی

متاسفانه برنامه نمیتونه سرورهایی که بهش وصل میشه رو نشون بده تا از لینک اونا استفاده کنی چون فیلتر میشن.

**Comment by matpat9191** [comment]
> > سلام من قبلا با مشکل
> > DPI Check: The SSL connection could not be established, see inner exception
> > روبرو بودم ولی تو نسخه جدید با همراه اول و ایرانسل تست گرفتم مشکل حل شد
> > عالی هستی شما دمت گرم
> > فقط ی سوال میشه ازین روش DNS برای موبایل هم استفاده کرد؟
> > مثلا با برنامه Intra
> > یعنی DNS سالم پیدا کرد با ISP ایرانسل، بعد لینک را قرار بدیم توبرنامه intra ؟ یا خیلی پیچیده تر از این حرفاست.
> 
> عالیه، فقط تنظیماتی که استفاده کردی یادت بمونه، چون هر ISP با یه تنظیمات متفاوت کار میکنه. برای موبایل من گذاشتم برنامه dns و پراکسی رو بروی شبکه share کنه.
> 
> مثلا برای اینترا که DoH قبول میکنه از تنظیمات برنامه ابتدا باید این گزینه رو فعال کنی: Settings -> Working mode -> Plain dns + DNS-Over-Https تا برنامه بهت لینک DoH لوکال بده. مثلا میشه مثل آدرس پایین: https://192.168.1.x/dns-query و اونوقت میتونی این آدرس رو توی اینترا استفاده کنی.
> 
> راه دیگه استفاده از پراکسیه که توی تب Share فعال میشه. مثلا میتونی با برنامه Nekobox یا ماتسوری یه پروفایل از نوع http بسازی
> 
> متاسفانه برنامه نمیتونه سرورهایی که بهش وصل میشه رو نشون بده تا از لینک اونا استفاده کنی چون فیلتر میشن.

مرسی آقا دمت گرم
ممنون بخاطر زحماتی که میکشی

**Comment by ghotbizadeh** [comment]
> > ![Untitled](https://private-user-images.githubusercontent.com/95145662/239683362-1800c12c-794c-4b77-b87a-d7c124b781b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTQ2MDAsIm5iZiI6MTcxMzAxNDMwMCwicGF0aCI6Ii85NTE0NTY2Mi8yMzk2ODMzNjItMTgwMGMxMmMtNzk0Yy00Yjc3LWI4N2EtZDdjMTI0Yjc4MWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEzMTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNTJiYzliZGJkNTIwZGRiZjY2NDcwMzI0ZGIyYzY4NDdlYWZlZmZjYThhNjI2OTA1ODFmZTZkNWI2ZTIwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kVElXDWi1wUz7gWtLcWEfuqv4-mRLMxtYEWlknUVEZc)
> > سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!
> 
> من فقط به سه تا ISP دسترسی دارم، مخابرات ندارم تا تست کنم اما توی این ورژن جدید در بخش پراکسی از روشی استفاده کردم که بتونه هر ISP رو دور بزنه. یعنی قوی و ضعیف عمل کردن برنامه الان دست خودتونه. توی بخش پراکسی توی قسمت additional dpi bypass سه تا متغیر یا همون عدد وجود داره. هرچقدر متغیر دوم پایین‌تر باشه (الان بروی ۲ هست، مثلا بذار روی یک) و متغیر سوم بالاتر باشه قدرت برنامه افزایش پیدا میکنه. احتمال دور زدن ISP بیشتر میشه و البته از cpu هم بیشتر استفاده میکنه. شما اگه تنظیمات مربوط به این قسمت رو متناسب با ISP مخابرات پیدا کنی، صددرصد میتونی دورش بزنی. من هر وقت اینترنت مخابرات گیرم بیاد تنظیماتش رو پیدا میکنم و برات میفرستم.



سلام این خطا رو توی windows 7 دارم. البته در نسخه ی 2.8.5 ، نسخه ی 2.9.2 در windows 7 اصلا از ابتدا به جایی وصل نمیشه

**Comment by msasanmh** [comment]
> > > ![Untitled](https://private-user-images.githubusercontent.com/95145662/239683362-1800c12c-794c-4b77-b87a-d7c124b781b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTQ2MDAsIm5iZiI6MTcxMzAxNDMwMCwicGF0aCI6Ii85NTE0NTY2Mi8yMzk2ODMzNjItMTgwMGMxMmMtNzk0Yy00Yjc3LWI4N2EtZDdjMTI0Yjc4MWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEzMTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNTJiYzliZGJkNTIwZGRiZjY2NDcwMzI0ZGIyYzY4NDdlYWZlZmZjYThhNjI2OTA1ODFmZTZkNWI2ZTIwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kVElXDWi1wUz7gWtLcWEfuqv4-mRLMxtYEWlknUVEZc)
> > > سلام ممنون بابت نسخه جدید ، روی نت مخابرات اوکی شده ؟ من همین الان تست کردم و جواب نگرفتم برای مخابرات!!
> > 
> > من فقط به سه تا ISP دسترسی دارم، مخابرات ندارم تا تست کنم اما توی این ورژن جدید در بخش پراکسی از روشی استفاده کردم که بتونه هر ISP رو دور بزنه. یعنی قوی و ضعیف عمل کردن برنامه الان دست خودتونه. توی بخش پراکسی توی قسمت additional dpi bypass سه تا متغیر یا همون عدد وجود داره. هرچقدر متغیر دوم پایین‌تر باشه (الان بروی ۲ هست، مثلا بذار روی یک) و متغیر سوم بالاتر باشه قدرت برنامه افزایش پیدا میکنه. احتمال دور زدن ISP بیشتر میشه و البته از cpu هم بیشتر استفاده میکنه. شما اگه تنظیمات مربوط به این قسمت رو متناسب با ISP مخابرات پیدا کنی، صددرصد میتونی دورش بزنی. من هر وقت اینترنت مخابرات گیرم بیاد تنظیماتش رو پیدا میکنم و برات میفرستم.
> 
> 
> 
> سلام این خطا رو توی windows 7 دارم. البته در نسخه ی 2.8.5 ، نسخه ی 2.9.2 در windows 7 اصلا از ابتدا به جایی وصل نمیشه

شما باید از SSL Decryption استفاده کنی، نحوه استفاده داخل دو یا سه تا issue آخر نوشته شده
