### ISSUE TITLE
مخابرات

### ISSUE THREAD

**Issue by reykins** [msasanmh/SecureDNSClient#70]
اکثرا دی ان اس ها با isp مخابرات فیلتر شدن، شما هم همین مشکل رو دارین؟

**Comment by msasanmh** [comment]
> اکثرا دی ان اس ها با isp مخابرات فیلتر شدن، شما هم همین مشکل رو دارین؟
> 

من که مخابرات ندارم، اما دیدم روی ایرانسل خیلی‌ها فیلتر هستن.
میشه از قسمت تنظیمات plain dns و no filter رو آزاد کرد اگه کلا سروری پیدا نشد.
من بعدا لیست رو آپدیت میکنم اما بالاخره اینا همه رو فیلتر میکنن.
واسه همین قسمت کانکت گزینه دوم میتونه dns فیلترشده کلودفلر رو باز کنه.
بخاطر همین روزا گذاشتمش که اگه هیچ سروری باز نبود بکار بیاد.

**Comment by nonbarbari** [comment]
> اکثرا دی ان اس ها با isp مخابرات فیلتر شدن، شما هم همین مشکل رو دارین؟

من چیزی که جدیدا فهمیدم اینه که هر مرکز مخابراتی فیلترینگش فرق داره من مخابراتم و سرور ها کار میکنن اما ممکنه مخابرات 2 تا خیابون اون طرف ما کار نکنن. به هر حال از سرور الکترو میتونید استفاده کنید

**Comment by magellandi** [comment]
امروز مخابرات از صبح همه رو بست.
اینترنتش داخلی شده
