### ISSUE TITLE
اینترنت بدون روشن کردنش کار نمیکنه

### ISSUE THREAD

**Issue by Ge64com** [msasanmh/SecureDNSClient#73]
من برای وصل شدن به اینترنت توی پی سی از گوشی (ایرانسل) به کامپیوتر هاتسپات میکنم. مشکلی که هست اینه که وقتی کامپیوتر رو هر دفعه روشن میکنم و به گوشی کانکت میشم هیچ سایتی رو باز نمیکنه تا وقتی که نرم افزارو باز کنم و کانکت بشم. من زیاد از وب سر در نمیارم ولی فکر کنم مربوط به dns باشه.

**Comment by msasanmh** [comment]
> من برای وصل شدن به اینترنت توی پی سی از گوشی (ایرانسل) به کامپیوتر هاتسپات میکنم. مشکلی که هست اینه که وقتی کامپیوتر رو هر دفعه روشن میکنم و به گوشی کانکت میشم هیچ سایتی رو باز نمیکنه تا وقتی که نرم افزارو باز کنم و کانکت بشم. من زیاد از وب سر در نمیارم ولی فکر کنم مربوط به dns باشه.

چون شما گوشی رو به کامپیوتر هاتسپات کردید و بعد برنامه رو اجرا کردید.
و وقتی کارتون تموم شد بدون اینکه اول برنامه رو دیسکانکت کنید هاتسپات رو قطع کردید.
وقتی هاتسپات قطع بشه، کانکشن مربوط بهش غیرفعال میشه و برنامه دیگه نمیتونه dns ای که بروش ست کرده بود رو برداره.
برای رفع مشکل:
۱. موبایل رو به کامپیوتر هاسپات کن.
۲. برنامه رو کانکت کن و dns رو ست کن.
۳. برنامه رو دیسکانکت کن.
