### ISSUE TITLE
v2.6.0 blocked by antivirus

### ISSUE THREAD

**Issue by godshades** [msasanmh/SecureDNSClient#77]
all previous version working ok, after update to 2.6.0 my symantec detect trojan
quick fix by using old file from 2.3.7
![image](https://github.com/msasanmh/SecureDNSClient/assets/12244851/0ebe4f54-f478-4836-9fe5-d0438d386dab)

**Comment by msasanmh** [comment]
My browser raised an alert too, it's the new version of [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy) there's nothing I can do about it.
I'm sure it's false positive alert but you can open an issue on dnscrypt-proxy's github page.

https://github.com/DNSCrypt/dnscrypt-proxy
