### ISSUE TITLE
how to use the new version

### ISSUE THREAD

**Issue by saeex71** [msasanmh/SecureDNSClient#78]
سلام امکامش هست یک فایل راهنما یا ویدیو جدید برای قابلیت های جدید برنامه اضافه کنید؟ قابلیت های برنامه به مرور زیاد و عالی شده و استفاده برای کاربران عادی دشوار شده
سپاس از تمام زحمات

**Comment by msasanmh** [comment]
> سلام امکامش هست یک فایل راهنما یا ویدیو جدید برای قابلیت های جدید برنامه اضافه کنید؟ قابلیت های برنامه به مرور زیاد و عالی شده و استفاده برای کاربران عادی دشوار شده
> سپاس از تمام زحمات

منتظرم یه کمی سرم خلوت شه تا برم سراغ ویدئوها.

**Comment by Noob2Pr0** [comment]
سلام و وقت بخیر
واقعاً خسته نباشید
خیلی برنامه عالی هست من بشدت راضی بودم
برات بهترین ها رو آرزو دارم

برای نسخه ورژن جدید متاسفانه منم همین مشکل رو دارم که فایل zip رو دانلود کردم و فایل exe نداشت مثل نسخه قبلیم
و الان نمیدونم چطور دوباره میشه از این نرم افزار خوب استفاده کرد

**Comment by msasanmh** [comment]
> سلام و وقت بخیر
> واقعاً خسته نباشید
> خیلی برنامه عالی هست من بشدت راضی بودم
> برات بهترین ها رو آرزو دارم
> 
> برای نسخه ورژن جدید متاسفانه منم همین مشکل رو دارم که فایل zip رو دانلود کردم و فایل exe نداشت مثل نسخه قبلیم
> و الان نمیدونم چطور دوباره میشه از این نرم افزار خوب استفاده کرد

سلام، ممنون، 
آنتی‌ویروس شما فایل exe رو پاک کرده، من بارها توضیح دادم که چرا گاهی آنتی‌ویروس‌ها گیر میدن.
این توضیحات داخل issue ها هست.
فقط مطمئن باشید این آلارم‌ها false positive هستن.
اگه برنامه آلوده بود dnscrypt هرگز برنامه sdc رو داخل وب‌سایتش قرار نمی‌داد. 

برنامه رو با خیال راحت داخل لیست سفید آنتی‌ویروس تون قرار بدید.

![Screenshot_20230922_000547_MiXplorer.jpg](https://github.com/msasanmh/SecureDNSClient/assets/1586825/77923d1f-ffa1-4f10-a27c-77e8e469711c)

همونطور که در عکس بالا می‌بینی فایل exe داخل آرشیو وجود داره.

**Comment by msasanmh** [comment]
> سلام و وقت بخیر
> واقعاً خسته نباشید
> خیلی برنامه عالی هست من بشدت راضی بودم
> برات بهترین ها رو آرزو دارم
> 
> برای نسخه ورژن جدید متاسفانه منم همین مشکل رو دارم که فایل zip رو دانلود کردم و فایل exe نداشت مثل نسخه قبلیم
> و الان نمیدونم چطور دوباره میشه از این نرم افزار خوب استفاده کرد

و راستی فایل zip رو دانلود نکنید اون سورس برنامه هستش.
فایل 7z رو دانلود کنید.

**Comment by Noob2Pr0** [comment]
چون نوشته بود ARM64 گمراه شدم گفتم شاید برای سیستم عامل های مربوط به معماری پردازنده ARM باشه مثل رزبری و یا گوشی ها
ممنون

**Comment by Noob2Pr0** [comment]
نه مشکل از انتی ویروس نبوده من چون فایل 7z رو دانلود نکردم سر همون اسم arm64 و zip رو همش دانلود می کردم.
مشکلی با انتی ویروس ندارم و خوب فایلتونم امنه و نگرانی از این بابت نیست هم تو ویروس توتال چک کردم هم این که سورس برنامه بازه میشه چک کرد کد ها رو
سپاس از زحماتی که کشیدی

**Comment by Salimoh** [comment]
کاش توی ویدیوی جدید نحوه ترکیب این ابزار با v2ray رو هم توضیح بدید تا بشه همه سایتای ایرانی رو بدون مشکل باز کرد، برای یوتیوب از وی پی ان استفاده نکرد و یوتیوبم از ابزار شما رد بشه. 
ممنون از شما

**Comment by msasanmh** [comment]
> کاش توی ویدیوی جدید نحوه ترکیب این ابزار با v2ray رو هم توضیح بدید تا بشه همه سایتای ایرانی رو بدون مشکل باز کرد، برای یوتیوب از وی پی ان استفاده نکرد و یوتیوبم از ابزار شما رد بشه. 
> ممنون از شما

من قبلا با Oblivion Desktop ترکیب کردم خیلی عالی کرد. با V2ray هم باید تست کنم. فردا یا پس‌فردا تست میکنم و اطلاع میدم.
اما در کل کاری نداره، فقط V2ray رو بروی حالت پراکسی بزارید. کانکتش کنید.
آدرس پراکسی V2ray رو در قسمت 
Settings  ->  Share  ->  Upstream Proxy
وارد کنید و گزینه Apply only to blocked IPs هم تیک داشته باشه.
بعد SDC رو راه‌اندازی کنید و پراکسیش رو یا روی ویندوز یا مرورگر ست کنید و استفاده کنید.

این شکلی فقط سایت‌هایی که SDC خودش نمیتونه باز کنه از V2ray استفاده می‌کنه.

**Comment by msasanmh** [comment]
> کاش توی ویدیوی جدید نحوه ترکیب این ابزار با v2ray رو هم توضیح بدید تا بشه همه سایتای ایرانی رو بدون مشکل باز کرد، برای یوتیوب از وی پی ان استفاده نکرد و یوتیوبم از ابزار شما رد بشه. 
> ممنون از شما

با V2rayN هم تست کردم عالی جواب میده.
دقیقا طبق همون مراحلی که گفتم انجام بدید.

**Comment by Noob2Pr0** [comment]
> کاش توی ویدیوی جدید نحوه ترکیب این ابزار با v2ray رو هم توضیح بدید تا بشه همه سایتای ایرانی رو بدون مشکل باز کرد، برای یوتیوب از وی پی ان استفاده نکرد و یوتیوبم از ابزار شما رد بشه. ممنون از شما

من وقتی sdc رو باز میکنم و connect میشم میرم سراغ dns set بعد از اون کلا اینترنتم همه سایت های فیلتر شده رو باز میکنه و مشکلی نداره چه رو ایرانسل (در حال حاضر) چه رو adsl از sepanta و کافیه اون لحظه v2ray باز کنم و سایت های تحریم شده رو هم رد میکنم و اموزش خاصی نداره
