### ISSUE TITLE
Software scaling bug

### ISSUE THREAD

**Issue by amijafi** [msasanmh/SecureDNSClient#79]
تو نسخه 2.6.3 دوباره مشکل برگشته ، تو صفحه اول مشکلی نیست ولی وقتی میرم تو صفحه ادیت کردن کاستوم dns بهم ریخته اس

**Comment by msasanmh** [comment]
> تو نسخه 2.6.3 دوباره مشکل برگشته ، تو صفحه اول مشکلی نیست ولی وقتی میرم تو صفحه ادیت کردن کاستوم dns بهم ریخته اس

از همون صفحه اسکرین شات بفرست بهمراه تنظیمات DPI scale که روی چند درصد قرار داره
و همچنین رزولوشن مانیتورت.

**Comment by msasanmh** [comment]
فکر کنم شما [Override](https://github.com/msasanmh/SecureDNSClient/issues/76#issuecomment-1711094768) کرده بودی، برنامه دیگه به اون نیاز نداره باید غیرفعال کنی.

و درهرصورت اسکرین شات و مشخصات dpi scale و مانیتورت رو بفرست
