### ISSUE TITLE
Wait until DNS gets online.

### ISSUE THREAD

**Issue by navidsadri** [msasanmh/SecureDNSClient#80]
سلام خسته نباشی
بعد کانکت شدن تو نسخه جدید اول پیغام Connect Task: RanToCompletion میاد بعد که گزینه set/unset رو میزنم پیغام Wait until DNS gets online. میاد درحالی که dns مناسب با پینک خوب هم پیدا کرده و وصل شده

**Comment by msasanmh** [comment]
> سلام خسته نباشی
> بعد کانکت شدن تو نسخه جدید اول پیغام Connect Task: RanToCompletion میاد بعد که گزینه set/unset رو میزنم پیغام Wait until DNS gets online. میاد درحالی که dns مناسب با پینک خوب هم پیدا کرده و وصل شده

سلام، دقیقا از چه ورژنی داری استفاده میکنی؟
چون گزینه set/unset قدیمیه
آخرین ورژن 2.6.3 هستش، لطفا چک کن بهم اطلاع بده.

**Comment by navidsadri** [comment]
ورژن 2.6.3 هست
بله گزینه Set Dns هست من به اشتباه گفتم ولی پبغام همون هایی هست که نوشتم 
تو قسمت status گزینه local dns  افلاین نشون میده

**Comment by msasanmh** [comment]
> ورژن 2.6.3 هست
> بله گزینه Set Dns هست من به اشتباه گفتم ولی پبغام همون هایی هست که نوشتم 
> تو قسمت status گزینه local dns  افلاین نشون میده 

چون local dns رو آفلاین نشون میده dns رو ست نمیکنه. 
همین الان تست کردم مشکل نداشت. باید یه مقدار بمونی تا local dns آنلاین بشه، اگه نشد یعنی سرورها خوب نیستن، یا دوباره اسکن کن یا از بخش کانکت گزینه دوم رو تست کن.

**Comment by navidsadri** [comment]
اوکی ....یه مقدار صبر میکنم ببینم درست میشه.من همین الان با نسخه قدیمی تر کانکت میشم این مشکل نیست.تو همین نسخه هم وقتی گزینه get saved servers delay  رو می زنم پینگ ها عالی هست....تو گزینه scan هم سرور های doh زیادی پیدا میکنه ولی نمیدونم چرا این مشکل به وجود میاد

**Comment by msasanmh** [comment]
> اوکی ....یه مقدار صبر میکنم ببینم درست میشه.من همین الان با نسخه قدیمی تر کانکت میشم این مشکل نیست.تو همین نسخه هم وقتی گزینه get saved servers delay  رو می زنم پینگ ها عالی هست....تو گزینه scan هم سرور های doh زیادی پیدا میکنه ولی نمیدونم چرا این مشکل به وجود میاد 

منظورم از صبر کردن حداکثر ۳۰ ثانیه بود.
وقتی برنامه کانکت شد داخل تسک منیجر نگاه کن ببین پراسس dnsproxy هست یا نه

**Comment by navidsadri** [comment]
مشکل برطرف شد ....ممنونم

**Comment by msasanmh** [comment]
> مشکل برطرف شد ....ممنونم

خب چی بود مشکل؟

**Comment by navidsadri** [comment]
یه برنامه yogadns  ران بود تو سرویس هام .اون رو که بستم مشکل حل شد....ولی اگه میشد به نحوی یه tun ساخته میشد امکان شیر کردنش با روتر هم فراهم میشد عالی می شد

**Comment by msasanmh** [comment]
> یه برنامه yogadns  ران بود تو سرویس هام .اون رو که بستم مشکل حل شد....ولی اگه میشد به نحوی یه tun ساخته میشد امکان شیر کردنش با روتر هم فراهم میشد عالی می شد
> 

آخه tun برای vpn استفاده میشه خیلی به کار این برنامه نمیاد.
الان امکان شیر کردن با http proxy هستش، درواقع هم local dns و هم proxy روی شبکه شیر میشن

**Comment by navidsadri** [comment]
ولی واقعا درود بر تو....پیاده سازی این ایده به این تمیزی....امیدوارم همیشه موفق باشی

**Comment by navidsadri** [comment]
یه خورده کار کردن با این http proxy کلا سخته....من یه pc stick دارم و یه روتر .هر کاری می کنم شیر نمیشه

**Comment by msasanmh** [comment]
> یه خورده کار کردن با این http proxy کلا سخته....من یه pc stick دارم و یه روتر .هر کاری می کنم شیر نمیشه
> 

من روی گوشیم پراکسی رو ست کردن و تونست یوتیوب رو داخل گوشی باز کنه، میتونی روی گوشیت تست بزنی شاید ایده‌ای دستت اومد

**Comment by navidsadri** [comment]
میشه تنظیمات روی گوشیت رو بگی که چی کار کردی.کمک بزرگیه

**Comment by msasanmh** [comment]
> میشه تنظیمات روی گوشیت رو بگی که چی کار کردی.کمک بزرگیه

تنظیمات wifi گوشی رو ادیت زدم و پراکسی رو ست کردم، آی‌پی 192.168.1.112 این رو زدم که خود برنامه میده، پورت هم 8080 تنظیمات خاصی نداره، همین فقط.
