### ISSUE TITLE
Secure dns 

### ISSUE THREAD

**Issue by yoosefsk** [msasanmh/SecureDNSClient#81]
آقا سلام خوبی ببخشید من برنامه secure dns با مودم امتحان کردم شد ولی با همراه اول میرم خطا میده میزنه faild to open youtube chang dpi mode چه تنظیماتی در قسمت dpi باید انجام بدم تا درست بشه ؟؟؟ از اولین ورژن هم استفاده میکنم این جدیدا اصلا نمیارن

**Comment by yoosefsk** [comment]
بله یا تب چهارم یا سوم نسخه جدید چهار فکر کنم

**Comment by msasanmh** [comment]
> بله یا تب چهارم یا سوم نسخه جدید چهار فکر کنم

نوشتی برنامه بهت گفته change dpi mode تنها زمانی این پیام میاد که داری از GoodbyDPI استفاده میکنی و GoodbyDPI بروی همراه اول جواب نمیده.
بجاش تب چهارم که نوشته شده share + dpi bypass استفاده کن، پراکسی رو فعال کن و بعد روی سیستم ست کن.
بروی همراه و ایرانسل تست کردم جواب میده، درواقع تب چهارم برای همه isp ها جواب میده

**Comment by yoosefsk** [comment]
> > > بله یا تب چهارم یا سوم نسخه جدید چهار فکر کنم
> > 
> > نوشتی برنامه بهت گفته change dpi mode تنها زمانی این پیام میاد که داری از GoodbyDPI استفاده میکنی و GoodbyDPI بروی همراه اول جواب نمیده. بجاش تب چهارم که نوشته شده share + dpi bypass استفاده کن، پراکسی رو فعال کن و بعد روی سیستم ست کن. بروی همراه و ایرانسل تست کردم جواب میده، درواقع تب چهارم برای همه isp ها جواب میده
> 
> ببین بعضی وقت ها جواب میده یعنی مشکل فیلترینگ نیست مشکل اینه که GoodbyDPI سایت رو خراب میکنه 
> با کم و زیاد کردن فرگمنت سایز و تغییر مود میشه وصل شد

این دومی که گفتی گزینه select mode بود یا goodbye dpi mode بود ؟؟؟

**Comment by nonbarbari** [comment]
> > > > بله یا تب چهارم یا سوم نسخه جدید چهار فکر کنم
> > > 
> > > 
> > > نوشتی برنامه بهت گفته change dpi mode تنها زمانی این پیام میاد که داری از GoodbyDPI استفاده میکنی و GoodbyDPI بروی همراه اول جواب نمیده. بجاش تب چهارم که نوشته شده share + dpi bypass استفاده کن، پراکسی رو فعال کن و بعد روی سیستم ست کن. بروی همراه و ایرانسل تست کردم جواب میده، درواقع تب چهارم برای همه isp ها جواب میده
> > 
> > 
> > ببین بعضی وقت ها جواب میده یعنی مشکل فیلترینگ نیست مشکل اینه که GoodbyDPI سایت رو خراب میکنه
> > با کم و زیاد کردن فرگمنت سایز و تغییر مود میشه وصل شد
> 
> این دومی که گفتی گزینه select mode بود یا goodbye dpi mode بود ؟؟؟

جفتش فرگمنت سایز28
