### ISSUE TITLE
Twitch Support

### ISSUE THREAD

**Issue by Cortex-x** [msasanmh/SecureDNSClient#84]
سلام اگ بشه امکان انتخاب کردن که واسه چه سرویسی اسکن میکنه باشه خیلی خوب میشه چون بعضی مواقع twitch هم بالا میاره بعضی دی ان اس ها

**Comment by msasanmh** [comment]
> سلام اگ بشه امکان انتخاب کردن که واسه چه سرویسی اسکن میکنه باشه خیلی خوب میشه چون بعضی مواقع twitch هم بالا میاره بعضی دی ان اس ها

سرفرصت بررسی میکنم و اگه امکانش بود یه راه کار براش میدم.
به احتمال زیاد fake dns بتونه انجامش بده اما آموزش نذاشتم فکر نکنم شما بلد باشی، خودم وقت کنم روش کار کنم.

**Comment by nonbarbari** [comment]
> سلام اگ بشه امکان انتخاب کردن که واسه چه سرویسی اسکن میکنه باشه خیلی خوب میشه چون بعضی مواقع twitch هم بالا میاره بعضی دی ان اس ها

فکر کنم می خواهین که داخل لاگ به جای یوتوب سایت توییچ رو برسی کنه ببینه باز میشه یا ن درسته ؟
اگه منظور تون این بود میتونید از داخل تنظیمات قسمت check یوتوب رو تغییر بدید به توییچ

**Comment by Cortex-x** [comment]
> > سلام اگ بشه امکان انتخاب کردن که واسه چه سرویسی اسکن میکنه باشه خیلی خوب میشه چون بعضی مواقع twitch هم بالا میاره بعضی دی ان اس ها
> 
> فکر کنم می خواهین که داخل لاگ به جای یوتوب سایت توییچ رو برسی کنه ببینه باز میشه یا ن درسته ؟ اگه منظور تون این بود میتونید از داخل تنظیمات قسمت check یوتوب رو تغییر بدید به توییچ

نه یعنی موقع اسکن دی ان اس برای بازی کردن twitch اسکن کنه نه یوتیوب و توییتر

**Comment by nonbarbari** [comment]
> > > سلام اگ بشه امکان انتخاب کردن که واسه چه سرویسی اسکن میکنه باشه خیلی خوب میشه چون بعضی مواقع twitch هم بالا میاره بعضی دی ان اس ها
> > 
> > 
> > فکر کنم می خواهین که داخل لاگ به جای یوتوب سایت توییچ رو برسی کنه ببینه باز میشه یا ن درسته ؟ اگه منظور تون این بود میتونید از داخل تنظیمات قسمت check یوتوب رو تغییر بدید به توییچ
> 
> نه یعنی موقع اسکن دی ان اس برای بازی کردن twitch اسکن کنه نه یوتیوب و توییتر

مگه الان غیر از موردی که گفتم یوتوب برسی میشه ؟
این رو می خواهی ؟
![gfxzhzfgh](https://github.com/msasanmh/SecureDNSClient/assets/123904563/1ef1a6bb-e432-49be-8f14-b1ffead377e0)



DNS الکترو
Goodbye DPI extreme

اول توییچ رو باز میکنی صفحه که لود شد Goodbye DPI رو خاموش میکنی بعد بین استریمر ها جا به چا شو بعد تصویر وصل میشه

**Comment by nonbarbari** [comment]
![image](https://github.com/msasanmh/SecureDNSClient/assets/123904563/9eb5fe48-2e8b-4504-a7ea-926b3df7c7cb)
 2K 60FPS 30s buffer 

اگه با تنظیمات ادوس Goodbye DPI بازی کنی میتونی بدون نیاز به خاموش کردن Goodbye DPI هم سایت رو باز کنی و باهمچین سرعتی استفاده کنی... بستگی به ISP هم داره اگه هم خودت استریم میکنی نمیدونم چه کار میشه کرد
