### ISSUE TITLE
SecureDNSClientPortable مشکل در

### ISSUE THREAD

**Issue by ehsan-am** [msasanmh/SecureDNSClient#85]
سلام و درود بر شما
ممنون از این dnsclient باحال ، در مدت یک ماه استفاده خیلی لذت بردم فقط امروز یه مشکل پیش اومد برام که وقتی اون دکمه آخر ست پراکسی رو میزنم این ارور رو میده:dpi check: the ssl connection could not be established, see inner exception. میتونید راهنماییم کنید.قبلا اینطور نبود .خیلی خیلی ممنون نمیدونم ویروسه یا چی.تقریبا تو یوتیوب اکثر ویدیو هایی که راهکار میگفتن رو رفتم، مثل زدن بعضی تیکها تو internet options(advanced) یا clear certificate و... البته اکثر راه حل مشکل ssl که تو یوتیوب میگفتن، مربوط به بروزر یا گوگل کروم بودن و نه مشکل من که بتونم رفعش کنم. میشه لطفا بهم بگید چه کنم.واقعا ممنون

**Comment by msasanmh** [comment]
https://github.com/msasanmh/SecureDNSClient/issues/31#issuecomment-1736066687
