### ISSUE TITLE
Couldn't communicate with Proxy Console

### ISSUE THREAD

**Issue by mr-adrien** [msasanmh/SecureDNSClient#86]
Please make sure you have .NET Desktop v6 installed on your OS. این ارور رو میده حتی بعد از اینکه مطمعن شدم .net v6 نصبه
windows 11
client version 2.6.3

**Comment by msasanmh** [comment]
> Please make sure you have .NET Desktop v6 installed on your OS. این ارور رو میده حتی بعد از اینکه مطمعن شدم .net v6 نصبه
> windows 11
> client version 2.6.3

باید هر دو نسخه 32 و 64 بیتی نصب باشن.
شما به احتمال زیاد نسخه 32 بیتی رو نصب ندارید
