### ISSUE TITLE
Tuturials are not full as enough

### ISSUE THREAD

**Issue by AImakerrr** [msasanmh/SecureDNSClient#87]
سلام وقت به خیر. آموزش هاش به گمانم کامل نیستن.
من با ترکیب های مختلف از گزینه هایی که ارائه داد استفاده کردم ولی تنها به یوتوب و توییتر دسترسی پیدا کردم.
ندونستم چطوری با وی تو ری به هر سایتی یا تقریبا فیسبوک وصل بشم. ای کاش اینو بگید. که چطوری میشه کاملا به هر سایتی دسترسی داشت باهاش به غیر از ویتوبو توییتر(به بازی ها هم همینطور مثل بازی تایتان آرنا که کریپتویی هست و ایرانی ها هم توش هستن)

**Comment by msasanmh** [comment]
به طور کلی میگم که دست تون بیاد.
این برنامه یه vpn نیست یه کلاینت dns هستش.
کارهایی که انجام میده:
- هر وبسایتی که براساس اسم دامنه فیلتر شده باشه اما ip اون وبسایت فیلتر نباشه رو باز میکنه.
- تاخیر و پینگ رو کاهش میده.
- سرورهای v2ray که فیلتر شدن اما پشت cdn قرار دارن رو بکار میندازه.
- اسم وبسایت‌ها رو از دید isp مخفی میکنه.
- با قسمت upstream پراکسی میشه کاری کرد تا فقط وبسایتهایی که خودش نمیتونه باز کنه رو از پراکسی عبور بده برای کاهش مصرف پهنای باند vpn و بالابردن سرعت.

پس درواقع یه کانکشن اولیه پایدار ایجاد میکنه که بعدش بشه راحت‌تر به وبسایت‌ها یا VPN ها دسترسی داشت.

اگه برای Facebook چیزی میخوای میتونی این پک پراکسی رو امتحان کنی:
https://msasanmh.github.io/PAC/Germany.pac

مابقی:
https://github.com/msasanmh/msasanmh.github.io/tree/master/PAC

**Comment by davidx7** [comment]
درود بر شما

**Comment by msasanmh** [comment]
> درود بر شما. وقتتون بخیر 
> از این فایل های پروکسی که گذاشتید چطوری استفاده کنیم؟
> 

میتونید داخل مرورگرها ست کنید، مثلا برای گوگل کروم از افزونه switchy omega استفاده کنید.
اما الان زمان مناسبی نیست، به سرورها فشار اومده و متاسفانه بیشتر اوقات وصل نمیشن.

**Comment by davidx7** [comment]
ممنون از شما بابت برنامه ای که نوشتید
