### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by mahdiyarzx** [msasanmh/SecureDNSClient#88]
واقعا فوق العادس ممنونم ازتون فقط برای رفع این مشکل یه راهنمایی بکنید ممنون میشم

**Comment by mahdiyarzx** [comment]
ممنونم

**Comment by Milad-shbz** [comment]
دوست عزیز، ممنون از زحمتات
منم متاسفانه جدیدا با این مشکل مواجه شدم، فبلا کانکت میشدم الان یه چند وقتیه این ارور میاد برام بعد ست پروکسی
اینم بگم که نتی که استفاده میکنم همون هست که قبلا بوده عوض نشده.
راه حلی نیست؟

**Comment by msasanmh** [comment]
> دوست عزیز، ممنون از زحمتات
> منم متاسفانه جدیدا با این مشکل مواجه شدم، فبلا کانکت میشدم الان یه چند وقتیه این ارور میاد برام بعد ست پروکسی
> اینم بگم که نتی که استفاده میکنم همون هست که قبلا بوده عوض نشده.
> راه حلی نیست؟

نمی‌دونم چرا اخیرا چند نفر همچین مشکلی پیدا کردن، شاید بخاطر اینه که اختلال اینترنت رو یه هفته‌ای هست بالا بردن.
فعلا راه حلی برای این مشکل ندارم تا زمانیکه دست خودم به یکی از این isp ها برسه.

**Comment by rezakailas** [comment]
ما هم بسیار منتظریم😅

**Comment by msasanmh** [comment]
> ما هم بسیار منتظریم😅

آخه چطور دستم به مخابرات و شاتل برسه 😞

**Comment by msasanmh** [comment]
> ما هم بسیار منتظریم😅

برای شما هم راه چاره‌ای پیدا کردم 🔥

**Comment by rezakailas** [comment]
> > ما هم بسیار منتظریم😅
> 
> برای شما هم راه چاره‌ای پیدا کردم 🔥

چقدر عالی ولی الان این راه چاره در دسترسه؟

**Comment by msasanmh** [comment]
> > > ما هم بسیار منتظریم😅
> > 
> > برای شما هم راه چاره‌ای پیدا کردم 🔥
> 
> چقدر عالی ولی الان این راه چاره در دسترسه؟

نه، در ورژن بعد یه گزینه‌ای اضافه میشه که شما باید اونو فعال کنید، همون موقع توضیح میدم.

**Comment by msasanmh** [comment]
کسایی که این مشکل رو داشتن در ورژن جدید ابتدا سرورها اسکن بشن و dns ست بشه و بعد از تب پراکسی گزینه SSL Decryption رو فعال کنید و تیک گزینه پایینش رو هم فعال کنید و بعد پراکسی رو استارت و ست کنید.
دیگه GoodbyeDPI رو اجرا نکنید.
در این روش نصب certificate الزامیه

**Comment by msasanmh** [comment]
حتی میتونید sni یوتیوب رو به گوگل تغییر بدید، با فعال کردن Fake DNS و اضافه کردن قانون پایین داخل فایل:
youtube.com|google.com
