### ISSUE TITLE
مشکل فونت

### ISSUE THREAD

**Issue by saeex71** [msasanmh/SecureDNSClient#9]
![Screenshot 2023-05-02 131517](https://user-images.githubusercontent.com/124634578/235634128-55d62d48-40cb-401c-bb03-e23ff8c163ce.png)
سلام زمانی که DPI یا زوم ویندوز بیشتر از 100 درصد باشه بعضی از کلمات از کادر خارج میشن
و در اخر تشکر بابت این برنامه کاربردی
سپاس

**Comment by msasanmh** [comment]
سلام، ممنون بابت گزارش این مشکل، من با Magnifier ویندوز تست کردم این مشکل ایجاد نشد.
اما میدونم که هست چون شما دومین نفری هستید که این مشکل رو داره.
اگه بهم بگی چطور میتونم همین کاری که شما انجام دادی رو روی سیستم خودم پیاده کنم اونوقت میتونم مشکل رو حل کنم.
همچنین اسکرین شاتی که فرستادی باعث میشه بفهمم توی کدوم قسمتها مشکل وجود داره.
فقط داخل تب های دیگه برنامه چطور؟ اگه در هر صفحه‌ای از برنامه که این مشکل پدیدار میشه یه اسکرین بفرستی عالی میشه.

**Comment by saeex71** [comment]
> سلام، ممنون بابت گزارش این مشکل، من با Magnifier ویندوز تست کردم این مشکل ایجاد نشد. اما میدونم که هست چون شما دومین نفری هستید که این مشکل رو داره. اگه بهم بگی چطور میتونم همین کاری که شما انجام دادی رو روی سیستم خودم پیاده کنم اونوقت میتونم مشکل رو حل کنم. همچنین اسکرین شاتی که فرستادی باعث میشه بفهمم توی کدوم قسمتها مشکل وجود داره. فقط داخل تب های دیگه برنامه چطور؟ اگه در هر صفحه‌ای از برنامه که این مشکل پدیدار میشه یه اسکرین بفرستی عالی میشه.

برای تنظیم قسمت setting>system>display>scale and layout 125%

**Comment by saeex71** [comment]
![Screenshot 2023-05-02 162330](https://user-images.githubusercontent.com/124634578/235672513-03cc2eab-984b-4830-b64d-dcb2d741e6d7.png)

**Comment by saeex71** [comment]
تشکر
میشه راهنمایی کنید چطور دیوایس های دیگه موجود در شبکه (ایفون اندروید یا تلویزیون هوشمند) از طریق پروکسی وصل کنیم؟
من از طریق تنظیم پروکسی با مشخصات ایپی سیستم و پورت تونستم روی ایفون وصل بشم ایا با تنظیم DNS سایر دیوایس ها به ایپی سیستم اصلی هم میشه وصل شد؟
و کاربرد goodbye dpi mode چیه؟

**Comment by msasanmh** [comment]
در قسمت کانکت اگه گزینه Enable HTTP Proxy رو فعال کنی اونوقت میتونی آدرس پروکسی که بهت میده رو بروی دیوایس‌های داخل شبکه ست کنی و باعث میشه اونها هم از DNS و DPI استفاده کنن.
برنامه GoodbyeDPI برای باز کردن یوتیوب و توییتر استفاده میشه. یعنی همون Bypass کردن SNI های فیلتر شده.
