### ISSUE TITLE
How do I get it to connect o windows startup?

### ISSUE THREAD

**Issue by rohitghali** [msasanmh/SecureDNSClient#90]
There are no settings for windows startup. How do I make it start with windows?

**Comment by nonbarbari** [comment]
Go to program folder

Create a text file with these contents

`@echo OFF`
`START SecureDNSClient.exe`
`exit`

Save it as .bat file

Create a shortcut of it and move it to start up folder 

You can go to start up folder like that 

Presse Windows kye + R
`shell:startup`
Presse Enter

**Comment by msasanmh** [comment]
> There are no settings for windows startup. How do I make it start with windows?

Startup feature will be implemented in 2 next version.

**Comment by msasanmh** [comment]
Startup feature implemented 
https://github.com/msasanmh/SecureDNSClient/releases/tag/v2.7.5
