### ISSUE TITLE
 It works . ❤️

### ISSUE THREAD

**Issue by DogancanYr** [msasanmh/SecureDNSClient#91]
It works even in countries with extreme internet restrictions. (With correct settings)
It easily replaced Goodbyedpi.

**Comment by msasanmh** [comment]
> It works even in countries with extreme internet restrictions. (With correct settings)
> It easily replaced Goodbyedpi.
> 

Glad to hear that 🙏

**Comment by nonbarbari** [comment]
آقا یه چیز باحال اگه برنامه کانکت باشه و ویندوز رو به صورت خاموشی موقت خاموش کنیم بعد از روشن شدن ویندوز برنامه اتصال رو حفظ میکنه و همه چی آماده هست

**Comment by msasanmh** [comment]
> آقا یه چیز باحال اگه برنامه کانکت باشه و ویندوز رو به صورت خاموشی موقت خاموش کنیم بعد از روشن شدن ویندوز برنامه اتصال رو حفظ میکنه و همه چی آماده هست

آره این رو کشف کرده بودم 😄
حالا ورژن بعد startup رو ببینی حال می‌کنی، بدون اینکه UAC آلارم بده میاد بالا
