### ISSUE TITLE
Everything is great, but ...

### ISSUE THREAD

**Issue by DogancanYr** [msasanmh/SecureDNSClient#92]
Everything is great, but if any software is connected to the internet and when use the program, that software does not connect to the internet again and it is necessary to restart that software.

**Comment by DogancanYr** [comment]
I think I solved the problem. I was activating goodbye dpi with share + bypassdpi. Instead, I set quick connect to connect to fake proxy via goodbyedpi from the settings.

**Comment by DogancanYr** [comment]
Let me explain the problem in another way. If there is a program connecting to the internet in real time in the background, if SDC becomes active later, it cuts off the internet of the program in the background.

**Comment by msasanmh** [comment]
> Let me explain the problem in another way. If there is a program connecting to the internet in real time in the background, if SDC becomes active later, it cuts off the internet of the program in the background.
> 

I know what you mean now.
SDC only cuts off the Internet while it's flushing DNS and it's natural, if I remove DNS flushing, then you might have problems with getting correct IPs since previous DNS cache still exist.
However I'll try to fix this issue in the next version. (I need to see what can I do)
Until then just execute SDC before any other application, because it's making the base connection. 

Thank you for reporting this.
Let me know if there's any other issue.

**Comment by msasanmh** [comment]
> I think I solved the problem. I was activating goodbye dpi with share + bypassdpi. Instead, I set quick connect to connect to fake proxy via goodbyedpi from the settings.

It doesn't matter, they don't have any conflict with each other. 
Connect to "working servers" is faster though. 

You can use
"Connect via proxy dpi bypass"
Or 
"Connect via GoodbyeDPI"
when app can't find any "working servers"

**Comment by DogancanYr** [comment]
Thank you very much indeed.There is no need to open all those features, but if someone who has this problem comes here, it will be useful.
 This program is very op, it contains all applications and you can run it easily. How long did it take you to do this program ?

**Comment by msasanmh** [comment]
> Thank you very much indeed.There is no need to open all those features, but if someone who has this problem comes here, it will be useful.

❤️

>  This program is very op, it contains all applications and you can run it easily. How long did it take you to do this program ?

Well, the first version took about 3 months without proxy server and most features.
But overall it took 11 months.
