### ISSUE TITLE
expose internal list

### ISSUE THREAD

**Issue by horusra** [msasanmh/SecureDNSClient#95]
After I scan using the built-in server list, there is no way to check the built-in list.
Even when choosing "view working servers" it opens an empty file, probably because that only works with custom server lists.
![image](https://github.com/msasanmh/SecureDNSClient/assets/17074394/cb05e277-58e2-4ac3-b5fb-9ce3101df492)
I would like to see the working built-in server list so that I can copy and paste that into [this dns benchmark tool](https://www.grc.com/dns/benchmark.htm) to double check speed and latency differences more accurately.
I want to do this because checking a single domain once per dns server is not an accurate way of finding the fastest dns server.
That's why I want to use SDC in combination with: [grc.com/dns/benchmark.htm](https://www.grc.com/dns/benchmark.htm)

Exposing the built-in list would also make it easier to set up custom server lists, so that you can combine your own custom list with some of the ones from the built-in list.
![image](https://github.com/msasanmh/SecureDNSClient/assets/17074394/1b3d8177-92bc-48b3-8f6c-e60393c46897)
from this output, I can not copy or paste the dns servers. All I see is the company and protocol, so if I wanted to copy paste the settings elsewhere, I couldn't do it.

**Comment by msasanmh** [comment]
In countries with internet restrictions, governments block every secure dns server they find so they can hijack dns queries easily, that's why I can't expose the internal list.
Just find some dns servers on the internet and import them as your custom list, then you can do your benchmarking.
