### ISSUE TITLE
Launch on Startup 

### ISSUE THREAD

**Issue by Ahmad-2213** [msasanmh/SecureDNSClient#96]
Hello.
I was wondering that it'll be so good if I could've had the app launched and connected whenever I boot my Computer.
for instance , when I boot my PC , The app run and connect to the previous server that I've been using since the last time.
if works, great! , else , pop up an error message so that the user will notice and rescan for new fresh servers .

**Comment by msasanmh** [comment]
Startup feature will be implemented in next version and it can automatically connect to whatever you want.

**Comment by msasanmh** [comment]
Startup feature implemented 
https://github.com/msasanmh/SecureDNSClient/releases/tag/v2.7.5
