### ISSUE TITLE
توسعه برنامه برای آندروید

### ISSUE THREAD

**Issue by hosseinTSR** [msasanmh/SecureDNSClient#97]
سلام آقا ساسان خسته نباشی
امکان اینکه این برنامه رو برای آندروید هم بسازی وجود داره؟

**Comment by msasanmh** [comment]
> سلام آقا ساسان خسته نباشی
> امکان اینکه این برنامه رو برای آندروید هم بسازی وجود داره؟
> 

فعلا احتمالش ۵۰ ۵۰ هستش، باید برم جلو ببینم چی میشه.
