### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by msn386** [msasanmh/SecureDNSClient#99]
با سلام و احترام. آیا ورژنی از برنامه Secure DNS Client هست که در ویندوز 7 اجرا بشه؟ اگر هست لطفا لینکش رو قرار بدید. با تشکر فراوان

**Comment by Ne0xor16** [comment]
Как раздавать на телефон?

**Comment by msasanmh** [comment]
> با سلام و احترام. آیا ورژنی از برنامه Secure DNS Client هست که در ویندوز 7 اجرا بشه؟ اگر هست لطفا لینکش رو قرار بدید. با تشکر فراوان

این ورژن رو تست کنید:
https://github.com/msasanmh/SecureDNSClient/releases/download/v2.7.5/SecureDNSClientPortable_v2.7.5_x86_x64.7z

**Comment by msasanmh** [comment]
آخرین ورژن ۳۲ بیت:
https://github.com/msasanmh/SecureDNSClient/releases/download/v2.8.0/SecureDNSClientPortable_v2.8.0_x86.7z
